<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AutorizarDevolucionTSP/AutorizarDevolucionTSP/autorizarDevolucionTSP" name="autorizarDevolucionTSP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AutorizarDevolucionTSP/AutorizarDevolucionTSP/autorizarDevolucionTSP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AutorizarDevolucionTSP/AutorizarDevolucionTSP/autorizarDevolucionTSP" location="autorizarDevolucionTSP.wsdl"/>
  <binding name="autorizarDevolucionTSP_ptt-binding" type="tns:autorizarDevolucionTSP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="autorizarDevolucionTSP">
      <soap:operation soapAction="autorizarDevolucionTSP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="autorizarDevolucionTSP-service">
    <port name="autorizarDevolucionTSP-port" binding="tns:autorizarDevolucionTSP_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTSP"/>
    </port>
  </service>
</definitions>