<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/HN/consultaTiposRevisionesTasa/consultaTiposRevisionesTasa" name="consultaTiposRevisionesTasa-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/HN/consultaTiposRevisionesTasa/consultaTiposRevisionesTasa" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/HN/consultaTiposRevisionesTasa/consultaTiposRevisionesTasa" location="consultaTiposRevisionesTasa.wsdl"/>
  <binding name="consultaTiposRevisionesTasa_ptt-binding" type="tns:consultaTiposRevisionesTasa_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaTiposRevisionesTasa">
      <soap:operation soapAction="consultaTiposRevisionesTasa"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaTiposRevisionesTasa-service">
    <port name="consultaTiposRevisionesTasa-port" binding="tns:consultaTiposRevisionesTasa_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>