<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/GetValidSubApplication" name="GetValidSubApplication-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GetValidSubApplication.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/GetValidSubApplication"/>
    <wsdl:binding name="GetValidSubApplication_ptt-binding" type="get:GetValidSubApplication_ptt" xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/GetValidSubApplication">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="GetValidSubApplication">
            <soap:operation soapAction="GetValidSubApplication"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>