<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MD/conConsultaSaldosCuentaTC" name="conConsultaSaldosCuentaTC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MD/conConsultaSaldosCuentaTC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MD/conConsultaSaldosCuentaTC" location="conConsultaSaldosCuentaTC.wsdl"/>
  <binding name="conConsultaSaldosCuentaTC_ptt-binding" type="tns:conConsultaSaldosCuentaTC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conConsultaSaldosCuentaTC">
      <soap:operation soapAction="conConsultaSaldosCuentaTC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conConsultaSaldosCuentaTC-service">
    <port name="conConsultaSaldosCuentaTC-port" binding="tns:conConsultaSaldosCuentaTC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>