<wsdl:definitions targetNamespace="http://www.ficohsa.com.hn/middleware.services/registroImpresionCheque/" name="registroImpresionChequePS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/registroImpresionCheque/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/registroImpresionChequeTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/registroImpresionChequeTypes" schemaLocation="registroImpresionChequeTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
   	<wsdl:message name="registroImpresionChequeRequest">
		<wsdl:part element="cons:registroImpresionCheque" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="registroImpresionChequeResponse">
		<wsdl:part element="cons:registroImpresionChequeResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="registroImpresionChequePS">
		<wsdl:operation name="registroImpresionCheque" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:registroImpresionChequeRequest"/>
			<wsdl:output message="fic:registroImpresionChequeResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="registroImpresionChequePSSOAP" type="fic:registroImpresionChequePS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="registroImpresionCheque">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/registroImpresionCheque/registroImpresionCheque"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:registroImpresionChequeRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:registroImpresionChequeResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="registroImpresionChequePS">
	    <wsdl:port binding="fic:registroImpresionChequePSSOAP" name="registroImpresionChequePSSOAP">
	      <soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/Payments/RegistroImpresionChequesPropios"/>
	    </wsdl:port>
	</wsdl:service>

</wsdl:definitions>