sequenceDiagram
    autonumber
    participant Consumidor as Consumidore/Aplicación
    participant API as API Reversar Credit Card TFS <br> Epica 2490: ReversarTransaccion <br> HU 6644: <br> POST: /transaction-financial-services-mgmt/v1/reverse-transaction
    participant BD as DynamoDB <br> Registro Transacciones
    participant Reversar as HU 6664 <br> API Reversos <br> POST: /payments/payment-execution-admin/v1/reverse-transaction 
    participant Idempotencia as Componente de Idempotencia <br> POST: integrity-handler/v1/idempotency/generate
    participant AuthReversar as HU 6627 <br> API Autorizar Reversos <br> POST: /payments/payment-execution-admin/v1/authorize-reverse-transaction 
    participant Reintentos as AWS EventBridge <br> Componente de Idempotencia / Reintentos
    participant SP1 as SP: OSB_P_REGISTRA_REVERSION_TC_CB <br/> ConnectionPagosWSTC <br> Schema: PAGOSWSTC
    participant LibraryPipeline as Library Pipeline <br> transactionFinancialServicesMgmt-Product
    participant SP2 as SP: OSBRegistraReversaTC <br/> ConnectionTarjetas <br> Schema: PagosTC <br> Package: dbo
    participant Errors as Control de Errores <br/> <<Librería de mapeo de errores>>

    Note over Consumidor, Errors: Flujo Honduras (HN01) - Reversar Pago Tarjeta de Crédito TFS

    Consumidor->>API: Rest Request
    Note right of Consumidor: Header: SourceBank=HN01<br/>Body: transactionReference, transactionType

    API->>API: Validar Request
    Note over  API: Validar obligatoriedad campos según contrato OpenAPI <br/> transactionReference != vacío <br> transactionType = "CREDIT_CARD_TFS"

    API->>API: Validación exitosa

    API->>API: Validar Servicio Regional
    Note over API: key de config: TRANSACTION_FINANCIAL_SERVICES_MANAGEMENT
    
    API->>API: Validación Regional Exitosa
    Note over API: Servicio habilitado para HN01

    API->>API: Validación Exitosa

    API->>API: Determinar tipo de transacción
    Note over API: Substring transactionReference: <br> trxType3: substr(transactionReference 1, 3)

    API->>API: Validar trxType3
    
    alt Tipo de transacción inválido trxType3 != "TFS"
        rect rgba(248, 238, 238, 1)
            API->>Errors: Mapea Error "Tipo de transacción inválida"

            Errors ->> API: Retorna código mapeado

            API->>Consumidor: Retorna error controlado
            Note over Consumidor: "Tipo de transacción inválida"
        end
    else Tipo de transacción válido trxType3 = "TFS"

            API->>BD: Consulta transacción en BD
            Note right of API: SourceBank, transactionReference, transactionType

            BD->>API: Resultado Consulta transacción en BD

            API->>API: Evalúa resultado de la consulta a la BD

        alt Transacción Existe en la BD
            rect rgba(224, 232, 246, 1)

                API->>Consumidor: API Response
                Note over Consumidor: "HTTP 202: Transacción Recibida Exitosamente" 

                API->>API: Determina paso que debe ejecutar

                alt stateProcess = "AUTHORIZATION" and stateTransacción = "PENDING"
                    rect rgba(242, 247, 211, 1)    

                        API->>AuthReversar: Consume Autorización Reverso
                        Note right of API: SourceBank, transactionReference, transactionType, retryRequired: false

                        AuthReversar->>API: Response Autorización Reverso
                        Note left of AuthReversar: SuccessIndicator

                        API->>API: Evalúa Response Autorización Reverso

                        alt Response Autoriza Reverso successIndicator != "SUCCESS"

                            API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                            Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_financial_services_mgmt-comp-reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: TimeOut 

                        else Response Autoriza Reverso successIndicator = "SUCCESS"

                            API->>BD: Update BD - stateProcess = "AUTHORIZATION" and stateTransacción = "COMPLETE"

                            API->>API: Construye request SP Registra Reversión
                            Note over API: PV_TRANSACTION_ID = transactionReference

                            API->>BD: Update BD - stateProcess = "REG_REVERSE" and stateTransacción = "PENDING"

                            API->>SP1: Consume SP Registra Reversión
                            Note right of API: PV_TRANSACTION_ID

                            SP1->>API: Response OSB_P_REGISTRA_REVERSION_TC_CB
                            Note left of SP1: successIndicator

                            API->>API: Evalúa Response OSB_P_REGISTRA_REVERSION_TC_CB 

                            alt Response Registra Reversión successIndicator != "SUCCESS"

                                API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_financial_services_mgmt-comp-reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: TimeOut 

                            else Response Registra Reversión successIndicator = "SUCCESS"

                                API->>BD: Update BD - stateProcess = "REG_REVERSE" and stateTransacción = "COMPLETE"

                                API->>LibraryPipeline: Consulta Constantes de Pipeline

                                LibraryPipeline->>API: Retorna Constantes de Pipeline
                                Note left of LibraryPipeline: Constantes que retorna <br> Pais = "HND" <br/> CodigoError = 0 <br/> MensajeError = "temp" 

                                API->>API: Construye request SP OSBRegistraReversaTC
                                Note right of API: Pais = "HND" <br> SecuenciaMovimiento = body.transactionReference <br> CodigoError = 0 <br/> MensajeError = temp 

                                API->>BD: Update BD - stateProcess = "REG_REVERSE_CC" and stateTransacción = "PENDING"

                                API->>SP2: Consume SP OSBRegistraReversaTC
                                Note right of API: Pais, SecuenciaMovimiento, CodigoError, MensajeError

                                SP2->>API: Response SP OSBRegistraReversaTC
                                Note left of SP2: successIndicator

                                API->>API: Evalúa Response OSBRegistraReversaTC 

                                alt Response Registra Reverso TC successIndicator != "SUCCESS"

                                    API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                    Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_financial_services_mgmt-comp-reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: TimeOut 

                                else Response Registra Reverso TC successIndicator = "SUCCESS"

                                    API->>BD: Update BD - stateProcess = "REG_REVERSE_CC" and stateTransacción = "COMPLETE"

                                    API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                    Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: payment_execution_admin-Product_authorize_reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: Exitosa

                                end
                            end
                        end
                    end
                end
                alt stateProcess = "REG_REVERSE" and stateTransacción = "PENDING"
                    rect rgba(246, 226, 236, 1)

                        API->>API: Construye request SP OSB_P_REGISTRA_REVERSION_TC_CB
                        Note over API: PV_TRANSACTION_ID = transactionReference

                        API->>BD: Update BD - stateProcess = "REG_REVERSE" and stateTransacción = "PENDING"

                        API->>SP1: Consume SP OSB_P_REGISTRA_REVERSION_TC_CB
                        Note right of API: PV_TRANSACTION_ID

                        SP1->>API: Response OSB_P_REGISTRA_REVERSION_TC_CB
                        Note left of SP1: successIndicator

                        API->>API: Evalúa Response OSB_P_REGISTRA_REVERSION_TC_CB 

                        alt Response Registra Reversión successIndicator != "SUCCESS"

                            API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                            Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_financial_services_mgmt-comp-reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: TimeOut 

                        else Response Registra Reversión successIndicator = "SUCCESS"

                            API->>BD: Update BD - stateProcess = "REG_REVERSE" and stateTransacción = "COMPLETE"

                            API->>LibraryPipeline: Consulta Constantes de Pipeline

                            LibraryPipeline->>API: Retorna Constantes de Pipeline
                            Note left of LibraryPipeline: Constantes que retorna <br> Pais = "HND" <br/> CodigoError = 0 <br/> MensajeError = "temp" 

                            API->>API: Construye request SP OSBRegistraReversaTC
                            Note right of API: Pais = "HND" <br> SecuenciaMovimiento = body.transactionReference <br> CodigoError = 0 <br/> MensajeError = temp 

                            API->>BD: Update BD - stateProcess = "REG_REVERSE_CC" and stateTransacción = "PENDING"

                            API->>SP2: Consume SP OSBRegistraReversaTC
                            Note right of API: Pais, SecuenciaMovimiento, CodigoError, MensajeError
                            
                            SP2->>API: Response SP OSBRegistraReversaTC
                            Note left of SP2: successIndicator

                            API->>API: Evalúa Response OSBRegistraReversaTC 

                            alt Response Registra Reverso TC successIndicator != "SUCCESS"

                                API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_financial_services_mgmt-comp-reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: TimeOut 

                            else Response Registra Reverso TC successIndicator = "SUCCESS"

                                API->>BD: Update BD - stateProcess = "REG_REVERSE_CC" and stateTransacción = "COMPLETE"

                                API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: payment_execution_admin-Product_authorize_reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: Exitosa

                            end
                        end
                    end
                end
                alt stateProcess = "REG_REVERSE_CC" and stateTransacción = "PENDING"
                    rect rgba(246, 242, 226, 1)
                        API->>LibraryPipeline: Consulta Constantes de Pipeline

                        LibraryPipeline->>API: Retorna Constantes de Pipeline
                        Note left of LibraryPipeline: Constantes que retorna <br> Pais = "HND" <br/> CodigoError = 0 <br/> MensajeError = "temp" 

                        API->>API: Construye request SP Registra Reverso TC
                        Note over API: Pais = "HND" <br> SecuenciaMovimiento = body.transactionReference <br> CodigoError = 0 <br/> MensajeError = temp 

                        API->>BD: Update BD - stateProcess = "REG_REVERSE_CC" and stateTransacción = "PENDING"

                        API->>SP2: Consume SP Registra Reverso TC
                        Note right of API: Pais, SecuenciaMovimiento, CodigoError, MensajeError
                        
                        SP2->>API: Response SP OSBRegistraReversaTC
                        Note left of SP2: successIndicator

                        API->>API: Evalúa Response OSBRegistraReversaTC 

                        alt Response Registra Reverso TC successIndicator != "SUCCESS"

                            API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                            Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_financial_services_mgmt-comp-reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: TimeOut 

                        else Response Registra Reverso TC successIndicator = "SUCCESS"

                            API->>BD: Update BD - stateProcess = "REG_REVERSE_CC" and stateTransacción = "COMPLETE"

                            API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                            Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: payment_execution_admin-Product_authorize_reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: Exitosa

                        end
                    end
                end
            end 
        else Transacción NO Existe en la BD
            rect rgba(232, 251, 230, 1)

                API->>Reversar: Consume API reversos
                Note right of API: SourceBank, transactionReference, transactionType

                Reversar->>API: Respose reversos
                Note left of Reversar: SuccessIndicator

                API->>API: Evalúa response reversos

                alt Response reversos NO Exitoso - successIndicator != "SUCCESS"
                    rect rgba(248, 238, 238, 1)
                        API->> Errors: Mapear código de error
                        Errors ->> API: Retorna código mapeado
                        API->> Consumidor: Retorna error
                        Note over Consumidor: "HTTP 422: Transacción No Reversada"
                    end
                else Response reversos Exitoso - successIndicator = "SUCCESS"

                    API->>BD: Insert BD - stateProcess = "AUTHORIZATION" and stateTransacción = "PENDING"

                    API->>Idempotencia: Consume API Idempotencia 
                    Note right of API: Mapeo de Campos: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_financial_services_mgmt-comp-reverse_transaction <br> "methodVersion": "1.0" <br> dataPayload: { transactionReference, transactionType}

                    API->>Idempotencia: Response API Idempotencia 

                    API->>AuthReversar: Consume Autorización Reverso
                    Note right of API: SourceBank, transactionReference, transactionType, retryRequired: false

                    AuthReversar->>API: Response Autorización Reverso
                    Note left of AuthReversar: SuccessIndicator

                    API->>API: Evalúa Response Autorización Reverso

                    alt Response Autoriza Reverso successIndicator != "SUCCESS"

                        API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                        Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_financial_services_mgmt-comp-reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: TimeOut 

                        API->>Errors: Mapea Error "Transacción en proceso"

                        Errors ->> API: Retorna código mapeado

                        API->>Consumidor: Retorna error controlado
                        Note over Consumidor: "Transacción en proceso"

                    else Response Autoriza Reverso successIndicator = "SUCCESS"

                        API->>BD: Update BD - stateProcess = "AUTHORIZATION" and stateTransacción = "COMPLETE"

                        API->>API: Construye request SP Registra Reversión
                        Note over API: PV_TRANSACTION_ID = transactionReference

                        API->>BD: Update BD - stateProcess = "REG_REVERSE" and stateTransacción = "PENDING"

                        API->>SP1: Consume SP Registra Reversión
                        Note right of API: PV_TRANSACTION_ID

                        SP1->>API: Response OSB_P_REGISTRA_REVERSION_TC_CB
                        Note left of SP1: successIndicator

                        API->>API: Evalúa Response OSB_P_REGISTRA_REVERSION_TC_CB 

                        alt Response Registra Reversión successIndicator != "SUCCESS"

                            API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                            Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_financial_services_mgmt-comp-reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: TimeOut 

                            API->>Errors: Mapea Error "Transacción en proceso"

                            Errors ->> API: Retorna código mapeado

                            API->>Consumidor: Retorna error controlado
                            Note over Consumidor: "Transacción en proceso"

                        else Response Registra Reversión successIndicator = "SUCCESS"

                            API->>BD: Update BD - stateProcess = "REG_REVERSE" and stateTransacción = "COMPLETE"

                            API->>LibraryPipeline: Consulta Constantes de Pipeline

                            LibraryPipeline->>API: Retorna Constantes de Pipeline
                            Note left of LibraryPipeline: Constantes que retorna <br> Pais = "HND" <br/> CodigoError = 0 <br/> MensajeError = "temp" 

                            API->>API: Construye request SP Registra Reverso TC
                            Note right of API: Pais = "HND" <br> SecuenciaMovimiento = body.transactionReference <br> CodigoError = 0 <br/> MensajeError = temp 

                            API->>BD: Update BD - stateProcess = "REG_REVERSE_CC" and stateTransacción = "PENDING"

                            API->>SP2: Consume SP OSBRegistraReversaTC
                            Note right of API: Pais, SecuenciaMovimiento, CodigoError, MensajeError

                            SP2->>API: Response SP OSBRegistraReversaTC
                            Note left of SP2: successIndicator

                            API->>API: Evalúa Response OSBRegistraReversaTC 

                            alt Response Registra Reverso TC successIndicator != "SUCCESS"

                                API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_financial_services_mgmt-comp-reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: TimeOut 

                                API->>Errors: Mapea Error "Transacción en proceso"

                                Errors ->> API: Retorna código mapeado

                                API->>Consumidor: Retorna error controlado
                                Note over Consumidor: "Transacción en proceso"

                            else Response Registra Reverso TC successIndicator = "SUCCESS"

                                API->>BD: Update BD - stateProcess = "REG_REVERSE_CC" and stateTransacción = "COMPLETE"
                                
                                API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: payment_execution_admin-Product_authorize_reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: Exitosa

                                API->>Consumidor: API Response
                                Note over Consumidor: "HTTP 200: Transacción Reversada Exitosamente"
                            end
                        end
                    end
                end 
            end
        end
    end

    activate API
    alt Exception occurs
        note over Errors: Error Library Handler
        activate Errors
            API->> Errors: Mapear código de error
            Errors -->> API: Retorna código mapeado
        deactivate Errors
        activate Consumidor
            API-->> Consumidor: Retorna error
        deactivate Consumidor
        Note over Consumidor,Errors: Diagrama guía de manejo de errores <br> http://bit.ly/4rpKVIU
    end
    deactivate API