sequenceDiagram
    autonumber
    participant Consumidor as Consumidore/Aplicación
    participant API as API Reverso Pago Cheque
    participant UUID as Generar UUID <br/> Librería de generación de UUID
    participant Wrapper T24 as Wrapper T24 <br> svcResversaTransaccion <br> Operation: ReversiondePagodeCheques
    participant Reintentos as Manejo de reintentos <br/> Componente de idempotencia

    Note over Consumidor, Reintentos: Flujo Honduras (HN01) - Reversar Pago Cheque

    alt Reverso Exitoso
        Consumidor->>API: Rest Request
        Note right of Consumidor: Header: SourceBank=HN01<br/>Body: TRANSACTION_ID, TRANSACTION_TYPE

        API->>API: Validar Rquest
        Note right of API: Validar campos según contrato OpenAPI

        API->>API: Validación exitosa

        API->>API: Validar Servicio Regional
        Note right of API: key de config: XXXXXXXX
        
        API->>API: Validación Regional Exitosa
        Note right of API: Servicio habilitado para HN01

        API->>API: Validación Exitosa

        API->>Consumidor: Response Exitoso
        Note left of API: code: 202 <br> successIndicator: SUCCESS <br/> Body: Transacción recibida para reverso

        API->>UUID: Solicitar UUID
        UUID-->>API: Retorna UUID

        API->>API: Construir Request a Wrapper T24
        Note right of API: trxId = TRANSACTION_ID<br/>transactionType = TRANSACTION_TYPE <br/>requestUUID = UUID generado

        API->>Wrapper T24: CALL ReversiondePagodeCheques
        Note left of Wrapper T24: El mapeo es exactamente igual al request recibido<br/>por la API, solo se agrega el requestUUID

        Wrapper T24-->>API: Response Reversión Cheque

        API->>API: Procesar Response
        Note right of API: Determinar successIndicator

    end 

    activate API
    alt Envío para reintentos
    note over API, Reintentos: ¿¿¿¿Como se maneja el envío a reintentos???
        activate Reintentos
            API->> Reintentos: Envíar información al componente de reintentos
            Reintentos -->> API: Existe respuesta o se envía a una cola para reintentos???
        deactivate Reintentos
    end
    deactivate API