sequenceDiagram
    autonumber
    participant Consumidor as Consumidore/Aplicación
    participant API as API Reverso Transacciones <br> Epica 2490: ReversarTransaccion <br> HU 6664: <br> POST: /payments/payment-execution-admin/v1/reverse-transaction 
    participant CL as Caché Local
    participant Lambda as Lambda de Parámetros
    participant WT24 as Wrapper T24 <br> svcResversaTransaccion/services
    participant Errors as Control de Errores <br/> <<Librería de mapeo de errores>>

    Note over Consumidor, Errors: Flujo Honduras (HN01) - Reversar Pago Cheque

    alt Reverso Exitoso
        Consumidor->>API: Rest Request
        Note right of Consumidor: Header: SourceBank=HN01<br/>Body: transactionReference, transactionType, paymentMethod

        API->>API: Validar Rquest
        Note over  API: Validar obligatoriedad campos según contrato OpenAPI <br/> transactionReference != vacío <br> transactionType (Presente)

        API->>API: Validación exitosa

        API->>API: Validar Servicio Regional
        Note over API: key de config: PAYMENT_EXECUTION_ADMIN
        
        API->>API: Validación Regional Exitosa
        Note over API: Servicio habilitado para HN01

        API->>API: Determinar tipo de transacción
        Note over API: Substring transactionReference: <br> trxType2: substr(transactionReference 1, 2) <br> trxType3: substr(transactionReference 1, 3)

        alt Consulta información de operación a consumir en caché local

            API->>CL: Consultar información de operación a consumir
            Note right of API: country = Header. SourceBank <br> value.transactionType = Body.transactionType <br> 

            CL->>API: Retorna información de operación a consumir
            Note left of CL: value.transactionType.operations

        else Consulta información de operación a consumir con Lambda Parámetros

            API->>Lambda: Consultar información de operación a consumir
            Note right of API: country = Header. SourceBank <br> value.transactionType = Body.transactionType <br> 

            Lambda->>API: Retorna información de operación a consumir
            Note left of Lambda: value.transactionType.operations

            API->>CL: Guarda información de las operaciones en caché local
            Note right of API: country = Header. SourceBank <br> value.transactionType = Body.transactionType <br> 
        end
        
        API->>API: Evalua información de operación a consumir

        API->>API: Construir Request a WT24
        Note over API: Trasnsactionid = transactionReference <br> message = header.Correlation-Id (Opcional)

        API->>WT24: CALL Operación T24
        Note right of API: Trasnsactionid

        WT24->>API: Response Reversión Trasnacción
        Note left of WT24: successIndicator

        API->>API: count response "tellerType"
        Note over API: Si tellerType > 0 entonces <br> response.body.data.tellerType = true

        API->>Consumidor: REST Response exitoso
        Note right of Consumidor: body.data <br> transactionReference <br> transactionType <br> transactionDate <br> tellerType
    end 

    activate API
    alt Exception occurs
        note over Errors: Error Library Handler
        activate Errors
            API->> Errors: Mapear código de error
            Errors -->> API: Retorna código mapeado
        deactivate Errors
        activate Consumidor
            API-->> Consumidor: Retorna error
        deactivate Consumidor
        Note over Consumidor,Errors: Diagrama guía de manejo de errores <br> http://bit.ly/4rpKVIU
    end
    deactivate API
