sequenceDiagram
    autonumber
    participant Consumidor as Consumidor/Aplicación
    participant API as API Reversar TransactionCollection <br> Epica 2490: ReversarTransaccion <br> HU 6670: <br> POST: /transaction-collection-mgmt/v1/reverse-transaction
    participant Reversar as HU 6664 <br> API Reversos <br> POST: /payments/payment-execution-admin/v1/reverse-transaction 
    participant AuthReversar as HU 6627 <br> API Autorizar Reversos <br> POST: /payments/payment-execution-admin/v1/authorize-reverse-transaction 
    participant Consulta as HU 5388 <br> API Consulta Detalle Transacción <br> POST: /payments/payment-execution-retrieves/v1/retrieve-transaction-details
    participant BD as DynamoDB <br> Registro Transacciones
    participant Idempotencia as Componente de Idempotencia <br> POST: integrity-handler/v1/idempotency/generate
    participant SP1 as SP: REVERSION_COBRANZA <br/> ConnectionWebServices <br> PackageName: OSB_K_COBRANZA_ABANKS
    participant Eliminar as HU 6653 <br/> API Eliminar Pago Recaudo <br> POST: /payments/payment-execution-admin/v1/reverse-transaction-payment
    participant Reintentos as EventBridge <br> Componente de Reintentos
    participant Errors as Control de Errores <br/> <<Librería de mapeo de errores>>
    
    Note over Consumidor, Errors: Flujo Honduras (HN01) - Reversar Pago Tarjeta de Crédito TFS

    Consumidor->>API: Rest Request
    Note right of Consumidor: Header: SourceBank=HN01<br/>Body: transactionReference, transactionType

    API->>API: Validar Request
    Note over  API: Validar obligatoriedad campos según contrato OpenAPI <br/> transactionReference != vacío <br> transactionType = "REF_COLLECTION o <br> ABANKS_COLLECTION o <br> PROPTAX_COLLECTION o <br> ONLINE_COLLECTION o <br> LOCAL_COLLECTION"

    API->>API: Validación exitosa

    API->>API: Validar Servicio Regional
    Note over API: key de config: TRANSACTION_FINANCIAL_SERVICES_MANAGEMENT
    
    API->>API: Validación Regional Exitosa
    Note over API: Servicio habilitado para HN01

    API->>API: Validación Exitosa

    API->>API: Determinar tipo de transacción
    Note over API: Substring transactionReference: <br> trxType2: substr(transactionReference 1, 2)

    API->>API: Validar transactionType y trxType2
    
    alt Si transactionType = ABANKS_COLLECTION | PROPTAX_COLLECTION | ONLINE_COLLECTION | LOCAL_COLLECTION and trxType2 = " "
        rect rgba(248, 238, 238, 1)
            API->>Errors: Mapea Error "Tipo de transacción inválida"

            Errors ->> API: Retorna código mapeado

            API->>Consumidor: Retorna error controlado
            Note over Consumidor: "Tipo de transacción inválida"
        end

    end

    API->>BD: Consulta transacción en BD
    Note right of API: SourceBank, transactionReference, transactionType

    BD->>API: Resultado Consulta transacción en BD

    API->>API: Evalúa resultado de la consulta a la BD

    alt Si transactionType = REF_COLLECTION and trxType2 = " "
        rect rgba(242, 248, 222, 1)
            alt Transacción existe en la BD
                rect rgba(248, 246, 246, 1)

                    API->>Consumidor: API Response
                    Note over Consumidor: "HTTP 202: Transacción Recibida Exitosamente"

                    API->>API: Determina paso que debe ejecutar

                    alt Si stateProcess = "AUTHORIZATION"" and stateTransacción = "PENDING"

                        API->>AuthReversar: Consume Autorización Reverso
                        Note right of API: SourceBank, transactionReference, transactionType, retryRequired: true

                        AuthReversar->>API: Response Autorización Reverso
                        Note left of AuthReversar: SuccessIndicator

                        API->>API: Evalúa Response Autorización Reverso

                        alt Response Autoriza Reverso successIndicator != "SUCCESS"

                            API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                            Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_collection_mgmt-comp_reverse_transaction <br> detail-type: "provider.response" <br> request: { transactionReference, transactionType} <br> Transaccion: TimeOut 
                        
                        else Response Autoriza Reverso Exitoso - successIndicator = "SUCCESS"

                            API->>BD: Update BD - stateProcess = "AUTHORIZATION" and stateTransacción = "COMPLETE"

                            API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                            Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: payment_execution_admin-Product_authorize_reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: Exitosa

                        end
                    end
                end

            else Transacción NO existe en la BD
                rect rgba(248, 246, 246, 1)
                    API->>Reversar: Consume API reversos
                    Note right of API: SourceBank, transactionReference, transactionType

                    Reversar->>API: Respose reversos
                    Note left of Reversar: SuccessIndicator

                    API->>API: Evalúa response reversos

                    alt Response reversos NO Exitoso - successIndicator != "SUCCESS"
                        rect rgba(248, 238, 238, 1)
                            API->> Errors: Mapear código de error
                            Errors ->> API: Retorna código mapeado
                            API->> Consumidor: Retorna error
                            Note over Consumidor: "HTTP 422: Transacción No Reversada"
                        end
                    else Response reversos Exitoso - successIndicator = "SUCCESS"

                        API->>BD: Insert BD - stateProcess = "AUTHORIZATION" and stateTransacción = "PENDING"

                        API->>Idempotencia: Consume API Idempotencia 
                        Note right of API: Mapeo de Campos: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_collection_mgmt-comp_reverse_transaction <br> "methodVersion": "1.0" <br> dataPayload: { transactionReference, transactionType}

                        Idempotencia->>API: Response API Idempotencia 

                        API->>AuthReversar: Consume Autorización Reverso
                        Note right of API: SourceBank, transactionReference, transactionType, retryRequired: true

                        AuthReversar->>API: Response Autorización Reverso
                        Note left of AuthReversar: SuccessIndicator

                        API->>API: Evalúa Response Autorización Reverso

                        alt Response Autoriza Reverso successIndicator != "SUCCESS"

                            API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                            Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_collection_mgmt-comp_reverse_transaction <br> detail-type: "provider.response" <br> request: { transactionReference, transactionType} <br> Transaccion: TimeOut 

                            API->>Errors: Mapea Error "Transacción en proceso"

                            Errors ->> API: Retorna código mapeado

                            API->>Consumidor: Retorna error controlado
                            Note over Consumidor: "HTTP 202: Transacción en proceso"
                        
                        else Response Autoriza Reverso Exitoso - successIndicator = "SUCCESS"

                            API->>BD: Update BD - stateProcess = "AUTHORIZATION" and stateTransacción = "COMPLETE"

                            API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                            Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: payment_execution_admin-Product_authorize_reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: Exitosa

                            API->>Consumidor: API Response
                            Note over Consumidor: "HTTP 200: Transacción Reversada Exitosamente"

                        end
                    end
                end
            end
        end
    end

    alt Si transactionType = REF_COLLECTION | PROPTAX_COLLECTION | ONLINE_COLLECTION | LOCAL_COLLECTION and trxType2 = "TT" | "FT"
        rect rgba(252, 240, 203, 1)

            API->>API: Construye Request API Consulta Detalle Transacción
            Note over API: SourceBank, criteriaValue = transactionReference

            API->>Consulta: API Consulta Detalle Transacción
            Note right of API: SourceBank, criteriaValue

            Consulta->>API: Respose Consulta Detalle Transacción
            Note left of Consulta: data.transactions.paymentMethod

            API->>API: Evalúa response Consulta Detalle Transacción

            alt Response Consulta Detalle Transacción NO Exitoso
                rect rgba(248, 238, 238, 1)
                    API->> Errors: Mapear código de error
                    Errors ->> API: Retorna código mapeado
                    API->> Consumidor: Retorna error
                    Note over Consumidor: "HTTP 422: Transacción No Encontrada"
                end

            else Response Consulta Detalle Transacción Exitoso
                
                API->>Reversar: Consume API reversos
                Note right of API: SourceBank, transactionReference, transactionType, paymentMethod

                Reversar->>API: Respose reversos
                Note left of Reversar: SuccessIndicator

                API->>API: Evalúa response reversos

                alt Response reversos NO Exitoso - successIndicator != "SUCCESS"
                    rect rgba(248, 238, 238, 1)
                        API->> Errors: Mapear código de error
                        Errors ->> API: Retorna código mapeado
                        API->> Consumidor: Retorna error
                        Note over Consumidor: "HTTP 422: Transacción No Reversada"
                    end
                
                else Response reversos Exitoso - successIndicator = "SUCCESS"

                    API->>Consumidor: API Response
                    Note over Consumidor: "HTTP 200: Transacción Reversada Exitosamente"

                end
            end
        end
    end

    alt Si transactionType = ABANKS_COLLECTION and trxType2 = "TT" | "FT"
        rect rgba(199, 217, 245, 1)

            alt Transacción existe en la BD
                rect rgba(251, 210, 240, 1)

                    API->>Consumidor: API Response
                    Note over Consumidor: "HTTP 202: Transacción Recibida Exitosamente"
                    
                    API->>API: Determina paso que debe ejecutar

                    alt Si stateProcess = "REVERSE_COLLECTION_SP"" and stateTransacción = "PENDING"
                        rect rgba(238, 238, 238, 1)

                            API->>API: Construye request SP REVERSION_COBRANZA
                            Note over API: PV_USUARIO = JWT.User <br> PV_AGENCIA = header.channel <br> PV_TRANSACCION = body.transactionReference <br> PV_FECHA = currentDate (YYYYMMDD)
                            
                            API->>SP1: Consume SP REVERSION_COBRANZA
                            Note right of API: PV_USUARIO, PV_AGENCIA, PV_TRANSACCION, PV_FECHA

                            SP1->>API: Respose SP REVERSION_COBRANZA
                            Note left of SP1: SuccessIndicatorAbanks

                            API->>API: Evalúa response SP REVERSION_COBRANZA

                            alt Response SP REVERSION_COBRANZA NO Exitoso - SuccessIndicatorAbanks = "0"

                                API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_collection_mgmt-comp_reverse_transaction <br> detail-type: "provider.response" <br> request: { transactionReference, transactionType} <br> Transaccion: TimeOut 

                            else Response SP REVERSION_COBRANZA Exitoso - SuccessIndicatorAbanks != "0"

                                API->>BD: Update BD - stateProcess = "REVERSE_COLLECTION_SP"" and stateTransacción = "COMPLETE"

                                API->>API: Construye Request API EliminarPagoRecaudo

                                API->>BD: Update BD - stateProcess = "DELETE_COLLECTION" and stateTransacción = "PENDING"

                                API->>Eliminar: Consume API EliminarPagoRecaudo
                                Note right of API: transactionReference, transactionType, tellerType

                                Eliminar->>API: Response API EliminarPagoRecaudo
                                Note left of Eliminar: successIndicator

                                API->>API: Evalúa response API EliminarPagoRecaudo

                                alt Response API EliminarPagoRecaudo NO Exitoso - SuccessIndicator != "SUCCESS"

                                    API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                    Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_collection_mgmt-comp_reverse_transaction <br> detail-type: "provider.response" <br> request: { transactionReference, transactionType} <br> Transaccion: TimeOut 

                                else Response API EliminarPagoRecaudo Exitoso - SuccessIndicator = "SUCCESS"

                                    API->>BD: Update BD - stateProcess = "DELETE_COLLECTION" and stateTransacción = "COMPLETE"

                                    API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                    Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: payment_execution_admin-Product_authorize_reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: Exitosa

                                end
                            end
                        end
                    end
                    alt Si stateProcess = "DELETE_COLLECTION"" and stateTransacción = "PENDING"
                        rect rgba(225, 252, 202, 1)

                            API->>API: Construye Request API EliminarPagoRecaudo

                            API->>Eliminar: Consume API EliminarPagoRecaudo
                            Note right of API: transactionReference, transactionType, tellerType

                            Eliminar->>API: Response API EliminarPagoRecaudo
                            Note left of Eliminar: successIndicator

                            API->>API: Evalúa response API EliminarPagoRecaudo

                            alt Response API EliminarPagoRecaudo NO Exitoso - SuccessIndicator != "SUCCESS"

                                API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_collection_mgmt-comp_reverse_transaction <br> detail-type: "provider.response" <br> request: { transactionReference, transactionType} <br> Transaccion: TimeOut 

                            else Response API EliminarPagoRecaudo Exitoso - SuccessIndicator = "SUCCESS"

                                API->>BD: Update BD - stateProcess = "DELETE_COLLECTION" and stateTransacción = "COMPLETE"

                                API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: payment_execution_admin-Product_authorize_reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: Exitosa

                            end
                        end
                    end
                end
            else Transacción NO existe en la BD
                rect rgba(232, 255, 252, 1)

                    API->>API: Construye Request API Consulta Detalle Transacción
                    Note over API: SourceBank, criteriaValue = transactionReference

                    API->>Consulta: API Consulta Detalle Transacción
                    Note right of API: SourceBank, criteriaValue

                    Consulta->>API: Respose Consulta Detalle Transacción
                    Note left of Consulta: data.transactions.paymentMethod

                    API->>API: Evalúa response Consulta Detalle Transacción

                    alt Response Consulta Detalle Transacción NO Exitoso
                        rect rgba(248, 238, 238, 1)
                            API->> Errors: Mapear código de error
                            Errors ->> API: Retorna código mapeado
                            API->> Consumidor: Retorna error
                            Note over Consumidor: "HTTP 422: Transacción No Encontrada"
                        end

                    else Response Consulta Detalle Transacción Exitoso
                        
                        API->>Reversar: Consume API reversos
                        Note right of API: SourceBank, transactionReference, transactionType, paymentMethod

                        Reversar->>API: Respose reversos
                        Note left of Reversar: SuccessIndicator

                        API->>API: Evalúa response reversos

                        alt Response reversos NO Exitoso - successIndicator != "SUCCESS"
                            rect rgba(248, 238, 238, 1)
                                API->> Errors: Mapear código de error
                                Errors ->> API: Retorna código mapeado
                                API->> Consumidor: Retorna error
                                Note over Consumidor: "HTTP 422: Transacción No Reversada"
                            end
                        else Response reversos Exitoso - successIndicator = "SUCCESS"

                            API->>BD: Insert BD - stateProcess = "REVERSE_COLLECTION_SP" and stateTransacción = "PENDING", paymentMethod = response.retrieve-transaction-details.paymentMethod

                            API->>Idempotencia: Consume API Idempotencia 
                            Note right of API: Mapeo de Campos: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_collection_mgmt-comp_reverse_transaction <br> "methodVersion": "1.0" <br> dataPayload: { transactionReference, transactionType}

                            Idempotencia->>API: Response API Idempotencia 

                            API->>API: Construye request SP REVERSION_COBRANZA
                            Note over API: PV_USUARIO = JWT.User <br> PV_AGENCIA = header.channel <br> PV_TRANSACCION = body.transactionReference <br> PV_FECHA = currentDate (YYYYMMDD)
                            
                            API->>SP1: Consume SP REVERSION_COBRANZA
                            Note right of API: PV_USUARIO, PV_AGENCIA, PV_TRANSACCION, PV_FECHA

                            SP1->>API: Respose SP REVERSION_COBRANZA
                            Note left of SP1: SuccessIndicatorAbanks

                            API->>API: Evalúa response SP REVERSION_COBRANZA

                            alt Response SP REVERSION_COBRANZA NO Exitoso - SuccessIndicatorAbanks = "0"

                                API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_collection_mgmt-comp_reverse_transaction <br> detail-type: "provider.response" <br> request: { transactionReference, transactionType} <br> Transaccion: TimeOut 

                                API->>Errors: Mapea Error "Transacción en proceso"

                                Errors ->> API: Retorna código mapeado

                                API->>Consumidor: Retorna error controlado
                                Note over Consumidor: "HTTP 202: Transacción en proceso"

                            else Response SP REVERSION_COBRANZA Exitoso - SuccessIndicatorAbanks != "0"

                                API->>BD: Update BD - stateProcess = "REVERSE_COLLECTION_SP"" and stateTransacción = "COMPLETE"

                                API->>API: Construye Request API EliminarPagoRecaudo

                                API->>BD: Update BD - stateProcess = "DELETE_COLLECTION" and stateTransacción = "PENDING"

                                API->>Eliminar: Consume API EliminarPagoRecaudo
                                Note right of API: transactionReference, transactionType, tellerType

                                Eliminar->>API: Response API EliminarPagoRecaudo
                                Note left of Eliminar: successIndicator

                                API->>API: Evalúa response API EliminarPagoRecaudo

                                alt Response API EliminarPagoRecaudo NO Exitoso - SuccessIndicator != "SUCCESS"

                                    API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                    Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: transaction_collection_mgmt-comp_reverse_transaction <br> detail-type: "provider.response" <br> request: { transactionReference, transactionType} <br> Transaccion: TimeOut 

                                    API->>Errors: Mapea Error "Transacción en proceso"

                                    Errors ->> API: Retorna código mapeado

                                    API->>Consumidor: Retorna error controlado
                                    Note over Consumidor: "HTTP 202: Transacción en proceso"
                                    
                                else Response API EliminarPagoRecaudo Exitoso - SuccessIndicator = "SUCCESS"

                                    API->>BD: Update BD - stateProcess = "DELETE_COLLECTION" and stateTransacción = "COMPLETE"

                                    API->>Reintentos: Envía envento al eventBridge API Idempotencia 
                                    Note right of API: Mensaje: <br> Correlation-Id: header.Correlation-Id <br> Caller-Service: payment_execution_admin-Product_authorize_reverse_transaction <br> detail-type: "provider.response" <br> request: {transactionReference, transactionType} <br> Transaccion: Exitosa

                                    API->>Consumidor: API Response
                                    Note over Consumidor: "HTTP 200: Transacción Reversada Exitosamente" 

                                end
                            end
                        end
                    end
                end
            end
        end
    end    

    activate API
    alt Exception occurs
        note over Errors: Error Library Handler
        activate Errors
            API->> Errors: Mapear código de error
            Errors -->> API: Retorna código mapeado
        deactivate Errors
        activate Consumidor
            API-->> Consumidor: Retorna error
        deactivate Consumidor
        Note over Consumidor,Errors: Diagrama guía de manejo de errores <br> http://bit.ly/4rpKVIU
    end
    deactivate API