<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions 
	name="consultaTasaPromedioPS"
	targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaTasaPromedioPS/"
	xmlns:con="http://www.ficohsa.com.hn/middleware.services/consultaTasaPromedioPS/" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"  
	xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" 
	xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaTasaPromedioTypes"
>
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	    </xsd:schema>      
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaTasaPromedioTypes" schemaLocation="../xsd/consultaTasaPromedioTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="consultaTasaPromedioRequest">
		<wsdl:part element="cons:consultaTasaPromedioRequest" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
 	<wsdl:message name="consultaTasaPromedioResponse">
		<wsdl:part element="cons:consultaTasaPromedioResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaTasaPromedioPS">
		<wsdl:operation name="consultaTasaPromedio" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="con:consultaTasaPromedioRequest"/>
			<wsdl:output message="con:consultaTasaPromedioResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaTasaPromedioPSSOAP" type="con:consultaTasaPromedioPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaTasaPromedio">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaTasaPromedioPS"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="con:consultaTasaPromedioRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="con:consultaTasaPromedioResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaTasaPromedioPS">
		<wsdl:port binding="con:consultaTasaPromedioPSSOAP" name="consultaTasaPromedioPSSOAP">
	    	<soap:address location="https://mwomnicanal:8004/Middleware/OperationsAndExecution/ConsumerService/ConsultaTasaPromedio"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
