<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/conDatosPlanes/conDatosPlanes" name="conDatosPlanes-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/conDatosPlanes/conDatosPlanes" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/conDatosPlanes/conDatosPlanes" location="conDatosPlanes.wsdl"/>
  <binding name="conDatosPlanes_ptt-binding" type="tns:conDatosPlanes_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conDatosPlanes">
      <soap:operation soapAction="conDatosPlanes"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conDatosPlanes-service">
    <port name="conDatosPlanes-port" binding="tns:conDatosPlanes_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>