<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/DataWareHouse/CustomerOpi_BS" name="CustomerOpi_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CustomerOpi_BS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/DataWareHouse/CustomerOpi_BS"/>
    <wsdl:binding name="CustomerOpi_BS_ptt-binding" type="cus:CustomerOpi_BS_ptt" xmlns:cus="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/DataWareHouse/CustomerOpi_BS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CustomerOpi_BS">
            <soap:operation soapAction="CustomerOpi_BS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>