<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DepositoReferenciados/MasterDataGT/eCInsRequestControl" name="eCInsRequestControl-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DepositoReferenciados/MasterDataGT/eCInsRequestControl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DepositoReferenciados/MasterDataGT/eCInsRequestControl" location="eCInsRequestControl.wsdl"/>
  <binding name="eCInsRequestControl_ptt-binding" type="tns:eCInsRequestControl_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="eCInsRequestControl">
      <soap:operation soapAction="eCInsRequestControl"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="eCInsRequestControl-service">
    <port name="eCInsRequestControl-port" binding="tns:eCInsRequestControl_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetasGT"/>
    </port>
  </service>
</definitions>