<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/registrarBitacoraRemesasGravadasNI_db/registrarBitacoraRemesasGravadasNI_db/registrarBitacoraRemesasGravadas_db" name="registrarBitacoraRemesasGravadas_db-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/registrarBitacoraRemesasGravadasNI_db/registrarBitacoraRemesasGravadasNI_db/registrarBitacoraRemesasGravadas_db" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/registrarBitacoraRemesasGravadasNI_db/registrarBitacoraRemesasGravadasNI_db/registrarBitacoraRemesasGravadas_db" location="../wsdl/registrarBitacoraRemesasGravadas_db.wsdl"/>
  <binding name="registrarBitacoraRemesasGravadas_db_ptt-binding" type="tns:registrarBitacoraRemesasGravadas_db_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registrarBitacoraRemesasGravadas_db">
      <soap:operation soapAction="registrarBitacoraRemesasGravadas_db"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registrarBitacoraRemesasGravadas_db-service">
    <port name="registrarBitacoraRemesasGravadas_db-port" binding="tns:registrarBitacoraRemesasGravadas_db_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConveniosNI"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="../wsdl/registrarBitacoraRemesasGravadas_db.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/registrarBitacoraRemesasGravadasNI_db/registrarBitacoraRemesasGravadasNI_db/registrarBitacoraRemesasGravadas_db">
            <con:wsdl ref="Middleware/v2/BusinessServices/registrarBitacoraRemesasGravadasNI/wsdl/registrarBitacoraRemesasGravadas_db"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/registrarBitacoraRemesasGravadasNI_db/registrarBitacoraRemesasGravadasNI_db/registrarBitacoraRemesasGravadas_db</con:targetNamespace>
</con:wsdlEntry>