<wsdl:definitions name="sjConsultaSaldosTCPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaSaldosTCPS" xmlns:tns="SplitJoinTest" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/sjConsultaSaldosTCPS" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/sjConsultaSaldosTC" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

<wsdl:types>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaSaldosTC" schemaLocation="../xsd/sjConsultaSaldosTC.xsd"/>
	</xsd:schema>
</wsdl:types>
    
<wsdl:message name="sjConsultaSaldosTCRequest">
	<wsdl:part name="inputParameters" element="cons:sjConsultaSaldosTC"/>
</wsdl:message>
<wsdl:message name="sjConsultaSaldosTCResponse">
	<wsdl:part name="outputParameters" element="cons:sjConsultaSaldosTCResponse"/>
</wsdl:message>

<wsdl:portType name="sjConsultaSaldosTCPS">
	<wsdl:operation name="ConsultaSaldosTC">
		<wsdl:input message="fic:sjConsultaSaldosTCRequest"/>
		<wsdl:output message="fic:sjConsultaSaldosTCResponse"/>		
	</wsdl:operation>
</wsdl:portType>

<wsdl:binding name="sjConsultaSaldosTCPSSOAP" type="fic:sjConsultaSaldosTCPS">
	<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
	<wsdl:operation name="ConsultaSaldosTC">
		<wsdl:input>
			<soap:body parts="inputParameters" use="literal"/>
		</wsdl:input>
		<wsdl:output>
			<soap:body parts="outputParameters" use="literal"/>		
		</wsdl:output>
	</wsdl:operation>
</wsdl:binding>

<wsdl:service name="sjConsultaSaldosTCPS">
	<wsdl:port name="jConsultaSaldosTCPSSOAP" binding="fic:sjConsultaSaldosTCPSSOAP">
		<soap:address location="http://10.242.104.250:8003/Middleware/SJS/consultaSaldosTC"/>
	</wsdl:port>
</wsdl:service>

</wsdl:definitions>