<wsdl:definitions targetNamespace="http://www.ficohsa.com.hn/middleware.services/pushProvisioningNotification/" name="pushProvisioningNotificationPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/pushProvisioningNotification/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:com="http://www.ficohsa.com.hn/middleware.services/digitalizacionTarjetasTypes">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/digitalizacionTarjetasTypes" schemaLocation="../../DigitalizacionTarjetas/xsd/digitalizacionTarjetasTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="pushProvisioningNotification">
		<wsdl:part element="com:pushProvisioningNotification" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="pushProvisioningNotificationResponse">
		<wsdl:part element="com:pushProvisioningNotificationResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="pushProvisioningNotificationPS">
		<wsdl:operation name="pushProvisioningNotification" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:pushProvisioningNotification"/>
			<wsdl:output message="fic:pushProvisioningNotificationResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="pushProvisioningNotificationPSSOAP" type="fic:pushProvisioningNotificationPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="pushProvisioningNotification">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/pushProvisioningNotification"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:pushProvisioningNotification" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:pushProvisioningNotificationResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="pushProvisioningNotificationPS">
		<wsdl:port binding="fic:pushProvisioningNotificationPSSOAP" name="pushProvisioningNotificationPSSOAP">
			<soap:address location="http://mwomnicanal:8003/Middleware/OperationsAndExecution/pushProvisioningNotification"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>