<wsdl:definitions name="consultaFondosPensionesClientePS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaFondosPensionesClientePS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaFondosPensionesClientePS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:con="http://www.ficohsa.com.hn/middleware.services/consultaFondosPensionesClienteTypes" xmlns:aut="http://www.ficohsa.com.hn/middleware.services/autType">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
			</xsd:schema>
			<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaFondosPensionesClienteTypes" schemaLocation="../xsd/consultaFondosPensionesClienteTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	
	<wsdl:message name="consultaFondosPensionesClientePSRequest">
		<wsdl:part name="reqHeader" element="aut:RequestHeader"/>
		<wsdl:part name="inputParameters" element="con:consultaFondosPensionesClienteRequest"/>
	</wsdl:message>
	<wsdl:message name="consultaFondosPensionesClientePSResponse">
		<wsdl:part name="rspHeader" element="aut:ResponseHeader"/>
		<wsdl:part name="outputResult" element="con:consultaFondosPensionesClienteResponse"/>
	</wsdl:message>
	
	
	<wsdl:portType name="consultaFondosPensionesClientePS">
		<wsdl:operation name="consultaFondosPensionesCliente">
			<wsdl:input message="fic:consultaFondosPensionesClientePSRequest"/>					
			<wsdl:output message="fic:consultaFondosPensionesClientePSResponse"/>
		</wsdl:operation>
	</wsdl:portType>


	<wsdl:binding name="consultaFondosPensionesClientePSSOAP" type="fic:consultaFondosPensionesClientePS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.com/soap/http"/>
		<wsdl:operation name="consultaFondosPensionesCliente">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/ConsultaFondosPensionesClientePS/consultaFondosPensionesCliente"/>
			<wsdl:input>
				<soap:header use="literal" part="reqHeader" message="fic:consultaFondosPensionesClientePSRequest"/>
				<soap:body use="literal" parts="inputParameters"/>						
			</wsdl:input>
			<wsdl:output>
				<soap:header use="literal" part="rspHeader" message="fic:consultaFondosPensionesClientePSResponse"/>
				<soap:body use="literal" parts="outputResult"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  
	<wsdl:service name="ConsultaFondosPensionesClientePS">
		<wsdl:port name="consultaFondosPensionesClientePSSOAP" binding="fic:consultaFondosPensionesClientePSSOAP">
			<soap:address location="http://10.9.104.55:8003/Middleware/ReferenceData/BusinessPartner/ConsultaFondosPensionesCliente"/>		
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>