<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/consultaControlSistema/consultaValidaMasterData" name="consultaValidaMasterData-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/consultaControlSistema/consultaValidaMasterData" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/consultaControlSistema/consultaValidaMasterData" location="consultaValidaMasterData.wsdl"/>
  <binding name="consultaValidaMasterData_ptt-binding" type="tns:consultaValidaMasterData_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaValidaMasterData">
      <soap:operation soapAction="consultaValidaMasterData"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaValidaMasterData-service">
    <port name="consultaValidaMasterData-port" binding="tns:consultaValidaMasterData_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>