<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/movilCheckAvailableCards/movilCheckAvailableCards/movilCheckAvailableCards" name="movilCheckAvailableCards-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/movilCheckAvailableCards/movilCheckAvailableCards/movilCheckAvailableCards" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/movilCheckAvailableCards/movilCheckAvailableCards/movilCheckAvailableCards" location="movilCheckAvailableCards.wsdl"/>
  <binding name="movilCheckAvailableCards_ptt-binding" type="tns:movilCheckAvailableCards_ptt">
  	<soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
  	<operation name="movilCheckAvailableCards">
  		<soap:operation soapAction="movilCheckAvailableCards"/>
  		<input>
  			<soap:body use="literal"/>
  		</input>
  		<output>
  			<soap:body use="literal"/>
  		</output>
  	</operation>
  </binding>
  <service name="movilCheckAvailableCards-service">
    <port name="movilCheckAvailableCards-port" binding="tns:movilCheckAvailableCards_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionDigitalizacionTarjetas"/>
    </port>
  </service>
</definitions>