<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/registroNuevoACHRecibido/registroNuevoACHRecibido" name="registroNuevoACHRecibido-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/registroNuevoACHRecibido/registroNuevoACHRecibido" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/registroNuevoACHRecibido/registroNuevoACHRecibido" location="registroNuevoACHRecibido.wsdl"/>
  <binding name="registroNuevoACHRecibido_ptt-binding" type="tns:registroNuevoACHRecibido_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registroNuevoACHRecibido">
      <soap:operation soapAction="registroNuevoACHRecibido"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registroNuevoACHRecibido-service">
    <port name="registroNuevoACHRecibido-port" binding="tns:registroNuevoACHRecibido_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>