<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerDescripcion/ObtenerDescripcion/ObtenerDescripcion" name="ObtenerDescripcion-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerDescripcion/ObtenerDescripcion/ObtenerDescripcion" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerDescripcion/ObtenerDescripcion/ObtenerDescripcion" location="ObtenerDescripcion.wsdl"/>
  <binding name="ObtenerDescripcion_ptt-binding" type="tns:ObtenerDescripcion_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ObtenerDescripcion">
      <soap:operation soapAction="ObtenerDescripcion"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ObtenerDescripcion-service">
    <port name="ObtenerDescripcion-port" binding="tns:ObtenerDescripcion_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="ObtenerDescripcion.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerDescripcion/ObtenerDescripcion/ObtenerDescripcion">
            <con:wsdl ref="Middleware/v2/BusinessServices/MDW/obtenerDescripcion/wsdl/ObtenerDescripcion"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerDescripcion/ObtenerDescripcion/ObtenerDescripcion</con:targetNamespace>
</con:wsdlEntry>