apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':use-case')
    implementation project(':model')
    implementation project(':ports')
    implementation project(':reactive-web')
    implementation project(':visionplus-client-api')
    implementation project(':t24-client-api')
    implementation project(':cobis-client-api')
    implementation project(':abanks-client-api')
    implementation project(':secrets-manager')
    implementation project(':lambda-regionalization')
    implementation project(':creditcard-client-api')
    implementation project(':parameter-store')
    implementation project(':helpers')

    implementation libs.boot.starter.webflux
    implementation libs.boot.springdoc.webflux
    implementation libs.spring.cloud.starter.openfeign
    implementation libs.ficohsa.core
    implementation libs.ficohsa.router

    testImplementation libs.archunit
}

test {
    useJUnitPlatform()
    failFast = true
}

tasks.register('architectureTest', Test) {
    description = "Runs architecture tests"
    group = "verification"

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    useJUnitPlatform()

    filter {
        includeTestsMatching "*ArchitectureTest"
    }

    failFast = true
}

build.dependsOn architectureTest

jar {
    enabled = false
}

bootJar {
    destinationDirectory = file("${rootProject.projectDir}/boot/build/libs")
    archiveFileName = 'app.jar'
}
