<wsdl:definitions name="LineasCreditoRTNPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/lineasCreditoRTNPS" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/lineasCreditoRTNPS" xmlns:cred="http://www.ficohsa.com.hn/middleware.services/LineasCreditoRTNTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/LineasCreditoRTNTypes" schemaLocation="../xsd/LineasCreditoRTNTypes.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="LineasCreditoRTNRequest">
        <wsdl:part name="parameters" element="cred:LineasCreditoRTNRequest"/>
        <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
    </wsdl:message>

    <wsdl:message name="LineasCreditoRTNResponse">
        <wsdl:part name="result" element="cred:LineasCreditoRTNResponse"/>
        <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
    </wsdl:message>
    
    <wsdl:portType name="lineasCreditoRTNPS">
        <wsdl:operation name="lineasCreditoRTN" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="fic:LineasCreditoRTNRequest"/>
            <wsdl:output message="fic:LineasCreditoRTNResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="lineasCreditoRTNPSSOAP" type="fic:lineasCreditoRTNPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="lineasCreditoRTN">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/lineasCreditoRTN/NewOperation"/>
            <wsdl:input>
                <soap:body use="literal" parts="parameters"/>
                <soap:header message="fic:LineasCreditoRTNRequest" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
              <soap:body use="literal" parts="result"/>
              <soap:header message="fic:LineasCreditoRTNResponse" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
      <wsdl:service name="lineasCreditoRTNPS">
    <wsdl:port binding="fic:lineasCreditoRTNPSSOAP" name="lineasCreditoRTNPSSOAP">
      <soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/BusinessPartner/lineasCreditoRTNP"/>
    </wsdl:port>
  </wsdl:service>
    
</wsdl:definitions>