<wsdl:definitions name="consultaEstadoCuentaTCHistoricoPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaEstadoCuentaTCHistoricoPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaEstadoCuentaTCHistoricoPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaEstadoCuentaTCHistoricoTypes">

	<wsdl:types>
	    <xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaEstadoCuentaTCHistoricoTypes" schemaLocation="consultaEstadoCuentaTCHistoricoTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="consultaEstadoCuentaTCHistoricoRequest">
		<wsdl:part element="cons:consultaEstadoCuentaTCHistorico" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaEstadoCuentaTCHistoricoResponse">
		<wsdl:part element="cons:consultaEstadoCuentaTCHistoricoResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="consultaEstadoCuentaTCHistoricoPS">
		<wsdl:operation name="consultaEstadoCuentaTCHistorico" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaEstadoCuentaTCHistoricoRequest"/>
			<wsdl:output message="fic:consultaEstadoCuentaTCHistoricoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaEstadoCuentaTCHistoricoPSSOAP" type="fic:consultaEstadoCuentaTCHistoricoPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaEstadoCuentaTCHistorico">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaEstadoCuentaTCHistoricoPS/consultaEstadoCuentaTCHistorico"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaEstadoCuentaTCHistoricoRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaEstadoCuentaTCHistoricoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>	
	
	<wsdl:service name="consultaEstadoCuentaTCHistoricoPS">
	    <wsdl:port binding="fic:consultaEstadoCuentaTCHistoricoPSSOAP" name="consultaEstadoCuentaTCHistoricoPSSOAP">
	    	<soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/Cards/ConsultaEstadoCuentaTCHistorico"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>