<wsdl:definitions name="validaNumeroViajeroPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/validaNumeroViajeroPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/validaNumeroViajeroPS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:fgfs="http://www.ficohsa.com.hn/middleware.services/validaNumeroViajeroTypes">

 	<wsdl:types>
          <xsd:schema>
               <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
          </xsd:schema>
          <xsd:schema>
               <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/validaNumeroViajeroTypes" schemaLocation="../xsd/validaNumeroViajeroTypes.xsd"/>
          </xsd:schema>
    </wsdl:types>
  
  
  <wsdl:message name="ValidaNumeroViajeroRequest">
    <wsdl:part element="fgfs:validaNumeroViajero" name="parameters"/>
    <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
  </wsdl:message>
  
  <wsdl:message name="ValidaNumeroViajeroResponse">
    <wsdl:part element="fgfs:validaNumeroViajeroResponse" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="ValidaNumeroViajeroPS">
    <wsdl:operation name="ValidaNumeroViajero" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="tns:ValidaNumeroViajeroRequest"/>
      <wsdl:output message="tns:ValidaNumeroViajeroResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="ValidaNumeroViajeroPSSOAP" type="tns:ValidaNumeroViajeroPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ValidaNumeroViajero">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/validaNumeroViajeroPS/validaNumeroViajero"/>
      <wsdl:input>
      	<soap:body use="literal" parts="parameters"/>
        <soap:header message="tns:ValidaNumeroViajeroRequest" part="RequestHeader" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header message="tns:ValidaNumeroViajeroResponse" part="ResponseHeader" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="validaNumeroViajeroPS">
    <wsdl:port binding="tns:ValidaNumeroViajeroPSSOAP" name="validaNumeroViajeroPSSOAP">
      <soap:address location="https://172.23.13.19:8004/Middleware/V2/ValidaNumeroViajero"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>