<wsdl:definitions name="pagoDGIPS" 
	targetNamespace="http://www.ficohsa.com.hn/middleware.services/pagoDGIPS/" 
	xmlns:fic="http://www.ficohsa.com.hn/middleware.services/pagoDGIPS/"  
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"  
	xmlns:cons="http://www.ficohsa.com.hn/middleware.services/pagoDGITypes"  
	xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" 
					schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>    	    
    </xsd:schema>    	
    <xsd:schema>
    	<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/pagoDGITypes" 
    				schemaLocation="../xsd/pagoDGITypes.xsd"/>
    </xsd:schema>    
  </wsdl:types>  
  
  <wsdl:message name="pagoDGIRequest">
    <wsdl:part element="cons:pagoDGIRequest" name="parameters"/>
    <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
  </wsdl:message>
  
  <wsdl:message name="pagoDGIResponse">
    <wsdl:part element="cons:pagoDGIResponse" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="pagoDGIPS">
    <wsdl:operation name="pagoDGI" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="fic:pagoDGIRequest"/>
      <wsdl:output message="fic:pagoDGIResponse"/>
    </wsdl:operation>
  </wsdl:portType>  
  
  <wsdl:binding name="pagoDGIPSSOAP" type="fic:pagoDGIPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="pagoDGI">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/pagoDGIPS/pagoDGI"/>
      <wsdl:input>
        <soap:body use="literal" parts="parameters"/>
        <soap:header use="literal" part="RequestHeader" message="fic:pagoDGIRequest"></soap:header>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header use="literal" part="ResponseHeader" message="fic:pagoDGIResponse"></soap:header>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="pagoDGIPS">
    <wsdl:port binding="fic:pagoDGIPSSOAP" name="pagoDGIPSSOAP">
      <soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/CommonBusinessInformation/pagoDGI_v2"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
