<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ModificacionCAP/ModificacionCAP/modificacionCAP" name="modificacionCAP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ModificacionCAP/ModificacionCAP/modificacionCAP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ModificacionCAP/ModificacionCAP/modificacionCAP" location="modificacionCAP.wsdl"/>
  <binding name="modificacionCAP_ptt-binding" type="tns:modificacionCAP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="modificacionCAP">
      <soap:operation soapAction="modificacionCAP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="modificacionCAP-service">
    <port name="modificacionCAP-port" binding="tns:modificacionCAP_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionAhorroProgramado"/>
    </port>
  </service>
</definitions>