<wsdl:definitions name="sjPagoMultipleRecaudoPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjPagoMultipleRecaudoPS" xmlns:tns="SplitJoinTest" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/sjPagoMultipleRecaudoPS" xmlns:envi="http://www.ficohsa.com.hn/middleware.services/sjPagoMultipleRecaudo" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

<wsdl:types>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjPagoMultipleRecaudo" schemaLocation="../xsd/sjPagoMultipleRecaudo.xsd"/>
	</xsd:schema>
</wsdl:types>
    
<wsdl:message name="sjPagoMultipleRecaudoRequest">
	<wsdl:part name="inputParameters" element="envi:sjPagoMultipleRecaudo"/>
</wsdl:message>

<wsdl:message name="sjPagoMultipleRecaudoResponse">
	<wsdl:part name="outputParameters" element="envi:sjPagoMultipleRecaudoResponse"/>
</wsdl:message>


<wsdl:portType name="sjPagoMultipleRecaudoPS">
	<wsdl:operation name="PagoMultipleRecaudo">
		<wsdl:input message="fic:sjPagoMultipleRecaudoRequest"/>
		<wsdl:output message="fic:sjPagoMultipleRecaudoResponse"/>		
	</wsdl:operation>
</wsdl:portType>

<wsdl:binding name="sjPagoMultipleRecaudoPSSOAP" type="fic:sjPagoMultipleRecaudoPS">
	<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
	<wsdl:operation name="PagoMultipleRecaudo">
		<wsdl:input>
			<soap:body parts="inputParameters" use="literal"/>
		</wsdl:input>
		<wsdl:output>
			<soap:body parts="outputParameters" use="literal"/>		
		</wsdl:output>
	</wsdl:operation>
</wsdl:binding>

<wsdl:service name="sjPagoMultipleRecaudoPS">
	<wsdl:port name="jPagoMultipleRecaudoPSSOAP" binding="fic:sjPagoMultipleRecaudoPSSOAP">
		<soap:address location="http://mwomnidesa:8003/Middleware/SJS/PagoMultipleRecaudo"/>
	</wsdl:port>
</wsdl:service>

</wsdl:definitions>