<wsdl:definitions name="movilCheckAvailableCardsPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/movilCheckAvailableCards/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/movilCheckAvailableCards/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:con="http://www.ficohsa.com.hn/middleware.services/movilDigitizationCardsTypes">
	<wsdl:types>
   		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/movilDigitizationCardsTypes" schemaLocation="../../MovilDigitizationCards/xsd/movilDigitizationCardsTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="movilCheckAvailableCardsRequest">
		<wsdl:part element="con:movilCheckAvailableCards" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="movilCheckAvailableCardsResponse">
		<wsdl:part element="con:movilCheckAvailableCardsResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="movilCheckAvailableCardsPS">
		<wsdl:operation name="movilCheckAvailableCards" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:movilCheckAvailableCardsRequest"/>
			<wsdl:output message="fic:movilCheckAvailableCardsResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="movilCheckAvailableCardsPSSOAP" type="fic:movilCheckAvailableCardsPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="movilCheckAvailableCards">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/movilCheckAvailableCardsPS/movilCheckAvailableCards"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:movilCheckAvailableCardsRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:movilCheckAvailableCardsResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="movilCheckAvailableCardsPS">
   		<wsdl:port binding="fic:movilCheckAvailableCardsPSSOAP" name="movilCheckAvailableCardsPSSOAP">
   			<soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Cards/movilCheckAvailableCards"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>