<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication1/Project8/validaRemesasenListas" name="validaRemesasenListas-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication1/Project8/validaRemesasenListas" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication1/Project8/validaRemesasenListas" location="validaRemesasenListas.wsdl"/>
  <binding name="validaRemesasenListas_ptt-binding" type="tns:validaRemesasenListas_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="validaRemesasenListas">
      <soap:operation soapAction="validaRemesasenListas"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="validaRemesasenListas-service">
    <port name="validaRemesasenListas-port" binding="tns:validaRemesasenListas_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>