<wsdl:definitions name="consultaFICOPENPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENPS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsd/HeaderElements.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENTypes" schemaLocation="../xsd/GetFicopenTypes.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="consultaFICOPENRequest">
    <wsdl:part element="cons:consultaFICOPEN" name="parameters"/>
    <wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
  </wsdl:message>
  <wsdl:message name="consultaFICOPENResponse">
    <wsdl:part element="cons:consultaFICOPENResponse" name="result"/>
    <wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
  </wsdl:message>
  <wsdl:portType name="consultaFICOPENPS">
    <wsdl:operation name="consultaFICOPEN" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="fic:consultaFICOPENRequest"/>
      <wsdl:output message="fic:consultaFICOPENResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="consultaFICOPENPSSOAP" type="fic:consultaFICOPENPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultaFICOPEN">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENPS"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
        <soap:header message="fic:consultaFICOPENRequest" part="RequestHeader" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="result" use="literal"/>
        <soap:header message="fic:consultaFICOPENResponse" part="ResponseHeader" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="consultaFICOPENPS">
    <wsdl:port binding="fic:consultaFICOPENPSSOAP" name="consultaFICOPENPSSOAP">
      <soap:address location="https://dynamoosbdev:8004/regional/pension/soap/getFICOPEN/v11g"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>