<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/AfiliaClienteAFP/AfiliaClienteAFP" name="AfiliaClienteAFP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/AfiliaClienteAFP/AfiliaClienteAFP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/AfiliaClienteAFP/AfiliaClienteAFP" location="AfiliaClienteAFP.wsdl"/>
  <binding name="AfiliaClienteAFP_ptt-binding" type="tns:AfiliaClienteAFP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="AfiliaClienteAFP">
      <soap:operation soapAction="AfiliaClienteAFP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="AfiliaClienteAFP-service">
    <port name="AfiliaClienteAFP-port" binding="tns:AfiliaClienteAFP_ptt-binding">
      <soap:address location="jca://eis/DB/jdbc/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>