<wsdl:definitions name="afiliacionDeudoresPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/afiliacionDeudoresPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/afiliacionDeudoresPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/afiliacionDeudoresTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/afiliacionDeudoresTypes" schemaLocation="afiliacionDeudoresTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="afiliacionDeudoresRequest">
		<wsdl:part element="cons:afiliacionDeudores" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="afiliacionDeudoresResponse">
		<wsdl:part element="cons:afiliacionDeudoresResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="afiliacionDeudoresPS">
		<wsdl:operation name="afiliacionDeudores" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:afiliacionDeudoresRequest"/>
			<wsdl:output message="fic:afiliacionDeudoresResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="afiliacionDeudoresPSSOAP" type="fic:afiliacionDeudoresPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="afiliacionDeudores">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/afiliacionDeudoresPS/afiliacionDeudores"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:afiliacionDeudoresRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:afiliacionDeudoresResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="afiliacionDeudoresPS">
    <wsdl:port binding="fic:afiliacionDeudoresPSSOAP" name="afiliacionDeudoresPSSOAP">
      <soap:address location="http://mwinterbanca:8003/Middleware/ReferenceData/BusinessPartner/AfiliacionDeudores"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>