<wsdl:definitions name="GetCustomerListsHN_SJ" targetNamespace="http://www.ficohsa.com.hn/middleware.services/GetCustomerAssetsHN_SJ" xmlns:tns="SplitJoinTest" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/GetCustomerAssetsHN_SJ" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/getCustomerAssetsHN_SJ" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/getCustomerAssetsHN_SJ" schemaLocation="../XSD/GetCustomerAssetsHN_SJ.xsd"/>
		</xsd:schema>
	</wsdl:types>
    
	<wsdl:message name="getCustomerAssetsHN_SJRequest">
		<wsdl:part name="inputParameters" element="cons:getCustomerAssetsHN_SJRequest"/>
	</wsdl:message>
	<wsdl:message name="getCustomerAssetsHN_SJResponse">
		<wsdl:part name="outputParameters" element="cons:getCustomerAssetsHN_SJResponse"/>
	</wsdl:message>

	<wsdl:portType name="GetCustomerAssetsHN_SJ">
		<wsdl:operation name="consultaActivosCliente">
			<wsdl:input message="fic:getCustomerAssetsHN_SJRequest"/>
			<wsdl:output message="fic:getCustomerAssetsHN_SJResponse"/>		
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="GetCustomerAssetsHN_SJSOAP" type="fic:GetCustomerAssetsHN_SJ">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
		<wsdl:operation name="consultaActivosCliente">
			<wsdl:input>
				<soap:body parts="inputParameters" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="outputParameters" use="literal"/>		
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="GetCustomerAssetsHN">
		<wsdl:port name="jConsultaActivosClientePSSOAP" binding="fic:GetCustomerAssetsHN_SJSOAP">
			<soap:address location="http://mwinterbanca:8003/Middleware/RiskAndCompliance/RegulationsAndCompliance/getCustomerListsHN_SJ"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>