<wsdl:definitions name="sjConsultaActivosClientePS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaActivosClientePS" xmlns:tns="SplitJoinTest" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/sjConsultaActivosClientePS" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/sjConsultaActivosCliente" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

<wsdl:types>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaActivosCliente" schemaLocation="../XSD/sjConsultaActivosCliente.xsd"/>
	</xsd:schema>
</wsdl:types>
    
<wsdl:message name="sjConsultaActivosClienteRequest">
	<wsdl:part name="inputParameters" element="cons:sjConsultaActivosClienteRequest"/>
</wsdl:message>
<wsdl:message name="sjConsultaActivosClienteResponse">
	<wsdl:part name="outputParameters" element="cons:sjConsultaActivosClienteResponse"/>
</wsdl:message>

<wsdl:portType name="sjConsultaActivosClientePS">
	<wsdl:operation name="consultaActivosCliente">
		<wsdl:input message="fic:sjConsultaActivosClienteRequest"/>
		<wsdl:output message="fic:sjConsultaActivosClienteResponse"/>		
	</wsdl:operation>
</wsdl:portType>

<wsdl:binding name="sjConsultaActivosClientePSSOAP" type="fic:sjConsultaActivosClientePS">
	<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
	<wsdl:operation name="consultaActivosCliente">
		<wsdl:input>
			<soap:body parts="inputParameters" use="literal"/>
		</wsdl:input>
		<wsdl:output>
			<soap:body parts="outputParameters" use="literal"/>		
		</wsdl:output>
	</wsdl:operation>
</wsdl:binding>

<wsdl:service name="sjConsultaActivosClientePS">
	<wsdl:port name="jConsultaActivosClientePSSOAP" binding="fic:sjConsultaActivosClientePSSOAP">
		<soap:address location="http://mwomnidesa:8003/Middleware/PoC/SplitJoinTest"/>
	</wsdl:port>
</wsdl:service>

</wsdl:definitions>