<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SPEnvents/ConveniosTSP/conveniosTSP" name="conveniosTSP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SPEnvents/ConveniosTSP/conveniosTSP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SPEnvents/ConveniosTSP/conveniosTSP" location="conveniosTSP.wsdl"/>
  <binding name="conveniosTSP_ptt-binding" type="tns:conveniosTSP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conveniosTSP">
      <soap:operation soapAction="conveniosTSP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conveniosTSP-service">
    <port name="conveniosTSP-port" binding="tns:conveniosTSP_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionEventsRepository"/>
    </port>
  </service>
</definitions>