<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/eliminarCupon" name="eliminarCupon-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/eliminarCupon" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/eliminarCupon" location="eliminarCupon.wsdl"/>
  <binding name="eliminarCupon_ptt-binding" type="tns:eliminarCupon_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="eliminarCupon">
      <soap:operation soapAction="eliminarCupon"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="eliminarCupon-service">
    <port name="eliminarCupon-port" binding="tns:eliminarCupon_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionOperacionesTD"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="eliminarCupon.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/eliminarCupon">
            <con:wsdl ref="Middleware/v2/BusinessServices/OperacionesTarjetaDebito/EliminarCupon_db/wsdl/eliminarCupon"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/eliminarCupon</con:targetNamespace>
</con:wsdlEntry>