<wsdl:definitions name="consultaPlanesCreditoPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaPlanesCreditoPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:con="http://www.ficohsa.com.hn/middleware.services/consultaPlanesCreditoPS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/consultaPlanesCreditoTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaPlanesCreditoTypes" schemaLocation="../xsd/consultaPlanesCreditoTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="requestHeader">
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>

	<wsdl:message name="responseHeader">
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:message name="consultaPlanesCredito">
		<wsdl:part element="tns:consultaPlanesCredito" name="parameters"/>
	</wsdl:message>
	<wsdl:message name="consultaPlanesCreditoResponse">
		<wsdl:part element="tns:consultaPlanesCreditoResponse" name="result"/>
	</wsdl:message>

	<wsdl:portType name="consultaPlanesCreditoPS">

		<wsdl:operation name="consultaPlanesCredito" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="con:consultaPlanesCredito"/>
			<wsdl:output message="con:consultaPlanesCreditoResponse"/>
		</wsdl:operation>

	</wsdl:portType>

	<wsdl:binding name="consultaPlanesCreditoPSSOAP" type="con:consultaPlanesCreditoPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaPlanesCredito">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaPlanesCreditoPS/consultaPlanesCredito"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="con:requestHeader" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="con:responseHeader" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="consultaPlanesCreditoPS">
		<wsdl:port binding="con:consultaPlanesCreditoPSSOAP" name="consultaPlanesCreditoPSSOAP">
			<soap:address location="https://mwomnicanal:8004/Middleware/OperationsAndExecution/Cards/ConsultaPlanesCredito/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>