<wsdl:definitions name=" notificaEstadoRemesaCreditoCuentaPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/notificaEstadoRemesaCreditoCuentaPS/" xmlns:not="http://www.ficohsa.com.hn/middleware.services/notificaEstadoRemesaCreditoCuentaPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/notificaEstadoRemesaCreditoCuentaTypes">

   <wsdl:types>
          <xsd:schema>
               <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
          </xsd:schema>
          <xsd:schema>
               <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/notificaEstadoRemesaCreditoCuentaTypes" schemaLocation="../xsd/notificaEstadoRemesaCreditoCuentaTypes.xsd"/>
          </xsd:schema>
    </wsdl:types>
   <wsdl:message name="notificaEstadoRemesaCreditoCuentaRequest">
        <wsdl:part element="tns:NotificaEstadoRemesaCreditoCuenta" name="parameters"/>
        <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
    </wsdl:message>
    <wsdl:message name="notificaEstadoRemesaCreditoCuentaResponse">
        <wsdl:part element="tns:NotificaEstadoRemesaCreditoCuentaResponse" name="result"/>
        <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
    </wsdl:message>
 
  <wsdl:portType name="notificaEstadoRemesaCreditoCuentaPS">
    <wsdl:operation name="notificaEstadoRemesaCreditoCuenta">
      <wsdl:input message="not:notificaEstadoRemesaCreditoCuentaRequest"/>
      <wsdl:output message="not:notificaEstadoRemesaCreditoCuentaResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="notificaEstadoRemesaCreditoCuentaPSSOAP" type="not:notificaEstadoRemesaCreditoCuentaPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="notificaEstadoRemesaCreditoCuenta">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/notificaEstadoRemesaCreditoCuentaPS/notificaEstadoRemesaCreditoCuenta"/>
      <wsdl:input>
        <soap:body use="literal" parts="parameters"/>
				<soap:header message="not:notificaEstadoRemesaCreditoCuentaRequest" part="RequestHeader" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
				<soap:header message="not:notificaEstadoRemesaCreditoCuentaResponse" part="ResponseHeader" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    
  </wsdl:binding>
  <wsdl:service name="notificaEstadoRemesaCreditoCuentaPS">
    <wsdl:port binding="not:notificaEstadoRemesaCreditoCuentaPSSOAP" name="notificaEstadoRemesaCreditoCuentaPSSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>