<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/procesarSolicitudesCliente/procesarSolicitudesCliente" name="procesarSolicitudesCliente-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/procesarSolicitudesCliente/procesarSolicitudesCliente" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/procesarSolicitudesCliente/procesarSolicitudesCliente" location="procesarSolicitudesCliente.wsdl"/>
  <binding name="procesarSolicitudesCliente_ptt-binding" type="tns:procesarSolicitudesCliente_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="procesarSolicitudesCliente">
      <soap:operation soapAction="procesarSolicitudesCliente"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="procesarSolicitudesCliente-service">
    <port name="procesarSolicitudesCliente-port" binding="tns:procesarSolicitudesCliente_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionDLC"/>
    </port>
  </service>
</definitions>