<?binding.jca consultarRecaudoReferenciadoEnLinea_db.jca?><wsdl:definitions name="consultarRecaudoReferenciadoEnLinea" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarRecaudoReferenciadoEnLinea/consultarRecaudoReferenciadoEnLinea" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/FLINK/OSB_K_RECAUDOS_REF_ONLINE/OSB_CONSULTAR_REF_ONLINE/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarRecaudoReferenciadoEnLinea/consultarRecaudoReferenciadoEnLinea" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="consultarRecaudoReferenciadoEnLinea_plt">
        <plt:role name="consultarRecaudoReferenciadoEnLinea_role">
            <plt:portType name="tns:consultarRecaudoReferenciadoEnLinea_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/FLINK/OSB_K_RECAUDOS_REF_ONLINE/OSB_CONSULTAR_REF_ONLINE/" schemaLocation="../xsd/FLINK_OSB_K_RECAUDOS_REF_ONLINE_OSB_CONSULTAR_REF_ONLINE.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="consultarRecaudoReferenciadoEnLinea_ptt">
        <wsdl:operation name="consultarRecaudoReferenciadoEnLinea">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>