<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project2/Consulta_CruceMoneda" name="Consulta_CruceMoneda-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project2/Consulta_CruceMoneda" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project2/Consulta_CruceMoneda" location="Consulta_CruceMoneda.wsdl"/>
  <binding name="Consulta_CruceMoneda_ptt-binding" type="tns:Consulta_CruceMoneda_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="Consulta_CruceMoneda">
      <soap:operation soapAction="Consulta_CruceMoneda"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="Consulta_CruceMoneda-service">
    <port name="Consulta_CruceMoneda-port" binding="tns:Consulta_CruceMoneda_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>