<wsdl:definitions name="actualizacionLibretaAhorroPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/actualizacionLibretaAhorroPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/actualizacionLibretaAhorroPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:con="http://www.ficohsa.com.hn/middleware.services/actualizacionLibretaAhorroTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsds/General/Autenticacion.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/actualizacionLibretaAhorroTypes" schemaLocation="../xsds/ActualizacionLibretaAhorro/ActualizacionLibretaAhorro.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="actualizacionLibretaAhorroRequest">
		<wsdl:part element="con:actualizacionLibretaAhorro" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="actualizacionLibretaAhorroResponse">
		<wsdl:part element="con:actualizacionLibretaAhorroResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="actualizacionLibretaAhorroPS">
		<wsdl:operation name="actualizacionLibretaAhorro" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:actualizacionLibretaAhorroRequest"/>
			<wsdl:output message="fic:actualizacionLibretaAhorroResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="actualizacionLibretaAhorroPSSOAP" type="fic:actualizacionLibretaAhorroPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="actualizacionLibretaAhorro">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/actualizacionLibretaAhorroPS/actualizacionLibretaAhorro"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:actualizacionLibretaAhorroRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:actualizacionLibretaAhorroResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="actualizacionLibretaAhorroPS">
		<wsdl:port binding="fic:actualizacionLibretaAhorroPSSOAP" name="actualizacionLibretaAhorroPSSOAP">
			<soap:address location="http://10.9.104.54:8003/MiddlewareCaja/ActualizacionLibretaAhorro"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>