<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/conDatoTarjetas_v2/conDatoTarjetas_v2/conDatoTarjetas_v2" name="conDatoTarjetas_v2-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/conDatoTarjetas_v2/conDatoTarjetas_v2/conDatoTarjetas_v2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/conDatoTarjetas_v2/conDatoTarjetas_v2/conDatoTarjetas_v2" location="conDatoTarjetas_v2.wsdl"/>
  <binding name="conDatoTarjetas_v2_ptt-binding" type="tns:conDatoTarjetas_v2_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conDatoTarjetas_v2">
      <soap:operation soapAction="conDatoTarjetas_v2"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conDatoTarjetas_v2-service">
    <port name="conDatoTarjetas_v2-port" binding="tns:conDatoTarjetas_v2_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetasHN"/>
    </port>
  </service>
</definitions>