<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarTipoClienteExt/consultarTipoClienteExt" name="consultarTipoClienteExt-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarTipoClienteExt/consultarTipoClienteExt" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarTipoClienteExt/consultarTipoClienteExt" location="ConsultarTipoClienteExt.wsdl"/>
  <binding name="consultarTipoClienteExt_ptt-binding" type="tns:consultarTipoClienteExt_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultarTipoClienteExt">
      <soap:operation soapAction="consultarTipoClienteExt"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultarTipoClienteExt-service">
    <port name="consultarTipoClienteExt-port" binding="tns:consultarTipoClienteExt_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>