<wsdl:definitions name="consultaRecaudoAMDCPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaRecaudoAMDCPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaRecaudoAMDCPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaRecaudoAMDCTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsds/General/Autenticacion.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaRecaudoAMDCTypes" schemaLocation="../xsds/ConsultaRecaudoAMDC/ConsultaRecaudoAMDC.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaRecaudoAMDCRequest">
		<wsdl:part element="cons:consultaRecaudoAMDC" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaRecaudoAMDCResponse">
		<wsdl:part element="cons:consultaRecaudoAMDCResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaRecaudoAMDCPS">
		<wsdl:operation name="consultaRecaudoAMDC" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaRecaudoAMDCRequest"/>
			<wsdl:output message="fic:consultaRecaudoAMDCResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaRecaudoAMDCPSSOAP" type="fic:consultaRecaudoAMDCPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaRecaudoAMDC">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaRecaudoAMDCPS/consultaRecaudoAMDC"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaRecaudoAMDCRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaRecaudoAMDCResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaRecaudoAMDCPS">
		<wsdl:port binding="fic:consultaRecaudoAMDCPSSOAP" name="consultaRecaudoAMDCPSSOAP">
			<soap:address location="http://10.9.104.54:8003/MiddlewareCaja/ConsultaRecaudoAMDC"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>