<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/ConsultarReciboTrxRTE/consultarReciboTrxRTE" name="consultarReciboTrxRTE-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/ConsultarReciboTrxRTE/consultarReciboTrxRTE" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/ConsultarReciboTrxRTE/consultarReciboTrxRTE" location="ConsultarReciboTrxRTE.wsdl"/>
  <binding name="consultarReciboTrxRTE_ptt-binding" type="tns:consultarReciboTrxRTE_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultarReciboTrxRTE">
      <soap:operation soapAction="consultarReciboTrxRTE"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultarReciboTrxRTE-service">
    <port name="consultarReciboTrxRTE-port" binding="tns:consultarReciboTrxRTE_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterpreter"/>
    </port>
  </service>
</definitions>