<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultarRelacionOperacionRecaudo/consultarRelacionOperacionRecaudo" name="consultarRelacionOperacionRecaudo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultarRelacionOperacionRecaudo/consultarRelacionOperacionRecaudo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultarRelacionOperacionRecaudo/consultarRelacionOperacionRecaudo" location="ConsultarRelacionOperacionRecaudo.wsdl"/>
  <binding name="consultarRelacionOperacionRecaudo_ptt-binding" type="tns:consultarRelacionOperacionRecaudo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultarRelacionOperacionRecaudo">
      <soap:operation soapAction="consultarRelacionOperacionRecaudo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultarRelacionOperacionRecaudo-service">
    <port name="consultarRelacionOperacionRecaudo-port" binding="tns:consultarRelacionOperacionRecaudo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>