<wsdl:definitions name="consultaTransaccionRTEPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaTransaccionRTEPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaTransaccionRTEPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:con="http://www.ficohsa.com.hn/middleware.services/consultaTransaccionRTETypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsds/General/Autenticacion.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaTransaccionRTETypes" schemaLocation="../xsds/ConsultaTransaccionRTE/ConsultaTransaccionRTE.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="consultaTransaccionRTERequest">
		<wsdl:part element="con:consultaTransaccionRTE" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaTransaccionRTEResponse">
		<wsdl:part element="con:consultaTransaccionRTEResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="consultaTransaccionRTEPS">
		<wsdl:operation name="consultaTransaccionRTE" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaTransaccionRTERequest"/>
			<wsdl:output message="fic:consultaTransaccionRTEResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaTransaccionRTEPSSOAP" type="fic:consultaTransaccionRTEPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaTransaccionRTE">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaTransaccionRTEPS/consultaTransaccionRTE"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaTransaccionRTERequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaTransaccionRTEResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="consultaTransaccionRTEPS">
		<wsdl:port binding="fic:consultaTransaccionRTEPSSOAP" name="consultaTransaccionRTEPSSOAP">
			<soap:address location="http://10.9.104.54:8003/MiddlewareCaja/ConsultaTransaccionRTE"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>