<wsdl:definitions name="consultarTipoReversionPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultarTipoReversionPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultarTipoReversionPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultarTipoReversionTypes">
  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsds/General/Autenticacion.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultarTipoReversionTypes" schemaLocation="../xsds/ConsultarTipoReversion/ConsultarTipoReversion.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="consultarTipoReversionRequest">
    <wsdl:part element="cons:consultarTipoReversion" name="parameters"/>
    <wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
  </wsdl:message>
  
  <wsdl:message name="consultarTipoReversionResponse">
    <wsdl:part element="cons:consultarTipoReversionResponse" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="consultarTipoReversionPS">
    <wsdl:operation name="consultarTipoReversion" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
      <wsdl:input message="fic:consultarTipoReversionRequest"/>
      <wsdl:output message="fic:consultarTipoReversionResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="consultarTipoReversionPSSOAP" type="fic:consultarTipoReversionPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultarTipoReversion">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultarTipoReversionPS/NewOperation"/>
      <wsdl:input>
        <soap:body use="literal" parts="parameters"/>
        <soap:header message="fic:consultarTipoReversionRequest" part="AutenticacionRequestHeader" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header message="fic:consultarTipoReversionResponse" part="ResponseHeader" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="consultarTipoReversionPS">
    <wsdl:port binding="fic:consultarTipoReversionPSSOAP" name="consultarTipoReversionPSSOAP">
      <soap:address location="http://10.9.104.54:8003/MiddlewareCaja/ConsultarTipoReversion"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>