<wsdl:definitions name="consultaCuentaOCategoriaPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaCuentaOCategoriaPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaCuentaOCategoriaPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:con="http://www.ficohsa.com.hn/middleware.services/consultaCuentaOCategoriaTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsds/General/Autenticacion.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaCuentaOCategoriaTypes" schemaLocation="../xsds/ConsultaCuentaOCategoria/ConsultaCuentaOCategoria.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="consultaCuentaOCategoriaRequest">
		<wsdl:part element="con:consultaCuentaOCategoria" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaCuentaOCategoriaResponse">
		<wsdl:part element="con:consultaCuentaOCategoriaResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="consultaCuentaOCategoriaPS">
		<wsdl:operation name="consultaCuentaOCategoria" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaCuentaOCategoriaRequest"/>
			<wsdl:output message="fic:consultaCuentaOCategoriaResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaCuentaOCategoriaPSSOAP" type="fic:consultaCuentaOCategoriaPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaCuentaOCategoria">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaCuentaOCategoriaPS/consultaCuentaOCategoria"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaCuentaOCategoriaRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaCuentaOCategoriaResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="consultaCuentaOCategoriaPS">
		<wsdl:port binding="fic:consultaCuentaOCategoriaPSSOAP" name="consultaCuentaOCategoriaPSSOAP">
			<soap:address location="http://10.9.104.54:8003/MiddlewareCaja/ConsultaCuentaOCategoria"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>