<wsdl:definitions name="consultaDatosTarjetaCreditoPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaDatosTarjetaCreditoPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaDatosTarjetaCreditoPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaDatosTarjetaCreditoTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsds/General/Autenticacion.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaDatosTarjetaCreditoTypes" schemaLocation="../xsds/ConsultaDatosTarjetaCredito/consultaDatosTarjetaCreditoTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="consultaDatosTarjetaCreditoRequest">
		<wsdl:part element="cons:consultaDatosTarjetaCredito" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaDatosTarjetaCreditoResponse">
		<wsdl:part element="cons:consultaDatosTarjetaCreditoResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="consultaDatosTarjetaCreditoPS">
		<wsdl:operation name="consultaDatosTarjetaCredito" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaDatosTarjetaCreditoRequest"/>
			<wsdl:output message="fic:consultaDatosTarjetaCreditoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaDatosTarjetaCreditoPSSOAP" type="fic:consultaDatosTarjetaCreditoPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaDatosTarjetaCredito">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaDatosTarjetaCreditoPS/consultaDatosTarjetaCredito"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaDatosTarjetaCreditoRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaDatosTarjetaCreditoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="consultaDatosTarjetaCreditoPS">
    <wsdl:port binding="fic:consultaDatosTarjetaCreditoPSSOAP" name="consultaDatosTarjetaCreditoPSSOAP">
      <soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/Cards/ConsultaDatosTarjetaCredito"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>