<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/ConsultarFormularioRTE/consultarFormularioRTE" name="consultarFormularioRTE-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/ConsultarFormularioRTE/consultarFormularioRTE" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/ConsultarFormularioRTE/consultarFormularioRTE" location="ConsultarFormularioRTE.wsdl"/>
  <binding name="consultarFormularioRTE_ptt-binding" type="tns:consultarFormularioRTE_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultarFormularioRTE">
      <soap:operation soapAction="consultarFormularioRTE"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultarFormularioRTE-service">
    <port name="consultarFormularioRTE-port" binding="tns:consultarFormularioRTE_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>