<wsdl:definitions name="depositoACuentaPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/depositoACuentaPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/depositoACuentaPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:dep="http://www.ficohsa.com.hn/middleware.services/depositoACuenta">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsds/General/Autenticacion_v2.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/depositoACuenta" schemaLocation="../xsds/DepositoACuenta/DepositoACuenta.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="depositoACuentaRequest">
		<wsdl:part element="dep:depositoACuenta" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="depositoACuentaResponse">
		<wsdl:part element="dep:depositoACuentaResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="depositoACuentaPS">
		<wsdl:operation name="depositoACuenta" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:depositoACuentaRequest"/>
			<wsdl:output message="fic:depositoACuentaResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="depositoACuentaPSSOAP" type="fic:depositoACuentaPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="depositoACuenta">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/depositoACuentaPS/depositoACuenta"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:depositoACuentaRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:depositoACuentaResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="depositoACuentaPS">
		<wsdl:port binding="fic:depositoACuentaPSSOAP" name="depositoACuentaPSSOAP">
			<soap:address location="https://10.9.104.250:8006/MiddlewareCaja/DepositoACuenta"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>