<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/ObtenerSecuencia/obtenerSecuencia" name="obtenerSecuencia-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/ObtenerSecuencia/obtenerSecuencia" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/ObtenerSecuencia/obtenerSecuencia" location="obtenerSecuencia.wsdl"/>
  <binding name="obtenerSecuencia_ptt-binding" type="tns:obtenerSecuencia_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="obtenerSecuencia">
      <soap:operation soapAction="obtenerSecuencia"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="obtenerSecuencia-service">
    <port name="obtenerSecuencia-port" binding="tns:obtenerSecuencia_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>