<wsdl:definitions targetNamespace="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoMultiple/" name="pagoRecaudoMultiplePS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoMultiple/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:pag="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoMultipleTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsds/General/Autenticacion.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoMultipleTypes" schemaLocation="../xsds/PagoRecaudoMultiple/PagoRecaudoMultiple.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="pagoRecaudoMultipleRequest">
		<wsdl:part element="pag:pagoRecaudoMultiple" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="pagoRecaudoMultipleResponse">
		<wsdl:part element="pag:pagoRecaudoMultipleResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="pagoRecaudoMultiplePS">
		<wsdl:operation name="pagoRecaudoMultiple" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:pagoRecaudoMultipleRequest"/>
			<wsdl:output message="fic:pagoRecaudoMultipleResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="pagoRecaudoMultiplePSSOAP" type="fic:pagoRecaudoMultiplePS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="pagoRecaudoMultiple">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoMultiple/pagoRecaudoMultiple"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:pagoRecaudoMultipleRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:pagoRecaudoMultipleResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="pagoRecaudoMultiplePS">
		<wsdl:port binding="fic:pagoRecaudoMultiplePSSOAP" name="pagoRecaudoMultiplePSSOAP">
	  		<soap:address location="http://10.9.104.54:8003/MiddlewareCaja/PagoRecaudoMultiple"/>
	   	</wsdl:port>
	</wsdl:service>
</wsdl:definitions>