<wsdl:definitions targetNamespace="http://www.ficohsa.com.hn/middleware.services/pagoRemesas/" name="pagoRemesasPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/pagoRemesas/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:pag="http://www.ficohsa.com.hn/middleware.services/pagoRemesasTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsds/General/Autenticacion.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/pagoRemesasTypes" schemaLocation="../xsds/PagoRemesas/PagoRemesas.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="pagoRemesasRequest">
		<wsdl:part element="pag:pagoRemesas" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="pagoRemesasResponse">
		<wsdl:part element="pag:pagoRemesasResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="pagoRemesasPS">
		<wsdl:operation name="pagoRemesas" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:pagoRemesasRequest"/>
			<wsdl:output message="fic:pagoRemesasResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="pagoRemesasPSSOAP" type="fic:pagoRemesasPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="pagoRemesas">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/pagoRemesas/pagoRemesas"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:pagoRemesasRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:pagoRemesasResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="pagoRemesasPS">
		<wsdl:port binding="fic:pagoRemesasPSSOAP" name="pagoRemesasPSSOAP">
	  		<soap:address location="http://10.9.104.54:8003/MiddlewareCaja/PagoRemesas"/>
	   	</wsdl:port>
	</wsdl:service>
</wsdl:definitions>