<wsdl:definitions targetNamespace="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoAMDC/" name="pagoRecaudoAMDCPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoAMDC/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:pag="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoAMDCTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsds/General/Autenticacion.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoAMDCTypes" schemaLocation="../xsds/PagoRecaudoAMDC/PagoRecaudoAMDC.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="pagoRecaudoAMDCRequest">
		<wsdl:part element="pag:pagoRecaudoAMDC" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="pagoRecaudoAMDCResponse">
		<wsdl:part element="pag:pagoRecaudoAMDCResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="pagoRecaudoAMDCPS">
		<wsdl:operation name="pagoRecaudoAMDC" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:pagoRecaudoAMDCRequest"/>
			<wsdl:output message="fic:pagoRecaudoAMDCResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="pagoRecaudoAMDCPSSOAP" type="fic:pagoRecaudoAMDCPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="pagoRecaudoAMDC">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoAMDC/pagoRecaudoAMDC"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:pagoRecaudoAMDCRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:pagoRecaudoAMDCResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="pagoRecaudoAMDCPS">
		<wsdl:port binding="fic:pagoRecaudoAMDCPSSOAP" name="pagoRecaudoAMDCPSSOAP">
	  		<soap:address location="http://10.9.104.54:8003/MiddlewareCaja/PagoRecaudoAMDC"/>
	   	</wsdl:port>
	</wsdl:service>
</wsdl:definitions>