<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarTxnCaja/registrarTxnCaja" name="registrarTxnCaja-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarTxnCaja/registrarTxnCaja" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarTxnCaja/registrarTxnCaja" location="RegistrarTxnCaja.wsdl"/>
  <binding name="registrarTxnCaja_ptt-binding" type="tns:registrarTxnCaja_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registrarTxnCaja">
      <soap:operation soapAction="registrarTxnCaja"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registrarTxnCaja-service">
    <port name="registrarTxnCaja-port" binding="tns:registrarTxnCaja_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterpreter"/>
    </port>
  </service>
</definitions>