<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/RegistrarLiqFondosExt/registrarLiqFondosExt" name="registrarLiqFondosExt-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/RegistrarLiqFondosExt/registrarLiqFondosExt" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/RegistrarLiqFondosExt/registrarLiqFondosExt" location="RegistrarLiqFondosExt.wsdl"/>
  <binding name="registrarLiqFondosExt_ptt-binding" type="tns:registrarLiqFondosExt_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registrarLiqFondosExt">
      <soap:operation soapAction="registrarLiqFondosExt"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registrarLiqFondosExt-service">
    <port name="registrarLiqFondosExt-port" binding="tns:registrarLiqFondosExt_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>