<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarRelacionOperacionRecaudoMigracion/registrarRelacionOperacionRecaudoMigracion" name="registrarRelacionOperacionRecaudoMigracion-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarRelacionOperacionRecaudoMigracion/registrarRelacionOperacionRecaudoMigracion" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarRelacionOperacionRecaudoMigracion/registrarRelacionOperacionRecaudoMigracion" location="RegistrarRelacionOperacionRecaudoMigracion.wsdl"/>
  <binding name="registrarRelacionOperacionRecaudoMigracion_ptt-binding" type="tns:registrarRelacionOperacionRecaudoMigracion_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registrarRelacionOperacionRecaudoMigracion">
      <soap:operation soapAction="registrarRelacionOperacionRecaudoMigracion"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registrarRelacionOperacionRecaudoMigracion-service">
    <port name="registrarRelacionOperacionRecaudoMigracion-port" binding="tns:registrarRelacionOperacionRecaudoMigracion_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>