<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarEquivalenteTrxRTE/registrarEquivalenteTrxRTE" name="registrarEquivalenteTrxRTE-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarEquivalenteTrxRTE/registrarEquivalenteTrxRTE" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarEquivalenteTrxRTE/registrarEquivalenteTrxRTE" location="RegistrarEquivalenteTrxRTE.wsdl"/>
  <binding name="registrarEquivalenteTrxRTE_ptt-binding" type="tns:registrarEquivalenteTrxRTE_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registrarEquivalenteTrxRTE">
      <soap:operation soapAction="registrarEquivalenteTrxRTE"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registrarEquivalenteTrxRTE-service">
    <port name="registrarEquivalenteTrxRTE-port" binding="tns:registrarEquivalenteTrxRTE_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>