<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarConsultaMontosAMDC/registrarConsultaMontosAMDC" name="registrarConsultaMontosAMDC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarConsultaMontosAMDC/registrarConsultaMontosAMDC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarConsultaMontosAMDC/registrarConsultaMontosAMDC" location="RegistrarConsultaMontosAMDC.wsdl"/>
  <binding name="registrarConsultaMontosAMDC_ptt-binding" type="tns:registrarConsultaMontosAMDC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registrarConsultaMontosAMDC">
      <soap:operation soapAction="registrarConsultaMontosAMDC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registrarConsultaMontosAMDC-service">
    <port name="registrarConsultaMontosAMDC-port" binding="tns:registrarConsultaMontosAMDC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>