<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarConsultaMesesAMDC/registrarConsultaMesesAMDC" name="registrarConsultaMesesAMDC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarConsultaMesesAMDC/registrarConsultaMesesAMDC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/RegistrarConsultaMesesAMDC/registrarConsultaMesesAMDC" location="RegistrarConsultaMesesAMDC.wsdl"/>
  <binding name="registrarConsultaMesesAMDC_ptt-binding" type="tns:registrarConsultaMesesAMDC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registrarConsultaMesesAMDC">
      <soap:operation soapAction="registrarConsultaMesesAMDC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registrarConsultaMesesAMDC-service">
    <port name="registrarConsultaMesesAMDC-port" binding="tns:registrarConsultaMesesAMDC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>