<wsdl:definitions name="retiroDeCuentaPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/retiroDeCuentaPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/retiroDeCuentaPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:ret="http://www.ficohsa.com.hn/middleware.services/retiroDeCuenta">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsds/General/Autenticacion_v2.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/retiroDeCuenta" schemaLocation="../xsds/RetiroDeCuenta/RetiroDeCuenta.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="retiroDeCuentaRequest">
		<wsdl:part element="ret:retiroDeCuenta" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="retiroDeCuentaResponse">
		<wsdl:part element="ret:retiroDeCuentaResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="retiroDeCuentaPS">
		<wsdl:operation name="retiroDeCuenta" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:retiroDeCuentaRequest"/>
			<wsdl:output message="fic:retiroDeCuentaResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="retiroDeCuentaPSSOAP" type="fic:retiroDeCuentaPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="retiroDeCuenta">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/retiroDeCuentaPS/retiroDeCuenta"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:retiroDeCuentaRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:retiroDeCuentaResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="retiroDeCuentaPS">
		<wsdl:port binding="fic:retiroDeCuentaPSSOAP" name="retiroDeCuentaPSSOAP">
			<soap:address location="https://10.9.104.250:8006/MiddlewareCaja/RetiroDeCuenta"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>