<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/ReversionRecaudoAbanks_v2/reversionRecaudoAbanks_v2" name="reversionRecaudoAbanks_v2-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/ReversionRecaudoAbanks_v2/reversionRecaudoAbanks_v2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CajaSOAApplication/ReversionRecaudoAbanks_v2/reversionRecaudoAbanks_v2" location="reversionRecaudoAbanks_v2.wsdl"/>
  <binding name="reversionRecaudoAbanks_v2_ptt-binding" type="tns:reversionRecaudoAbanks_v2_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="reversionRecaudoAbanks_v2">
      <soap:operation soapAction="reversionRecaudoAbanks_v2"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="reversionRecaudoAbanks_v2-service">
    <port name="reversionRecaudoAbanks_v2-port" binding="tns:reversionRecaudoAbanks_v2_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>