<wsdl:definitions name="reversionFaltanteSobranteCajeroPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/reversionFaltanteSobranteCajeroPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/reversionFaltanteSobranteCajeroPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/reversionFaltanteSobranteCajeroTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsds/General/Autenticacion.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/reversionFaltanteSobranteCajeroTypes" schemaLocation="../xsds/ReversionFaltanteSobranteCajero/ReversionFaltanteSobranteCajero.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="reversionFaltanteSobranteCajeroRequest">
		<wsdl:part element="cons:reversionFaltanteSobranteCajero" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="reversionFaltanteSobranteCajeroResponse">
		<wsdl:part element="cons:reversionFaltanteSobranteCajeroResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="reversionFaltanteSobranteCajeroPS">
		<wsdl:operation name="reversionFaltanteSobranteCajero" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:reversionFaltanteSobranteCajeroRequest"/>
			<wsdl:output message="fic:reversionFaltanteSobranteCajeroResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="reversionFaltanteSobranteCajeroPSSOAP" type="fic:reversionFaltanteSobranteCajeroPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="reversionFaltanteSobranteCajero">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/reversionFaltanteSobranteCajeroPS/reversionFaltanteSobranteCajero"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:reversionFaltanteSobranteCajeroRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:reversionFaltanteSobranteCajeroResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="reversionFaltanteSobranteCajeroPS">
		<wsdl:port binding="fic:reversionFaltanteSobranteCajeroPSSOAP" name="reversionFaltanteSobranteCajeroPSSOAP">
			<soap:address location="http://10.9.104.54:8003/MiddlewareCaja/ReversionFaltanteSobranteCajero"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>