<!-- Published by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is Oracle JAX-WS 2.1.5. --><WL5G3N0:definitions name="PagoPrestamo" targetNamespace="http://www.ficohsa.com/PagoPrestamo/" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://www.ficohsa.com/db/sp/pagarPrestamo" xmlns:WL5G3N2="http://www.ficohsa.com/PagoPrestamo/" xmlns:WL5G3N3="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:db="http://www.ficohsa.com/db/sp/pagarPrestamo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com/PagoPrestamo/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com/db/sp/pagarPrestamo" schemaLocation="../xsd/pagar_prestamo_db_ws.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="PagarPrestamoRequest">
    <WL5G3N0:part element="WL5G3N1:PagarPrestamo" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="PagarPrestamoResponse">
    <WL5G3N0:part element="WL5G3N1:PagarPrestamoResponse" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="PagoPrestamo">
    <WL5G3N0:operation name="PagarPrestamo">
      <WL5G3N0:input message="WL5G3N2:PagarPrestamoRequest"/>
      <WL5G3N0:output message="WL5G3N2:PagarPrestamoResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="PagoPrestamoSOAP" type="WL5G3N2:PagoPrestamo">
    <WL5G3N3:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="PagarPrestamo">
      <WL5G3N3:operation soapAction="http://www.ficohsa.com/PagoPrestamo/PagarPrestamo"/>
      <WL5G3N0:input>
        <WL5G3N3:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N3:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="PagoPrestamo">
    <WL5G3N0:port binding="WL5G3N2:PagoPrestamoSOAP" name="PagoPrestamoSOAP">
      <WL5G3N3:address location="http://127.0.0.1:7001/PagoPrestamo/PagoPrestamo"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>