<WL5G3N0:definitions name="consultaFICOPENPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENPS/" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENTypes" xmlns:WL5G3N2="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:WL5G3N3="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENPS/" xmlns:WL5G3N4="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENTypes" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsd/XMLSchema_2066901341.xsd"/>
    </xsd:schema>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENTypes" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENTypes" schemaLocation="../xsd/XMLSchema_2058569568.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="consultaFICOPENRequest">
    <WL5G3N0:part element="WL5G3N1:consultaFICOPEN" name="parameters"/>
    <WL5G3N0:part element="WL5G3N2:RequestHeader" name="RequestHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="consultaFICOPENResponse">
    <WL5G3N0:part element="WL5G3N1:consultaFICOPENResponse" name="result"/>
    <WL5G3N0:part element="WL5G3N2:ResponseHeader" name="ResponseHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="consultaFICOPENPS">
    <WL5G3N0:operation name="consultaFICOPEN" parameterOrder="parameters RequestHeader ResponseHeader">
      <WL5G3N0:input message="WL5G3N3:consultaFICOPENRequest"/>
      <WL5G3N0:output message="WL5G3N3:consultaFICOPENResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="consultaFICOPENPSSOAP" type="WL5G3N3:consultaFICOPENPS">
    <WL5G3N4:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="consultaFICOPEN">
      <WL5G3N4:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaFICOPENPS/consultaFICOPEN"/>
      <WL5G3N0:input>
        <WL5G3N4:body parts="parameters" use="literal"/>
        <WL5G3N4:header message="WL5G3N3:consultaFICOPENRequest" part="RequestHeader" use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N4:body parts="result" use="literal"/>
        <WL5G3N4:header message="WL5G3N3:consultaFICOPENResponse" part="ResponseHeader" use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="consultaFICOPENPS">
    <WL5G3N0:port binding="WL5G3N3:consultaFICOPENPSSOAP" name="consultaFICOPENPSSOAP">
      <WL5G3N4:address location="http://mwomnicanal:8003/Middleware/OperationsAndExecution/BundledProducts/ConsultaFICOPEN_v2"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>