<wsdl:definitions name="GetCreditCardStatement" targetNamespace="http://xmlns.oracle.com/SBHN_Card/SBHN_Card_GetCreditCardStatement/GetCreditCardStatement" xmlns:tns="http://xmlns.oracle.com/SBHN_Card/SBHN_Card_GetCreditCardStatement/GetCreditCardStatement" xmlns:inp1="https://www.ficohsa.com/regional/card" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="https://www.ficohsa.com/regional/card" schemaLocation="../../SBHN_Card_Commons/Schemas/CardInquiryTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="part1" element="inp1:getCreditCardStatement"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="part1" element="inp1:getCreditCardStatementResponse"/>
    </wsdl:message>
    <wsdl:portType name="getCreditCardStatementPtt">
        <wsdl:operation name="getCreditCardStatement">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="getCreditCardStatementBind" type="tns:getCreditCardStatementPtt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getCreditCardStatement">
            <soap:operation style="document" soapAction="getCreditCardStatement"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://xmlns.oracle.com/SBHN_Card/SBHN_Card_GetCreditCardStatement/GetCreditCardStatement"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://xmlns.oracle.com/SBHN_Card/SBHN_Card_GetCreditCardStatement/GetCreditCardStatement"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>