<wsdl:definitions name="pagoPrestamoPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/pagoPrestamoPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/pagoPrestamoPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cred="http://www.ficohsa.com.hn/middleware.services/pagoPrestamoTypes">
 
  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/pagoPrestamoTypes" schemaLocation="../xsd/pagoPrestamoTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="pagoPrestamoRequest">
    <wsdl:part element="cred:pagoPrestamo" name="parameters"/>
    <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
  </wsdl:message>
  
  <wsdl:message name="pagoPrestamoResponse">
    <wsdl:part element="cred:pagoPrestamoResponse" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="pagoPrestamoPS">
    <wsdl:operation name="pagoPrestamo" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="fic:pagoPrestamoRequest"/>
      <wsdl:output message="fic:pagoPrestamoResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="pagoPrestamoPSSOAP" type="fic:pagoPrestamoPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="pagoPrestamo">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/pagoPrestamoPS/NewOperation"/>
      <wsdl:input>
        <soap:body use="literal" parts="parameters"/>
        <soap:header message="fic:pagoPrestamoRequest" part="RequestHeader" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header message="fic:pagoPrestamoResponse" part="ResponseHeader" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="pagoPrestamoPS">
    <wsdl:port binding="fic:pagoPrestamoPSSOAP" name="pagoPrestamoPSSOAP">
      <soap:address location="http://mwomnidesa:8003/Middleware/OperationsAndExecution/Payments/PagoPrestamo"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>