<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbConnections/MaestraInfoTransacciones/ConMaestraInfoTransaccionesTC" name="ConMaestraInfoTransaccionesTC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/dbConnections/MaestraInfoTransacciones/ConMaestraInfoTransaccionesTC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbConnections/MaestraInfoTransacciones/ConMaestraInfoTransaccionesTC" location="ConMaestraInfoTransaccionesTC.wsdl"/>
  <binding name="ConMaestraInfoTransaccionesTC_ptt-binding" type="tns:ConMaestraInfoTransaccionesTC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ConMaestraInfoTransaccionesTC">
      <soap:operation soapAction="ConMaestraInfoTransaccionesTC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ConMaestraInfoTransaccionesTC-service">
    <port name="ConMaestraInfoTransaccionesTC-port" binding="tns:ConMaestraInfoTransaccionesTC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProcesosHN"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="ConMaestraInfoTransaccionesTC.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbConnections/MaestraInfoTransacciones/ConMaestraInfoTransaccionesTC">
            <con:wsdl ref="Middleware/v2/BusinessServices/ConsultaMaestraInfoTransaccionesTC/wsdl/ConMaestraInfoTransaccionesTC"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/dbConnections/MaestraInfoTransacciones/ConMaestraInfoTransaccionesTC</con:targetNamespace>
</con:wsdlEntry>