<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Hans/Hans/MSG_P_DIAS_NO_HABILES" name="MSG_P_DIAS_NO_HABILES-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Hans/Hans/MSG_P_DIAS_NO_HABILES" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Hans/Hans/MSG_P_DIAS_NO_HABILES" location="consultaDiasNoHabiles.wsdl"/>
  <binding name="MSG_P_DIAS_NO_HABILES_ptt-binding" type="tns:MSG_P_DIAS_NO_HABILES_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="MSG_P_DIAS_NO_HABILES">
      <soap:operation soapAction="MSG_P_DIAS_NO_HABILES"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="MSG_P_DIAS_NO_HABILES-service">
    <port name="MSG_P_DIAS_NO_HABILES-port" binding="tns:MSG_P_DIAS_NO_HABILES_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>