<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/envioVerificacionToken/enviarVerificacionTokenInitiateAction" name="enviarVerificacionTokenInitiateAction-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/envioVerificacionToken/enviarVerificacionTokenInitiateAction" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/envioVerificacionToken/enviarVerificacionTokenInitiateAction" location="enviarVerificacionTokenInitiateAction.wsdl"/>
  <binding name="enviarVerificacionTokenInitiateAction_ptt-binding" type="tns:enviarVerificacionTokenInitiateAction_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="enviarVerificacionTokenInitiateAction">
      <soap:operation soapAction="enviarVerificacionTokenInitiateAction"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="enviarVerificacionTokenInitiateAction-service">
    <port name="enviarVerificacionTokenInitiateAction-port" binding="tns:enviarVerificacionTokenInitiateAction_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionDigitalizacionTarjetas"/>
    </port>
  </service>
</definitions>