<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate3/CoreBankingHN/DetailsMovementsAccount" name="DetailsMovementsAccount-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="DetailsMovementsAccount.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate3/CoreBankingHN/DetailsMovementsAccount"/>
    <wsdl:binding name="DetailsMovementsAccount_ptt-binding" type="det:DetailsMovementsAccount_ptt" xmlns:det="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate3/CoreBankingHN/DetailsMovementsAccount">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DetailsMovementsAccount">
            <soap:operation soapAction="DetailsMovementsAccount"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>