<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="GetFICOPENRestBS" targetNamespace="http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetFICOPEN/GetFICOPENRestBS" xmlns:tns="http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetFICOPEN/GetFICOPENRestBS" xmlns:inp1="https://www.ficohsa.com/regional/pension" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="GetFICOPENRestBS">
        <plnk:role name="GetFICOPENRestBSProvider" portType="tns:GetFICOPENRestBS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www.ficohsa.com/regional/pension" schemaLocation="../Schemas/GetFICOPENTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="getFICOPEN_inputMessage">
        <wsdl:part name="request" element="inp1:getFICOPEN"/>
    </wsdl:message>
    <wsdl:message name="getFICOPEN_outputMessage">
        <wsdl:part name="reply" element="inp1:getFICOPENResponse"/>
    </wsdl:message>
    <wsdl:portType name="GetFICOPENRestBS_ptt">
        <wsdl:operation name="getFICOPEN">
            <wsdl:input message="tns:getFICOPEN_inputMessage"/>
            <wsdl:output message="tns:getFICOPEN_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="GetFICOPENRestBS_ptt-binding" type="tns:GetFICOPENRestBS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getFICOPEN">
            <soap:operation soapAction="getFICOPEN"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../Schemas/GetFICOPENTypes.xsd" namespace="https://www.ficohsa.com/regional/pension" ref="SBRG_Pension_GetFICOPEN/Schemas/GetFICOPENTypes"/>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetFICOPEN/GetFICOPENRestBS</con:targetNamespace>
</con:wsdlEntry>