<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ejemplo/despignoracionSaldoRecaudo/despignoracionSaldoRecaudo" name="despignoracionSaldoRecaudo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Ejemplo/despignoracionSaldoRecaudo/despignoracionSaldoRecaudo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ejemplo/despignoracionSaldoRecaudo/despignoracionSaldoRecaudo" location="despignoracionSaldoRecaudo.wsdl"/>
  <binding name="despignoracionSaldoRecaudo_ptt-binding" type="tns:despignoracionSaldoRecaudo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="despignoracionSaldoRecaudo">
      <soap:operation soapAction="despignoracionSaldoRecaudo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="despignoracionSaldoRecaudo-service">
    <port name="despignoracionSaldoRecaudo-port" binding="tns:despignoracionSaldoRecaudo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksPA"/>
    </port>
  </service>
</definitions>