<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="actualizarLimiCarteraTCPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/actualizarLimiCarteraTCPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/actualizarLimiCarteraTCPS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:alctc="http://www.ficohsa.com.hn/middleware.services/actualizarLimiCarteraTCTypes">

 	<wsdl:types>
          <xsd:schema>
               <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
          </xsd:schema>
          <xsd:schema>
               <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/actualizarLimiCarteraTCTypes" schemaLocation="../xsd/actualizarLimiCarteraTCTypes.xsd"/>
          </xsd:schema>
    </wsdl:types>
  
  
  <wsdl:message name="actualizarLimiCarteraTC">
    <wsdl:part element="alctc:actualizarLimiCarteraTC" name="parameters"/>
    <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
  </wsdl:message>
  
  <wsdl:message name="actualizarLimiCarteraTCResponse">
    <wsdl:part element="alctc:actualizarLimiCarteraTCResponse" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="actualizarLimiCarteraTCPS">
    <wsdl:operation name="actualizarLimiCarteraTC" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="tns:actualizarLimiCarteraTC"/>
      <wsdl:output message="tns:actualizarLimiCarteraTCResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="actualizarLimiCarteraTCPSSOAP" type="tns:actualizarLimiCarteraTCPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="actualizarLimiCarteraTC">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/actualizarLimiCarteraTCPS/actualizarLimiCarteraTC"/>
      <wsdl:input>
      	<soap:body use="literal" parts="parameters"/>
        <soap:header message="tns:actualizarLimiCarteraTC" part="RequestHeader" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header message="tns:actualizarLimiCarteraTCResponse" part="ResponseHeader" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="actualizarLimiCarteraTCPS">
    <wsdl:port binding="tns:actualizarLimiCarteraTCPSSOAP" name="actualizarLimiCarteraTCPSSOAP">
      <soap:address location="https://172.23.13.19:8004/Middleware/V2/actualizarLimiCarteraTC"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../../esquemas_generales/HeaderElements.xsd" namespace="http://www.ficohsa.com.hn/middleware.services/autType" ref="Middleware/v2/Resources/esquemas_generales/HeaderElements"/>
        <con:schemaRef isInclude="false" schemaLocation="../xsd/actualizarLimiCarteraTCTypes.xsd" namespace="http://www.ficohsa.com.hn/middleware.services/actualizarLimiCarteraTCTypes" ref="Middleware/v2/Resources/ActualizarLimiCarteraTC/xsd/actualizarLimiCarteraTCTypes"/>
    </con:dependencies>
    <con:targetNamespace>http://www.ficohsa.com.hn/middleware.services/actualizarLimiCarteraTCPS/</con:targetNamespace>
</con:wsdlEntry>