<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/ingresarDeudoresCliente/ingresarDeudoresCliente" name="ingresarDeudoresCliente-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/ingresarDeudoresCliente/ingresarDeudoresCliente" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/ingresarDeudoresCliente/ingresarDeudoresCliente" location="ingresarDeudoresCliente.wsdl"/>
  <binding name="ingresarDeudoresCliente_ptt-binding" type="tns:ingresarDeudoresCliente_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ingresarDeudoresCliente">
      <soap:operation soapAction="ingresarDeudoresCliente"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ingresarDeudoresCliente-service">
    <port name="ingresarDeudoresCliente-port" binding="tns:ingresarDeudoresCliente_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>