<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MD/conRegistraPagoTCRG" name="conRegistraPagoTCRG-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MD/conRegistraPagoTCRG" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MD/conRegistraPagoTCRG" location="conRegistraPagoTCRG.wsdl"/>
  <binding name="conRegistraPagoTCRG_ptt-binding" type="tns:conRegistraPagoTCRG_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conRegistraPagoTCRG">
      <soap:operation soapAction="conRegistraPagoTCRG"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conRegistraPagoTCRG-service">
    <port name="conRegistraPagoTCRG-port" binding="tns:conRegistraPagoTCRG_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetasHN"/>
    </port>
  </service>
</definitions>