<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareRegionalSOAApplication/SolicitudChequeras/solicitudChequeras" name="solicitudChequeras-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareRegionalSOAApplication/SolicitudChequeras/solicitudChequeras" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareRegionalSOAApplication/SolicitudChequeras/solicitudChequeras" location="solicitudChequeras.wsdl"/>
  <binding name="solicitudChequeras_ptt-binding" type="tns:solicitudChequeras_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="solicitudChequeras">
      <soap:operation soapAction="solicitudChequeras"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="solicitudChequeras-service">
    <port name="solicitudChequeras-port" binding="tns:solicitudChequeras_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksPA"/>
    </port>
  </service>
</definitions>