<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/registrarBitacora/registrarBitacora" name="registrarBitacora-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/registrarBitacora/registrarBitacora" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/registrarBitacora/registrarBitacora" location="registrarBitacora.wsdl"/>
  <binding name="registrarBitacora_ptt-binding" type="tns:registrarBitacora_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registrarBitacora">
      <soap:operation soapAction="registrarBitacora"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="registrarBitacora-service">
    <port name="registrarBitacora-port" binding="tns:registrarBitacora_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWorkflow"/>
    </port>
  </service>
</definitions>