<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/consultaDiasNoHabiles/consultaDiasNoHabiles" name="consultaDiasNoHabiles-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/consultaDiasNoHabiles/consultaDiasNoHabiles" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/consultaDiasNoHabiles/consultaDiasNoHabiles" location="consultaDiasNoHabiles.wsdl"/>
  <binding name="consultaDiasNoHabiles_ptt-binding" type="tns:consultaDiasNoHabiles_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaDiasNoHabiles">
      <soap:operation soapAction="consultaDiasNoHabiles"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaDiasNoHabiles-service">
    <port name="consultaDiasNoHabiles-port" binding="tns:consultaDiasNoHabiles_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>