<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/HN/consultaOrigenes/consultaOrigenes" name="consultaOrigenes-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/HN/consultaOrigenes/consultaOrigenes" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/HN/consultaOrigenes/consultaOrigenes" location="consultaOrigenes.wsdl"/>
  <binding name="consultaOrigenes_ptt-binding" type="tns:consultaOrigenes_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaOrigenes">
      <soap:operation soapAction="consultaOrigenes"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaOrigenes-service">
    <port name="consultaOrigenes-port" binding="tns:consultaOrigenes_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="consultaOrigenes.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/HN/consultaOrigenes/consultaOrigenes">
            <con:wsdl ref="Middleware/v2/BusinessServices/CatalogosInfoCliente/consultaOrigenes/wsdl/consultaOrigenes"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/HN/consultaOrigenes/consultaOrigenes</con:targetNamespace>
</con:wsdlEntry>