<wsdl:definitions name="registroTransaccionesBALCAMPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/registroTransaccionesBALCAMPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/registroTransaccionesBALCAMPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/registroTransaccionesBALCAMTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/registroTransaccionesBALCAMTypes" schemaLocation="../xsd/registroTransaccionesBALCAMTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="registroTransaccionesBALCAMRequest">
		<wsdl:part element="cons:registroTransaccionesBALCAM" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="registroTransaccionesBALCAMResponse">
		<wsdl:part element="cons:registroTransaccionesBALCAMResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="registroTransaccionesBALCAMPS">
		<wsdl:operation name="registroTransaccionesBALCAM" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:registroTransaccionesBALCAMRequest"/>
			<wsdl:output message="fic:registroTransaccionesBALCAMResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="registroTransaccionesBALCAMPSSOAP" type="fic:registroTransaccionesBALCAMPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="registroTransaccionesBALCAM">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/registroTransaccionesBALCAMPS/registroTransaccionesBALCAM"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:registroTransaccionesBALCAMRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:registroTransaccionesBALCAMResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="registroTransaccionesBALCAMPS">
		<wsdl:port binding="fic:registroTransaccionesBALCAMPSSOAP" name="registroTransaccionesBALCAMPSSOAP">
			<soap:address location="http://172.23.13.19:8004/Middleware/OperationsAndExecution/Payments/RegistroTransaccionesBALCAM"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>