<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AppMiddleware/configuraBin/configuraBin" name="configuraBin-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AppMiddleware/configuraBin/configuraBin" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AppMiddleware/configuraBin/configuraBin" location="configuraBin.wsdl"/>
  <binding name="configuraBin_ptt-binding" type="tns:configuraBin_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="configuraBin">
      <soap:operation soapAction="configuraBin"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="configuraBin-service">
    <port name="configuraBin-port" binding="tns:configuraBin_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionDebitCard"/>
    </port>
  </service>
</definitions>