spring:
  application:
    name: ${SPRING_APPLICATION_NAME:prod-credit-card-retrieves}
  profiles:
    include: null
  jackson:
    time-zone: "UTC"
  security:
    basic:
      enabled: false

logging:
  level:
    web: ${LOG_LEVEL:INFO}
    root: INFO
    org.springframework.web: INFO
    com.ficohsa: INFO

# ---------------------------------------------
# [Ficohsa Configuration]
# ---------------------------------------------
ficohsa:
  logging:
    format: ${LOGGING_FORMAT:CONSOLE} # MINIMAL - PRETTY_JSON - CONSOLE - JSON
    mask-confidential: ${LOGGING_MASK_ENABLED:false} # false
    record-type: U
    environment: ${SPRING_PROFILES_ACTIVE:local}
    log-group: ficohsa-services
    aop:
      enabled: true
    service-name: ${spring.application.name}
    layer: api-product
    bian-api-name: CreditCardRetrieves
  rest:
    bian:
      business-area: ${BIAN_BUSINESS_AREA:OperationsAndExecution}
      business-domain: ${BIAN_BUSINESS_DOMAIN:Cards}
      service-domain: ${BIAN_SERVICE_DOMAIN:CreditCard}
  exception:
    type: ${EXCEPTION_TYPE:https://live.integration.ficohsa.com/errors/}
    error-mapping:
      url: ${ERROR_BASE_URL}
      path: ${ERROR_PATH}
  regionalization:
    functionName: ${AWS_LAMBDA_FUNCTION_ARN}
    card-position-retrieve:
      country: XRS
      domain: CREDIT_CARD_RETRIEVES
      method: card-position/retrieve
    debit-basic-information:
      country: XRS
      domain: CREDIT_CARD_RETRIEVES
      method: debit-basic-information
    debit-card-details:
      country: XRS
      domain: CREDIT_CARD_RETRIEVES
      method: debit-card-details
    settlement-quote-details:
      country: XRS
      domain: CREDIT_CARD_RETRIEVES
      method: settlement-quote-details
    associated-active-cards:
      country: XRS
      domain: CREDIT_CARD_RETRIEVES
      method: associated-active-cards
  external-apis:
    ms-dwh-wrapper:
      base-url: ${DWH_BASE_URL}
      connect-timeout-ms: ${DWH_WRAPPER_CONNECT_TIMEOUT_MS}
      read-timeout-ms: ${DWH_WRAPPER_READ_TIMEOUT_MS}
      retry-attempts: ${DWH_WRAPPER_RETRY_ATTEMPTS}
      path: ${DWH_WRAPPER_PATH}
    ms-abanks-wrapper:
      base-url: ${ABANKS_BASE_URL}
      path-PA01: ${BANKS_PA01}
      path-GT01: ${BANKS_GT01}
    ms-cobis-wrapper:
      base-url: ${COBIS_BASE_URL}
      path: ${COBIS_WRAPPER_PATH}
      sp-base-url: ${COBIS_SP_BASE_URL}
      sp-path: ${COBIS_SP_PATH}
    ms-t24-wrapper:
      base-url: ${T24_BASE_URL}
      url: ${T24_URL}
      path: ${T24_WRAPPER_PATH}
    ms-error:
      base-url: ${ERROR_BASE_URL}
      path: ${ERROR_PATH}
    ms-ccp-wrapper:
      base-url: ${CCP_BASE_URL}
      connect-timeout-ms: ${CCP_WRAPPER_CONNECT_TIMEOUT_MS}
      read-timeout-ms: ${CCP_WRAPPER_READ_TIMEOUT_MS}
      retry-attempts: ${CCP_WRAPPER_RETRY_ATTEMPTS}
      get-ccp-path: ${CCP_WRAPPER_PATH}
      set-ccp-path: ${CCP_WRAPPER_PATH}
    ms-vps-cache-manager:
      base-url: ${VPS_CACHE_MANAGER_BASE_URL}
      path: ${VPS_CACHE_MANAGER_PATH}
      connect-timeout-ms: ${VPS_CACHE_MANAGER_CONNECT_TIMEOUT_MS}
      read-timeout-ms: ${VPS_CACHE_MANAGER_READ_TIMEOUT_MS}
      retry-attempts: ${VPS_CACHE_MANAGER_RETRY_ATTEMPTS}
      cache-ttl: ${VPS_CACHE_MANAGER_CACHE_TTL:300}
      settlement-quote-inquiry-l8v1-operation: ${VPS_CACHE_MANAGER_SETTLEMENT_QUOTE_INQUIRY_L8V1_OPERATION}
      settlement-quote-inquiry-l8v1-param-name: ${VPS_CACHE_MANAGER_SETTLEMENT_QUOTE_INQUIRY_L8V1_PARAM_NAME}
      settlement-quote-inquiry-l8v2-operation: ${VPS_CACHE_MANAGER_SETTLEMENT_QUOTE_INQUIRY_L8V2_OPERATION}
      settlement-quote-inquiry-l8v2-param-name: ${VPS_CACHE_MANAGER_SETTLEMENT_QUOTE_INQUIRY_L8V2_PARAM_NAME}
      settlement-quote-inquiry-caller-service: credit_card_retrieves-product-settlement-quote-details
  database:
    connection-timeout-seconds: ${DB_CONNECTION_TIMEOUT}
    query-timeout-seconds: ${DB_QUERY_TIMEOUT}
    secrets-manager:
      hnd: ${HND_SECM_DB_CONN}
      gtm: ${GTM_SECM_DB_CONN}
      pan: ${PAN_SECM_DB_CONN}
      nic: ${NIC_SECM_DB_CONN}
      process-hn: ${PROCESS_HN_SECM_DB_CONN}
      cards-process-hn: ${CARDS_PROCESS_HN_SECM_DB_CONN}
      process-gt: ${PROCESS_GT_SECM_DB_CONN}
      process-pa: ${PROCESS_PA_SECM_DB_CONN}
      cards-process-ni: ${CARDS_PROCESS_NI_SECM_DB_CONN}
    parameter-store:
      hnd: ${HND_PARM_DB_CONN}
      gtm: ${GTM_PARM_DB_CONN}
      pan: ${PAN_PARM_DB_CONN}
      nic: ${NIC_PARM_DB_CONN}
      process-hn: ${PROCESS_HN_PARM_DB_CONN}
      cards-process-hn: ${CARDS_PROCESS_HN_PARM_DB_CONN}
      process-gt: ${PROCESS_GT_PARM_DB_CONN}
      process-pa: ${PROCESS_PA_PARM_DB_CONN}
      cards-process-ni: ${CARDS_PROCESS_NI_PARM_DB_CONN}

server:
  port: 8080
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
      base-path: /actuator
  endpoint:
    configprops:
      enabled: true
    mappings:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: when-authorized
      defaults:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  security:
    enabled: false

resilience4j:
  circuitbreaker:
    instances:
      externalApiCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 60
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 5
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 5s
        ignoreExceptions:
          - java.lang.IllegalArgumentException
          - org.springframework.web.client.HttpClientErrorException
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException

aws:
  region: ${AWS_REGION}
  secrets-manager:
    endpoint: ${SECRETS_MANAGER_ENDPOINT}
  parameter-store:
    endpoint: ${PARAMETER_STORE_ENDPOINT}
  lambda:
    region: ${AWS_REGION}
    function-arn: ${AWS_LAMBDA_FUNCTION_ARN}

# ---------------------------------------------
# [APP Info]
# ---------------------------------------------
info:
  app:
    name: "Credit Card Retrieves - Product"
    description: "API for credit card information retrieval, settlement quotes, and card details."
    version: "1.0.0"
    encoding: "UTF-8"
    java:
      version: "21"

# ---------------------------------------------
# [SWAGGER] Configuration for Swagger API documentation
# ---------------------------------------------
springdoc:
  swagger-ui:
    path: /credit-card-retrieves/swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true