<wsdl:definitions name="adhesionContratoDEIPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/adhesionContratoDEIPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/adhesionContratoDEIPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/tributosTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/tributosTypes" schemaLocation="../../TributosDEI/xsd/tributosTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="adhesionContratoRequest">
		<wsdl:part element="cons:adhesionContratoRequest" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="adhesionContratoResponse">
		<wsdl:part element="cons:adhesionContratoResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="adhesionContratoDEIPS">
		<wsdl:operation name="adhesionContrato" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:adhesionContratoRequest"/>
			<wsdl:output message="fic:adhesionContratoResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="adhesionContratoDEIPSSOAP" type="fic:adhesionContratoDEIPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="adhesionContrato">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/adhesionContratoDEIPS/adhesionContrato"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:adhesionContratoRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:adhesionContratoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="adhesionContratoDEIPS">
		<wsdl:port binding="fic:adhesionContratoDEIPSSOAP" name="adhesionContratoDEIPSSOAP">
			<soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/BusinessPartner/adhesionContrato"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>