<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/validaCliente/validaCliente" name="validaCliente-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/validaCliente/validaCliente" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/validaCliente/validaCliente" location="validaCliente.wsdl"/>
  <binding name="validaCliente_ptt-binding" type="tns:validaCliente_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="validaCliente">
      <soap:operation soapAction="validaCliente"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="validaCliente-service">
    <port name="validaCliente-port" binding="tns:validaCliente_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="validaCliente.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/validaCliente/validaCliente">
            <con:wsdl ref="Middleware/v2/BusinessServices/ABKGT/validaCliente/wsdl/validaCliente"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/OSB/validaCliente/validaCliente</con:targetNamespace>
</con:wsdlEntry>