<wsdl:definitions name="consultaOcupacionesPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaOcupacionesPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaOcupacionesPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaOcupacionesTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaOcupacionesTypes" schemaLocation="../xsd/consultaOcupacionesTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaOcupacionesRequest">
		<wsdl:part element="cons:consultaOcupaciones" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaOcupacionesResponse">
		<wsdl:part element="cons:consultaOcupacionesResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaOcupacionesPS">
		<wsdl:operation name="consultaOcupaciones" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaOcupacionesRequest"/>
			<wsdl:output message="fic:consultaOcupacionesResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaOcupacionesPSSOAP" type="fic:consultaOcupacionesPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaOcupaciones">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaOcupacionesPS/consultaOcupaciones"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaOcupacionesRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaOcupacionesResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaOcupacionesPS">
		<wsdl:port binding="fic:consultaOcupacionesPSSOAP" name="consultaOcupacionesPSSOAP">
			<soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/CommonBusinessInformation/consultaOcupaciones"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>