<WL5G3N0:definitions name="consultaImagenChequePS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaImagenCheque/" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://www.ficohsa.com.hn/middleware.services/procesoImagenesChequesTypes" xmlns:WL5G3N2="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:WL5G3N3="http://www.ficohsa.com.hn/middleware.services/consultaImagenCheque/" xmlns:WL5G3N4="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/procesoImagenesChequesTypes" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaImagenCheque/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsd/XMLSchema_1761317756.xsd"/>
    </xsd:schema>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/procesoImagenesChequesTypes" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaImagenCheque/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/procesoImagenesChequesTypes" schemaLocation="../xsd/XMLSchema_477112980.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="consultaImagenChequeRequest">
    <WL5G3N0:part element="WL5G3N1:consultaImagenChequeRequest" name="parameters"/>
    <WL5G3N0:part element="WL5G3N2:RequestHeader" name="RequestHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="consultaImagenChequeResponse">
    <WL5G3N0:part element="WL5G3N1:consultaImagenChequeResponse" name="result"/>
    <WL5G3N0:part element="WL5G3N2:ResponseHeader" name="ResponseHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="consultaImagenChequePS">
    <WL5G3N0:operation name="consultaImagenCheque" parameterOrder="parameters RequestHeader ResponseHeader">
      <WL5G3N0:input message="WL5G3N3:consultaImagenChequeRequest"/>
      <WL5G3N0:output message="WL5G3N3:consultaImagenChequeResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="consultaImagenChequePSSOAP" type="WL5G3N3:consultaImagenChequePS">
    <WL5G3N4:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="consultaImagenCheque">
      <WL5G3N4:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaImagenCheque/consultaImagenCheque"/>
      <WL5G3N0:input>
        <WL5G3N4:body parts="parameters" use="literal"/>
        <WL5G3N4:header message="WL5G3N3:consultaImagenChequeRequest" part="RequestHeader" use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N4:body parts="result" use="literal"/>
        <WL5G3N4:header message="WL5G3N3:consultaImagenChequeResponse" part="ResponseHeader" use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="consultaImagenChequePS">
    <WL5G3N0:port binding="WL5G3N3:consultaImagenChequePSSOAP" name="consultaImagenChequePSSOAP">
      <WL5G3N4:address location="http://mwomnicanal:8003/Middleware/OperationsAndExecution/Payments/ConsultaImagenCheque_v2"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>