<wsdl:definitions name="ProcesaFinanciamientoTCPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/ProcesaFinanciamientoTCPS/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/ProcesaFinanciamientoTCPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/financiamientoTCTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/financiamientoTCTypes" schemaLocation="../../FinanciamientoTC/xsd/financiamientoTCTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>


	<wsdl:message name="procesaFinanciamientoRequest">
		<wsdl:part element="cons:procesaFinanciamiento" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="procesaFinanciamientoResponse">
		<wsdl:part element="cons:procesaFinanciamientoResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>



	<wsdl:portType name="ProcesaFinanciamientoTCPS">
		<wsdl:operation name="ProcesaFinanciamiento" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="tns:procesaFinanciamientoRequest"/>
			<wsdl:output message="tns:procesaFinanciamientoResponse"/>
		</wsdl:operation>
	</wsdl:portType>


	<wsdl:binding name="ProcesaFinanciamientoTCPSSOAP" type="tns:ProcesaFinanciamientoTCPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="ProcesaFinanciamiento">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/ProcesaFinanciamientoTCPS/procesaFinanciamiento"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="tns:procesaFinanciamientoRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="tns:procesaFinanciamientoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="ProcesaFinanciamientoTCPS">
		<wsdl:port binding="tns:ProcesaFinanciamientoTCPSSOAP" name="ProcesaFinanciamientoTCPSSOAP">
			<soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/BusinessPartner/procesaFinanciamiento"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>