<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="GetCustomErrorByStackTraceRegionalBS" targetNamespace="http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_Commons/GetCustomErrorByStackTraceRegionalBS" xmlns:tns="http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_Commons/GetCustomErrorByStackTraceRegionalBS" xmlns:inp1="https://www.ficohsa.com/regional/constants" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="GetCustomErrorByStackTraceRegionalBS">
        <plnk:role name="GetCustomErrorByStackTraceRegionalBSProvider" portType="tns:GetCustomErrorByStackTraceRegionalBS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www.ficohsa.com/regional/constants" schemaLocation="SBRG_Constants_Commons/Schemas/ErrorMappingRegional.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="process_inputMessage">
        <wsdl:part name="request" element="inp1:errorMappingRegionalInput"/>
    </wsdl:message>
    <wsdl:message name="process_outputMessage">
        <wsdl:part name="reply" element="inp1:errorMappingRegionalOutput"/>
    </wsdl:message>
    <wsdl:portType name="GetCustomErrorByStackTraceRegionalBS_ptt">
        <wsdl:operation name="process">
            <wsdl:input message="tns:process_inputMessage"/>
            <wsdl:output message="tns:process_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="GetCustomErrorByStackTraceRegionalBS_ptt-binding" type="tns:GetCustomErrorByStackTraceRegionalBS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="SBRG_Constants_Commons/Schemas/ErrorMappingRegional.xsd" namespace="https://www.ficohsa.com/regional/constants" ref="SBRG_Pension_Commons/Resources/SBRG_Constants_Commons/Schemas/ErrorMappingRegional"/>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_Commons/GetCustomErrorByStackTraceRegionalBS</con:targetNamespace>
</con:wsdlEntry>