<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MD/conConsultaDatosTarjetaCredito_v3" name="conConsultaDatosTarjetaCredito_v3-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MD/conConsultaDatosTarjetaCredito_v3" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MD/conConsultaDatosTarjetaCredito_v3" location="conConsultaDatosTarjetaCredito_v3.wsdl"/>
  <binding name="conConsultaDatosTarjetaCredito_v3_ptt-binding" type="tns:conConsultaDatosTarjetaCredito_v3_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conConsultaDatosTarjetaCredito_v3">
      <soap:operation soapAction="conConsultaDatosTarjetaCredito_v3"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conConsultaDatosTarjetaCredito_v3-service">
    <port name="conConsultaDatosTarjetaCredito_v3-port" binding="tns:conConsultaDatosTarjetaCredito_v3_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetasHN"/>
    </port>
  </service>
</definitions>