<wsdl:definitions targetNamespace="http://www.ficohsa.com.hn/middleware.services/procesaMensajeFicocel/" name="procesaMensajeFicocelPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/procesaMensajeFicocel/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/procesaMensajeFicocelTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/procesaMensajeFicocelTypes" schemaLocation="procesaMensajeFicocelTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="procesaMensajeFicocelRequest">
		<wsdl:part element="cons:procesaMensajeFicocel" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="procesaMensajeFicocelResponse">
		<wsdl:part element="cons:procesaMensajeFicocelResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="procesaMensajeFicocelPS">
		<wsdl:operation name="procesaMensajeFicocel" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:procesaMensajeFicocelRequest"/>
			<wsdl:output message="fic:procesaMensajeFicocelResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="procesaMensajeFicocelPSSOAP" type="fic:procesaMensajeFicocelPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="procesaMensajeFicocel">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/procesaMensajeFicocel/procesaMensajeFicocel"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:procesaMensajeFicocelRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:procesaMensajeFicocelResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="procesaMensajeFicocelPS">
	    <wsdl:port binding="fic:procesaMensajeFicocelPSSOAP" name="procesaMensajeFicocelPSSOAP">
	      <soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/BundledProducts/ProcesaMensajeFicocel"/>
	    </wsdl:port>
	</wsdl:service>

</wsdl:definitions>