<wsdl:definitions name="afiliacionDeudoresDepRefPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/afiliacionDeudoresDepRefPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/afiliacionDeudoresDepRefPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/depositosReferenciadosTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/depositosReferenciadosTypes" schemaLocation="../../DepositosReferenciados/xsd/depositosReferenciadosTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="agregarDeudoresRequest">
		<wsdl:part element="cons:agregarDeudores" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="agregarDeudoresResponse">
		<wsdl:part element="cons:agregarDeudoresResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="afiliacionDeudoresDepRefPS">
		<wsdl:operation name="agregarDeudores" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:agregarDeudoresRequest"/>
			<wsdl:output message="fic:agregarDeudoresResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="afiliacionDeudoresDepRefPSSOAP" type="fic:afiliacionDeudoresDepRefPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="agregarDeudores">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/afiliacionDeudoresDepRefPS/afiliacionDeudores"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:agregarDeudoresRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:agregarDeudoresResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="afiliacionDeudoresDepRefPS">
		<wsdl:port binding="fic:afiliacionDeudoresDepRefPSSOAP" name="afiliacionDeudoresDepRefPSSOAP">
			<soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/BusinessPartner/afiliacionDeudoresDepRef"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>