<wsdl:definitions name="listaRecaudosPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/listaRecaudosPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/listaRecaudosPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/listaRecaudosTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/listaRecaudosTypes" schemaLocation="listaRecaudosTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="listaRecaudosRequest">
		<wsdl:part element="cons:listaRecaudos" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="listaRecaudosResponse">
		<wsdl:part element="cons:listaRecaudosResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="listaRecaudosPS">
		<wsdl:operation name="listaRecaudos" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:listaRecaudosRequest"/>
			<wsdl:output message="fic:listaRecaudosResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="listaRecaudosPSSOAP" type="fic:listaRecaudosPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="listaRecaudos">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/listaRecaudosPS/listaRecaudos"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:listaRecaudosRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:listaRecaudosResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="listaRecaudosPS">
    <wsdl:port binding="fic:listaRecaudosPSSOAP" name="listaRecaudosPSSOAP">
      <soap:address location="http://mwinterbanca:8003/Middleware/ReferenceData/BusinessPartner/ListaRecaudos"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>