<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/pruebaSuma/conDetalleComprasCuotas/conDetalleComprasCuotas" name="conDetalleComprasCuotas-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/pruebaSuma/conDetalleComprasCuotas/conDetalleComprasCuotas" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/pruebaSuma/conDetalleComprasCuotas/conDetalleComprasCuotas" location="conDetalleComprasCuotas.wsdl"/>
  <binding name="conDetalleComprasCuotas_ptt-binding" type="tns:conDetalleComprasCuotas_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conDetalleComprasCuotas">
      <soap:operation soapAction="conDetalleComprasCuotas"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conDetalleComprasCuotas-service">
    <port name="conDetalleComprasCuotas-port" binding="tns:conDetalleComprasCuotas_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>