<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/conDatoTarjetasActivasCliente/conDatoTarjetasActivasCliente/conDatoTarjetasActivasCliente" name="conDatoTarjetasActivasCliente-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/conDatoTarjetasActivasCliente/conDatoTarjetasActivasCliente/conDatoTarjetasActivasCliente" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/conDatoTarjetasActivasCliente/conDatoTarjetasActivasCliente/conDatoTarjetasActivasCliente" location="conDatoTarjetasActivasCliente.wsdl"/>
  <binding name="conDatoTarjetasActivasCliente_ptt-binding" type="tns:conDatoTarjetasActivasCliente_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conDatoTarjetasActivasCliente">
      <soap:operation soapAction="conDatoTarjetasActivasCliente"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conDatoTarjetasActivasCliente-service">
    <port name="conDatoTarjetasActivasCliente-port" binding="tns:conDatoTarjetasActivasCliente_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="conDatoTarjetasActivasCliente.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/conDatoTarjetasActivasCliente/conDatoTarjetasActivasCliente/conDatoTarjetasActivasCliente">
            <con:wsdl ref="Middleware/v2/BusinessServices/MasterDataHN/conDatoTarjetasActivasCliente/wsdl/conDatoTarjetasActivasCliente"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/conDatoTarjetasActivasCliente/conDatoTarjetasActivasCliente/conDatoTarjetasActivasCliente</con:targetNamespace>
</con:wsdlEntry>