<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBGT_Card/SBGT_Card_GetCreditCardTransactions/conTransaccionesActuales_v2" name="conTransaccionesActuales_v2-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="conTransaccionesActuales_v2.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBGT_Card/SBGT_Card_GetCreditCardTransactions/conTransaccionesActuales_v2"/>
    <wsdl:binding name="conTransaccionesActuales_v2_ptt-binding" type="con:conTransaccionesActuales_v2_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/SBGT_Card/SBGT_Card_GetCreditCardTransactions/conTransaccionesActuales_v2">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="conTransaccionesActuales_v2">
            <soap:operation soapAction="conTransaccionesActuales_v2"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>