<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/PagoFicoRemesasBS" name="PagoFicoRemesasBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="PagoFicoRemesasBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/PagoFicoRemesasBS"/>
    <wsdl:binding name="PagoFicoRemesasBS_ptt-binding" type="pag:PagoFicoRemesasBS_ptt" xmlns:pag="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/PagoFicoRemesasBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="PagoFicoRemesasBS">
            <soap:operation soapAction="PagoFicoRemesasBS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>