<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/RegistraBitacoraRemesasGravadasBS" name="RegistraBitacoraRemesasGravadasBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RegistraBitacoraRemesasGravadasBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/RegistraBitacoraRemesasGravadasBS"/>
    <wsdl:binding name="RegistraBitacoraRemesasGravadasBS_ptt-binding" type="reg:RegistraBitacoraRemesasGravadasBS_ptt" xmlns:reg="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/RegistraBitacoraRemesasGravadasBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="RegistraBitacoraRemesasGravadasBS">
            <soap:operation soapAction="RegistraBitacoraRemesasGravadasBS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>