<wsdl:definitions name="AuthorizeProvider" targetNamespace="https://www.ficohsa.com/regional/massivePayment" xmlns:tns="https://www.ficohsa.com/regional/massivePayment" xmlns:inp1="https://www.ficohsa.com/regional/massivePayment" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="https://www.ficohsa.com/regional/massivePayment" schemaLocation="../Schemas/AuthorizeProviderTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="authorizeProvider" element="inp1:authorizeProvider"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="authorizeProviderResponse" element="inp1:authorizeProviderResponse"/>
    </wsdl:message>
    <wsdl:portType name="authorizeProviderPtt">
        <wsdl:operation name="authorizeProvider">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="authorizeProviderBind" type="tns:authorizeProviderPtt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="authorizeProvider">
            <soap:operation style="document" soapAction="authorizeProvider"/>
            <wsdl:input>
                <soap:body use="literal" namespace="https://www.ficohsa.com/regional/massivePayment"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="https://www.ficohsa.com/regional/massivePayment"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>