<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions name="actualizaEstadoReprocesoACHFacadePS" 
targetNamespace="http://www.ficohsa.com.hn/middleware.services/actualizaEstadoReprocesoACHFacadePS/"
xmlns:fic="http://www.ficohsa.com.hn/middleware.services/actualizaEstadoReprocesoACHFacadePS/" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" 
xmlns:pmgf="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoT24Types">

  <wsdl:types>
    <xsd:schema>
    	<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
    </xsd:schema>
    <xsd:schema>
    	<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoT24Types" schemaLocation="../../ProcesaMensajeGenericoT24/xsd/procesaMensajeGenericoT24Types.xsd"/>
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="actualizaEstadoReprocesoACHFacade">
  	<wsdl:part element="pmgf:procesaMensajeGenericoT24" name="parameters"/>
    <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
  </wsdl:message>
  <wsdl:message name="actualizaEstadoReprocesoACHFacadeResponse">
  	<wsdl:part element="pmgf:procesaMensajeGenericoT24Response" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="actualizaEstadoReprocesoACHFacadePS">
    <wsdl:operation name="actualizaEstadoReprocesoACHFacade" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="fic:actualizaEstadoReprocesoACHFacade"/>
      <wsdl:output message="fic:actualizaEstadoReprocesoACHFacadeResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="actualizaEstadoReprocesoACHFacadePSSOAP" type="fic:actualizaEstadoReprocesoACHFacadePS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="actualizaEstadoReprocesoACHFacade">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/actualizaEstadoReprocesoACHFacade"/>
      <wsdl:input>
        <soap:body use="literal" parts="parameters"/>
        <soap:header message="fic:actualizaEstadoReprocesoACHFacade" part="RequestHeader" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header message="fic:actualizaEstadoReprocesoACHFacadeResponse" part="ResponseHeader" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="actualizaEstadoReprocesoACHFacadePS">
    <wsdl:port binding="fic:actualizaEstadoReprocesoACHFacadePSSOAP" name="actualizaEstadoReprocesoACHFacadePSSOAP">
      <soap:address location="http://mwonicanal:8003/Middleware/OperationsAndExecution/Messaging/actualizaEstadoReprocesoACHFacade"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
