<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application/ObtenerDatosContrato/ObtenerDatosContrato" name="ObtenerDatosContrato-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application/ObtenerDatosContrato/ObtenerDatosContrato" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application/ObtenerDatosContrato/ObtenerDatosContrato" location="ObtenerDatosContrato.wsdl"/>
  <binding name="ObtenerDatosContrato_ptt-binding" type="tns:ObtenerDatosContrato_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ObtenerDatosContrato">
      <soap:operation soapAction="ObtenerDatosContrato"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ObtenerDatosContrato-service">
    <port name="ObtenerDatosContrato-port" binding="tns:ObtenerDatosContrato_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWorkflow"/>
    </port>
  </service>
</definitions>