<wsdl:definitions name="procesaMensajeGenericoSwitchPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoSwitchPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoSwitchPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cred="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoSwitchTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoSwitchTypes" schemaLocation="../xsd/procesaMensajeGenericoSwitchTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="procesaMensajeGenericoSwitchRequest">
		<wsdl:part element="cred:procesaMensajeGenericoSwitchRequest" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>

	<wsdl:message name="procesaMensajeGenericoSwitchResponse">
		<wsdl:part element="cred:procesaMensajeGenericoSwitchResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="procesaMensajeGenericoSwitchPS">
		<wsdl:operation name="procesaMensajeGenericoSwitch" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:procesaMensajeGenericoSwitchRequest"/>
			<wsdl:output message="fic:procesaMensajeGenericoSwitchResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="procesaMensajeGenericoSwitchPSSOAP" type="fic:procesaMensajeGenericoSwitchPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="procesaMensajeGenericoSwitch">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoSwitchPS/NewOperation"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:procesaMensajeGenericoSwitchRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:procesaMensajeGenericoSwitchResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="procesaMensajeGenericoSwitchPS">
		<wsdl:port binding="fic:procesaMensajeGenericoSwitchPSSOAP" name="procesaMensajeGenericoSwitchPSSOAP">
			<soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Messaging/ProcesaMensajeGenericoSwitch"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>