<wsdl:definitions name="registrarTransaccionTCPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/registrarTransaccionTCPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/registrarTransaccionTCPS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:rt="http://www.ficohsa.com.hn/middleware.services/RegistrarTransaccionTCTypes">
                  
    <wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/RegistrarTransaccionTCTypes" schemaLocation="../../RegistrarTransaccionTC/xsd/RegistrarTransaccionTCTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
  
  	<wsdl:message name="RegistrarTransaccionTCRequest">
		<wsdl:part element="rt:RegistrarTransaccionTC" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="RegistrarTransaccionTCResponse">
		<wsdl:part element="rt:RegistrarTransaccionTCResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
  
  <wsdl:portType name="registrarTransaccionTCPS">
    <wsdl:operation name="RegistrarTransaccionTC" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="tns:RegistrarTransaccionTCRequest"/>
      <wsdl:output message="tns:RegistrarTransaccionTCResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="registrarTransaccionTCPSSOAP" type="tns:registrarTransaccionTCPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="RegistrarTransaccionTC">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/registrarTransaccionTCPS/RegistrarTransaccionTC"/>
      <wsdl:input>
        <soap:body use="literal" parts="parameters"/>
        <soap:header message="tns:RegistrarTransaccionTCRequest" part="RequestHeader" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header message="tns:RegistrarTransaccionTCResponse" part="ResponseHeader" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="registrarTransaccionTCPS">
    <wsdl:port binding="tns:registrarTransaccionTCPSSOAP" name="registrarTransaccionTCPSSOAP">
      <soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Cards/RegistrarTransaccionTC"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>