<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaTelefonoPersonaFPC/consultaTelefonoPersonaFPC" name="consultaTelefonoPersonaFPC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaTelefonoPersonaFPC/consultaTelefonoPersonaFPC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaTelefonoPersonaFPC/consultaTelefonoPersonaFPC" location="consultaTelefonoPersonaFPC.wsdl"/>
  <binding name="consultaTelefonoPersonaFPC_ptt-binding" type="tns:consultaTelefonoPersonaFPC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaTelefonoPersonaFPC">
      <soap:operation soapAction="consultaTelefonoPersonaFPC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaTelefonoPersonaFPC-service">
    <port name="consultaTelefonoPersonaFPC-port" binding="tns:consultaTelefonoPersonaFPC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionFicopen"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="consultaTelefonoPersonaFPC.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaTelefonoPersonaFPC/consultaTelefonoPersonaFPC">
            <con:wsdl ref="Middleware/v2/BusinessServices/FPC/consultaTelefonoPersona/wsdl/consultaTelefonoPersonaFPC"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaTelefonoPersonaFPC/consultaTelefonoPersonaFPC</con:targetNamespace>
</con:wsdlEntry>