<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/pagoRemesaCreditoCuentaGT/pagoRemesaCreditoCuentaGT" name="pagoRemesaCreditoCuentaGT-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/pagoRemesaCreditoCuentaGT/pagoRemesaCreditoCuentaGT" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/pagoRemesaCreditoCuentaGT/pagoRemesaCreditoCuentaGT" location="pagoRemesaCreditoCuentaGT.wsdl"/>
  <binding name="pagoRemesaCreditoCuentaGT_ptt-binding" type="tns:pagoRemesaCreditoCuentaGT_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="pagoRemesaCreditoCuentaGT">
      <soap:operation soapAction="pagoRemesaCreditoCuentaGT"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="pagoRemesaCreditoCuentaGT-service">
    <port name="pagoRemesaCreditoCuentaGT-port" binding="tns:pagoRemesaCreditoCuentaGT_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="pagoRemesaCreditoCuentaGT.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/pagoRemesaCreditoCuentaGT/pagoRemesaCreditoCuentaGT">
            <con:wsdl ref="Middleware/v2/BusinessServices/ABKGT/PagoRemesaCreditoCuenta/wsdl/pagoRemesaCreditoCuentaGT"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/pagoRemesaCreditoCuentaGT/pagoRemesaCreditoCuentaGT</con:targetNamespace>
</con:wsdlEntry>