<wsdl:definitions name="validaProductoClienteHNPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/validaProductoClientePS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/validaProductoClientePS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cpob="http://www.ficohsa.com.hn/middleware.services/validaProductoClienteTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>    	    
    </xsd:schema>    	
    <xsd:schema>
    	<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/validaProductoClienteTypes" schemaLocation="../../ValidaProductoCliente/xsd/validaProductoClienteTypes.xsd"/>
    </xsd:schema>    
  </wsdl:types>
  
  
  <wsdl:message name="validaProductoClienteRequest">
    <wsdl:part element="cpob:validaProductoCliente" name="parameters"/>
    <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
  </wsdl:message>
  
  <wsdl:message name="validaProductoClienteResponse">
    <wsdl:part element="cpob:validaProductoClienteResponse" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="validaProductoClientePS">
    <wsdl:operation name="validaProductoCliente" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="fic:validaProductoClienteRequest"/>
      <wsdl:output message="fic:validaProductoClienteResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  
  
  <wsdl:binding name="validaProductoClientePSSOAP" type="fic:validaProductoClientePS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="validaProductoCliente">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/validaProductoClientePS/validaProductoCliente"/>
      <wsdl:input>
        <soap:body use="literal" parts="parameters"/>
        <soap:header use="literal" part="RequestHeader" message="fic:validaProductoClienteRequest"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header use="literal" part="ResponseHeader" message="fic:validaProductoClienteResponse"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="validaProductoClientePS">
    <wsdl:port binding="fic:validaProductoClientePSSOAP" name="validaProductoClientePSSOAP">
      <soap:address location="http://10.9.104.55:8003/Middleware/ReferenceData/CommonBusinessInformation/validaProductoCliente_v2"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>