<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application4/Project3/ObtenerUrl" name="ObtenerUrl-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application4/Project3/ObtenerUrl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application4/Project3/ObtenerUrl" location="ObtenerUrl.wsdl"/>
  <binding name="ObtenerUrl_ptt-binding" type="tns:ObtenerUrl_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ObtenerUrl">
      <soap:operation soapAction="ObtenerUrl"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ObtenerUrl-service">
    <port name="ObtenerUrl-port" binding="tns:ObtenerUrl_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionAdquirVasa"/>
    </port>
  </service>
</definitions>