<?binding.jca regTransCorresponsalFallidas_db.jca?><wsdl:definitions name="regTransCorresponsalFallidas" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/regTransCorresponsalFallidas/regTransCorresponsalFallidas" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/regTransCorresponsalFallidas" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/regTransCorresponsalFallidas/regTransCorresponsalFallidas" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="regTransCorresponsalFallidas_plt">
        <plt:role name="regTransCorresponsalFallidas_role">
            <plt:portType name="tns:regTransCorresponsalFallidas_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/regTransCorresponsalFallidas" schemaLocation="../xsd/regTransCorresponsalFallidas_sp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="regTransCorresponsalFallidas_ptt">
        <wsdl:operation name="regTransCorresponsalFallidas">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>