<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/consultaEstadoLote" name="consultaEstadoLote-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/consultaEstadoLote" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/consultaEstadoLote" location="consultaEstadoLote.wsdl"/>
  <binding name="consultaEstadoLote_ptt-binding" type="tns:consultaEstadoLote_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaEstadoLote">
      <soap:operation soapAction="consultaEstadoLote"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaEstadoLote-service">
    <port name="consultaEstadoLote-port" binding="tns:consultaEstadoLote_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>