<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/conTransaccionRedencion/conTransaccionRedencion" name="conTransaccionRedencion-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/conTransaccionRedencion/conTransaccionRedencion" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/conTransaccionRedencion/conTransaccionRedencion" location="conTransaccionRedencion.wsdl"/>
  <binding name="conTransaccionRedencion_ptt-binding" type="tns:conTransaccionRedencion_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conTransaccionRedencion">
      <soap:operation soapAction="conTransaccionRedencion"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conTransaccionRedencion-service">
    <port name="conTransaccionRedencion-port" binding="tns:conTransaccionRedencion_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>