<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ArmarMensajeRecaudo/armarMensajeRecaudo" name="armarMensajeRecaudo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ArmarMensajeRecaudo/armarMensajeRecaudo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ArmarMensajeRecaudo/armarMensajeRecaudo" location="ArmarMensajeRecaudo.wsdl"/>
  <binding name="armarMensajeRecaudo_ptt-binding" type="tns:armarMensajeRecaudo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="armarMensajeRecaudo">
      <soap:operation soapAction="armarMensajeRecaudo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="armarMensajeRecaudo-service">
    <port name="armarMensajeRecaudo-port" binding="tns:armarMensajeRecaudo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>