<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/obtenerInformacionConvenio/obtenerInformacionConvenio" name="obtenerInformacionConvenio-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/obtenerInformacionConvenio/obtenerInformacionConvenio" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/obtenerInformacionConvenio/obtenerInformacionConvenio" location="obtenerInformacionConvenio.wsdl"/>
  <binding name="obtenerInformacionConvenio_ptt-binding" type="tns:obtenerInformacionConvenio_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="obtenerInformacionConvenio">
      <soap:operation soapAction="obtenerInformacionConvenio"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="obtenerInformacionConvenio-service">
    <port name="obtenerInformacionConvenio-port" binding="tns:obtenerInformacionConvenio_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>