<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/RealizarPagoROP/realizarPagoROP" name="realizarPagoROP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/RealizarPagoROP/realizarPagoROP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/RealizarPagoROP/realizarPagoROP" location="realizarPagoROP.wsdl"/>
  <binding name="realizarPagoROP_ptt-binding" type="tns:realizarPagoROP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="realizarPagoROP">
      <soap:operation soapAction="realizarPagoROP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="realizarPagoROP-service">
    <port name="realizarPagoROP-port" binding="tns:realizarPagoROP_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWorkflow"/>
    </port>
  </service>
</definitions>