<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareRegionalSOAApplication/ConsultaMaestraSaldoCuenta/consultaMaestraSaldoCuenta" name="consultaMaestraSaldoCuenta-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareRegionalSOAApplication/ConsultaMaestraSaldoCuenta/consultaMaestraSaldoCuenta" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareRegionalSOAApplication/ConsultaMaestraSaldoCuenta/consultaMaestraSaldoCuenta" location="consultaMaestraSaldoCuenta.wsdl"/>
  <binding name="consultaMaestraSaldoCuenta_ptt-binding" type="tns:consultaMaestraSaldoCuenta_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaMaestraSaldoCuenta">
      <soap:operation soapAction="consultaMaestraSaldoCuenta"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaMaestraSaldoCuenta-service">
    <port name="consultaMaestraSaldoCuenta-port" binding="tns:consultaMaestraSaldoCuenta_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>