<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="FraudAnalysis_PS"
     targetNamespace="http://xmlns.oracle.com/VUSecurity/Middleware/FraudAnalysis_PS"
     xmlns:tns="http://xmlns.oracle.com/VUSecurity/Middleware/FraudAnalysis_PS"
     xmlns:inp1="http://www.ficohsa.com.hn/middleware.services/FraudAnalysisTypes"
     xmlns:inp2="http://www.ficohsa.com.hn/middleware.services/autType"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/FraudAnalysisTypes"
                 schemaLocation="../xsd/FraudAnalysisTypes.xsd"/>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../Esquemas_Generales/HeaderElements.xsd"/>
               </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="inputParameters" element="inp1:FraudAnalysisRequest"/>
        <wsdl:part name="RequestHeader" element="inp2:RequestHeader"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="outputParameters" element="inp1:FraudAnalysisResponse"/>
        <wsdl:part name="ResponseHeader" element="inp2:ResponseHeader"/>
    </wsdl:message>
    <wsdl:portType name="fraudAnalysis_ptt">
        <wsdl:operation name="fraudAnalysis">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="fraudAnalysis_bind" type="tns:fraudAnalysis_ptt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="fraudAnalysis">
            <soap:operation style="document" soapAction="fraudAnalysis"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://xmlns.oracle.com/VUSecurity/Middleware/FraudAnalysis_PS" parts="inputParameters"/>
                <soap:header message="tns:requestMessage" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://xmlns.oracle.com/VUSecurity/Middleware/FraudAnalysis_PS" parts="outputParameters"/>
                <soap:header message="tns:replyMessage" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../xsd/FraudAnalysisTypes.xsd" namespace="http://www.ficohsa.com.hn/middleware.services/FraudAnalysisTypes" ref="Middleware/v2/Resources/FraudAnalysis/xsd/FraudAnalysisTypes"/>
        <con:schemaRef isInclude="false" schemaLocation="../../Esquemas_Generales/HeaderElements.xsd" namespace="http://www.ficohsa.com.hn/middleware.services/autType" ref="Middleware/v2/Resources/Esquemas_Generales/HeaderElements"/>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/VUSecurity/Middleware/FraudAnalysis_PS</con:targetNamespace>
</con:wsdlEntry>