<?binding.jca consultarRemLocalId_db.jca?><wsdl:definitions name="consultarRemLocalId" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarRemLocalId/consultarRemLocalId" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/consultarRemLocalId" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarRemLocalId/consultarRemLocalId" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="consultarRemLocalId_plt">
        <plt:role name="consultarRemLocalId_role">
            <plt:portType name="tns:consultarRemLocalId_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/consultarRemLocalId" schemaLocation="consultarRemLocalId_sp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="consultarRemLocalId_ptt">
        <wsdl:operation name="consultarRemLocalId">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>