<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="ValidaProductoCliente" targetNamespace="http://www.ficohsa.com.hn/middleware.services/validaProductoClienteTypes" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/validaProductoClienteTypes" xmlns:inp1="http://www.ficohsa.com.hn/middleware.services/validaProductoClienteTypes" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/validaProductoClienteTypes" schemaLocation="../Schemas/ValidaProductoClienteTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="validaProductoCliente" element="tns:validaProductoCliente"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="validaProductoClienteResponse" element="tns:validaProductoClienteResponse"/>
    </wsdl:message>
    <wsdl:portType name="validaProductoClientePtt">
        <wsdl:operation name="validaProductoCliente">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="validaProductoClienteBind" type="tns:validaProductoClientePtt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="validaProductoCliente">
            <soap:operation style="document" soapAction="validaProductoCliente"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://www.ficohsa.com.hn/middleware.services/validaProductoClienteTypes"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://www.ficohsa.com.hn/middleware.services/validaProductoClienteTypes"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../Schemas/ValidaProductoClienteTypes.xsd" namespace="http://www.ficohsa.com.hn/middleware.services/validaProductoClienteTypes" ref="SBRG_Pension_GetValidProductCustomer/Schemas/ValidaProductoClienteTypes"/>
    </con:dependencies>
    <con:targetNamespace>http://www.ficohsa.com.hn/middleware.services/validaProductoClienteTypes</con:targetNamespace>
</con:wsdlEntry>