<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MCSolicitudEfectivo/MCSolicitudEfectivo" name="MCSolicitudEfectivo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MCSolicitudEfectivo/MCSolicitudEfectivo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MCSolicitudEfectivo/MCSolicitudEfectivo" location="MCSolicitudEfectivo.wsdl"/>
  <binding name="MCSolicitudEfectivo_ptt-binding" type="tns:MCSolicitudEfectivo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="MCSolicitudEfectivo">
      <soap:operation soapAction="MCSolicitudEfectivo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="MCSolicitudEfectivo-service">
    <port name="MCSolicitudEfectivo-port" binding="tns:MCSolicitudEfectivo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>