<?binding.jca registrarBitacora_db.jca?><wsdl:definitions name="registrarBitacora" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/registrarBitacora/registrarBitacora" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/registrarBitacora" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/registrarBitacora/registrarBitacora" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="registrarBitacora_plt">
        <plt:role name="registrarBitacora_role">
            <plt:portType name="tns:registrarBitacora_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/registrarBitacora" schemaLocation="../xsd/registrarBitacora_sp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:portType name="registrarBitacora_ptt">
        <wsdl:operation name="registrarBitacora">
            <wsdl:input message="tns:args_in_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>