<wsdl:definitions name="consultaDatoAplicacionPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaDatoAplicacionPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/consultaDatoAplicacionPS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:con="http://www.ficohsa.com.hn/middleware.services/consultaDatoAplicacionTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaDatoAplicacionTypes" schemaLocation="../xsd/consultaDatoAplicacionTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="consultaDatoAplicacion">
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
		<wsdl:part name="parameters" element="con:consultaDatoAplicacion"/>
	</wsdl:message>
	<wsdl:message name="consultaDatoAplicacionResponse">
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
		<wsdl:part name="result" element="con:consultaDatoAplicacionResponse"/>
	</wsdl:message>
	
	<wsdl:portType name="consultaDatoAplicacionPS">
		<wsdl:operation name="consultaDatoAplicacion" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="tns:consultaDatoAplicacion"/>
			<wsdl:output message="tns:consultaDatoAplicacionResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaDatoAplicacionPSSOAP" type="tns:consultaDatoAplicacionPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaDatoAplicacion">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaDatoAplicacionPS/consultaDatoAplicacion"/>
			<wsdl:input>
				<soap:header use="literal" part="RequestHeader" message="tns:consultaDatoAplicacion"/>
	      		<soap:body use="literal" parts="parameters"/>
			</wsdl:input>
			<wsdl:output>
				<soap:header use="literal" part="ResponseHeader" message="tns:consultaDatoAplicacionResponse"/>
	      		<soap:body use="literal" parts="result"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="consultaDatoAplicacionPS">
		<wsdl:port binding="tns:consultaDatoAplicacionPSSOAP" name="consultaDatoAplicacionPSSOAP">
			<soap:address location="https://172.23.13.19:8004/Middleware/ITManagement/SystemsOperations/ConsultaDatoAplicacion"/>
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>