<wsdl:definitions name="consultaProfesionesPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaProfesionesPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaProfesionesPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaProfesionesTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaProfesionesTypes" schemaLocation="consultaProfesionesTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaProfesionesRequest">
		<wsdl:part element="cons:consultaProfesiones" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaProfesionesResponse">
		<wsdl:part element="cons:consultaProfesionesResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaProfesionesPS">
		<wsdl:operation name="consultaProfesiones" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaProfesionesRequest"/>
			<wsdl:output message="fic:consultaProfesionesResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaProfesionesPSSOAP" type="fic:consultaProfesionesPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaProfesiones">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaProfesionesPS/consultaProfesiones"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaProfesionesRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaProfesionesResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaProfesionesPS">
		<wsdl:port binding="fic:consultaProfesionesPSSOAP" name="consultaProfesionesPSSOAP">
			<soap:address location="http://mwinterbanca:8003/Middleware/ReferenceData/CommonBusinessInformation/consultaProfesiones"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>