<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/OSB/validaListaNegraOfacONU" name="validaListaNegraOfacONU-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/OSB/validaListaNegraOfacONU" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/OSB/validaListaNegraOfacONU" location="validaListaNegraOfacONU.wsdl"/>
  <binding name="validaListaNegraOfacONU_ptt-binding" type="tns:validaListaNegraOfacONU_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="validaListaNegraOfacONU">
      <soap:operation soapAction="validaListaNegraOfacONU"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="validaListaNegraOfacONU-service">
    <port name="validaListaNegraOfacONU-port" binding="tns:validaListaNegraOfacONU_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionPrecredit"/>
    </port>
  </service>
</definitions>