<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaDireccionPersonaFPC/consultaDireccionPersonaFPC" name="consultaDireccionPersonaFPC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaDireccionPersonaFPC/consultaDireccionPersonaFPC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaDireccionPersonaFPC/consultaDireccionPersonaFPC" location="consultaDireccionPersonaFPC.wsdl"/>
  <binding name="consultaDireccionPersonaFPC_ptt-binding" type="tns:consultaDireccionPersonaFPC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaDireccionPersonaFPC">
      <soap:operation soapAction="consultaDireccionPersonaFPC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaDireccionPersonaFPC-service">
    <port name="consultaDireccionPersonaFPC-port" binding="tns:consultaDireccionPersonaFPC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionFicopen"/>
    </port>
  </service>
</definitions>