<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SPEnvents/TransactionTSP/transactionTSP" name="transactionTSP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SPEnvents/TransactionTSP/transactionTSP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SPEnvents/TransactionTSP/transactionTSP" location="transactionTSP.wsdl"/>
  <binding name="transactionTSP_ptt-binding" type="tns:transactionTSP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="transactionTSP">
      <soap:operation soapAction="transactionTSP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="transactionTSP-service">
    <port name="transactionTSP-port" binding="tns:transactionTSP_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionEventsRepository"/>
    </port>
  </service>
</definitions>