<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/actualizaPeticionesDisponiblesH2H" name="actualizaPeticionesDisponiblesH2H-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/actualizaPeticionesDisponiblesH2H" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/actualizaPeticionesDisponiblesH2H" location="actualizaPeticionesDisponiblesH2H.wsdl"/>
  <binding name="actualizaPeticionesDisponiblesH2H_ptt-binding" type="tns:actualizaPeticionesDisponiblesH2H_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="actualizaPeticionesDisponiblesH2H">
      <soap:operation soapAction="actualizaPeticionesDisponiblesH2H"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="actualizaPeticionesDisponiblesH2H-service">
    <port name="actualizaPeticionesDisponiblesH2H-port" binding="tns:actualizaPeticionesDisponiblesH2H_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="actualizaPeticionesDisponiblesH2H.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/actualizaPeticionesDisponiblesH2H">
            <con:wsdl ref="MWHostToHost/v1/BusinessServices/ABKHN/actualizaPeticionesDisponiblesH2H/wsdl/actualizaPeticionesDisponiblesH2H"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/actualizaPeticionesDisponiblesH2H</con:targetNamespace>
</con:wsdlEntry>