<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBGT_Card/SBGT_Card_GetHistoricalCreditCardStatement/DBconInfoHistoricaTCDBBS" name="DBconInfoHistoricaTCDBBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="DBconInfoHistoricaTCDBBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBGT_Card/SBGT_Card_GetHistoricalCreditCardStatement/DBconInfoHistoricaTCDBBS"/>
    <wsdl:binding name="DBconInfoHistoricaTCDBBS_ptt-binding" type="dbc:DBconInfoHistoricaTCDBBS_ptt" xmlns:dbc="http://xmlns.oracle.com/pcbpel/adapter/db/SBGT_Card/SBGT_Card_GetHistoricalCreditCardStatement/DBconInfoHistoricaTCDBBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DBconInfoHistoricaTCDBBS">
            <soap:operation soapAction="DBconInfoHistoricaTCDBBS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>