<wsdl:definitions name="consultaCargosRecurrentesDiariosPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaCargosRecurrentesDiariosPS/" xmlns:ccr="http://www.ficohsa.com.hn/middleware.services/consultaCargosRecurrentesDiariosPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/consultaCargosRecurrentesDiariosTypes">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>

		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaCargosRecurrentesDiariosTypes" schemaLocation="../xsd/consultaCargosRecurrentesDiariosTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="requestHeader">
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>

	<wsdl:message name="responseHeader">
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:message name="consultaCargosRecurrentesDiarios">
		<wsdl:part element="tns:consultaCargosRecurrentesDiarios" name="parameters"/>
	</wsdl:message>

	<wsdl:message name="consultaCargosRecurrentesDiariosResponse">
		<wsdl:part element="tns:consultaCargosRecurrentesDiariosResponse" name="result"/>
	</wsdl:message>

	<wsdl:portType name="consultaCargosRecurrentesDiariosPS">
		<wsdl:operation name="consultaCargosRecurrentesDiarios" parameterOrder="parameters RequestHeader ResponseHeader">

			<wsdl:input message="ccr:consultaCargosRecurrentesDiarios"/>

			<wsdl:output message="ccr:consultaCargosRecurrentesDiariosResponse"/>
		</wsdl:operation>
	</wsdl:portType>




	<wsdl:binding name="consultaCargosRecurrentesDiariosPSSOAP" type="ccr:consultaCargosRecurrentesDiariosPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaCargosRecurrentesDiarios">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaCargosRecurrentesDiariosPS/consultaCargosRecurrentesDiarios"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="ccr:requestHeader" part="RequestHeader" use="literal"/>
			</wsdl:input>

			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="ccr:responseHeader" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>




	<wsdl:service name="consultaCargosRecurrentesDiariosPS">
		<wsdl:port binding="ccr:consultaCargosRecurrentesDiariosPSSOAP" name="consultaCargosRecurrentesDiariosPSSOAP">
			<soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Cards/ConsultaCargosRecurrentesDiarios/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>