<wsdl:definitions name="solicitudReposicionPinTarjetaCreditoPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/solicitudReposicionPinTarjetaCreditoPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/solicitudReposicionPinTarjetaCreditoPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/solicitudReposicionPinTarjetaCreditoTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/solicitudReposicionPinTarjetaCreditoTypes" schemaLocation="solicitudReposicionPinTarjetaCreditoTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="solicitudReposicionPinTarjetaCreditoRequest">
		<wsdl:part element="cons:solicitudReposicionPinTarjetaCredito" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="solicitudReposicionPinTarjetaCreditoResponse">
		<wsdl:part element="cons:solicitudReposicionPinTarjetaCreditoResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="solicitudReposicionPinTarjetaCreditoPS">
		<wsdl:operation name="solicitudReposicionPinTarjetaCredito" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:solicitudReposicionPinTarjetaCreditoRequest"/>
			<wsdl:output message="fic:solicitudReposicionPinTarjetaCreditoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="solicitudReposicionPinTarjetaCreditoPSSOAP" type="fic:solicitudReposicionPinTarjetaCreditoPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="solicitudReposicionPinTarjetaCredito">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/solicitudReposicionPinTarjetaCreditoPS/solicitudReposicionPinTarjetaCredito"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:solicitudReposicionPinTarjetaCreditoRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:solicitudReposicionPinTarjetaCreditoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="solicitudReposicionPinTarjetaCreditoPS">
	    <wsdl:port binding="fic:solicitudReposicionPinTarjetaCreditoPSSOAP" name="solicitudReposicionPinTarjetaCreditoPSSOAP">
	    	<soap:address location="http://mwinterbanca:8003/MiddlewareAbanks/OperationsAndExecution/Cards/SolicitudReposicionPinTarjetaCredito"/>
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>