<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ProcesaLotePagoMasivo/procesaLotePagoMasivo" name="procesaLotePagoMasivo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ProcesaLotePagoMasivo/procesaLotePagoMasivo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ProcesaLotePagoMasivo/procesaLotePagoMasivo" location="procesaLotePagoMasivo.wsdl"/>
  <binding name="procesaLotePagoMasivo_ptt-binding" type="tns:procesaLotePagoMasivo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="procesaLotePagoMasivo">
      <soap:operation soapAction="procesaLotePagoMasivo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="procesaLotePagoMasivo-service">
    <port name="procesaLotePagoMasivo-port" binding="tns:procesaLotePagoMasivo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>