<wsdl:definitions name="actualizaEstadoTDSwitchPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/actualizaEstadoTDSwitchPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:reg="http://www.ficohsa.com.hn/middleware.services/actualizaEstadoTDSwitchPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/actualizaEstadoTDSwitchTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/actualizaEstadoTDSwitchTypes" schemaLocation="../xsd/actualizaEstadoTDSwitchTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="requestHeader">
		<wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="responseHeader">
		<wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
	</wsdl:message>
	<wsdl:message name="actualizaEstadoTDSwitch">
		<wsdl:part element="tns:actualizaEstadoTDSwitch" name="parameters"/>
	</wsdl:message>
	<wsdl:message name="actualizaEstadoTDSwitchResponse">
		<wsdl:part element="tns:actualizaEstadoTDSwitchResponse" name="result"/>
	</wsdl:message>
	<wsdl:portType name="actualizaEstadoTDSwitchPS">
		<wsdl:operation name="actualizaEstadoTDSwitch" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="reg:actualizaEstadoTDSwitch"/>
			<wsdl:output message="reg:actualizaEstadoTDSwitchResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="actualizaEstadoTDSwitchPSSOAP" type="reg:actualizaEstadoTDSwitchPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="actualizaEstadoTDSwitch">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/actualizaEstadoTDSwitchPS/actualizaEstadoTDSwitch"/>
			<wsdl:input>
				<soap:body parts="parameters" use="literal"/>
				<soap:header message="reg:requestHeader" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="result" use="literal"/>
				<soap:header message="reg:responseHeader" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="actualizaEstadoTDSwitchPS">
		<wsdl:port binding="reg:actualizaEstadoTDSwitchPSSOAP" name="actualizaEstadoTDSwitchPSSOAP">
			<soap:address location="http://172.23.13.19:8003/Middleware/v2/ProxyServices/ActualizaEstadoTDSwitch"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>