<wsdl:definitions name="consultaSaldoCuentaPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaSaldoCuentaPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaSaldoCuentaPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultasType">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultasType" schemaLocation="../Resources/consultasGeneralesCuentasTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaSaldoCuentaRequest">
		<wsdl:part element="cons:consultaSaldoCuenta" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaSaldoCuentaResponse">
		<wsdl:part element="cons:consultaSaldoCuentaResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaSaldoCuentaPS">
		<wsdl:operation name="consultaSaldoCuenta" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaSaldoCuentaRequest"/>
			<wsdl:output message="fic:consultaSaldoCuentaResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaSaldoCuentaPSSOAP" type="fic:consultaSaldoCuentaPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaSaldoCuenta">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaSaldoCuentaPS/consultaSaldoCuenta"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaSaldoCuentaRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaSaldoCuentaResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaSaldoCuentaPS">
		<wsdl:port binding="fic:consultaSaldoCuentaPSSOAP" name="consultaSaldoCuentaPSSOAP">
			<soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/CustomerDeposits/ConsultaSaldoCuenta"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>