<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionSysbase/registraBitacoraLog/registraBitacoraLog" name="registraBitacoraLog_db-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="registraBitacoraLog.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionSysbase/registraBitacoraLog/registraBitacoraLog"/>
    <wsdl:binding name="registraBitacoraLog_ptt-binding" type="reg:registraBitacoraLog_ptt" xmlns:reg="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionSysbase/registraBitacoraLog/registraBitacoraLog">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="registraBitacoraLog">
            <soap:operation soapAction="registraBitacoraLog"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>