<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationSOA/actualizarDatosPlantilla/actualizarDatosPlantilla" name="actualizarDatosPlantilla-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationSOA/actualizarDatosPlantilla/actualizarDatosPlantilla" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationSOA/actualizarDatosPlantilla/actualizarDatosPlantilla" location="eCInsRequestControl.wsdl"/>
  <binding name="actualizarDatosPlantilla_ptt-binding" type="tns:actualizarDatosPlantilla_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="actualizarDatosPlantilla">
      <soap:operation soapAction="actualizarDatosPlantilla"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="actualizarDatosPlantilla-service">
    <port name="actualizarDatosPlantilla-port" binding="tns:actualizarDatosPlantilla_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>