dependencies {
    implementation project(':model')
    implementation project(':ports')
    implementation project(':helpers')

    implementation libs.boot.starter.webflux
    implementation libs.ficohsa.core
    implementation libs.ficohsa.web.client
    implementation libs.resilience4j.circuitbreaker
    implementation libs.resilience4j.spring.boot3
    implementation libs.caffeine
}
