<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaFondoPensiones/consultaFondoPensiones" name="consultaFondoPensiones-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaFondoPensiones/consultaFondoPensiones" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaFondoPensiones/consultaFondoPensiones" location="consultaFondoPensiones.wsdl"/>
  <binding name="consultaFondoPensiones_ptt-binding" type="tns:consultaFondoPensiones_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaFondoPensiones">
      <soap:operation soapAction="consultaFondoPensiones"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaFondoPensiones-service">
    <port name="consultaFondoPensiones-port" binding="tns:consultaFondoPensiones_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionFicopen"/>
    </port>
  </service>
</definitions>