<wsdl:definitions targetNamespace="http://www.ficohsa.com.hn/middleware.services/confirmacionCheque/" name="confirmacionChequePS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/confirmacionCheque/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/confirmacionChequeTypes">
  
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/confirmacionChequeTypes" schemaLocation="confirmacionChequeTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	  
   	<wsdl:message name="confirmacionChequeRequest">
		<wsdl:part element="cons:confirmacionCheque" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="confirmacionChequeResponse">
		<wsdl:part element="cons:confirmacionChequeResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	
	<wsdl:portType name="confirmacionChequePS">
		<wsdl:operation name="confirmacionCheque" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:confirmacionChequeRequest"/>
			<wsdl:output message="fic:confirmacionChequeResponse"/>
		</wsdl:operation>
	</wsdl:portType>
  
  <wsdl:binding name="confirmacionChequePSSOAP" type="fic:confirmacionChequePS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="confirmacionCheque">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/confirmacionCheque/confirmacionCheque"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:confirmacionChequeRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:confirmacionChequeResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="confirmacionChequePS">
    <wsdl:port binding="fic:confirmacionChequePSSOAP" name="confirmacionChequePSSOAP">
      <soap:address location="http://10.9.104.55:8003/Middleware/OperationsAndExecution/Payments/ConfirmacionCheque"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>