dependencies {
    implementation project(':model')
    implementation project(':ports')
    implementation project(':helpers')
    implementation project(':secrets-manager')

    implementation libs.boot.starter.webflux
    implementation libs.boot.starter.data.r2dbc
    implementation libs.metrics.actuator
    implementation libs.r2dbc.sqlserver
    implementation libs.spring.cloud.starter.openfeign
    implementation libs.aws.lambda
    implementation libs.ficohsa.core
    implementation libs.ficohsa.web.client
    implementation libs.jsonXml
    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor
}
