<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/crearTransfCorresponsal/crearTransfCorresponsal" name="crearTransfCorresponsal-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/crearTransfCorresponsal/crearTransfCorresponsal" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/crearTransfCorresponsal/crearTransfCorresponsal" location="crearTransfCorresponsal.wsdl"/>
  <binding name="crearTransfCorresponsal_ptt-binding" type="tns:crearTransfCorresponsal_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="crearTransfCorresponsal">
      <soap:operation soapAction="crearTransfCorresponsal"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="crearTransfCorresponsal-service">
    <port name="crearTransfCorresponsal-port" binding="tns:crearTransfCorresponsal_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksPA"/>
    </port>
  </service>
</definitions>