<wsdl:definitions name="consultaPrestamoATMPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaPrestamoATMPS" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaPrestamoATMPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/consultaPrestamoATMTypes">
  
    <wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaPrestamoATMTypes" schemaLocation="../xsd/consultaPrestamoATMTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>



	<wsdl:message name="consultaPrestamoATMPSRequest">
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
		<wsdl:part element="tns:consultaPrestamoATMRequest" name="parameters"/>
	</wsdl:message>
	<wsdl:message name="consultaPrestamoATMPSResponse">
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
		<wsdl:part element="tns:consultaPrestamoATMResponse" name="result"/>
	</wsdl:message>
  
  
  <wsdl:portType name="consultaPrestamoATMPS">
    <wsdl:operation name="consultaPrestamoATM">
      <wsdl:input message="fic:consultaPrestamoATMPSRequest"/>
      <wsdl:output message="fic:consultaPrestamoATMPSResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="consultaPrestamoATMPSSOAP" type="fic:consultaPrestamoATMPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultaPrestamoATM">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaPrestamoATMPS"/>
      <wsdl:input>
        <soap:header message="fic:consultaPrestamoATMPSRequest" part="RequestHeader" use="literal"/>
        <soap:body use="literal" parts="parameters"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="fic:consultaPrestamoATMPSResponse" part="ResponseHeader" use="literal"/>
        <soap:body use="literal" parts="result"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="consultaPrestamoATMPS">
    <wsdl:port binding="fic:consultaPrestamoATMPSSOAP" name="consultaPrestamoATMPSSOAP">
      <soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Messaging/ConsultaPrestamoATM"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>