<wsdl:definitions name="consultaAprobadorasPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaAprobadorasPS/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/consultaAprobadorasPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:set="http://www.ficohsa.com.hn/middleware.services/catalogosInfoClienteTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/catalogosInfoClienteTypes" schemaLocation="../../CatalogosInfoCliente/xsd/catalogosInfoClienteTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="consultaAprobadoras">
		<wsdl:part element="set:consultaAprobadoras" name="parameters"/>
		<wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaAprobadorasResponse">
		<wsdl:part element="set:consultaAprobadorasResponse" name="result"/>
		<wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="consultaAprobadorasPS">	
		<wsdl:operation name="consultaAprobadoras" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="tns:consultaAprobadoras"/>
			<wsdl:output message="tns:consultaAprobadorasResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaAprobadorasPSSOAP" type="tns:consultaAprobadorasPS">
	
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		
		<wsdl:operation name="consultaAprobadoras">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/catalogosInfoClientePS/catalogosInfoCliente"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="tns:consultaAprobadoras" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="tns:consultaAprobadorasResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>	
	</wsdl:binding>

	<wsdl:service name="consultaAprobadorasPS">
		<wsdl:port binding="tns:consultaAprobadorasPSSOAP" name="consultaAprobadorasPS">
	  		<soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/CustomerLoans/ConsultaAprobadoras"/>
	   	</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>