<wsdl:definitions name="consultaTarjetaCreditoReciente" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaTarjetaCreditoReciente/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaTarjetaCreditoReciente/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:con="http://www.ficohsa.com.hn/middleware.services/ConsultaTarjetaCreditoRecientexsd">
   <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/ConsultaTarjetaCreditoRecientexsd" schemaLocation="../xsd/ConsultaTarjetaCreditoRecienteTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
     
    <wsdl:message name="consultaTarjetaCreditoRecienteRequest">
        <wsdl:part element="con:ConsultaTarjetaCreditoRecienteRequest" name="parameters"/>
        <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
    </wsdl:message>
    
    <wsdl:message name="consultaTarjetaCreditoRecienteResponse">
        <wsdl:part element="con:ConsultaTarjetaCreditoRecienteResponse" name="result"/>
        <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
    </wsdl:message>
    
    <wsdl:portType name="consultaTarjetaCreditoRecientePS">
        <wsdl:operation name="consultaTarjetaCreditoReciente" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="fic:consultaTarjetaCreditoRecienteRequest"/>
            <wsdl:output message="fic:consultaTarjetaCreditoRecienteResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="consultaTarjetaCreditoRecientePSSOAP" type="fic:consultaTarjetaCreditoRecientePS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="consultaTarjetaCreditoReciente">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaTarjetaCreditoRecientePS/consultaTarjetaCreditoReciente"/>
            <wsdl:input>
                <soap:body use="literal" parts="parameters"/>
                <soap:header message="fic:consultaTarjetaCreditoRecienteRequest" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="result"/>
                <soap:header message="fic:consultaTarjetaCreditoRecienteResponse" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
     <wsdl:service name="consultaTarjetaCreditoRecientePS">
        <wsdl:port binding="fic:consultaTarjetaCreditoRecientePSSOAP" name="consultaTarjetaCreditoRecientePSSOAP">
           <soap:address location="https://mwomnicanal:8004/Middleware/OperationsAndExecution/Cards/ConsultaTarjetaCreditoReciente"/>
        </wsdl:port>
    </wsdl:service>
  
</wsdl:definitions>