<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/AssembleMessageCollection" name="AssembleMessageCollection-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="AssembleMessageCollection.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/AssembleMessageCollection"/>
    <wsdl:binding name="AssembleMessageCollection_ptt-binding" type="ass:AssembleMessageCollection_ptt" xmlns:ass="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/AssembleMessageCollection">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="AssembleMessageCollection">
            <soap:operation soapAction="AssembleMessageCollection"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>