<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MDA-58323_1/Project1/actualizarTransaccionesGenericas" name="actualizarTransaccionesGenericas-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MDA-58323_1/Project1/actualizarTransaccionesGenericas" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MDA-58323_1/Project1/actualizarTransaccionesGenericas" location="actualizarTransaccionesGenericas.wsdl"/>
  <binding name="actualizarTransaccionesGenericas_ptt-binding" type="tns:actualizarTransaccionesGenericas_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="actualizarTransaccionesGenericas">
      <soap:operation soapAction="actualizarTransaccionesGenericas"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="actualizarTransaccionesGenericas-service">
    <port name="actualizarTransaccionesGenericas-port" binding="tns:actualizarTransaccionesGenericas_ptt-binding">
      <soap:address location="jca://eis/DB/regiondb"/>
    </port>
  </service>
</definitions>