<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizaDatosGFF/registrarBitacoraTercero/registrarBitacoraTercero" name="registrarBitacoraTercero-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizaDatosGFF/registrarBitacoraTercero/registrarBitacoraTercero" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizaDatosGFF/registrarBitacoraTercero/registrarBitacoraTercero" location="registrarBitacoraTercero.wsdl"/>
  <binding name="registrarBitacoraTercero_ptt-binding" type="tns:registrarBitacoraTercero_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registrarBitacoraTercero">
      <soap:operation soapAction="registrarBitacoraTercero"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registrarBitacoraTercero-service">
    <port name="registrarBitacoraTercero-port" binding="tns:registrarBitacoraTercero_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConveniosGT"/>
    </port>
  </service>
</definitions>