<wsdl:definitions name="consultaTransaccionesTotalesPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaTransaccionesTotalesPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:con="http://www.ficohsa.com.hn/middleware.services/consultaTransaccionesTotalesPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/consultaTransaccionesTotalesTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaTransaccionesTotalesTypes" schemaLocation="../xsd/consultaTransaccionesTotalesTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    
    <wsdl:message name="requestHeader">
        <wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
    </wsdl:message>
    
    <wsdl:message name="responseHeader">
        <wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
    </wsdl:message>
    
    <wsdl:message name="consultaTransaccionesTotales">
        <wsdl:part element="tns:consultaTransaccionesTotales" name="parameters"/>
    </wsdl:message>
    
    <wsdl:message name="consultaTransaccionesTotalesResponse">
        <wsdl:part element="tns:consultaTransaccionesTotalesResponse" name="result"/>
    </wsdl:message>
    
    <wsdl:portType name="consultaTransaccionesTotalesPS">
        <wsdl:operation name="consultaTransaccionesTotales" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="con:consultaTransaccionesTotales"/>
            <wsdl:output message="con:consultaTransaccionesTotalesResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="consultaTransaccionesTotalesPSSOAP" type="con:consultaTransaccionesTotalesPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="consultaTransaccionesTotales">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaTransaccionesTotalesPS/consultaTransaccionesTotales"/>
            <wsdl:input>
                <soap:body use="literal" parts="parameters"/>
                <soap:header message="con:requestHeader" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="result"/>
                <soap:header message="con:responseHeader" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="consultaTransaccionesTotalesPS">
        <wsdl:port binding="con:consultaTransaccionesTotalesPSSOAP" name="consultaTransaccionesTotalesPSSOAP">
            <soap:address location="https://mwomnicanal:8004/Middleware/OperationsAndExecution/ConsumerService/ConsultaTransaccionesTotales"/>
        </wsdl:port>
    </wsdl:service>
    
</wsdl:definitions>