<wsdl:definitions name="consultaDetalleIntraPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaDetalleIntraPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/consultaDetalleIntraPS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaDetalleIntraTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaDetalleIntraTypes" schemaLocation="../xsd/consultaDetalleIntraTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaDetalleIntra">
		<wsdl:part element="cons:consultaDetalleIntra" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>

	<wsdl:message name="consultaDetalleIntraResponse">
		<wsdl:part element="cons:consultaDetalleIntraResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaDetalleIntraPS">
		<wsdl:operation name="consultaDetalleIntra">
			<wsdl:input message="tns:consultaDetalleIntra"/>
			<wsdl:output message="tns:consultaDetalleIntraResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaDetalleIntraPSSOAP" type="tns:consultaDetalleIntraPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaDetalleIntra">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaDetalleIntraPS/consultaDetalleIntra"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="tns:consultaDetalleIntra" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="tns:consultaDetalleIntraResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaDetalleIntraPS">
		<wsdl:port binding="tns:consultaDetalleIntraPSSOAP" name="consultaDetalleIntraPSSOAP">
			<soap:address location="https://mwomnicanal:8004/Middleware/OperationsAndExecution/Cards/consultaDetalleIntraPS"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>