<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/guardaBitacoraEnvioSMS/guardaBitacoraEnvioSMS" name="guardaBitacoraEnvioSMS-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/guardaBitacoraEnvioSMS/guardaBitacoraEnvioSMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/guardaBitacoraEnvioSMS/guardaBitacoraEnvioSMS" location="guardaBitacoraEnvioSMS.wsdl"/>
  <binding name="guardaBitacoraEnvioSMS_ptt-binding" type="tns:guardaBitacoraEnvioSMS_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="guardaBitacoraEnvioSMS">
      <soap:operation soapAction="guardaBitacoraEnvioSMS"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="guardaBitacoraEnvioSMS-service">
    <port name="guardaBitacoraEnvioSMS-port" binding="tns:guardaBitacoraEnvioSMS_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>