<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/MWBanking/GetCustomerDetailsPA_BS" name="GetCustomerDetailsPA_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GetCustomerDetailsPA_BS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/MWBanking/GetCustomerDetailsPA_BS"/>
    <wsdl:binding name="GetCustomerDetailsPA_BS_ptt-binding" type="get:GetCustomerDetailsPA_BS_ptt" xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/MWBanking/GetCustomerDetailsPA_BS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="GetCustomerDetailsPA_BS">
            <soap:operation soapAction="GetCustomerDetailsPA_BS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>