<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOAApplication/Project3/MCPagoCHQOtroBCO" name="MCPagoCHQOtroBCO-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAApplication/Project3/MCPagoCHQOtroBCO" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOAApplication/Project3/MCPagoCHQOtroBCO" location="MCPagoCHQOtroBCO.wsdl"/>
  <binding name="MCPagoCHQOtroBCO_ptt-binding" type="tns:MCPagoCHQOtroBCO_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="MCPagoCHQOtroBCO">
      <soap:operation soapAction="MCPagoCHQOtroBCO"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="MCPagoCHQOtroBCO-service">
    <port name="MCPagoCHQOtroBCO-port" binding="tns:MCPagoCHQOtroBCO_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>