<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareRegionalSOAApplication/BloqueoTarjetaDebito/bloqueoTarjetaDebito" name="bloqueoTarjetaDebito-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareRegionalSOAApplication/BloqueoTarjetaDebito/bloqueoTarjetaDebito" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareRegionalSOAApplication/BloqueoTarjetaDebito/bloqueoTarjetaDebito" location="bloqueoTarjetaDebito.wsdl"/>
  <binding name="bloqueoTarjetaDebito_ptt-binding" type="tns:bloqueoTarjetaDebito_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="bloqueoTarjetaDebito">
      <soap:operation soapAction="bloqueoTarjetaDebito"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="bloqueoTarjetaDebito-service">
    <port name="bloqueoTarjetaDebito-port" binding="tns:bloqueoTarjetaDebito_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksPA"/>
    </port>
  </service>
</definitions>