<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/SolicitudReposicionPinTarjetaCreditoT24/reposicionPinTarjetaCreditoT24" name="reposicionPinTarjetaCreditoT24-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/SolicitudReposicionPinTarjetaCreditoT24/reposicionPinTarjetaCreditoT24" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/SolicitudReposicionPinTarjetaCreditoT24/reposicionPinTarjetaCreditoT24" location="SolicitudReposicionPinTarjetaCreditoT24/reposicionPinTarjetaCreditoT24.wsdl"/>
  <binding name="reposicionPinTarjetaCreditoT24_ptt-binding" type="tns:reposicionPinTarjetaCreditoT24_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="reposicionPinTarjetaCreditoT24">
      <soap:operation soapAction="reposicionPinTarjetaCreditoT24"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="reposicionPinTarjetaCreditoT24-service">
    <port name="reposicionPinTarjetaCreditoT24-port" binding="tns:reposicionPinTarjetaCreditoT24_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterbanca"/>
    </port>
  </service>
</definitions>