<wsdl:definitions name="pagoGOPDEIPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/pagoGOPPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/pagoGOPPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:trb="http://www.ficohsa.com.hn/middleware.services/tributosTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>    	    
    </xsd:schema>    	
    <xsd:schema>
    	<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/tributosTypes" schemaLocation="../../TributosDEI/xsd/tributosTypes.xsd"/>
    </xsd:schema>    
  </wsdl:types>
  
  
  <wsdl:message name="pagoGOPRequest">
    <wsdl:part element="trb:pagoGOP" name="parameters"/>
    <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
  </wsdl:message>
  
  <wsdl:message name="pagoGOPResponse">
    <wsdl:part element="trb:pagoGOPResponse" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="pagoGOPPS">
    <wsdl:operation name="pagoGOP" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="fic:pagoGOPRequest"/>
      <wsdl:output message="fic:pagoGOPResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  
  
  <wsdl:binding name="pagoGOPPSSOAP" type="fic:pagoGOPPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="pagoGOP">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/pagoGOPPS/pagoGOP"/>
      <wsdl:input>
        <soap:body use="literal" parts="parameters"/>
        <soap:header use="literal" part="RequestHeader" message="fic:pagoGOPRequest"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header use="literal" part="ResponseHeader" message="fic:pagoGOPResponse"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="pagoGOPPS">
    <wsdl:port binding="fic:pagoGOPPSSOAP" name="pagoGOPPSSOAP">
      <soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/CommonBusinessInformation/pagoGOP_v2"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>