<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplePay/MovilGetPushReceipt/movilGetPushReceipt" name="movilGetPushReceipt-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ApplePay/MovilGetPushReceipt/movilGetPushReceipt" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplePay/MovilGetPushReceipt/movilGetPushReceipt" location="movilGetPushReceipt.wsdl"/>
  <binding name="movilGetPushReceipt_ptt-binding" type="tns:movilGetPushReceipt_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="movilGetPushReceipt">
      <soap:operation soapAction="movilGetPushReceipt"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="movilGetPushReceipt-service">
    <port name="movilGetPushReceipt-port" binding="tns:movilGetPushReceipt_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionDigitalizacionTarjetas"/>
    </port>
  </service>
</definitions>