<wsdl:definitions name="sjConsultaTarjetasCreditoAll" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaTarjetasCreditoAll/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/sjConsultaTarjetasCreditoAll/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaClientesTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../../../../Resources/esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaClientesTypes" schemaLocation="../../../../../../Business_Resources/consultasCliente/Resources/consultaClientesTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="consultaPasivosClienteRequest">
    <wsdl:part element="cons:consultaPasivosClienteRequest" name="parameters"/>
    <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
  </wsdl:message>
  <wsdl:message name="consultaPasivosClienteResponse">
    <wsdl:part element="cons:consultaPasivosClienteResponse" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="sjConsultaTarjetasCreditoAll">
    <wsdl:operation name="consultaTarjetasCreditoAll" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="fic:consultaPasivosClienteRequest"/>
      <wsdl:output message="fic:consultaPasivosClienteResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="sjConsultaTarjetasCreditoAllSOAP" type="fic:sjConsultaTarjetasCreditoAll">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultaTarjetasCreditoAll">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/sjConsultaTarjetasCreditoAll/consultaPasivosCliente"/>
      <wsdl:input>
        <soap:body use="literal" parts="parameters"/>
        <soap:header message="fic:consultaPasivosClienteRequest" part="RequestHeader" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header message="fic:consultaPasivosClienteResponse" part="ResponseHeader" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="sjConsultaTarjetasCreditoAll">
    <wsdl:port binding="fic:sjConsultaTarjetasCreditoAllSOAP" name="sjConsultaTarjetasCreditoAllSOAP">
      <soap:address location="http://10.242.104.250:8003/Middleware/OperationsAndExecution/PositionManagement/ConsultaPasivosCliente"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>