<wsdl:definitions targetNamespace="http://common.ws.mcrewards.mastercard.com/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://common.ws.mcrewards.mastercard.com/" xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<xs:schema>
      
  <xs:import namespace="http://common.ws.mcrewards.mastercard.com/" schemaLocation="../xsd/CommonResponses.xsd"/>
    
</xs:schema>
  </wsdl:types>
  <wsdl:message name="identity">
    <wsdl:part element="tns:identity" name="identity">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="mrsErrorResponse">
    <wsdl:part element="tns:ErrorResp" name="parameters">
    </wsdl:part>
  </wsdl:message>
    <wsp:Policy wsu:Id="XMLGW_Inbound_Policy">
    <!-- We use an asymmetric RSA key for signing, so use AsymmetricBinding -->
    <sp:AsymmetricBinding>
      <wsp:Policy>
        <!-- Describes the BinarySecurityToken element that contains signing key -->
        <sp:InitiatorSignatureToken>
          <wsp:Policy>
            <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
              <wsp:Policy>
                <sp:WssX509V3Token11/>
              </wsp:Policy>
            </sp:X509Token>
          </wsp:Policy>
        </sp:InitiatorSignatureToken>

        <!-- Include timestamp with default expiry -->
        <sp:IncludeTimestamp/>

        <!-- Sign the binary security token -->
        <sp:ProtectTokens/>

        <!-- Ensure we don't use SHA1 as this is not accepted by the gateway, minimum of SHA256 or above. -->
        <sp:AlgorithmSuite signatureAlgorithm="SHA512withRSA">
          <wsp:Policy>
            <sp:Basic256Sha256/>
          </wsp:Policy>
        </sp:AlgorithmSuite>

        <sp:OnlySignEntireHeadersAndBody/>
      </wsp:Policy>
    </sp:AsymmetricBinding>

    <!-- Sign the entire body -->
    <sp:SignedParts>
      <sp:Body/>
      <sp:Header Namespace="http://common.ws.mcrewards.mastercard.com/" name="identity"/>
    </sp:SignedParts>

  </wsp:Policy>
</wsdl:definitions>