<wsdl:definitions targetNamespace="http://www.ficohsa.com.hn/middleware.services/modificacionTarjetaDebito/" name="modificacionTarjetaDebitoPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/modificacionTarjetaDebito/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/modificacionTarjetaDebitoTypes">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/modificacionTarjetaDebitoTypes" schemaLocation="../xsd/modificacionTarjetaDebitoTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="modificacionTarjetaDebitoRequest">
		<wsdl:part element="tns:modificacionTarjetaDebito" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="modificacionTarjetaDebitoResponse">
		<wsdl:part element="tns:modificacionTarjetaDebitoResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="modificacionTarjetaDebitoPS">
		<wsdl:operation name="modificacionTarjetaDebito" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:modificacionTarjetaDebitoRequest"/>
			<wsdl:output message="fic:modificacionTarjetaDebitoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="modificacionTarjetaDebitoPSSOAP" type="fic:modificacionTarjetaDebitoPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="modificacionTarjetaDebito">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/modificacionTarjetaDebitoPS/modificacionTarjetaDebito"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:modificacionTarjetaDebitoRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:modificacionTarjetaDebitoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="modificacionTarjetaDebitoPS">
		<wsdl:port binding="fic:modificacionTarjetaDebitoPSSOAP" name="modificacionTarjetaDebitoPSSOAP">
	  		<soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/CustomerDeposits/modificacionTarjetaDebito"/>
	   	</wsdl:port>
	</wsdl:service>

</wsdl:definitions>