<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CobisNIApplication/ConsultarTasaCambio/consultarTasaCambio" name="consultarTasaCambio-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CobisNIApplication/ConsultarTasaCambio/consultarTasaCambio" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CobisNIApplication/ConsultarTasaCambio/consultarTasaCambio" location="consultarTasaCambio.wsdl"/>
  <binding name="consultarTasaCambio_ptt-binding" type="tns:consultarTasaCambio_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultarTasaCambio">
      <soap:operation soapAction="consultarTasaCambio"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultarTasaCambio-service">
    <port name="consultarTasaCambio-port" binding="tns:consultarTasaCambio_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterbanca"/>
    </port>
  </service>
</definitions>