<wsdl:definitions name="consultaSaldoPromedioCuentaPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaSaldoPromedioCuentaPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaSaldoPromedioCuentaPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultasType">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultasType" schemaLocation="../Resources/consultasGeneralesCuentasTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaSaldoPromedioCuentaRequest">
		<wsdl:part element="cons:consultaSaldoPromedioCuenta" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaSaldoPromedioCuentaResponse">
		<wsdl:part element="cons:consultaSaldoPromedioCuentaResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaSaldoPromedioCuentaPS">
		<wsdl:operation name="consultaSaldoPromedioCuenta" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaSaldoPromedioCuentaRequest"/>
			<wsdl:output message="fic:consultaSaldoPromedioCuentaResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaSaldoPromedioCuentaPSSOAP" type="fic:consultaSaldoPromedioCuentaPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaSaldoPromedioCuenta">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaSaldoPromedioCuentaPS/consultaSaldoPromedioCuenta"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaSaldoPromedioCuentaRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaSaldoPromedioCuentaResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaSaldoPromedioCuentaPS">
		<wsdl:port binding="fic:consultaSaldoPromedioCuentaPSSOAP" name="consultaSaldoPromedioCuentaPSSOAP">
			<soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/CustomerDeposits/ConsultaSaldoPromedioCuenta"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>