<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultaLineasCreditoCliente/consultaLineasCreditoCliente/consultaLineasCreditoCliente" name="consultaLineasCreditoCliente-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/consultaLineasCreditoCliente/consultaLineasCreditoCliente/consultaLineasCreditoCliente" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultaLineasCreditoCliente/consultaLineasCreditoCliente/consultaLineasCreditoCliente" location="consultaLineasCreditoCliente.wsdl"/>
  <binding name="consultaLineasCreditoCliente_ptt-binding" type="tns:consultaLineasCreditoCliente_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaLineasCreditoCliente">
      <soap:operation soapAction="consultaLineasCreditoCliente"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaLineasCreditoCliente-service">
    <port name="consultaLineasCreditoCliente-port" binding="tns:consultaLineasCreditoCliente_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>