<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultarRespuestaTercero/consultarRespuestaTercero" name="consultarRespuestaTercero-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultarRespuestaTercero/consultarRespuestaTercero" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultarRespuestaTercero/consultarRespuestaTercero" location="ConsultarRespuestaTercero/consultarRespuestaTercero.wsdl"/>
  <binding name="consultarRespuestaTercero_ptt-binding" type="tns:consultarRespuestaTercero_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultarRespuestaTercero">
      <soap:operation soapAction="consultarRespuestaTercero"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultarRespuestaTercero-service">
    <port name="consultarRespuestaTercero-port" binding="tns:consultarRespuestaTercero_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>