<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/registraVentaMenor/registraVentaMenor/registraVentaMenor" name="registraVentaMenor-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/registraVentaMenor/registraVentaMenor/registraVentaMenor" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/registraVentaMenor/registraVentaMenor/registraVentaMenor" location="registraVentaMenor.wsdl"/>
  <binding name="registraVentaMenor_ptt-binding" type="tns:registraVentaMenor_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registraVentaMenor">
      <soap:operation soapAction="registraVentaMenor"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registraVentaMenor-service">
    <port name="registraVentaMenor-port" binding="tns:registraVentaMenor_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>