<WL5G3N0:definitions name="procesaMensajeGenericoT24PS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoT24PS/" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoT24Types" xmlns:WL5G3N2="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:WL5G3N3="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoT24PS/" xmlns:WL5G3N4="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoT24Types" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoT24PS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsd/XMLSchema_24336980.xsd"/>
    </xsd:schema>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoT24Types" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoT24PS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoT24Types" schemaLocation="../xsd/XMLSchema_1301989128.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="procesaMensajeGenericoT24Request">
    <WL5G3N0:part element="WL5G3N1:procesaMensajeGenericoT24" name="parameters"/>
    <WL5G3N0:part element="WL5G3N2:RequestHeader" name="RequestHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="procesaMensajeGenericoT24Response">
    <WL5G3N0:part element="WL5G3N1:procesaMensajeGenericoT24Response" name="result"/>
    <WL5G3N0:part element="WL5G3N2:ResponseHeader" name="ResponseHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="procesaMensajeGenericoT24PS">
    <WL5G3N0:operation name="procesaMensajeGenericoT24" parameterOrder="parameters RequestHeader ResponseHeader">
      <WL5G3N0:input message="WL5G3N3:procesaMensajeGenericoT24Request"/>
      <WL5G3N0:output message="WL5G3N3:procesaMensajeGenericoT24Response"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="procesaMensajeGenericoT24PSSOAP" type="WL5G3N3:procesaMensajeGenericoT24PS">
    <WL5G3N4:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="procesaMensajeGenericoT24">
      <WL5G3N4:operation soapAction="http://www.ficohsa.com.hn/middleware.services/procesaMensajeGenericoT24PS"/>
      <WL5G3N0:input>
        <WL5G3N4:header message="WL5G3N3:procesaMensajeGenericoT24Request" part="RequestHeader" use="literal"/>
        <WL5G3N4:body parts="parameters" use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N4:header message="WL5G3N3:procesaMensajeGenericoT24Response" part="ResponseHeader" use="literal"/>
        <WL5G3N4:body parts="result" use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="procesaMensajeGenericoT24PS">
    <WL5G3N0:port binding="WL5G3N3:procesaMensajeGenericoT24PSSOAP" name="procesaMensajeGenericoT24PSSOAP">
      <WL5G3N4:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Messaging/ProcesaMensajeGenericoT24TC"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>