<wsdl:definitions name="consultaUltimosNMovimientosCuentaPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaUltimosNMovimientosCuentaPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaUltimosNMovimientosCuentaPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultasType">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultasType" schemaLocation="../Resources/consultasGeneralesCuentasTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaUltimosNMovimientosCuentaRequest">
		<wsdl:part element="cons:consultaUltimosNMovimientosCuenta" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaUltimosNMovimientosCuentaResponse">
		<wsdl:part element="cons:consultaUltimosNMovimientosCuentaResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaUltimosNMovimientosCuentaPS">
		<wsdl:operation name="consultaUltimosNMovimientosCuenta" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaUltimosNMovimientosCuentaRequest"/>
			<wsdl:output message="fic:consultaUltimosNMovimientosCuentaResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaUltimosNMovimientosCuentaPSSOAP" type="fic:consultaUltimosNMovimientosCuentaPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaUltimosNMovimientosCuenta">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaUltimosNMovimientosCuentaPS/consultaUltimosNMovimientosCuenta"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaUltimosNMovimientosCuentaRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaUltimosNMovimientosCuentaResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaUltimosNMovimientosCuentaPS">
		<wsdl:port binding="fic:consultaUltimosNMovimientosCuentaPSSOAP" name="consultaUltimosNMovimientosCuentaPSSOAP">
			<soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/CustomerDeposits/ConsultaUltimosNMovimientosCuenta"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>