<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/cache3/registraAutorizacionesFlotantes" name="registraAutorizacionesFlotantes-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/cache3/registraAutorizacionesFlotantes" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/cache3/registraAutorizacionesFlotantes" location="registraAutorizacionesFlotantes.wsdl"/>
  <binding name="registraAutorizacionesFlotantes_ptt-binding" type="tns:registraAutorizacionesFlotantes_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registraAutorizacionesFlotantes">
      <soap:operation soapAction="registraAutorizacionesFlotantes"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registraAutorizacionesFlotantes-service">
    <port name="registraAutorizacionesFlotantes-port" binding="tns:registraAutorizacionesFlotantes_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionClientdata"/>
    </port>
  </service>
</definitions>