<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/ConsultaEstadoTransaccionTC/ConsultaEstadoTransaccionACH" name="ConsultaEstadoTransaccionACH-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/ConsultaEstadoTransaccionTC/ConsultaEstadoTransaccionACH" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/ConsultaEstadoTransaccionTC/ConsultaEstadoTransaccionACH" location="ConsultaEstadoTransaccionACH.wsdl"/>
  <binding name="ConsultaEstadoTransaccionACH_ptt-binding" type="tns:ConsultaEstadoTransaccionACH_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ConsultaEstadoTransaccionACH">
      <soap:operation soapAction="ConsultaEstadoTransaccionACH"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ConsultaEstadoTransaccionACH-service">
    <port name="ConsultaEstadoTransaccionACH-port" binding="tns:ConsultaEstadoTransaccionACH_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionPagosWSTC"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="ConsultaEstadoTransaccionACH.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/ConsultaEstadoTransaccionTC/ConsultaEstadoTransaccionACH">
            <con:wsdl ref="Middleware/v2/BusinessServices/OperacionesACH/ConsultaEstadoTransaccionTC/wsdl/ConsultaEstadoTransaccionACH"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/Application1/ConsultaEstadoTransaccionTC/ConsultaEstadoTransaccionACH</con:targetNamespace>
</con:wsdlEntry>