<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/inbound/T24NewCustomerEvent/T24NewCustomerEvent/T24NewCustomerEvent" name="T24NewCustomerEvent-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/inbound/T24NewCustomerEvent/T24NewCustomerEvent/T24NewCustomerEvent" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/inbound/T24NewCustomerEvent/T24NewCustomerEvent/T24NewCustomerEvent" location="T24NewCustomerEvent.wsdl"/>
  <binding name="EventPoll_ptt-binding" type="tns:EventPoll_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="EventPoll">
      <soap:operation soapAction="EventPoll"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="T24NewCustomerEvent-service">
    <port name="T24NewCustomerEvent-port" binding="tns:EventPoll_ptt-binding">
      <soap:address location="jca://eis/T24Adapter"/>
    </port>
  </service>
</definitions>