<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTargetDLC/consultaTargetTipoPrestamo/consultaTargetTipoPrestamo" name="consultaTargetTipoPrestamo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTargetDLC/consultaTargetTipoPrestamo/consultaTargetTipoPrestamo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTargetDLC/consultaTargetTipoPrestamo/consultaTargetTipoPrestamo" location="consultaTargetTipoPrestamo.wsdl"/>
  <binding name="consultaTargetTipoPrestamo_ptt-binding" type="tns:consultaTargetTipoPrestamo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaTargetTipoPrestamo">
      <soap:operation soapAction="consultaTargetTipoPrestamo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaTargetTipoPrestamo-service">
    <port name="consultaTargetTipoPrestamo-port" binding="tns:consultaTargetTipoPrestamo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionDLC"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="consultaTargetTipoPrestamo.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTargetDLC/consultaTargetTipoPrestamo/consultaTargetTipoPrestamo">
            <con:wsdl ref="Middleware/v2/BusinessServices/ServiciosEmpresariales/consultaTargetTipoPrestamo/wsdl/consultaTargetTipoPrestamo"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarTargetDLC/consultaTargetTipoPrestamo/consultaTargetTipoPrestamo</con:targetNamespace>
</con:wsdlEntry>