<wsdl:definitions name="reservaFondosChequePS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/reservaFondosChequePS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/reservaFondosChequePS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/reservaFondosChequeTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/reservaFondosChequeTypes" schemaLocation="reservaFondosChequeTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="reservaFondosChequeRequest">
		<wsdl:part element="cons:reservaFondosCheque" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="reservaFondosChequeResponse">
		<wsdl:part element="cons:reservaFondosChequeResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="reservaFondosChequePS">
		<wsdl:operation name="reservaFondosCheque" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:reservaFondosChequeRequest"/>
			<wsdl:output message="fic:reservaFondosChequeResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="reservaFondosChequePSSOAP" type="fic:reservaFondosChequePS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="reservaFondosCheque">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/reservaFondosChequePS/reservaFondosCheque"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:reservaFondosChequeRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:reservaFondosChequeResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="reservaFondosChequePS">
    <wsdl:port binding="fic:reservaFondosChequePSSOAP" name="reservaFondosChequePSSOAP">
      <soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/Payments/ReservaFondosCheque"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>