<wsdl:definitions name="consultaInventarioPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaInventarioPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaInventarioPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaInventarioTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaInventarioTypes" schemaLocation="../xsd/consultaInventarioTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="consultaInventarioRequest">
		<wsdl:part element="cons:consultaInventario" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaInventarioResponse">
		<wsdl:part element="cons:consultaInventarioResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="consultaInventarioPS">
		<wsdl:operation name="consultaInventario" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaInventarioRequest"/>
			<wsdl:output message="fic:consultaInventarioResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaInventarioPSSOAP" type="fic:consultaInventarioPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaInventario">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaInventarioPS"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaInventarioRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaInventarioResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="consultaInventarioPS">
    <wsdl:port binding="fic:consultaInventarioPSSOAP" name="consultaInventarioPSSOAP">
      <soap:address location="http://10.9.104.55:8003/Middleware/SalesAndServices/SalesProduct/consultaInventario"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>