<WL5G3N0:definitions name="pagoRecaudoPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/pagoRecaudo/" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoTypes" xmlns:WL5G3N2="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:WL5G3N3="http://www.ficohsa.com.hn/middleware.services/pagoRecaudo/" xmlns:WL5G3N4="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/pagoRecaudo/" xmlns:pag="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoTypes" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElementsCB.xsd"/>
    </xsd:schema>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/pagoRecaudo/" xmlns:pag="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoTypes" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/pagoRecaudoTypes" schemaLocation="../xsd/pagoRecaudoCBTypes.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="pagoRecaudoRequest">
    <WL5G3N0:part element="WL5G3N1:pagoRecaudo" name="parameters"/>
    <WL5G3N0:part element="WL5G3N2:RequestHeader" name="RequestHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="pagoRecaudoResponse">
    <WL5G3N0:part element="WL5G3N1:pagoRecaudoResponse" name="result"/>
    <WL5G3N0:part element="WL5G3N2:ResponseHeader" name="ResponseHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="pagoRecaudoPS">
    <WL5G3N0:operation name="pagoRecaudo" parameterOrder="parameters RequestHeader ResponseHeader">
      <WL5G3N0:input message="WL5G3N3:pagoRecaudoRequest"/>
      <WL5G3N0:output message="WL5G3N3:pagoRecaudoResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="pagoRecaudoPSSOAP" type="WL5G3N3:pagoRecaudoPS">
    <WL5G3N4:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="pagoRecaudo">
      <WL5G3N4:operation soapAction="http://www.ficohsa.com.hn/middleware.services/pagoRecaudo/pagoRecaudo"/>
      <WL5G3N0:input>
        <WL5G3N4:body parts="parameters" use="literal"/>
        <WL5G3N4:header message="WL5G3N3:pagoRecaudoRequest" part="RequestHeader" use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N4:body parts="result" use="literal"/>
        <WL5G3N4:header message="WL5G3N3:pagoRecaudoResponse" part="ResponseHeader" use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="pagoRecaudoPS">
    <WL5G3N0:port binding="WL5G3N3:pagoRecaudoPSSOAP" name="pagoRecaudoPSSOAP">
      <WL5G3N4:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/Payments/PagoRecaudoCB"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>