<wsdl:definitions name="confirmaChequeVirtualPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/confirmaChequeVirtualPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/confirmaChequeVirtualPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:ccvt="http://www.ficohsa.com.hn/middleware.services/confirmaChequeVirtualTypes">
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/confirmaChequeVirtualTypes" schemaLocation="../xsd/confirmaChequeVirtualTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="confirmaChequeVirtualRequest">
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
		<wsdl:part name="parameters" element="ccvt:confirmaChequeVirtual"/>
	</wsdl:message>
	<wsdl:message name="confirmaChequeVirtualResponse">
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
		<wsdl:part name="result" element="ccvt:confirmaChequeVirtualResponse"/>
	</wsdl:message>
	<wsdl:portType name="confirmaChequeVirtualPS">
		<wsdl:operation name="confirmaChequeVirtual" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:confirmaChequeVirtualRequest"/>
			<wsdl:output message="fic:confirmaChequeVirtualResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="confirmaChequeVirtualPSSOAP" type="fic:confirmaChequeVirtualPS">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
		<wsdl:operation name="confirmaChequeVirtual">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/confirmaChequeVirtualPS/confirmaChequeVirtual"/>
			<wsdl:input>
				<soap:header use="literal" part="RequestHeader" message="fic:confirmaChequeVirtualRequest"/>
				<soap:body use="literal" parts="parameters"/>
			</wsdl:input>
			<wsdl:output>
				<soap:header use="literal" part="ResponseHeader" message="fic:confirmaChequeVirtualResponse"/>
				<soap:body use="literal" parts="result"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="confirmaChequeVirtualPS">
		<wsdl:port name="confirmaChequeVirtualPSSOAP" binding="fic:confirmaChequeVirtualPSSOAP">
			<soap:address location="https://172.23.13.19:8004/Middleware/OperationsAndExecution/CustomeDeposits/ConfirmaChequeVirtual"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>