<wsdl:definitions name="RollbackTaxesBulletin" targetNamespace="https://www.ficohsa.com/regional/transfer/transferTypes" xmlns:tns="https://www.ficohsa.com/regional/transfer/transferTypes" xmlns:inp1="https://www.ficohsa.com/regional/transfer/transferTypes" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="https://www.ficohsa.com/regional/transfer/transferTypes" schemaLocation="../Schemas/RollbackTaxesBulletinTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="rollbackTaxesBulletin" element="tns:rollbackTaxesBullletin"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="rollbackTaxesBulletinResponse" element="tns:rollbackTaxesBullletinResponse"/>
    </wsdl:message>
    <wsdl:portType name="rollbackTaxesBulletinPtt">
        <wsdl:operation name="rollbackTaxesBulletin">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="rollbackTaxesBulletinBind" type="tns:rollbackTaxesBulletinPtt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="rollbackTaxesBulletin">
            <soap:operation style="document" soapAction="rollbackTaxesBulletin"/>
            <wsdl:input>
                <soap:body use="literal" namespace="https://www.ficohsa.com/regional/transfer/transferTypes"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="https://www.ficohsa.com/regional/transfer/transferTypes"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>