<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/obtenerEquivalencia/obtenerEquivalencia" name="obtenerEquivalencia-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/obtenerEquivalencia/obtenerEquivalencia" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/obtenerEquivalencia/obtenerEquivalencia" location="obtenerEquivalencia.wsdl"/>
  <binding name="obtenerEquivalencia_ptt-binding" type="tns:obtenerEquivalencia_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="obtenerEquivalencia">
      <soap:operation soapAction="obtenerEquivalencia"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="obtenerEquivalencia-service">
    <port name="obtenerEquivalencia-port" binding="tns:obtenerEquivalencia_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionClientdata"/>
    </port>
  </service>
</definitions>