<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ValidacionOverlimit/ValidacionOverlimit/ValidacionOverlimit" name="ValidacionOverlimit-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ValidacionOverlimit/ValidacionOverlimit/ValidacionOverlimit" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ValidacionOverlimit/ValidacionOverlimit/ValidacionOverlimit" location="ValidacionOverlimit.wsdl"/>
  <binding name="ValidacionOverlimit_ptt-binding" type="tns:ValidacionOverlimit_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ValidacionOverlimit">
      <soap:operation soapAction="ValidacionOverlimit"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ValidacionOverlimit-service">
    <port name="ValidacionOverlimit-port" binding="tns:ValidacionOverlimit_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>