<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultaRutaInfoCheques/consultaRutaInfoCheques" name="consultaRutaInfoCheques-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultaRutaInfoCheques/consultaRutaInfoCheques" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultaRutaInfoCheques/consultaRutaInfoCheques" location="consultaRutaInfoCheques.wsdl"/>
  <binding name="consultaRutaInfoCheques_ptt-binding" type="tns:consultaRutaInfoCheques_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaRutaInfoCheques">
      <soap:operation soapAction="consultaRutaInfoCheques"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaRutaInfoCheques-service">
    <port name="consultaRutaInfoCheques-port" binding="tns:consultaRutaInfoCheques_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>