<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionWorkflow/consultaConceptos/consultaConceptos" name="consultaConceptos-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionWorkflow/consultaConceptos/consultaConceptos" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionWorkflow/consultaConceptos/consultaConceptos" location="consultaConceptos.wsdl"/>
  <binding name="consultaConceptos_ptt-binding" type="tns:consultaConceptos_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaConceptos">
      <soap:operation soapAction="consultaConceptos"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaConceptos-service">
    <port name="consultaConceptos-port" binding="tns:consultaConceptos_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWorkflow"/>
    </port>
  </service>
</definitions>