<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/RegistroBitacoraVtaMenor/registroBitacoraVtaMenor" name="registroBitacoraVtaMenor-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/RegistroBitacoraVtaMenor/registroBitacoraVtaMenor" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/RegistroBitacoraVtaMenor/registroBitacoraVtaMenor" location="registroBitacoraVtaMenor.wsdl"/>
  <binding name="registroBitacoraVtaMenor_ptt-binding" type="tns:registroBitacoraVtaMenor_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registroBitacoraVtaMenor">
      <soap:operation soapAction="registroBitacoraVtaMenor"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="registroBitacoraVtaMenor-service">
    <port name="registroBitacoraVtaMenor-port" binding="tns:registroBitacoraVtaMenor_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>