<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultaReciboServicio/consultaReciboServicio" name="consultaReciboServicio-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultaReciboServicio/consultaReciboServicio" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultaReciboServicio/consultaReciboServicio" location="consultaReciboServicio.wsdl"/>
  <binding name="consultaReciboServicio_ptt-binding" type="tns:consultaReciboServicio_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaReciboServicio">
      <soap:operation soapAction="consultaReciboServicio"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaReciboServicio-service">
    <port name="consultaReciboServicio-port" binding="tns:consultaReciboServicio_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>