<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultaDetalleTransaccion/consultaDetalleTransaccion" name="consultaDetalleTransaccion-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultaDetalleTransaccion/consultaDetalleTransaccion" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultaDetalleTransaccion/consultaDetalleTransaccion" location="ConsultaDetalleTransaccionAbanks/consultaDetalleTransaccion.wsdl"/>
  <binding name="consultaDetalleTransaccion_ptt-binding" type="tns:consultaDetalleTransaccion_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaDetalleTransaccion">
      <soap:operation soapAction="consultaDetalleTransaccion"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaDetalleTransaccion-service">
    <port name="consultaDetalleTransaccion-port" binding="tns:consultaDetalleTransaccion_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterbanca"/>
    </port>
  </service>
</definitions>