<wsdl:definitions name="consultaVisanetPosDwhPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaVisanetPosDwhPS" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaVisanetPosDwhPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:aut="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:con="http://www.ficohsa.com.hn/middleware.services/consultaVisanetPosDwhTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaVisanetPosDwhTypes" schemaLocation="../xsd/consultaVisanetPosDwhTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
 
  <wsdl:message name="consultaVisanetPosDwhPSRequest">
  	<wsdl:part name="reqHeader" element="aut:RequestHeader"/>
  	<wsdl:part name="inputParameters" element="con:consultaVisanetPosDwhRequest"/>
  </wsdl:message>
  
  <wsdl:message name="consultaVisanetPosDwhPSResponse">
  	<wsdl:part name="resHeader" element="aut:ResponseHeader"/>
  	<wsdl:part name="outputResult" element="con:consultaVisanetPosDwhResponse"/>
  </wsdl:message>
  
  <wsdl:portType name="consultaVisanetPosDwhPS">
    <wsdl:operation name="consultaVisanetPosDwh">
      <wsdl:input message="fic:consultaVisanetPosDwhPSRequest"/>
      <wsdl:output message="fic:consultaVisanetPosDwhPSResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="consultaVisanetPosDwhPSSOAP" type="fic:consultaVisanetPosDwhPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultaVisanetPosDwh">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaVisanetPosDwhPS/consultaVisanetPosDwh"/>
      
      <wsdl:input>
      	<soap:header use="literal" part="reqHeader" message="fic:consultaVisanetPosDwhPSRequest"/>
        <soap:body use="literal" parts="inputParameters"/>
      </wsdl:input>
      
      <wsdl:output>
        <soap:header use="literal" part="resHeader" message="fic:consultaVisanetPosDwhPSResponse"/>
        <soap:body use="literal" parts="outputResult"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="consultaVisanetPosDwhPS">
    <wsdl:port binding="fic:consultaVisanetPosDwhPSSOAP" name="consultaVisanetPosDwhPSSOAP">
      <soap:address location="https://172.23.13.19/Middleware/ReferenceData/BusinessPartner/ConsultaVisanetPosDwh"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>