<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultaMaestraSaldosTC/consultaMaestraSaldosTC/consultaMaestraSaldosTC" name="consultaMaestraSaldosTC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/consultaMaestraSaldosTC/consultaMaestraSaldosTC/consultaMaestraSaldosTC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultaMaestraSaldosTC/consultaMaestraSaldosTC/consultaMaestraSaldosTC" location="consultaMaestraSaldosTC.wsdl"/>
  <binding name="consultaMaestraSaldosTC_ptt-binding" type="tns:consultaMaestraSaldosTC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaMaestraSaldosTC">
      <soap:operation soapAction="consultaMaestraSaldosTC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaMaestraSaldosTC-service">
    <port name="consultaMaestraSaldosTC-port" binding="tns:consultaMaestraSaldosTC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionClientdata"/>
    </port>
  </service>
</definitions>