<wsdl:definitions name="envioTransferenciasACHPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/envioTransferenciasACHPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/envioTransferenciasACHPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tran="http://www.ficohsa.com.hn/middleware.services/envioTransferenciasACHTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/envioTransferenciasACHTypes" schemaLocation="../xsd/envioTransferenciasACHTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="envioTransferenciasACHRequest">
        <wsdl:part element="tran:envioTransferenciasACH" name="parameters"/>
        <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
    </wsdl:message>
    <wsdl:message name="envioTransferenciasACHResponse">
        <wsdl:part element="tran:envioTransferenciasACHResponse" name="result"/>
        <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
    </wsdl:message>
 
    <wsdl:portType name="envioTransferenciasACHPS">
        <wsdl:operation name="envioTransferenciasACH" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="fic:envioTransferenciasACHRequest"/>
            <wsdl:output message="fic:envioTransferenciasACHResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="envioTransferenciasACHPSSOAP" type="fic:envioTransferenciasACHPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="envioTransferenciasACH">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/envioTransferenciasACHPS/envioTransferenciasACH"/>
            <wsdl:input>
                <soap:body use="literal" parts="parameters"/>
                <soap:header message="fic:envioTransferenciasACHRequest" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="result"/>
                <soap:header message="fic:envioTransferenciasACHResponse" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="envioTransferenciasACHPS">
        <wsdl:port binding="fic:envioTransferenciasACHPSSOAP" name="envioTransferenciasACHPSSOAP">
            <soap:address location="http://10.9.104.55:8003/Middleware/OperationsAndExecution/CustomerDeposits/envioTransferenciasACH"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>