<?binding.jca ValidaXml_db.jca?><wsdl:definitions name="ValidaXml" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ValidaXml/ValidaXml/ValidaXml" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ValidaXml" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ValidaXml/ValidaXml/ValidaXml" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="ValidaXml_plt">
        <plt:role name="ValidaXml_role">
            <plt:portType name="tns:ValidaXml_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/ValidaXml" schemaLocation="../xsd/ValidaXml_sp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="ValidaXml_ptt">
        <wsdl:operation name="ValidaXml">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>