<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaInformacionPersonaFPC/consultaInformacionPersonaFPC" name="consultaInformacionPersonaFPC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaInformacionPersonaFPC/consultaInformacionPersonaFPC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaInformacionPersonaFPC/consultaInformacionPersonaFPC" location="consultaInformacionPersonaFPC.wsdl"/>
  <binding name="consultaInformacionPersonaFPC_ptt-binding" type="tns:consultaInformacionPersonaFPC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaInformacionPersonaFPC">
      <soap:operation soapAction="consultaInformacionPersonaFPC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaInformacionPersonaFPC-service">
    <port name="consultaInformacionPersonaFPC-port" binding="tns:consultaInformacionPersonaFPC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionFicopen"/>
    </port>
  </service>
</definitions>