<wsdl:definitions name="consultaLoteDeudoresPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaLoteDeudoresPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaLoteDeudoresPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/cobranzasElectronicasTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/cobranzasElectronicasTypes" schemaLocation="../../CobranzasElectronicas/xsd/cobranzasElectronicasTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaLoteDeudoresRequest">
		<wsdl:part element="cons:consultaLoteDeudores" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaLoteDeudoresResponse">
		<wsdl:part element="cons:consultaLoteDeudoresResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaLoteDeudoresPS">
		<wsdl:operation name="consultaLoteDeudores" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaLoteDeudoresRequest"/>
			<wsdl:output message="fic:consultaLoteDeudoresResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaLoteDeudoresPSSOAP" type="fic:consultaLoteDeudoresPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaLoteDeudores">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaLoteDeudoresPS/consultaLoteDeudores"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaLoteDeudoresRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaLoteDeudoresResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaLoteDeudoresPS">
		<wsdl:port binding="fic:consultaLoteDeudoresPSSOAP" name="consultaLoteDeudoresPSSOAP">
			<soap:address location="http://mwomnidesa:8003/Middleware/ReferenceData/BusinessPartner/consultaLoteDeudores"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>