<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/OSB/validaListaNegraPEP" name="validaListaNegraPEP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/OSB/validaListaNegraPEP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/OSB/validaListaNegraPEP" location="validaListaNegraPEP.wsdl"/>
  <binding name="validaListaNegraPEP_ptt-binding" type="tns:validaListaNegraPEP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="validaListaNegraPEP">
      <soap:operation soapAction="validaListaNegraPEP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="validaListaNegraPEP-service">
    <port name="validaListaNegraPEP-port" binding="tns:validaListaNegraPEP_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionPrecredit"/>
    </port>
  </service>
</definitions>