<WL5G3N0:definitions name="distribuirConceptosRecaudos-concrete" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/DistribuirConceptosRecaudos/distribuirConceptosRecaudos" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/DistribuirConceptosRecaudos/distribuirConceptosRecaudos" xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:import location="WSDL_1329598027.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/DistribuirConceptosRecaudos/distribuirConceptosRecaudos"/>
  <WL5G3N0:binding name="distribuirConceptosRecaudos_ptt-binding" type="WL5G3N1:distribuirConceptosRecaudos_ptt">
    <WL5G3N2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="distribuirConceptosRecaudos">
      <WL5G3N2:operation soapAction="distribuirConceptosRecaudos"/>
      <WL5G3N0:input>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N2:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="distribuirConceptosRecaudos_ptt-bindingQSService">
    <WL5G3N0:port binding="WL5G3N1:distribuirConceptosRecaudos_ptt-binding" name="distribuirConceptosRecaudos_ptt-bindingQSPort">
      <WL5G3N2:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Payments/DistribucionConceptosRecaudos"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>