<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/creacionRemesaLocal/creacionRemesaLocal" name="creacionRemesaLocal-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/creacionRemesaLocal/creacionRemesaLocal" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/creacionRemesaLocal/creacionRemesaLocal" location="creacionRemesaLocal.wsdl"/>
  <binding name="creacionRemesaLocal_ptt-binding" type="tns:creacionRemesaLocal_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="creacionRemesaLocal">
      <soap:operation soapAction="creacionRemesaLocal"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="creacionRemesaLocal-service">
    <port name="creacionRemesaLocal-port" binding="tns:creacionRemesaLocal_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>