
sequenceDiagram
    autonumber
    participant Consumidor as Consumidore/Aplicación
    participant API as API Consulta Info Lealtad <br> Epica 2382: ConsultaPuntosLealtad <br> HU 55701:  GET - /operational-services/issued-dev-admin-retrieves/v1/retrieve-customer
    participant CL as Caché Local
    participant Lambda as Lambda de parámetros
    participant Parameter as Parameter Store
    participant Homologador as Liberería de <br> Homologación
    participant secret as Secret Manager
    participant Lib as Librería Pipeline (ConfigMap)
    participant SP as ConnectionProcesosHN <br/> SP OSBConInfoLealtad
    participant Errors as Control de Errores <br> <<Librería de mapeo de errores>>
    
    Note over Consumidor, Errors: Flujo Honduras (HN01) - ConsultaPuntosTransaccion Alcance

    Consumidor->>API: REST Request
    Note right of Consumidor: Header, queryParam: creditCardId

    API->>API: Validar Request
    Note over API: Valida campos obligatorios según contrato OpenAPI <br> creditCardId (obligatorio)

    API->>API: Validación exitosa

    alt Consulta parametros en caché local

        API->>CL: Consultar parámetros Lambda Parámetros caché local
        Note right of API: Domain: "ISSUED_DEV_ADMIN_RETRIEVES" <br> name: "retrieve-customer" <br> country: XRS 

        CL->>API: Obtiene parámetros Lambda Parámetros Cahé Local
        Note left of CL: Obtiene parámetros de regionalización y negocio
 
        API->>CL: Consultar parámetros Parameter Store caché local
        Note right of API: Param Name: lambda.param-name

        CL->>API: Obtiene parámetros Parameter Store Caché Local
        Note left of CL: Obtiene parámetros de consumo a SP OSBConInfoLealtad

    else Consulta  parametros en Lambda Parámetros / Parameter Store

        API->>Lambda: Consultar parámetros lambda parámetros
        Note right of API: Domain: "ISSUED_DEV_ADMIN_RETRIEVES" <br> name: "retrieve-customer" <br> country: XRS 

        Lambda->>API: Obtiene parámetros Lambda Parámetros
        Note left of Lambda: Obtiene parámetros de regionalización y negocio

        API->>CL: Guarda parámetros lambda Parámetros en caché local
        Note right of API: value.param-name 

        API->>Parameter: Consultar parámetros Parameter Store
        Note right of API: Param Name: lambda.param-name

        Parameter->>API: Obtiene parámetros Parameter Store
        Note left of Parameter: Obtiene parámetros de consumo a SP OSBConInfoLealtad

        API->>CL: Guarda parámetros Parameter Store en caché local
        Note right of API: Parámetros de consumo a SP OSBConInfoLealtad

    end

    API->>API: Validar Servicio Regional
    Note over API: Usando parámetros de regionalización obtenidos

    API->>API: Validación Regional Exitosa
    Note over API: Servicio habilitado para HN01 

    API->>Homologador: Consulta Homologación sourceBank
    Note right of API: params: resolve(arr, 'header.sourceBank', 'Ficohsa', 'ISO3')

    Homologador->>API: Retorna Valor Homologado 
    Note left of Homologador: HN01 → HND 

    API->>secret: Consulta Secretos para conexion a la BD
    Note right of API: secretName: lambda.secret-name

    secret->>API: Retorna secretos para conexión a la BD
    Note left of Homologador: user, password

    API->>Lib: Consulta Constantes
    
    Lib->>API: Retorna constantes necesarias
    Note left of Lib: Constantes: <br> package = dbo <br> procedureName = OSBConInfoLealtad

    API->>API: Construye Request SP OSBConInfoLealtad
    Note over API: Mapeo: <br> NumeroTarjeta = request.creditCardId <br> Pais = header.sourceBank (Homologado ISO3)

    API->>SP: Consume SP OSBConInfoLealtad
    Note right of API: serverName, port, databaseName, package, procedureName, NumeroTarjeta, Pais

    SP->>API: Response SP OSBConInfoLealtad
    Note over SP: Response: <br> RowSet: <br> NumeroIdentificacion <br> NombreClente <br> Logo <br> TipoTarjeta <br> CodigoError, MensajeError

    API->>API: Evalúa Response SP OSBConInfoLealtad
    
    alt If CodigoError == -1

        API->>API: Construye response API
        Note over API: customerLegalReference = RowSet.NumeroIdentificacion <br> cardHolderName = RowSet.NombreClente <br> cardLogoReference = RowSet.Logo <br> cardType = RowSet.TipoTarjeta 

        API->>Consumidor: Response Exitoso
        Note left of API: HTTP 200: Response Body 

    else If If CodigoError != -1

        API->> Errors: Mapear código de error
        
        Errors ->> API: Retorna código mapeado
        
        API->> Consumidor: Retorna error
        Note left of API: HTTP 422 + responseSP.mensajeError
    
    end

    Note over Consumidor, Errors: Flujo Alternativo - Error
    activate API
    alt Exception occurs
        note over Errors: Error Library Handler
        activate Errors
            API->> Errors: Mapear código de error
            Errors -->> API: Retorna código mapeado
        deactivate Errors
        activate Consumidor
            API-->> Consumidor: Retorna error
        deactivate Consumidor
        Note over Consumidor,Errors: Diagrama guía de manejo de errores <br> http://bit.ly/4rpKVIU
    end
    deactivate API