
sequenceDiagram
    autonumber
    participant Consumidor as Consumidore/Aplicación
    participant API as API Consulta Puntos Disponible MasterCard <br> Epica 2382: ConsultaPuntosLealtad <br> HU 54363:  GET - /account-management/reward-points-account-retrieves/v1/available-loyalty-points
    participant CL as Caché Local
    participant Lambda as Lambda de parámetros
    participant Parameter as Parameter Store
    participant Lib as Librería Pipeline (ConfigMap)
    participant MRS as Mastercard CustomerService <br/> Operación: getPointDetails | getRTRPreferences <br> URI DEV: https://192.168.55.21:7021/mastercard-webservices/CustomerService
    participant Errors as Control de Errores <br> <<Librería de mapeo de errores>>
    
    Note over Consumidor, Errors: Flujos Honduras, Guatemala, Panamá y Nicaragua (HN01 | GT01| PA01 | NI01) - ConsultaPuntosMastercard

    Consumidor->>API: REST Request
    Note right of Consumidor: Header, queryParam: <br> customerLegalReference, institutionName, <br> periodStartDate, periodEndDate, <br> balanceComponents, detailLevel

    API->>API: Validar Request
    Note over API: Valida campos obligatorios según contrato OpenAPI <br> customerLegalReference (obligatorio) <br> institutionName (obligatorio)

    API->>API: Validación exitosa

    alt Consulta parametros en caché local

        API->>CL: Consultar parámetros Lambda Parámetros caché local
        Note right of API: Domain: REWARD_POINTS_ACCOUNT_RETRIEVES <br>  name: "available-loyalty-points" <br> country: XRS 

        CL->>API: Obtiene parámetros Lambda Parámetros Cahé Local
        Note left of CL: ObtenerParametrizacion 1 Parámetro: <br> lambda.param-name = ban-xrs-lc-mastercard-ws-param-wsdl-<env>

        API->>CL: Consultar parámetros Parameter Store caché local
        Note right of API: Param Name: ban-xrs-lc-mastercard-ws-param-wsdl-<env>

        CL->>API: Obtiene parámetros Parameter Store Caché Local
        Note left of CL: ObtenerParametrizacion 3 Campos: <br> ip = “htts://192.168.50.54” <br> port = "7021" <br> basePath = “/mastercard-webservices/CustomerService” 

    else Consulta  parametros en Lambda Parámetros / Parameter Store

        API->>Lambda: Consultar parámetros lambda parámetros
        Note right of API: Domain: REWARD_POINTS_ACCOUNT_RETRIEVES <br>  name: "available-loyalty-points" <br> country: XRS 

        Lambda->>API: Obtiene parámetros Lambda Parámetros
        Note left of Lambda: ObtenerParametrizacion 1 Parámetro: <br> lambda.param-name = ban-xrs-lc-mastercard-ws-param-wsdl-<env>

        API->>CL: Guarda parámetros lambda Parámetros en caché local
        Note right of API: lambda.param-name 

        API->>Parameter: Consultar parámetros Parameter Store
        Note right of API: Param Name: lambda.param-name

        Parameter->>API: Obtiene parámetros Parameter Store
        Note left of Parameter: ObtenerParametrizacion 3 Campos: <br> ip = “htts://192.168.50.54” <br> port = "7021" <br> basePath = “/mastercard-webservices/CustomerService” 

        API->>CL: Guarda parámetros Parameter Store en caché local
        Note right of API: ip, port, basepPath

    end

    API->>API: Validar Servicio Regional
    Note over API: Usando parámetros de regionalización obtenidos

    API->>API: Validación Regional Exitosa
    Note over API: Servicio habilitado para HN01 | GT01 | NI01 | PA01

    API->>Lib: Consulta Constantes
   
    Lib->>API: Retorna constantes necesarias
    Note left of Lib: operation = "getPointDetails", operationGt = "getRTRPreferences"

    alt Flujos HN01  PA01 | NI01 - ConsultaPuntosMastercard

         API->>API: Construye URL WSDL
         Note over API: url = ip + port + basePath + "?wsdl"
        API->>API: Construye Request WS Mastercard - Identity (header) 
        Note over API: InstitutionName = request.institutionName <br> AppID = request.customerLegalReference

        API->>API: Construye Request WS Mastercard - getPointDetails (body)
        Note over API: fromDate = request.periodStartDate <br> toDate = request.periodEndDate <br> components = request.balanceComponents <br> breakdownLevel = request.detailLevel

        API->>MRS: Consume WS Mastercard - getPointDetails
        Note right of API: Header: InstitutionName, AppID <br> Body: fromDate, toDate, components, breakdownLevel

        MRS->>API: Response WS Mastercard - getPointDetailsResponse
        Note left of MRS: Group HouseholdPointDetails : householdId <br> Group CustomerPointDetails : customerId <br> Group AccountPointDetails : accountId  <br> Campos para todos los grupos : <br> AvailablePoints, OnHoldPoints, previousBalance, pointsEarned, pointsRedeemed

        API->>API: Construye response API
        Note over API: availableRewardPointsBalance = AvailablePoints <br> onHoldBalance = OnHoldPoints <br> previousBalance = previousBalance <br> earnedPoints = pointsEarned <br> redeemedPoints = pointsRedeemed

        API->>Consumidor: Response Exitoso
        Note left of API: HTTP 200: <br> availableRewardPointsBalance, onHoldBalance, <br> previousBalance, earnedPoints, redeemedPoints
    
    end

    alt Flujo GT01 - ConsultaPuntosMastercard

        API->>API: Construye Request WS Mastercard - Identity (header) 
        Note over API: InstitutionName = request.institutionName <br> AppID = request.customerLegalReference

        API->>API: Construye Request WS Mastercard - getRTRPreferences (body)
        Note over API: fromDate = request.periodStartDate <br> toDate = request.periodEndDate <br> components = request.balanceComponents <br> breakdownLevel = request.detailLevel

        API->>MRS: Consume WS Mastercard - getRTRPreferences
        Note right of API: Header: InstitutionName, AppID <br> Body: fromDate, toDate, components, breakdownLevel

        MRS->>API: Response WS Mastercard - getRTRPreferencesResponse
        Note left of MRS: Group HouseholdPointDetails : householdId <br> Group CustomerPointDetails : customerId <br> Group AccountPointDetails : accountId  <br> Campos para todos los grupos : <br> AvailablePoints, OnHoldPoints, previousBalance, pointsEarned, pointsRedeemed

        API->>API: Construye response API
        Note over API: availableRewardPointsBalance = AvailablePoints <br> onHoldBalance = OnHoldPoints <br> previousBalance = previousBalance <br> earnedPoints = pointsEarned <br> redeemedPoints = pointsRedeemed

        API->>Consumidor: Response Exitoso
        Note left of API: HTTP 200: <br> availableRewardPointsBalance, onHoldBalance, <br> previousBalance, earnedPoints, redeemedPoints
    
    end 

    Note over Consumidor, Errors: Flujo Alternativo - Error
    activate API
    alt Exception occurs
        note over Errors: Error Library Handler
        activate Errors
            API->> Errors: Mapear código de error
            Errors -->> API: Retorna código mapeado
        deactivate Errors
        activate Consumidor
            API-->> Consumidor: Retorna error
        deactivate Consumidor
        Note over Consumidor,Errors: Diagrama guía de manejo de errores <br> http://bit.ly/4rpKVIU
    end
    deactivate API