<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TestOSB/consultaDetallesTarjetas/consultaProductosLineaCredito" name="consultaProductosLineaCredito-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TestOSB/consultaDetallesTarjetas/consultaProductosLineaCredito" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TestOSB/consultaDetallesTarjetas/consultaProductosLineaCredito" location="consultaProductosLineaCredito.wsdl"/>
  <binding name="consultaProductosLineaCredito_ptt-binding" type="tns:consultaProductosLineaCredito_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaProductosLineaCredito">
      <soap:operation soapAction="consultaProductosLineaCredito"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaProductosLineaCredito-service">
    <port name="consultaProductosLineaCredito-port" binding="tns:consultaProductosLineaCredito_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>