<wsdl:definitions name="gestionesGenericasCRMPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/gestionesGenericasCRMPS/" xmlns:ges="http://www.ficohsa.com.hn/middleware.services/gestionesGenericasCRMPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/gestionesGenericasCRMTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/gestionesGenericasCRMTypes" schemaLocation="../xsd/gestionesGenericasCRMTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="gestionesGenericasCRM">
		<wsdl:part element="tns:gestionesGenericasCRM" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="gestionesGenericasCRMResponse">
		<wsdl:part element="tns:gestionesGenericasCRMResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="gestionesGenericasCRMPS">
		<wsdl:operation name="gestionesGenericasCRM" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="ges:gestionesGenericasCRM"/>
			<wsdl:output message="ges:gestionesGenericasCRMResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="gestionesGenericasCRMPSSOAP" type="ges:gestionesGenericasCRMPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="gestionesGenericasCRM">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/gestionesGenericasCRMPS/gestionesGenericasCRM"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="ges:gestionesGenericasCRM" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="ges:gestionesGenericasCRMResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="gestionesGenericasCRMPS">
		<wsdl:port binding="ges:gestionesGenericasCRMPSSOAP" name="gestionesGenericasCRMPSSOAP">
			<soap:address location="https://mwomnicanal:8004/Middleware/OperationsAndExecution/Cards/gestionesGenericasCRM/"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>