<wsdl:definitions name="CloudCodeLogin" targetNamespace="https://www.ficohsa.com/honduras/pension" xmlns:tns="https://www.ficohsa.com/honduras/pension" xmlns:inp1="https://www.ficohsa.com/honduras/pension/getEncryptCredentialsTypes" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="https://www.ficohsa.com/honduras/pension/getEncryptCredentialsTypes" schemaLocation="../Schemas/GetEncryptCredentialsTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="cloudCodeLoginRequest" element="inp1:cloudCodeLoginRequest"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="cloudCodeLoginResponse" element="inp1:cloudCodeLoginResponse"/>
    </wsdl:message>
    <wsdl:portType name="cloudCodeLoginPtt">
        <wsdl:operation name="cloudCodeLogin">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="cloudCodeLoginBind" type="tns:cloudCodeLoginPtt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="cloudCodeLogin">
            <soap:operation style="document" soapAction="cloudCodeLogin"/>
            <wsdl:input>
                <soap:body use="literal" namespace="https://www.ficohsa.com/honduras/pension"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="https://www.ficohsa.com/honduras/pension"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>