<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Pension/SBHN_Pension_CloudCodeLogin/UpdateCloudCodeSessionToken" name="UpdateCloudCodeSessionToken-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="UpdateCloudCodeSessionToken.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Pension/SBHN_Pension_CloudCodeLogin/UpdateCloudCodeSessionToken"/>
    <wsdl:binding name="UpdateCloudCodeSessionToken_ptt-binding" type="upd:UpdateCloudCodeSessionToken_ptt" xmlns:upd="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Pension/SBHN_Pension_CloudCodeLogin/UpdateCloudCodeSessionToken">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="UpdateCloudCodeSessionToken">
            <soap:operation soapAction="UpdateCloudCodeSessionToken"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>