<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBGT_Card/SBGT_Card_GetCreditCardStatement/conTransaccionesHistorica" name="conTransaccionesHistorica-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="conTransaccionesHistorica.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBGT_Card/SBGT_Card_GetCreditCardStatement/conTransaccionesHistorica"/>
    <wsdl:binding name="conTransaccionesHistorica_ptt-binding" type="con:conTransaccionesHistorica_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/SBGT_Card/SBGT_Card_GetCreditCardStatement/conTransaccionesHistorica">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="conTransaccionesHistorica">
            <soap:operation soapAction="conTransaccionesHistorica"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>