<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/registraSeguros/consultaDatosTC_v2/consultaDatosTC_V2" name="consultaDatosTC_V2-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/registraSeguros/consultaDatosTC_v2/consultaDatosTC_V2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/registraSeguros/consultaDatosTC_v2/consultaDatosTC_V2" location="consultaDatosTC_V2.wsdl"/>
  <binding name="consultaDatosTC_V2_ptt-binding" type="tns:consultaDatosTC_V2_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaDatosTC_V2">
      <soap:operation soapAction="consultaDatosTC_V2"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaDatosTC_V2-service">
    <port name="consultaDatosTC_V2-port" binding="tns:consultaDatosTC_V2_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionClientdata"/>
    </port>
  </service>
</definitions>