<wsdl:definitions name="suspensionChequesPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/suspensionChequesPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/suspensionChequesPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/suspensionChequesTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>    	    
    </xsd:schema>    	
    <xsd:schema>
    	<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/suspensionChequesTypes" schemaLocation="../xsd/suspensionChequesTypes.xsd"/>
    </xsd:schema>    
  </wsdl:types>
    
  <wsdl:message name="suspensionChequesRequest">
    <wsdl:part element="cons:suspensionChequesRequest" name="parameters"/>
    <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
  </wsdl:message>
  
  <wsdl:message name="suspensionChequesResponse">
    <wsdl:part element="cons:suspensionChequesResponse" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="suspensionChequesPS">
    <wsdl:operation name="suspensionCheques" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="fic:suspensionChequesRequest"/>
      <wsdl:output message="fic:suspensionChequesResponse"/>
    </wsdl:operation>
  </wsdl:portType>
    
  <wsdl:binding name="suspensionChequesPSSOAP" type="fic:suspensionChequesPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="suspensionCheques">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/suspensionChequesPS/suspensionCheques"/>
      <wsdl:input>
        <soap:body use="literal" parts="parameters"/>
        <soap:header use="literal" part="RequestHeader" message="fic:suspensionChequesRequest"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header use="literal" part="ResponseHeader" message="fic:suspensionChequesResponse"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="suspensionChequesPS">
    <wsdl:port binding="fic:suspensionChequesPSSOAP" name="suspensionChequesPSSOAP">
      <soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/CommonBusinessInformation/suspensionCheques"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>