<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="GetEmploymentInformationRestBS" targetNamespace="http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetEmploymentInformation/GetEmploymentInformationRestBS" xmlns:tns="http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetEmploymentInformation/GetEmploymentInformationRestBS" xmlns:inp1="https://www.ficohsa.com/regional/pension" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="GetEmploymentInformationRestBS">
        <plnk:role name="GetEmploymentInformationRestBSProvider" portType="tns:GetEmploymentInformationRestBS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www.ficohsa.com/regional/pension" schemaLocation="../Schemas/GetEmploymentInformationTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="getEmploymentInformation_inputMessage">
        <wsdl:part name="request" element="inp1:getEmploymentInformation"/>
    </wsdl:message>
    <wsdl:message name="getEmploymentInformation_outputMessage">
        <wsdl:part name="reply" element="inp1:getEmploymentInformationResponse"/>
    </wsdl:message>
    <wsdl:portType name="GetEmploymentInformationRestBS_ptt">
        <wsdl:operation name="getEmploymentInformation">
            <wsdl:input message="tns:getEmploymentInformation_inputMessage"/>
            <wsdl:output message="tns:getEmploymentInformation_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="GetEmploymentInformationRestBS_ptt-binding" type="tns:GetEmploymentInformationRestBS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getEmploymentInformation">
            <soap:operation soapAction="getEmploymentInformation"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../Schemas/GetEmploymentInformationTypes.xsd" namespace="https://www.ficohsa.com/regional/pension" ref="SBRG_Pension_GetEmploymentInformation/Schemas/GetEmploymentInformationTypes"/>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetEmploymentInformation/GetEmploymentInformationRestBS</con:targetNamespace>
</con:wsdlEntry>