<wsdl:definitions name="SrvAplCobisPasivos" targetNamespace="http://impl.service.srvaplcobispasivos.ecobis.cobiscorp/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://service.srvaplcobispasivos.ecobis.cobiscorp" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:S1="http://impl.service.srvaplcobispasivos.ecobis.cobiscorp/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://impl.service.srvaplcobispasivos.ecobis.cobiscorp/"><xsd:import namespace="http://service.srvaplcobispasivos.ecobis.cobiscorp" schemaLocation="../xsd/services.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:message name="MsjOpConsultaPasivosClienteSolicitud">
    <wsdl:part name="parameters" element="tns:opConsultaPasivosClienteSolicitud">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="MsjOpConsultaPasivosClienteRespuesta">
    <wsdl:part name="parameters" element="tns:opConsultaPasivosClienteRespuesta">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="SrvAplCobisPasivos">
    <wsdl:operation name="OpConsultaPasivosCliente">
      <wsdl:input message="S1:MsjOpConsultaPasivosClienteSolicitud">
    </wsdl:input>
      <wsdl:output message="S1:MsjOpConsultaPasivosClienteRespuesta">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SrvAplCobisPasivosBindingSOAP12" type="S1:SrvAplCobisPasivos">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="OpConsultaPasivosCliente">
      <soap12:operation/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SrvAplCobisPasivosService">
    <wsdl:port name="SrvAplCobisPasivosBindingSOAP12" binding="S1:SrvAplCobisPasivosBindingSOAP12">
      <soap12:address location="http://10.235.53.145:9080/GerenciaProductoPasivos/SrvAplCobisPasivosService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>