<wsdl:definitions name="afiliaClienteFondoPensionesPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/afiliaClienteFondoPensionesPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/afiliaClienteFondoPensionesPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/afiliaClienteFondoPensionesTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/afiliaClienteFondoPensionesTypes" schemaLocation="../xsd/afiliaClienteFondoPensionesTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="afiliaClienteFondoPensionesRequest">
		<wsdl:part element="cons:afiliaClienteFondoPensionesRequest" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="afiliaClienteFondoPensionesResponse">
		<wsdl:part element="cons:afiliaClienteFondoPensionesResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="afiliaClienteFondoPensionesPS">
		<wsdl:operation name="afiliaClienteFondoPensiones" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:afiliaClienteFondoPensionesRequest"/>
			<wsdl:output message="fic:afiliaClienteFondoPensionesResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="afiliaClienteFondoPensionesPSSOAP" type="fic:afiliaClienteFondoPensionesPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="afiliaClienteFondoPensiones">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/afiliaClienteFondoPensionesPS/afiliaClienteFondoPensiones"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:afiliaClienteFondoPensionesRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:afiliaClienteFondoPensionesResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="afiliaClienteFondoPensionesPS">
    <wsdl:port binding="fic:afiliaClienteFondoPensionesPSSOAP" name="afiliaClienteFondoPensionesPSSOAP">
      <soap:address location="http://mwomnicanal:8003/Middleware/ReferenceData/BusinessPartner/afiliaClienteFondoPensiones"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>