<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/Prueba/consultaOferta" name="consultaOferta-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/Prueba/consultaOferta" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/Prueba/consultaOferta" location="consultaOferta.wsdl"/>
  <binding name="consultaOferta_ptt-binding" type="tns:consultaOferta_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaOferta">
      <soap:operation soapAction="consultaOferta"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaOferta-service">
    <port name="consultaOferta-port" binding="tns:consultaOferta_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProcesosGT"/>
    </port>
  </service>
</definitions>