<wsdl:definitions name="SrvAplCobisCertificadoDeposito" targetNamespace="http://impl.service.srvaplcobiscertificadodeposito.ecobis.cobiscorp/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://service.srvaplcobiscertificadodeposito.ecobis.cobiscorp" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:S1="http://impl.service.srvaplcobiscertificadodeposito.ecobis.cobiscorp/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://impl.service.srvaplcobiscertificadodeposito.ecobis.cobiscorp/"><xsd:import namespace="http://service.srvaplcobiscertificadodeposito.ecobis.cobiscorp" schemaLocation="../xsd/services.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:message name="MsjOpBuscarCertificadoDPFRespuesta">
    <wsdl:part name="parameters" element="tns:opBuscarCertificadoDPFRespuesta">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="MsjOpBuscarCertificadoDPFSolicitud">
    <wsdl:part name="parameters" element="tns:opBuscarCertificadoDPFSolicitud">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="SrvAplCobisCertificadoDeposito">
    <wsdl:operation name="OpBuscarCertificadoDPF">
      <wsdl:input message="S1:MsjOpBuscarCertificadoDPFSolicitud">
    </wsdl:input>
      <wsdl:output message="S1:MsjOpBuscarCertificadoDPFRespuesta">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SrvAplCobisCertificadoDepositoBindingSOAP12" type="S1:SrvAplCobisCertificadoDeposito">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="OpBuscarCertificadoDPF">
      <soap12:operation/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SrvAplCobisCertificadoDepositoService">
    <wsdl:port name="SrvAplCobisCertificadoDepositoBindingSOAP12" binding="S1:SrvAplCobisCertificadoDepositoBindingSOAP12">
      <soap12:address location="http://10.235.53.145:9080/GerenciaProductoDPF/SrvAplCobisCertificadoDepositoService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>