<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/svcActualizacionACHMasivasPending/actualizarEstadoACHMasivasPending" name="actualizarEstadoACHMasivasPending-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/svcActualizacionACHMasivasPending/actualizarEstadoACHMasivasPending" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/svcActualizacionACHMasivasPending/actualizarEstadoACHMasivasPending" location="../wsdl/actualizarEstadoACHMasivasPending.wsdl"/>
  <binding name="actualizarEstadoACHMasivasPending_ptt-binding" type="tns:actualizarEstadoACHMasivasPending_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="actualizarEstadoACHMasivasPending">
      <soap:operation soapAction="actualizarEstadoACHMasivasPending"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="actualizarEstadoACHMasivasPending-service">
    <port name="actualizarEstadoACHMasivasPending-port" binding="tns:actualizarEstadoACHMasivasPending_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterfazdb"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="../wsdl/actualizarEstadoACHMasivasPending.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/svcActualizacionACHMasivasPending/actualizarEstadoACHMasivasPending">
            <con:wsdl ref="Middleware/v2/BusinessServices/TransferenciasACH/svcActualizacionACHMasivasPending/wsdl/actualizarEstadoACHMasivasPending"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/svcActualizacionACHMasivasPending/actualizarEstadoACHMasivasPending</con:targetNamespace>
</con:wsdlEntry>