<wsdl:definitions name="sjTransferenciaEntreCuentaH2HPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjTransferenciaEntreCuentaH2HPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/sjTransferenciaEntreCuentaH2HPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:hcob="http://www.ficohsa.com.hn/middleware.services/sjTransfersH2HTypes">

    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjTransfersH2HTypes" schemaLocation="../xsd/sjTransferenciaEntreCuentasH2H.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="sjTransferenciaEntreCuentaH2H">
        <wsdl:part element="hcob:sjTransferenciaEntreCuentas" name="inputParameters"/>
    </wsdl:message>

    <wsdl:message name="sjTransferenciaEntreCuentaH2HResponse">
        <wsdl:part element="hcob:sjTransferenciaEntreCuentasResponse" name="outputParameters"/>
    </wsdl:message>

    <wsdl:portType name="sjTransferenciaEntreCuentaH2HPS">
        <wsdl:operation name="sjTransferenciaEntreCuentaH2H" parameterOrder="inputParameters">
            <wsdl:input message="fic:sjTransferenciaEntreCuentaH2H"/>
            <wsdl:output message="fic:sjTransferenciaEntreCuentaH2HResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="sjTransferenciaEntreCuentaH2HPSSOAP" type="fic:sjTransferenciaEntreCuentaH2HPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="sjTransferenciaEntreCuentaH2H">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/sjTransferenciaEntreCuentaH2HPS/sjTransferenciaEntreCuentaH2H"/>
            <wsdl:input>
                <soap:body use="literal" parts="inputParameters"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="outputParameters"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="sjTransferenciaEntreCuentaH2HPS">
        <wsdl:port binding="fic:sjTransferenciaEntreCuentaH2HPSSOAP" name="sjTransferenciaEntreCuentaH2HPSSOAP">
            <soap:address location="http://172.23.13.19:8003/MWHostToHost/OperationsAndExecution/CustomerDeposits/TransferenciaCuentasH2H"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>