<wsdl:definitions name="ValidacionOverlimit" targetNamespace="http://www.ficohsa.com.hn/middleware.services/ValidacionOverlimitPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/ValidacionOverlimitPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/ValidacionOverlimitTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../../../v2/Resources/esquemas_generales/HeaderElements.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/ValidacionOverlimitTypes" schemaLocation="../xsd/ValidacionOverlimitTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="validacionOverlimitRequest">
        <wsdl:part element="tns:validacionOverlimitRequest" name="parameters"/>
        <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
    </wsdl:message>
    <wsdl:message name="validacionOverlimitResponse">
        <wsdl:part element="tns:validacionOverlimitResponse" name="result"/>
        <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
    </wsdl:message>

    <wsdl:portType name="ValidacionOverlimitPS">
        <wsdl:operation name="ValidacionOverlimit" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="fic:validacionOverlimitRequest"/>
            <wsdl:output message="fic:validacionOverlimitResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="ValidacionOverlimitPSSOAP" type="fic:ValidacionOverlimitPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ValidacionOverlimit">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/ValidacionOverlimitPS/ValidacionOverlimit"/>
            <wsdl:input>
                <soap:body use="literal" parts="parameters"/>
                <soap:header message="fic:validacionOverlimitRequest" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="result"/>
                <soap:header message="fic:validacionOverlimitResponse" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="ValidacionOverlimitPS">
        <wsdl:port binding="fic:ValidacionOverlimitPSSOAP" name="ValidacionOverlimitSOAP">
            <soap:address location="https://mwomnicanal:8004/Middleware/OperationsAndExecution/Payments/ValidacionOverlimit"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>