<wsdl:definitions name="consultaGestionesMonetariasPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaGestionesMonetariasPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaGestionesMonetariasPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tran="http://www.ficohsa.com.hn/middleware.services/consultaGestionesMonetariasTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">

	<!-- Se define los namespaces de los XSD que se estaran mapeando -->			  
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaGestionesMonetariasTypes" schemaLocation="../xsd/consultaGestionesMonetariasTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<!-- Se define los parametros de Entrada -->
	<wsdl:message name="consultaGestionesMonetariasRequest">
        <wsdl:part element="tran:consultaGestionesMonetarias" name="parameters"/>
        <wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
    </wsdl:message>
    
    <!-- Se define los parametros de Salida -->
    <wsdl:message name="consultaGestionesMonetariasResponse">
        <wsdl:part element="tran:consultaGestionesMonetariasResponse" name="result"/>
        <wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
    </wsdl:message>
	
	<!-- Establecemos los parametros con sus puertos de Entrada y Salida-->
    <wsdl:portType name="consultaGestionesMonetariasPS">
        <wsdl:operation name="consultaGestionesMonetarias" parameterOrder="parameters RequestHeader result ResponseHeader">
            <wsdl:input message="fic:consultaGestionesMonetariasRequest"/>
            <wsdl:output message="fic:consultaGestionesMonetariasResponse"/>
        </wsdl:operation>
    </wsdl:portType>
	
	<!-- Establecemos los parametros de la mensajeria SOAP de Entrada y Salida-->
    <wsdl:binding name="consultaGestionesMonetariasPSSOAP" type="fic:consultaGestionesMonetariasPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="consultaGestionesMonetarias">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaGestionesMonetariasPS/consultaGestionesMonetarias"/>
            <wsdl:input>
                <soap:body parts="parameters" use="literal"/>
                <soap:header message="fic:consultaGestionesMonetariasRequest" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body parts="result" use="literal"/>
                <soap:header message="fic:consultaGestionesMonetariasResponse" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

	<!-- Establecemos los parametros de llamado al servicio-->
    <wsdl:service name="consultaGestionesMonetariasPS">
        <wsdl:port binding="fic:consultaGestionesMonetariasPSSOAP" name="consultaGestionesMonetariasPSSOAP">
            <soap:address location="https://mwomnicanal:8004/Middleware/OperationsAndExecution/BundledProducts/ConsultaGestionesMonetarias"/>
        </wsdl:port>
    </wsdl:service>
				
</wsdl:definitions>