<wsdl:definitions name="sjconsultaCuentaTCPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjconsultaCuentaTCPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:sjc="http://www.ficohsa.com.hn/middleware.services/sjconsultaCuentaTCPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/sjconsultaCuentaTCTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../../../Resources/esquemas_generales/HeaderElements.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjconsultaCuentaTCTypes" schemaLocation="../xsd/sjconsultaCuentaTCTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestHeader">
        <wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
    </wsdl:message>
    <wsdl:message name="responseHeader">
        <wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
    </wsdl:message>
    <wsdl:message name="sjconsultaCuentaTC">
        <wsdl:part element="tns:sjconsultaCuentaTC" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="sjconsultaCuentaTCResponse">
        <wsdl:part element="tns:sjconsultaCuentaTCResponse" name="result"/>
    </wsdl:message>
    <wsdl:portType name="sjconsultaCuentaTCPS">
        <wsdl:operation name="sjconsultaCuentaTC" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="sjc:sjconsultaCuentaTC"/>
            <wsdl:output message="sjc:sjconsultaCuentaTCResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="sjconsultaCuentaTCPSSOAP" type="sjc:sjconsultaCuentaTCPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="sjconsultaCuentaTC">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/sjconsultaCuentaTCPS/sjconsultaCuentaTC"/>
            <wsdl:input>
                <soap:body parts="parameters" use="literal"/>
                <soap:header message="sjc:requestHeader" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body parts="result" use="literal"/>
                <soap:header message="sjc:responseHeader" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="sjconsultaCuentaTCPS">
        <wsdl:port binding="sjc:sjconsultaCuentaTCPSSOAP" name="sjconsultaCuentaTCPSSOAP">
            <soap:address location="http://172.23.13.19:8003/Middleware/SJS/sjconsultaCuentaTC/sjconsultaCuentaTC"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>