<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate2/CreditCardProcessor/RegisterCreditCardData" name="RegisterCreditCardData-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="RegisterCreditCardData.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate2/CreditCardProcessor/RegisterCreditCardData"/>
    <wsdl:binding name="RegisterCreditCardData_ptt-binding" type="reg:RegisterCreditCardData_ptt" xmlns:reg="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate2/CreditCardProcessor/RegisterCreditCardData">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="RegisterCreditCardData">
            <soap:operation soapAction="RegisterCreditCardData"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>