<WL5G3N0:definitions name="transferenciaCuentasPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/transferenciaCuentasPS/" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://www.ficohsa.com.hn/middleware.services/transferenciasType" xmlns:WL5G3N2="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:WL5G3N3="http://www.ficohsa.com.hn/middleware.services/transferenciaCuentasPS/" xmlns:WL5G3N4="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/transferenciaCuentasPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:trans="http://www.ficohsa.com.hn/middleware.services/transferenciasType" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsd/XMLSchema_1737314831.xsd"/>
    </xsd:schema>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/transferenciaCuentasPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:trans="http://www.ficohsa.com.hn/middleware.services/transferenciasType" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/transferenciasType" schemaLocation="../xsd/XMLSchema_-1337596366.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="transferenciaCuentasRequest">
    <WL5G3N0:part element="WL5G3N1:transferenciaCuentasRequest" name="parameters"/>
    <WL5G3N0:part element="WL5G3N2:RequestHeader" name="RequestHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="transferenciaCuentasResponse">
    <WL5G3N0:part element="WL5G3N1:transferenciaCuentasResponse" name="result"/>
    <WL5G3N0:part element="WL5G3N2:ResponseHeader" name="ResponseHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="transferenciaCuentasPS">
    <WL5G3N0:operation name="transferenciaCuentas" parameterOrder="parameters RequestHeader ResponseHeader">
      <WL5G3N0:input message="WL5G3N3:transferenciaCuentasRequest"/>
      <WL5G3N0:output message="WL5G3N3:transferenciaCuentasResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="transferenciaCuentasPSSOAP" type="WL5G3N3:transferenciaCuentasPS">
    <WL5G3N4:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="transferenciaCuentas">
      <WL5G3N4:operation soapAction="http://www.ficohsa.com.hn/middleware.services/transferenciaCuentasPS/transferenciaCuentas"/>
      <WL5G3N0:input>
        <WL5G3N4:body parts="parameters" use="literal"/>
        <WL5G3N4:header message="WL5G3N3:transferenciaCuentasRequest" part="RequestHeader" use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N4:body parts="result" use="literal"/>
        <WL5G3N4:header message="WL5G3N3:transferenciaCuentasResponse" part="ResponseHeader" use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="transferenciaCuentasPS">
    <WL5G3N0:port binding="WL5G3N3:transferenciaCuentasPSSOAP" name="transferenciaCuentasPSSOAP">
      <WL5G3N4:address location="http://mwomnicanal:8003/Middleware/OperationsAndExecution/CustomerDeposits/TransferenciaCuentas_v2"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>