<wsdl:definitions 
	xmlns:fic="http://www.ficohsa.com.hn/middleware.services/OwnCheckPymtPS/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	name="OwnCheckPymtPS"
	xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType"
	xmlns:cko="http://www.ficohsa.com.hn/middleware.services/checkOperationsTypes"
	targetNamespace="http://www.ficohsa.com.hn/middleware.services/OwnCheckPymtPS/">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType"
				schemaLocation="../../../General/xsd/Header.xsd" />
		</xsd:schema>
		<xsd:schema>
			<xsd:import
				namespace="http://www.ficohsa.com.hn/middleware.services/checkOperationsTypes"
				schemaLocation="../../xsd/CheckOperationsTypes.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="ownCheckPymtRequest">
		<wsdl:part element="cko:ownCheckPymt" name="parameters" />
		<wsdl:part name="RequestHeader" element="auth:RequestHeader" />
	</wsdl:message>
	<wsdl:message name="ownCheckPymtResponse">
		<wsdl:part element="cko:ownCheckPymtResponse" name="result" />
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader" />
	</wsdl:message>
	<wsdl:portType name="OwnCheckPymtPS">
		<wsdl:operation name="ownCheckPymt"
			parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:ownCheckPymtRequest" />
			<wsdl:output message="fic:ownCheckPymtResponse" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="OwnCheckPymtPSSOAP" type="fic:OwnCheckPymtPS">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="ownCheckPymt">
			<soap:operation
				soapAction="http://www.ficohsa.com.hn/middleware.services/OwnCheckPymtPS/ownCheckPymt" />
			<wsdl:input>
				<soap:body use="literal" parts="parameters" />
				<soap:header message="fic:ownCheckPymtRequest" part="RequestHeader"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result" />
				<soap:header message="fic:ownCheckPymtResponse" part="ResponseHeader"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="OwnCheckPymtPS">
		<wsdl:port binding="fic:OwnCheckPymtPSSOAP" name="OwnCheckPymtPSSOAP">
			<soap:address location="http://mwteller:8004/mwteller/accounts/checkOperations" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
