<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/safewatchRegistraBitacora/safewatchRegistraBitacora" name="safewatchRegistraBitacora-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/safewatchRegistraBitacora/safewatchRegistraBitacora" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/safewatchRegistraBitacora/safewatchRegistraBitacora" location="safewatchRegistraBitacora.wsdl"/>
  <binding name="safewatchRegistraBitacora_ptt-binding" type="tns:safewatchRegistraBitacora_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="safewatchRegistraBitacora">
      <soap:operation soapAction="safewatchRegistraBitacora"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="safewatchRegistraBitacora-service">
    <port name="safewatchRegistraBitacora-port" binding="tns:safewatchRegistraBitacora_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>