<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/OperacionGarantiaCredito/operacionGarantiaCredito" name="operacionGarantiaCredito-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/OperacionGarantiaCredito/operacionGarantiaCredito" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/OperacionGarantiaCredito/operacionGarantiaCredito" location="operacionGarantiaCredito.wsdl"/>
  <binding name="operacionGarantiaCredito_ptt-binding" type="tns:operacionGarantiaCredito_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="operacionGarantiaCredito">
      <soap:operation soapAction="operacionGarantiaCredito"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="operacionGarantiaCredito-service">
    <port name="operacionGarantiaCredito-port" binding="tns:operacionGarantiaCredito_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>