<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="sjConsultaMultipleRemesadorasNI" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaMultipleRemesadorasNI" xmlns:tns="SplitJoinTest" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/sjConsultaMultipleRemesadorasNI" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/sjConsultaMultipleRemesadorasNI" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
<wsdl:types>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaMultipleRemesadorasNI" schemaLocation="../xsd/sjConsultaMultipleRemesadorasNI.xsd"/>
	</xsd:schema>
</wsdl:types>
    
<wsdl:message name="sjConsultaMultipleRemesadorasNI">
	<wsdl:part name="inputParameters" element="cons:sjConsultaMultipleRemesadorasNI"/>
</wsdl:message>
<wsdl:message name="sjConsultaMultipleRemesadorasNIResponse">
	<wsdl:part name="outputParameters" element="cons:sjConsultaMultipleRemesadorasNIResponse"/>
</wsdl:message>

<wsdl:portType name="sjConsultaMultipleRemesadorasNI">
	<wsdl:operation name="consultaRemesadoras">
		<wsdl:input message="fic:sjConsultaMultipleRemesadorasNI"/>
		<wsdl:output message="fic:sjConsultaMultipleRemesadorasNIResponse"/>		
	</wsdl:operation>
</wsdl:portType>

<wsdl:binding name="sjConsultaMultipleRemesadorasNISOAP" type="fic:sjConsultaMultipleRemesadorasNI">
	<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
	<wsdl:operation name="consultaRemesadoras">
		<wsdl:input>
			<soap:body parts="inputParameters" use="literal"/>
		</wsdl:input>
		<wsdl:output>
			<soap:body parts="outputParameters" use="literal"/>		
		</wsdl:output>
	</wsdl:operation>
</wsdl:binding>

<wsdl:service name="sjConsultaMultipleRemesadorasNI">
	<wsdl:port name="sjConsultaRemesadorasPSSOAP" binding="fic:sjConsultaMultipleRemesadorasNISOAP">
		<soap:address location="http://172.23.13.19:8003/Middleware/SJS/ConsultaMultipleRemesadoras"/>
	</wsdl:port>
</wsdl:service>

</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../xsd/sjConsultaMultipleRemesadorasNI.xsd" namespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaMultipleRemesadorasNI" ref="Middleware/v2/BusinessServices/SJS/consultaMultipleRemesadorasNI/xsd/sjConsultaMultipleRemesadorasNI"/>
    </con:dependencies>
    <con:targetNamespace>http://www.ficohsa.com.hn/middleware.services/sjConsultaMultipleRemesadorasNI</con:targetNamespace>
</con:wsdlEntry>