<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_CARD/SBHN_Card_RollbackPurchase/DBGetStatusTicketAdapter" name="DBGetStatusTicketAdapter-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="DBGetStatusTicketAdapter.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_CARD/SBHN_Card_RollbackPurchase/DBGetStatusTicketAdapter"/>
    <wsdl:binding name="DBGetStatusTicketAdapter_ptt-binding" type="dbg:DBGetStatusTicketAdapter_ptt" xmlns:dbg="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_CARD/SBHN_Card_RollbackPurchase/DBGetStatusTicketAdapter">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DBGetStatusTicketAdapter">
            <soap:operation soapAction="DBGetStatusTicketAdapter"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>