<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionConvenios/ConsultaCamposRemNoEstandar/consultaCamposRemNoEstandar" name="consultaCamposRemNoEstandar-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionConvenios/ConsultaCamposRemNoEstandar/consultaCamposRemNoEstandar" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionConvenios/ConsultaCamposRemNoEstandar/consultaCamposRemNoEstandar" location="consultaCamposRemNoEstandar.wsdl"/>
  <binding name="consultaCamposRemNoEstandar_ptt-binding" type="tns:consultaCamposRemNoEstandar_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaCamposRemNoEstandar">
      <soap:operation soapAction="consultaCamposRemNoEstandar"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaCamposRemNoEstandar-service">
    <port name="consultaCamposRemNoEstandar-port" binding="tns:consultaCamposRemNoEstandar_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>