<wsdl:definitions name="sjConsultaProductosPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaProductos" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/sjConsultaProductos" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/sjConsultaProductos" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

<wsdl:types>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaProductos" schemaLocation="../xsd/sjConsultaProductos.xsd"/>
	</xsd:schema>
</wsdl:types>
    
<wsdl:message name="sjConsultaProductosRequest">
	<wsdl:part name="inputParameters" element="cons:sjConsultaProductos"/>
</wsdl:message>
<wsdl:message name="sjConsultaProductosResponse">
	<wsdl:part name="outputParameters" element="cons:sjConsultaProductosResponse"/>
</wsdl:message>

<wsdl:portType name="sjConsultaProductosPS">
	<wsdl:operation name="consultaProductos">
		<wsdl:input message="fic:sjConsultaProductosRequest"/>
		<wsdl:output message="fic:sjConsultaProductosResponse"/>		
	</wsdl:operation>
</wsdl:portType>

<wsdl:binding name="sjConsultaProductosPSSOAP" type="fic:sjConsultaProductosPS">
	<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
	<wsdl:operation name="consultaProductos">
		<wsdl:input>
			<soap:body parts="inputParameters" use="literal"/>
		</wsdl:input>
		<wsdl:output>
			<soap:body parts="outputParameters" use="literal"/>		
		</wsdl:output>
	</wsdl:operation>
</wsdl:binding>

<wsdl:service name="sjConsultaProductosPS">
	<wsdl:port name="jConsultaProductosPSSOAP" binding="fic:sjConsultaProductosPSSOAP">
		<soap:address location="http://mwomnicanal:8003/Middleware/SJS/ConsultaProductos"/>
	</wsdl:port>
</wsdl:service>

</wsdl:definitions>