<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ConnectionTarjetas/conResumenFinanciamientos" name="conResumenFinanciamientos-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ConnectionTarjetas/conResumenFinanciamientos" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ConnectionTarjetas/conResumenFinanciamientos" location="conResumenFinanciamientos.wsdl"/>
  <binding name="conResumenFinanciamientos_ptt-binding" type="tns:conResumenFinanciamientos_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conResumenFinanciamientos">
      <soap:operation soapAction="conResumenFinanciamientos"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conResumenFinanciamientos-service">
    <port name="conResumenFinanciamientos-port" binding="tns:conResumenFinanciamientos_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>