<wsdl:definitions name="sjConsultaRemesaPorNombrePS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaRemesaPorNombrePS" xmlns:tns="SplitJoinTest" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/sjConsultaRemesaPorNombrePS" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/sjConsultaRemesaPorNombre" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

<wsdl:types>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../../../Resources/esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaRemesaPorNombre" schemaLocation="../xsd/sjConsultaRemesaPorNombre.xsd"/>
	</xsd:schema>
</wsdl:types>
    
<wsdl:message name="sjConsultaRemesaPorNombreRequest">
	<wsdl:part name="inputParameters" element="cons:sjConsultaRemesaPorNombreRequest"/>
	<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
</wsdl:message>
<wsdl:message name="sjConsultaRemesaPorNombreResponse">
	<wsdl:part name="outputParameters" element="cons:sjConsultaRemesaPorNombreResponse"/>
	<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
</wsdl:message>

<wsdl:portType name="sjConsultaRemesaPorNombrePS">
	<wsdl:operation name="consultaRemesaPorNombre" parameterOrder="parameters RequestHeader ResponseHeader">
		<wsdl:input message="fic:sjConsultaRemesaPorNombreRequest"/>
		<wsdl:output message="fic:sjConsultaRemesaPorNombreResponse"/>		
	</wsdl:operation>
</wsdl:portType>

<wsdl:binding name="sjConsultaRemesaPorNombrePSSOAP" type="fic:sjConsultaRemesaPorNombrePS">
	<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
	<wsdl:operation name="consultaRemesaPorNombre">
		<wsdl:input>
			<soap:body parts="inputParameters" use="literal"/>
			<soap:header message="fic:sjConsultaRemesaPorNombreRequest" part="RequestHeader" use="literal"/>
		</wsdl:input>
		<wsdl:output>
			<soap:body parts="outputParameters" use="literal"/>	
			<soap:header message="fic:sjConsultaRemesaPorNombreResponse" part="ResponseHeader" use="literal"/>	
		</wsdl:output>
	</wsdl:operation>
</wsdl:binding>

<wsdl:service name="sjConsultaRemesaPorNombrePS">
	<wsdl:port name="jConsultaRemesaPorNombrePSSOAP" binding="fic:sjConsultaRemesaPorNombrePSSOAP">
		<soap:address location="http://soabus:8003/Middleware/RiskAndCompliance/RegulationsAndCompliance/sjConsultaRemesaPorNombre"/>
	</wsdl:port>
</wsdl:service>

</wsdl:definitions>