<wsdl:definitions targetNamespace="http://www.ficohsa.com.hn/middleware.services/creaCobranzaAutomatica/" name="creaCobranzaAutomaticaPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/creaCobranzaAutomatica/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:sol="http://www.ficohsa.com.hn/middleware.services/creaCobranzaAutomaticaTypes">

  <wsdl:types>
    <xsd:schema>
    	<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
    </xsd:schema>
    <xsd:schema>
    	<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/creaCobranzaAutomaticaTypes" schemaLocation="../xsd/creaCobranzaAutomaticaTypes.xsd"/>
    </xsd:schema>
  </wsdl:types>
  
  
  <wsdl:message name="creaCobranzaAutomaticaRequest">
    <wsdl:part element="sol:creaCobranzaAutomatica" name="parameters"/>
    <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
  </wsdl:message>  
  <wsdl:message name="creaCobranzaAutomaticaResponse">
    <wsdl:part element="sol:creaCobranzaAutomaticaResponse" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="creaCobranzaAutomaticaPS">
    <wsdl:operation name="creaCobranzaAutomatica" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="fic:creaCobranzaAutomaticaRequest"/>
      <wsdl:output message="fic:creaCobranzaAutomaticaResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="creaCobranzaAutomaticaPSSOAP"
  	type="fic:creaCobranzaAutomaticaPS">
  	<soap:binding style="document"
  		transport="http://schemas.xmlsoap.org/soap/http" />
  	<wsdl:operation name="creaCobranzaAutomatica">
  		<soap:operation
  			soapAction="http://www.ficohsa.com.hn/middleware.services/creaCobranzaAutomaticaPS/creaCobranzaAutomatica" />
  		<wsdl:input>
  			<soap:body use="literal" parts="parameters" />
  			<soap:header use="literal" part="RequestHeader"
  				message="fic:creaCobranzaAutomaticaRequest" />
  		</wsdl:input>
  		<wsdl:output>
  			<soap:body use="literal" parts="result" />
  			<soap:header use="literal" part="ResponseHeader"
  				message="fic:creaCobranzaAutomaticaResponse" />
  		</wsdl:output>
  	</wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="creaCobranzaAutomaticaPS">
    <wsdl:port binding="fic:creaCobranzaAutomaticaPSSOAP" name="creaCobranzaAutomaticaPSSOAP">
      <soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Payments/CreaCobranzaAutomatica"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>
