<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/OSBRegistraPagosTCMasterData/conActualizaPagoTCTengo" name="conActualizaPagoTCTengo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/OSBRegistraPagosTCMasterData/conActualizaPagoTCTengo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/OSBRegistraPagosTCMasterData/conActualizaPagoTCTengo" location="conActualizaPagoTCTengo.wsdl"/>
  <binding name="conActualizaPagoTCTengo_ptt-binding" type="tns:conActualizaPagoTCTengo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conActualizaPagoTCTengo">
      <soap:operation soapAction="conActualizaPagoTCTengo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conActualizaPagoTCTengo-service">
    <port name="conActualizaPagoTCTengo-port" binding="tns:conActualizaPagoTCTengo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetasHN"/>
    </port>
  </service>
</definitions>