<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareCajaSOAApplication/ConsultaMapeoCuentaT24Citi/consultaMapeoCuentaT24Citi" name="consultaMapeoCuentaT24Citi-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareCajaSOAApplication/ConsultaMapeoCuentaT24Citi/consultaMapeoCuentaT24Citi" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareCajaSOAApplication/ConsultaMapeoCuentaT24Citi/consultaMapeoCuentaT24Citi" location="consultaMapeoCuentaT24Citi.wsdl"/>
  <binding name="consultaMapeoCuentaT24Citi_ptt-binding" type="tns:consultaMapeoCuentaT24Citi_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaMapeoCuentaT24Citi">
      <soap:operation soapAction="consultaMapeoCuentaT24Citi"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaMapeoCuentaT24Citi-service">
    <port name="consultaMapeoCuentaT24Citi-port" binding="tns:consultaMapeoCuentaT24Citi_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>