<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionWebServices/RegistraTramaEventoT24/registraTramaEventoT24_db" name="registraTramaEventoT24_db-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionWebServices/RegistraTramaEventoT24/registraTramaEventoT24_db" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionWebServices/RegistraTramaEventoT24/registraTramaEventoT24_db" location="registraTramaEventoT24.wsdl"/>
  <binding name="registraTramaEventoT24_db_ptt-binding" type="tns:registraTramaEventoT24_db_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registraTramaEventoT24_db">
      <soap:operation soapAction="registraTramaEventoT24_db"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registraTramaEventoT24_db-service">
    <port name="registraTramaEventoT24_db-port" binding="tns:registraTramaEventoT24_db_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>