<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultaTiposTransaccionSwitch/Project1/registrarBitacoraMensajeISO8583" name="registrarBitacoraMensajeISO8583-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/consultaTiposTransaccionSwitch/Project1/registrarBitacoraMensajeISO8583" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultaTiposTransaccionSwitch/Project1/registrarBitacoraMensajeISO8583" location="registrarBitacoraMensajeISO8583.wsdl"/>
  <binding name="registrarBitacoraMensajeISO8583_ptt-binding" type="tns:registrarBitacoraMensajeISO8583_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registrarBitacoraMensajeISO8583">
      <soap:operation soapAction="registrarBitacoraMensajeISO8583"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registrarBitacoraMensajeISO8583-service">
    <port name="registrarBitacoraMensajeISO8583-port" binding="tns:registrarBitacoraMensajeISO8583_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>