trigger:
  branches:
    include:
      - develop
      - staging
      - uat
      - main
  paths:
    exclude:
      - azure-pipelines.yml

resources:
  repositories:
    - repository: pipeline-xrs-templates
      type: git
      name: GFF-DevSecOps-Foundation/_git/pipeline-xrs-templates
      ref: 'refs/heads/mainV2'

extends:
  template: main.yml@pipeline-xrs-templates
  parameters:
    account_name: lending_cards