pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = "https://repo.spring.io/milestone" }
        maven { url = "https://repo.spring.io/snapshot" }
    }
}

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = "https://repo.spring.io/milestone" }
        maven { url = "https://repo.spring.io/snapshot" }
    }
}

buildCache {
    local {
        directory = new File(rootDir, 'build-cache')
    }
}

rootProject.name = 'ms-lc-ccard-credit_card_retrieves-product'

// --- [APPLICATION LAYER] ---
include "app-service"
include "use-case"

// --- [DOMAIN LAYER] ---
include "model"
include "ports"

// --- [INFRASTRUCTURE LAYER] ---
include "reactive-web"
include 'visionplus-client-api'
include 't24-client-api'
include 'cobis-client-api'
include 'abanks-client-api'
include 'secrets-manager'
include 'lambda-regionalization'
include 'creditcard-client-api'
include 'parameter-store'
include 'helpers'

// --- [DIRECTORY MAPPING] ---
project(':app-service').projectDir = file('applications/app-service')
project(':use-case').projectDir = file('domain/use-case')
project(':model').projectDir = file('domain/model')
project(':ports').projectDir = file('domain/ports')
project(':reactive-web').projectDir = file('infrastructure/entry-points/reactive-web')
project(':visionplus-client-api').projectDir = file('infrastructure/driven-adapters/visionplus-client-api')
project(':t24-client-api').projectDir = file('infrastructure/driven-adapters/t24-client-api')
project(':cobis-client-api').projectDir = file('infrastructure/driven-adapters/cobis-client-api')
project(':abanks-client-api').projectDir = file('infrastructure/driven-adapters/abanks-client-api')
project(':secrets-manager').projectDir = file('infrastructure/driven-adapters/secrets-manager')
project(':lambda-regionalization').projectDir = file('infrastructure/driven-adapters/lambda-regionalization')
project(':creditcard-client-api').projectDir = file('infrastructure/driven-adapters/creditcard-client-api')
project(':parameter-store').projectDir = file('infrastructure/driven-adapters/parameter-store')
project(':helpers').projectDir = file('infrastructure/helpers')
