<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasPA/conDatosTarjetaVP/conDatosTarjetaVP" name="conDatosTarjetaVP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasPA/conDatosTarjetaVP/conDatosTarjetaVP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasPA/conDatosTarjetaVP/conDatosTarjetaVP" location="conDatosTarjetaVP.wsdl"/>
  <binding name="conDatosTarjetaVP_ptt-binding" type="tns:conDatosTarjetaVP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conDatosTarjetaVP">
      <soap:operation soapAction="conDatosTarjetaVP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conDatosTarjetaVP-service">
    <port name="conDatosTarjetaVP-port" binding="tns:conDatosTarjetaVP_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>