<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/modificaTargetTipoPrestamo/modificaTargetTipoPrestamo/modificaTargetTipoPrestamo" name="modificaTargetTipoPrestamo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/modificaTargetTipoPrestamo/modificaTargetTipoPrestamo/modificaTargetTipoPrestamo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/modificaTargetTipoPrestamo/modificaTargetTipoPrestamo/modificaTargetTipoPrestamo" location="modificaTargetTipoPrestamo.wsdl"/>
  <binding name="modificaTargetTipoPrestamo_ptt-binding" type="tns:modificaTargetTipoPrestamo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="modificaTargetTipoPrestamo">
      <soap:operation soapAction="modificaTargetTipoPrestamo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="modificaTargetTipoPrestamo-service">
    <port name="modificaTargetTipoPrestamo-port" binding="tns:modificaTargetTipoPrestamo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionDLC"/>
    </port>
  </service>
</definitions>