<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOAApplication/Project3/MCVentaEfectivo" name="MCVentaEfectivo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAApplication/Project3/MCVentaEfectivo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOAApplication/Project3/MCVentaEfectivo" location="MCVentaEfectivo.wsdl"/>
  <binding name="MCVentaEfectivo_ptt-binding" type="tns:MCVentaEfectivo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="MCVentaEfectivo">
      <soap:operation soapAction="MCVentaEfectivo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="MCVentaEfectivo-service">
    <port name="MCVentaEfectivo-port" binding="tns:MCVentaEfectivo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>