<wsdl:definitions name="pagosMasivosInternoPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/pagosMasivosPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/pagosMasivosPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:pag="http://www.ficohsa.com.hn/middleware.services/pagosMasivosTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/pagosMasivosTypes" schemaLocation="../../PagosMasivos/xsd/pagosMasivosTypes.xsd"/>
	</xsd:schema>
  </wsdl:types> 
  
  	<wsdl:message name="pagosMasivosInternoRequest">
		<wsdl:part element="pag:pagosMasivos" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="pagosMasivosInternoResponse">
		<wsdl:part element="pag:pagosMasivosResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="pagosMasivosInternoPS">
		<wsdl:operation name="pagosMasivosInterno" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:pagosMasivosInternoRequest"/>
			<wsdl:output message="fic:pagosMasivosInternoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="pagosMasivosInternoPSSOAP" type="fic:pagosMasivosInternoPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="pagosMasivosInterno">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/pagosMasivosInternoPS/pagosMasivosInterno"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:pagosMasivosInternoRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:pagosMasivosInternoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation> 
	</wsdl:binding>
	
	<wsdl:service name="pagosMasivosInternoPS">
	    <wsdl:port binding="fic:pagosMasivosInternoPSSOAP" name="pagosMasivosInternoPSSOAP">
	    	<soap:address location="http://mwomnicanal:8003/Middleware/OperationsAndExecution/Cards/PagosMasivosInterno"/>
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>