<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasPA/conDatosTarjetasActivasCliente/conDatosTarjetasActivasCliente" name="conDatosTarjetasActivasCliente-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasPA/conDatosTarjetasActivasCliente/conDatosTarjetasActivasCliente" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasPA/conDatosTarjetasActivasCliente/conDatosTarjetasActivasCliente" location="conDatosTarjetasActivasCliente.wsdl"/>
  <binding name="conDatosTarjetasActivasCliente_ptt-binding" type="tns:conDatosTarjetasActivasCliente_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conDatosTarjetasActivasCliente">
      <soap:operation soapAction="conDatosTarjetasActivasCliente"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conDatosTarjetasActivasCliente-service">
    <port name="conDatosTarjetasActivasCliente-port" binding="tns:conDatosTarjetasActivasCliente_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>