<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingNI/GetLoanDetailsNI" name="GetLoanDetailsNI-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GetLoanDetailsNI.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingNI/GetLoanDetailsNI"/>
    <wsdl:binding name="GetLoanDetailsNI_ptt-binding" type="get:GetLoanDetailsNI_ptt" xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingNI/GetLoanDetailsNI">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="GetLoanDetailsNI">
            <soap:operation soapAction="GetLoanDetailsNI"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>