<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/BLAZE_BOM_SALIDA/BLAZE_BOM_SALIDA" name="BLAZE_BOM_SALIDA-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/BLAZE_BOM_SALIDA/BLAZE_BOM_SALIDA" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/BLAZE_BOM_SALIDA/BLAZE_BOM_SALIDA" location="BLAZE_BOM_SALIDA.wsdl"/>
  <binding name="BLAZE_BOM_SALIDA_ptt-binding" type="tns:BLAZE_BOM_SALIDA_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="BLAZE_BOM_SALIDA">
      <soap:operation soapAction="BLAZE_BOM_SALIDA"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="BLAZE_BOM_SALIDA-service">
    <port name="BLAZE_BOM_SALIDA-port" binding="tns:BLAZE_BOM_SALIDA_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionAdquirCreditos"/>
    </port>
  </service>
</definitions>