<wsdl:definitions targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaSolicitudAperturaCuenta/" name="consultaSolicitudAperturaCuentaPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaSolicitudAperturaCuenta/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:sol="http://www.ficohsa.com.hn/middleware.services/consultaSolicitudAperturaCuentaTypes">
  
  <wsdl:types>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaSolicitudAperturaCuentaTypes" schemaLocation="../xsd/consultaSolicitudAperturaCuentaTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="consultaSolicitudAperturaCuentaRequest">
    <wsdl:part element="sol:consultaSolicitudAperturaCuenta" name="parameters"/>
    <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
  </wsdl:message>
  <wsdl:message name="consultaSolicitudAperturaCuentaResponse">
    <wsdl:part element="sol:consultaSolicitudAperturaCuentaResponse" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="consultaSolicitudAperturaCuentaPS">
    <wsdl:operation name="consultaSolicitudAperturaCuenta" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="fic:consultaSolicitudAperturaCuentaRequest"/>
      <wsdl:output message="fic:consultaSolicitudAperturaCuentaResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="consultaSolicitudAperturaCuentaPSSOAP" type="fic:consultaSolicitudAperturaCuentaPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultaSolicitudAperturaCuenta">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaSolicitudAperturaCuenta/consultaSolicitudAperturaCuenta"/>
      <wsdl:input>
        <soap:body use="literal" parts="parameters"/>
        <soap:header message="fic:consultaSolicitudAperturaCuentaRequest" part="RequestHeader" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header message="fic:consultaSolicitudAperturaCuentaResponse" part="ResponseHeader" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="consultaSolicitudAperturaCuentaPS">
    <wsdl:port binding="fic:consultaSolicitudAperturaCuentaPSSOAP" name="consultaSolicitudAperturaCuentaPSSOAP">
      <soap:address location="https://mwomnicanal:8004/Middleware/OperationsAndExecution/CustomerDeposits/consultaSolicitudAperturaCuenta"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>