<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="GetPensionFundStatusRestBS" targetNamespace="http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetPensionFundStatus/GetPensionFundStatusRestBS" xmlns:tns="http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetPensionFundStatus/GetPensionFundStatusRestBS" xmlns:inp1="https://www.ficohsa.com/regional/pension" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="GetPensionFundStatusRestBS">
        <plnk:role name="GetPensionFundStatusRestBSProvider" portType="tns:GetPensionFundStatusRestBS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www.ficohsa.com/regional/pension" schemaLocation="../Schemas/GetPensionFundStatusTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="getPensionFundStatus_inputMessage">
        <wsdl:part name="request" element="inp1:getPensionFundStatus"/>
    </wsdl:message>
    <wsdl:message name="getPensionFundStatus_outputMessage">
        <wsdl:part name="reply" element="inp1:getPensionFundStatusResponse"/>
    </wsdl:message>
    <wsdl:portType name="GetPensionFundStatusRestBS_ptt">
        <wsdl:operation name="getPensionFundStatus">
            <wsdl:input message="tns:getPensionFundStatus_inputMessage"/>
            <wsdl:output message="tns:getPensionFundStatus_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="GetPensionFundStatusRestBS_ptt-binding" type="tns:GetPensionFundStatusRestBS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getPensionFundStatus">
            <soap:operation soapAction="getPensionFundStatus"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../Schemas/GetPensionFundStatusTypes.xsd" namespace="https://www.ficohsa.com/regional/pension" ref="SBRG_Pension_GetPensionFundStatus/Schemas/GetPensionFundStatusTypes"/>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetPensionFundStatus/GetPensionFundStatusRestBS</con:targetNamespace>
</con:wsdlEntry>