<wsdl:definitions name="consultaUsuarioPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaUsuarioPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaUsuarioPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaUsuarioTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaUsuarioTypes" schemaLocation="../xsd/consultaUsuarioTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="consultaUsuarioRequest">
		<wsdl:part element="cons:consultaUsuario" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaUsuarioResponse">
		<wsdl:part element="cons:consultaUsuarioResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="consultaUsuarioPS">
		<wsdl:operation name="consultaUsuario" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaUsuarioRequest"/>
			<wsdl:output message="fic:consultaUsuarioResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaUsuarioPSSOAP" type="fic:consultaUsuarioPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaUsuario">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaUsuarioPS/consultaUsuario"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaUsuarioRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaUsuarioResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="consultaUsuarioPS">
    <wsdl:port binding="fic:consultaUsuarioPSSOAP" name="consultaUsuarioPSSOAP">
      <soap:address location="https://mwomnicanal:8004/Middleware/ReferenceData/CommonBusinessInformation/ConsultaUsuario"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>