<wsdl:definitions name="RegisterExternalBatchCountryGenericRestBS" targetNamespace="http://xmlns.oracle.com/SBRG_MassivePayment/SBRG_MassivePayment_RegisterExternalBatch/RegisterExternalBatchCountryGenericRestBS" xmlns:tns="http://xmlns.oracle.com/SBRG_MassivePayment/SBRG_MassivePayment_RegisterExternalBatch/RegisterExternalBatchCountryGenericRestBS" xmlns:inp1="https://www.ficohsa.com/regional/massivePayment" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="RegisterExternalBatchCountryGenericRestBS">
        <plnk:role name="RegisterExternalBatchCountryGenericRestBSProvider" portType="tns:RegisterExternalBatchCountryGenericRestBS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www.ficohsa.com/regional/massivePayment" schemaLocation="../Schemas/RegisterExternalBatchTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="registerExternalBatch_inputMessage">
        <wsdl:part name="request" element="inp1:registerExternalBatch"/>
    </wsdl:message>
    <wsdl:message name="registerExternalBatch_outputMessage">
        <wsdl:part name="reply" element="inp1:registerExternalBatchResponse"/>
    </wsdl:message>
    <wsdl:portType name="RegisterExternalBatchCountryGenericRestBS_ptt">
        <wsdl:operation name="registerExternalBatch">
            <wsdl:input message="tns:registerExternalBatch_inputMessage"/>
            <wsdl:output message="tns:registerExternalBatch_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="RegisterExternalBatchCountryGenericRestBS_ptt-binding" type="tns:RegisterExternalBatchCountryGenericRestBS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="registerExternalBatch">
            <soap:operation soapAction="registerExternalBatch"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>