<wsdl:definitions name="creaRemesaPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/creaRemesaPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/creaRemesaPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/creaRemesaTypes">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/creaRemesaTypes" schemaLocation="../xsd/creaRemesaTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="creaRemesaRequest">
		<wsdl:part name="parameters" element="tns:creaRemesa"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="creaRemesaResponse">
		<wsdl:part name="result" element="tns:creaRemesaResponse"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	<wsdl:portType name="creaRemesaPS">
		<wsdl:operation name="creaRemesa" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:creaRemesaRequest"/>
			<wsdl:output message="fic:creaRemesaResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="creaRemesaPSSOAP" type="fic:creaRemesaPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="creaRemesa">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/creaRemesaPS/creaRemesa"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:creaRemesaRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:creaRemesaResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="creaRemesaPS">
		<wsdl:port binding="fic:creaRemesaPSSOAP" name="creaRemesaPSSOAP">
			<soap:address location="https://172.23.13.19:8004/Middleware/ConsumerServices/Remittance/CreaRemesa"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>