<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_ADAPTER/ConsultaCuentaEquivalente/ConsultaCuentaEquivalente" name="ConsultaCuentaEquivalente-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DB_ADAPTER/ConsultaCuentaEquivalente/ConsultaCuentaEquivalente" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_ADAPTER/ConsultaCuentaEquivalente/ConsultaCuentaEquivalente" location="ConsultaCuentaEquivalente.wsdl"/>
  <binding name="ConsultaCuentaEquivalente_ptt-binding" type="tns:ConsultaCuentaEquivalente_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ConsultaCuentaEquivalente">
      <soap:operation soapAction="ConsultaCuentaEquivalente"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ConsultaCuentaEquivalente-service">
    <port name="ConsultaCuentaEquivalente-port" binding="tns:ConsultaCuentaEquivalente_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionValidaCTA"/>
    </port>
  </service>
</definitions>