<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MCVentaCHQGerencia/MCVentaCHQGerencia" name="MCVentaCHQGerencia-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MCVentaCHQGerencia/MCVentaCHQGerencia" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MCVentaCHQGerencia/MCVentaCHQGerencia" location="MCVentaCHQGerencia.wsdl"/>
  <binding name="MCVentaCHQGerencia_ptt-binding" type="tns:MCVentaCHQGerencia_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="MCVentaCHQGerencia">
      <soap:operation soapAction="MCVentaCHQGerencia"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="MCVentaCHQGerencia-service">
    <port name="MCVentaCHQGerencia-port" binding="tns:MCVentaCHQGerencia_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>