<wsdl:definitions name="GetBatchDetail" targetNamespace="https://www.ficohsa.com/regional/massivePayment" xmlns:tns="https://www.ficohsa.com/regional/massivePayment" xmlns:inp1="https://www.ficohsa.com/regional/massivePayment" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="https://www.ficohsa.com/regional/massivePayment" schemaLocation="../Schemas/GetBatchDetailTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="getBatchDetail" element="tns:getBatchDetail"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="getBatchDetailResponse" element="tns:getBatchDetailResponse"/>
    </wsdl:message>
    <wsdl:portType name="getBatchDetailPtt">
        <wsdl:operation name="getBatchDetail">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="getBatchDetailBind" type="tns:getBatchDetailPtt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getBatchDetail">
            <soap:operation style="document" soapAction="getBatchDetail"/>
            <wsdl:input>
                <soap:body use="literal" namespace="https://www.ficohsa.com/regional/massivePayment"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="https://www.ficohsa.com/regional/massivePayment"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>