<wsdl:definitions name="consultaBancoInternacionalPS" targetNamespace="http://www.example.org/consultaBancoInternacionalPS/" xmlns:cbi="http://www.example.org/consultaBancoInternacionalPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/consultaBancoInternacionalTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.example.org/consultaBancoInternacionalTypes" schemaLocation="../xsd/consultaBancoInternacionalTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaBancoInternacionalRequest">
		<wsdl:part element="tns:consultaBancoInternacionalRequest" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaBancoInternacionalResponse">
		<wsdl:part element="tns:consultaBancoInternacionalResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaBancoInternacionalPS">
		<wsdl:operation name="consultaBancoInternacional" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="cbi:consultaBancoInternacionalRequest"/>
			<wsdl:output message="cbi:consultaBancoInternacionalResponse"/>
		</wsdl:operation>
	</wsdl:portType>


	<wsdl:binding name="consultaBancoInternacionalPSSOAP" type="cbi:consultaBancoInternacionalPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/wsdl/soap/"/>
		<wsdl:operation name="consultaBancoInternacional">
			<soap:operation soapAction="http://www.example.org/consultaBancoInternacionalPS/consultaBancoInternacionalPS"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="cbi:consultaBancoInternacionalRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="cbi:consultaBancoInternacionalResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>


	<wsdl:service name="consultaBancoInternacionalPS">
		<wsdl:port binding="cbi:consultaBancoInternacionalPSSOAP" name="consultaBancoInternacionalPSSOAP">
			<soap:address location="http://mwomniprod:8003/Middleware/OperationsAndExecution/Payments/ConsultaBancoInternacional"/>
		</wsdl:port>
	</wsdl:service>


</wsdl:definitions>