<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RegistraBitacoraNI/RegistraBitacoraNI/RegistraBitacoraNI" name="RegistraBitacoraNI-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/RegistraBitacoraNI/RegistraBitacoraNI/RegistraBitacoraNI" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/RegistraBitacoraNI/RegistraBitacoraNI/RegistraBitacoraNI" location="RegistraBitacoraNI.wsdl"/>
  <binding name="RegistraBitacoraNI_ptt-binding" type="tns:RegistraBitacoraNI_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="RegistraBitacoraNI">
      <soap:operation soapAction="RegistraBitacoraNI"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="RegistraBitacoraNI-service">
    <port name="RegistraBitacoraNI-port" binding="tns:RegistraBitacoraNI_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConveniosNI"/>
    </port>
  </service>
</definitions>