<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionAlertas/AdministracionSubscripcion/administracionSubscripcion_db" name="administracionSubscripcion_db-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionAlertas/AdministracionSubscripcion/administracionSubscripcion_db" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionAlertas/AdministracionSubscripcion/administracionSubscripcion_db" location="administracionSubscripcion_db.wsdl"/>
  <binding name="administracionSubscripcion_db_ptt-binding" type="tns:administracionSubscripcion_db_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="administracionSubscripcion_db">
      <soap:operation soapAction="administracionSubscripcion_db"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="administracionSubscripcion_db-service">
    <port name="administracionSubscripcion_db-port" binding="tns:administracionSubscripcion_db_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionAlertas"/>
    </port>
  </service>
</definitions>