<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Card/SBHN_Card_PurchaseCreditCard/DBActBrokerTicketAdapter" name="DBActBrokerTicketAdapter-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="DBActBrokerTicketAdapter.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Card/SBHN_Card_PurchaseCreditCard/DBActBrokerTicketAdapter"/>
    <wsdl:binding name="DBActBrokerTicketAdapter_ptt-binding" type="dbac:DBActBrokerTicketAdapter_ptt" xmlns:dbac="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Card/SBHN_Card_PurchaseCreditCard/DBActBrokerTicketAdapter">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DBActBrokerTicketAdapter">
            <soap:operation soapAction="DBActBrokerTicketAdapter"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>