<wsdl:definitions name="sjConsultaMultipleProductosHNPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaMultipleProductosHN" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/sjConsultaMultipleProductosHN" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/sjConsultaMultipleProductosHN" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

<wsdl:types>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaMultipleProductosHN" schemaLocation="../xsd/sjConsultaMultipleProductosHN.xsd"/>
	</xsd:schema>
</wsdl:types>
    
<wsdl:message name="sjConsultaMultipleProductosHNRequest">
	<wsdl:part name="inputParameters" element="cons:sjConsultaMultipleProductosHN"/>
</wsdl:message>
<wsdl:message name="sjConsultaMultipleProductosHNResponse">
	<wsdl:part name="outputParameters" element="cons:sjConsultaMultipleProductosHNResponse"/>
</wsdl:message>

<wsdl:portType name="sjConsultaMultipleProductosHNPS">
	<wsdl:operation name="consultaProductos">
		<wsdl:input message="fic:sjConsultaMultipleProductosHNRequest"/>
		<wsdl:output message="fic:sjConsultaMultipleProductosHNResponse"/>		
	</wsdl:operation>
</wsdl:portType>

<wsdl:binding name="sjConsultaMultipleProductosHNPSSOAP" type="fic:sjConsultaMultipleProductosHNPS">
	<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
	<wsdl:operation name="consultaProductos">
		<wsdl:input>
			<soap:body parts="inputParameters" use="literal"/>
		</wsdl:input>
		<wsdl:output>
			<soap:body parts="outputParameters" use="literal"/>		
		</wsdl:output>
	</wsdl:operation>
</wsdl:binding>

<wsdl:service name="sjConsultaMultipleProductosHNPS">
	<wsdl:port name="jConsultaProductosPSSOAP" binding="fic:sjConsultaMultipleProductosHNPSSOAP">
		<soap:address location="http://172.23.13.19:8003/Middleware/SJS/ConsultaProductos"/>
	</wsdl:port>
</wsdl:service>

</wsdl:definitions>