<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/registraBitacora" name="registraBitacora-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/registraBitacora" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/registraBitacora" location="registraBitacora.wsdl"/>
  <binding name="registraBitacora_ptt-binding" type="tns:registraBitacora_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registraBitacora">
      <soap:operation soapAction="registraBitacora"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="registraBitacora-service">
    <port name="registraBitacora-port" binding="tns:registraBitacora_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionOperacionesTD"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="registraBitacora.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/registraBitacora">
            <con:wsdl ref="Middleware/v2/BusinessServices/OperacionesTarjetaDebito/RegistraBitacora_db/wsdl/registraBitacora"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/registraBitacora</con:targetNamespace>
</con:wsdlEntry>