<?binding.jca consultarTiposCredencialesStepUp_db.jca?><wsdl:definitions name="consultarTiposCredencialesStepUp" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultarTiposCredencialesStepUp/consultarTiposCredencialesStepUp" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DIGITARCLI/OSB_K_VCAS/STEP_UP/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultarTiposCredencialesStepUp/consultarTiposCredencialesStepUp" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="consultarTiposCredencialesStepUp_plt">
        <plt:role name="consultarTiposCredencialesStepUp_role">
            <plt:portType name="tns:consultarTiposCredencialesStepUp_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DIGITARCLI/OSB_K_VCAS/STEP_UP/" schemaLocation="../xsd/consultarTiposCredencialesStepUp_db.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="consultarTiposCredencialesStepUp_ptt">
        <wsdl:operation name="consultarTiposCredencialesStepUp">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>