<wsdl:definitions name="sjConsultaMovsRecientesTCNIPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaMovsRecientesTCNI/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/sjConsultaMovsRecientesTCNI/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:envi="http://www.ficohsa.com.hn/middleware.services/sjConsultaMovsRecientesTCNI">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaMovsRecientesTCNI" schemaLocation="../xsd/sjConsultaMovsRecientesTCNI.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="sjConsultaMovsRecientesTCNIRequest">
		<wsdl:part element="envi:sjConsultaMovsRecientesTCNIRequest" name="inputParameters"/>
	</wsdl:message>
	<wsdl:message name="sjConsultaMovsRecientesTCNIResponse">
		<wsdl:part element="envi:sjConsultaMovsRecientesTCNIResponse" name="outputParameters"/>
	</wsdl:message>

	<wsdl:portType name="sjConsultaMovsRecientesTCNIPS">
		<wsdl:operation name="ConsultaMovimientosTCNI">
			<wsdl:input message="fic:sjConsultaMovsRecientesTCNIRequest"/>
			<wsdl:output message="fic:sjConsultaMovsRecientesTCNIResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="sjConsultaMovsRecientesTCNIPSSOAP" type="fic:sjConsultaMovsRecientesTCNIPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="ConsultaMovimientosTCNI">
			<wsdl:input>
				<soap:body use="literal" parts="inputParameters"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="outputParameters"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="sjConsultaMovsRecientesTCNIPS">
		<wsdl:port binding="fic:sjConsultaMovsRecientesTCNIPSSOAP" name="jConsultaMovsRecientesTCNI">
			<soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/BusinessPartner/ConsultaMovimientosTCNI"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>