<wsdl:definitions name="consultaDemograficaProspectoPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaDemograficaProspectoPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cdp="http://www.ficohsa.com.hn/middleware.services/consultaDemograficaProspectoTypes" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaDemograficaProspectoPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaDemograficaProspectoTypes" schemaLocation="../xsd/consultaDemograficaProspectoTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="consultaDemograficaProspecto">
		<wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
		<wsdl:part element="cdp:consultaDemograficaProspecto" name="parameters"/>
	</wsdl:message>
	<wsdl:message name="consultaDemograficaProspectoResponse">
		<wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
		<wsdl:part element="cdp:consultaDemograficaProspectoResponse" name="result"/>
	</wsdl:message>
	<wsdl:portType name="consultaDemograficaProspectoPS">
		<wsdl:operation name="consultaDemograficaProspecto" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaDemograficaProspecto"/>
			<wsdl:output message="fic:consultaDemograficaProspectoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="consultaDemograficaProspectoPSSOAP" type="fic:consultaDemograficaProspectoPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaDemograficaProspecto">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaDemograficaProspectoPS/consultaDemograficaProspecto"/>
			<wsdl:input>
				<soap:header message="fic:consultaDemograficaProspecto" part="RequestHeader" use="literal"/>
				<soap:body use="literal" parts="parameters"/>
			</wsdl:input>
			<wsdl:output>
				<soap:header message="fic:consultaDemograficaProspectoResponse" part="ResponseHeader" use="literal"/>
				<soap:body use="literal" parts="result"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="consultaDemograficaProspectoPS">
		<wsdl:port binding="fic:consultaDemograficaProspectoPSSOAP" name="consultaDemograficaProspectoPSSOAP">
			<soap:address location="https://172.23.13.19:8004/Middleware/OperationsAndExecution/Cards/ConsultaDemograficaProspecto"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>