<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/AfiliarDeudoresDepRef/ingresarDeudoresDepRef" name="ingresarDeudoresDepRef-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/AfiliarDeudoresDepRef/ingresarDeudoresDepRef" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/AfiliarDeudoresDepRef/ingresarDeudoresDepRef" location="ingresarDeudoresDepRef.wsdl"/>
  <binding name="ingresarDeudoresDepRef_ptt-binding" type="tns:ingresarDeudoresDepRef_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ingresarDeudoresDepRef">
      <soap:operation soapAction="ingresarDeudoresDepRef"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ingresarDeudoresDepRef-service">
    <port name="ingresarDeudoresDepRef-port" binding="tns:ingresarDeudoresDepRef_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>