<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BussinesGT/ProjectICGGT/InhabilitacionGT" name="InhabilitacionGT-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BussinesGT/ProjectICGGT/InhabilitacionGT" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BussinesGT/ProjectICGGT/InhabilitacionGT" location="InhabilitacionGT.wsdl"/>
  <binding name="InhabilitacionGT_ptt-binding" type="tns:InhabilitacionGT_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="InhabilitacionGT">
      <soap:operation soapAction="InhabilitacionGT"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="InhabilitacionGT-service">
    <port name="InhabilitacionGT-port" binding="tns:InhabilitacionGT_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionAbanksGT"/>
    </port>
  </service>
</definitions>