<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/inbound/T24Events/T24ConveniosTSP/T24ConveniosTSP" name="T24ConveniosTSP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/inbound/T24Events/T24ConveniosTSP/T24ConveniosTSP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/inbound/T24Events/T24ConveniosTSP/T24ConveniosTSP" location="T24ConveniosTSP.wsdl"/>
  <binding name="EventPoll_ptt-binding" type="tns:EventPoll_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="EventPoll">
      <soap:operation soapAction="EventPoll"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="T24ConveniosTSP-service">
    <port name="T24ConveniosTSP-port" binding="tns:EventPoll_ptt-binding">
      <soap:address location="jca://eis/T24Adapter"/>
    </port>
  </service>
</definitions>