<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarMontoTSPBanco/consultaMontoTSPBanco" name="consultaMontoTSPBanco-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarMontoTSPBanco/consultaMontoTSPBanco" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarMontoTSPBanco/consultaMontoTSPBanco" location="consultaMontoTSPBanco.wsdl"/>
  <binding name="consultaMontoTSPBanco_ptt-binding" type="tns:consultaMontoTSPBanco_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaMontoTSPBanco">
      <soap:operation soapAction="consultaMontoTSPBanco"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaMontoTSPBanco-service">
    <port name="consultaMontoTSPBanco-port" binding="tns:consultaMontoTSPBanco_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTSP"/>
    </port>
  </service>
</definitions>