<?binding.jca consultaMontoTSPBanco_db.jca?><wsdl:definitions name="consultaMontoTSPBanco" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarMontoTSPBanco/consultaMontoTSPBanco" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/consultaMontoTSPBanco" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarMontoTSPBanco/consultaMontoTSPBanco" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="consultaMontoTSPBanco_plt">
        <plt:role name="consultaMontoTSPBanco_role">
            <plt:portType name="tns:consultaMontoTSPBanco_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/consultaMontoTSPBanco" schemaLocation="../xsd/consultaMontoTSPBanco_sp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="consultaMontoTSPBanco_ptt">
        <wsdl:operation name="consultaMontoTSPBanco">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>