<wsdl:definitions 
	name="operacionesBilleteraPS"
	targetNamespace="http://www.ficohsa.com.hn/middleware.services/operacionesBilleteraPS/"
	xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType"
	xmlns:ope="http://www.ficohsa.com.hn/middleware.services/operacionesBilleteraPS/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.ficohsa.com.hn/middleware.services/operacionesBilleteraTypes"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType"
				schemaLocation="../../esquemas_generales/HeaderElements.xsd" />
		</xsd:schema>
		<xsd:schema>
			<xsd:import
				namespace="http://www.ficohsa.com.hn/middleware.services/operacionesBilleteraTypes"
				schemaLocation="../xsd/operacionesBilleteraTypes.xsd" />
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="consultaProductosCliente">
		<wsdl:part element="tns:consultaProductosCliente" name="parameters" />
		<wsdl:part element="auth:RequestHeader" name="RequestHeader" />
	</wsdl:message>
	
	<wsdl:message name="consultaProductosClienteResponse">
		<wsdl:part element="tns:consultaProductosClienteResponse" name="result" />
		<wsdl:part element="auth:ResponseHeader" name="ResponseHeader" />
	</wsdl:message>
	
	<wsdl:portType name="operacionesBilleteraPS">
		<wsdl:operation name="consultaProductosCliente"
			parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="ope:consultaProductosCliente" />
			<wsdl:output message="ope:consultaProductosClienteResponse" />
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="operacionesBilleteraPSSOAP" type="ope:operacionesBilleteraPS">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="consultaProductosCliente">
			<soap:operation
				soapAction="http://www.ficohsa.com.hn/middleware.services/operacionesBilleteraPS/consultaProductosCliente" />
			<wsdl:input>
				<soap:body parts="parameters" use="literal" />
				<soap:header message="ope:consultaProductosCliente" part="RequestHeader"
					use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="result" use="literal" />
				<soap:header message="ope:consultaProductosClienteResponse" part="ResponseHeader"
					use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="operacionesBilleteraPS">
		<wsdl:port binding="ope:operacionesBilleteraPSSOAP" name="operacionesBilleteraPSSOAP">
			<soap:address location="http://172.19.2.73:8080/OnBaseSoap/Enlace?wsdl" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
