<wsdl:definitions name="reprocesoACHRecibidasCRPS" 
				targetNamespace="http://www.ficohsa.com.hn/middleware.services/reprocesoACHRecibidasCR/" 
				xmlns:fic="http://www.ficohsa.com.hn/middleware.services/reprocesoACHRecibidasCR/" 
				xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
				xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
				xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
				xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" 
				xmlns:rep="http://www.ficohsa.com.hn/middleware.services/reprocesoACHRecibidasCRTypes">
				
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/reprocesoACHRecibidasCRTypes" schemaLocation="../xsd/reprocesoACHRecibidasCRTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="reprocesoACHRecibidasCRRequest">
		<wsdl:part element="rep:reprocesoACHRecibidasCR" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="reprocesoACHRecibidasCRResponse">
		<wsdl:part element="rep:reprocesoACHRecibidasCRResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="reprocesoACHRecibidasCRPS">
		<wsdl:operation name="reprocesoACHRecibidasCR" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:reprocesoACHRecibidasCRRequest"/>
			<wsdl:output message="fic:reprocesoACHRecibidasCRResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="reprocesoACHRecibidasCRPSSOAP" type="fic:reprocesoACHRecibidasCRPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="reprocesoACHRecibidasCR">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/reprocesoACHRecibidasCRPS/reprocesoACHRecibidasCR"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:reprocesoACHRecibidasCRRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:reprocesoACHRecibidasCRResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="reprocesoACHRecibidasCRPS">
	    <wsdl:port binding="fic:reprocesoACHRecibidasCRPSSOAP" name="reprocesoACHRecibidasCRPSSOAP">
	      <soap:address location="http://10.9.104.55:8003/Middleware/OperationsAndExecution/Payments/ReprocesoACHRecibidasCR"/>
	    </wsdl:port>
  	</wsdl:service>
	
</wsdl:definitions>