<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ModificaFechaAporteAFP/ModificaFechaAporteAFP" name="ModificaFechaAporteAFP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ModificaFechaAporteAFP/ModificaFechaAporteAFP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ModificaFechaAporteAFP/ModificaFechaAporteAFP" location="ModificaFechaAporteAFP.wsdl"/>
  <binding name="ModificaFechaAporteAFP_ptt-binding" type="tns:ModificaFechaAporteAFP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ModificaFechaAporteAFP">
      <soap:operation soapAction="ModificaFechaAporteAFP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ModificaFechaAporteAFP-service">
    <port name="ModificaFechaAporteAFP-port" binding="tns:ModificaFechaAporteAFP_ptt-binding">
      <soap:address location="jca://eis/DB/jdbc/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>