<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/consultaParametros" name="consultaParametros-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/consultaParametros" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/consultaParametros" location="consultaParametros.wsdl"/>
  <binding name="consultaParametros_ptt-binding" type="tns:consultaParametros_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaParametros">
      <soap:operation soapAction="consultaParametros"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaParametros-service">
    <port name="consultaParametros-port" binding="tns:consultaParametros_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="consultaParametros.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/consultaParametros">
            <con:wsdl ref="MWHostToHost/v1/BusinessServices/PWS/consultaParametros/wsdl/consultaParametros"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/consultaParametros</con:targetNamespace>
</con:wsdlEntry>