<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/inbound/FicoTSPAdapterInbound001/T24TSPAdapter001/T24FtAdapterPoll001" name="T24FtAdapterPoll001-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/inbound/FicoTSPAdapterInbound001/T24TSPAdapter001/T24FtAdapterPoll001" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/inbound/FicoTSPAdapterInbound001/T24TSPAdapter001/T24FtAdapterPoll001" location="T24FtAdapterPoll001.wsdl"/>
  <binding name="EventPoll_ptt-binding" type="tns:EventPoll_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="EventPoll">
      <soap:operation soapAction="EventPoll"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="T24FtAdapterPoll001-service">
    <port name="T24FtAdapterPoll001-port" binding="tns:EventPoll_ptt-binding">
      <soap:address location="jca://eis/T24Adapter"/>
    </port>
  </service>
</definitions>