<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="GetBalancesWarrantiesBS" targetNamespace="http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetBalancesWarranties/GetBalancesWarrantiesBS" xmlns:tns="http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetBalancesWarranties/GetBalancesWarrantiesBS" xmlns:inp1="https://www.ficohsa.com/regional/pension" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="GetBalancesWarrantiesBS">
        <plnk:role name="GetBalancesWarrantiesBSProvider" portType="tns:GetBalancesWarrantiesBS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www.ficohsa.com/regional/pension" schemaLocation="../Schemas/GetBalancesWarrantiesTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="getBalancesWarranties_inputMessage">
        <wsdl:part name="request" element="inp1:getBalancesWarranties"/>
    </wsdl:message>
    <wsdl:message name="getBalancesWarranties_outputMessage">
        <wsdl:part name="reply" element="inp1:getBalancesWarrantiesResponse"/>
    </wsdl:message>
    <wsdl:portType name="GetBalancesWarrantiesBS_ptt">
        <wsdl:operation name="getBalancesWarranties">
            <wsdl:input message="tns:getBalancesWarranties_inputMessage"/>
            <wsdl:output message="tns:getBalancesWarranties_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="GetBalancesWarrantiesBS_ptt-binding" type="tns:GetBalancesWarrantiesBS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getBalancesWarranties">
            <soap:operation soapAction="getBalancesWarranties"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../Schemas/GetBalancesWarrantiesTypes.xsd" namespace="https://www.ficohsa.com/regional/pension" ref="SBRG_Pension_GetBalancesWarranties/Schemas/GetBalancesWarrantiesTypes"/>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetBalancesWarranties/GetBalancesWarrantiesBS</con:targetNamespace>
</con:wsdlEntry>