<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/reversarVentaMenor/registrarVentaMenor/reversarVentaMenor" name="reversarVentaMenor-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/reversarVentaMenor/registrarVentaMenor/reversarVentaMenor" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/reversarVentaMenor/registrarVentaMenor/reversarVentaMenor" location="reversarVentaMenor.wsdl"/>
  <binding name="reversarVentaMenor_ptt-binding" type="tns:reversarVentaMenor_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="reversarVentaMenor">
      <soap:operation soapAction="reversarVentaMenor"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="reversarVentaMenor-service">
    <port name="reversarVentaMenor-port" binding="tns:reversarVentaMenor_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>