<wsdl:definitions name="CreateCustomerProfilePS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/CreateCustomerProfilePS/" xmlns:ccp="http://www.ficohsa.com.hn/middleware.services/CreateCustomerProfilePS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:mon="http://www.ficohsa.com.hn/middleware.services/moneyTransferOperationsTypes">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../../General/xsd/Header.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/moneyTransferOperationsTypes" schemaLocation="../../xsd/MoneyTransferOperationsTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="createCustomerProfileRequest">
		<wsdl:part element="mon:createCustomerProfile" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="createCustomerProfileResponse">
		<wsdl:part element="mon:createCustomerProfileResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="CreateCustomerProfilePS">
		<wsdl:operation name="createCustomerProfile">			
			<wsdl:input message="ccp:createCustomerProfileRequest"/>
			<wsdl:output message="ccp:createCustomerProfileResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="CreateCustomerProfilePSSOAP" type="ccp:CreateCustomerProfilePS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="createCustomerProfile">
			<soap:operation soapAction="http://www.example.org/CreateCustomerProfilePS/createCustomerProfile"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="ccp:createCustomerProfileRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="ccp:createCustomerProfileResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="CreateCustomerProfilePS">
		<wsdl:port binding="ccp:CreateCustomerProfilePSSOAP" name="CreateCustomerProfilePSSOAP">
			<soap:address location="http://mwteller:8004/mwteller/moneyTransfer/moneyTransferOperations"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>