<wsdl:definitions name="ConsultaPatronosPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/ConsultaPatronosPS" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/ConsultaPatronosPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:con="http://www.ficohsa.com.hn/middleware.services/consultaPatronosTypes" xmlns:aut="http://www.ficohsa.com.hn/middleware.services/autType">

<wsdl:types>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>	
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaPatronosTypes" schemaLocation="../xsd/consultaPatronosTypes.xsd"/>	
	</xsd:schema>
</wsdl:types>

<wsdl:message name="consultaPatronosPSRequest">
	<wsdl:part name="requestHeader" element="aut:RequestHeader"/>
	<wsdl:part name="inputParameters" element="con:consultaPatronosRequest"/>
</wsdl:message>

<wsdl:message name="consultaPatronosPSResponse">
	<wsdl:part name="responseHeader" element="aut:ResponseHeader"/>
	<wsdl:part name="outputResult" element="con:consultaPatronosResponse"/>
</wsdl:message>

<wsdl:portType name="consultaPatronosPS">
	<wsdl:operation name="consultaPatronos">
		<wsdl:input message="fic:consultaPatronosPSRequest"/>
		<wsdl:output message="fic:consultaPatronosPSResponse"/>
	</wsdl:operation>
</wsdl:portType>

<wsdl:binding name="consultaPatronosPSSOAP" type="fic:consultaPatronosPS">
	<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
	<wsdl:operation name="consultaPatronos">
		<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/ConsultaPatronoPS/consultaPatronos"/>
		<wsdl:input>			
			<soap:header use="literal" part="requestHeader" message="fic:consultaPatronosPSRequest"/>
			<soap:body use="literal" parts="inputParameters"/>
		</wsdl:input>
		<wsdl:output>
			<soap:header use="literal" part="responseHeader" message="fic:consultaPatronosPSResponse"/>			
			<soap:body use="literal" parts="outputResult"/>			
		</wsdl:output>
	</wsdl:operation>
</wsdl:binding>

<wsdl:service name="consultaPatronosPS">
	<wsdl:port name="consultaPatronosPSSOAP" binding="fic:consultaPatronosPSSOAP">
		<soap:address location="http://10.9.104.55:8003/Middleware/ReferenceData/CommonBusinessInformation/ConsultaPatronos"/>
	</wsdl:port>	
</wsdl:service>
</wsdl:definitions>