<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerInfoConvenios/ObtenieInfoConvenio/ObtenerInfomacionConvenio" name="ObtenerInfomacionConvenio-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerInfoConvenios/ObtenieInfoConvenio/ObtenerInfomacionConvenio" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerInfoConvenios/ObtenieInfoConvenio/ObtenerInfomacionConvenio" location="ObtenerInfomacionConvenio.wsdl"/>
  <binding name="ObtenerInfomacionConvenio_ptt-binding" type="tns:ObtenerInfomacionConvenio_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ObtenerInfomacionConvenio">
      <soap:operation soapAction="ObtenerInfomacionConvenio"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ObtenerInfomacionConvenio-service">
    <port name="ObtenerInfomacionConvenio-port" binding="tns:ObtenerInfomacionConvenio_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>