<wsdl:definitions name="transferenciasACHRecibidasPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/transferenciasACHRecibidasPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/transferenciasACHRecibidasPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:trans="http://www.ficohsa.com.hn/middleware.services/transferenciasACHRecibidasTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">
 <wsdl:types>
  <xsd:schema>
   <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
  </xsd:schema>
  <xsd:schema>
   <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/transferenciasACHRecibidasTypes" schemaLocation="../xsd/transferenciasACHRecibidasTypes.xsd"/>
  </xsd:schema>
 </wsdl:types>

 <wsdl:message name="transferenciasACHRecibidasRequest">
  <wsdl:part element="trans:transferenciasACHRecibidas" name="parameters"/>
  <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
 </wsdl:message>
 <wsdl:message name="transferenciasACHRecibidasResponse">
  <wsdl:part element="trans:transferenciasACHRecibidasResponse" name="result"/>
  <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
 </wsdl:message>
 
 <wsdl:portType name="transferenciasACHRecibidasPS">
  <wsdl:operation name="transferenciasACHRecibidas" parameterOrder="parameters RequestHeader ResponseHeader">
   <wsdl:input message="fic:transferenciasACHRecibidasRequest"/>
   <wsdl:output message="fic:transferenciasACHRecibidasResponse"/>
  </wsdl:operation>
 </wsdl:portType>

 <wsdl:binding name="transferenciasACHRecibidasPSSOAP" type="fic:transferenciasACHRecibidasPS">
  <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <wsdl:operation name="transferenciasACHRecibidas">
   <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/transferenciasACHRecibidasPS/transferenciasACHRecibidas"/>
   <wsdl:input>
    <soap:body use="literal" parts="parameters"/>
    
    <soap:header message="fic:transferenciasACHRecibidasRequest" part="RequestHeader" use="literal"/>
   </wsdl:input>
   <wsdl:output>
    <soap:body use="literal" parts="result"/>
    <soap:header message="fic:transferenciasACHRecibidasResponse" part="ResponseHeader" use="literal"/>
   </wsdl:output>
  </wsdl:operation>
 </wsdl:binding>

 <wsdl:service name="transferenciasACHRecibidasPS">
  <wsdl:port binding="fic:transferenciasACHRecibidasPSSOAP" name="transferenciasACHRecibidasPSSOAP">
   <soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/CustomerDeposits/transferenciasACHRecibidas"/>
  </wsdl:port>
 </wsdl:service>
</wsdl:definitions>