<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/listadoPatronosFPC/listadoPatronosFPC" name="listadoPatronosFPC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/listadoPatronosFPC/listadoPatronosFPC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/listadoPatronosFPC/listadoPatronosFPC" location="listadoPatronosFPC.wsdl"/>
  <binding name="listadoPatronosFPC_ptt-binding" type="tns:listadoPatronosFPC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="listadoPatronosFPC">
      <soap:operation soapAction="listadoPatronosFPC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="listadoPatronosFPC-service">
    <port name="listadoPatronosFPC-port" binding="tns:listadoPatronosFPC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionFicopen"/>
    </port>
  </service>
</definitions>