<wsdl:definitions name="consultaListaClientePS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/verificaPagoRecaudoPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/verificaPagoRecaudoPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:rei="http://www.ficohsa.com.hn/middleware.services/verificaPagoRecaudoTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/verificaPagoRecaudoTypes" schemaLocation="../xsd/verificaPagoRecaudoTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="verificaPagoRecaudoRequest">
		<wsdl:part element="rei:verificaPagoRecaudo" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="verificaPagoRecaudoResponse">
		<wsdl:part element="rei:verificaPagoRecaudoResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="verificaPagoRecaudoPS">
		<wsdl:operation name="verificaPagoRecaudo" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:verificaPagoRecaudoRequest"/>
			<wsdl:output message="fic:verificaPagoRecaudoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="verificaPagoRecaudoPSSOAP" type="fic:verificaPagoRecaudoPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="verificaPagoRecaudo">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/verificaPagoRecaudoPS"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:verificaPagoRecaudoRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:verificaPagoRecaudoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="verificaPagoRecaudoPS">
    <wsdl:port binding="fic:verificaPagoRecaudoPSSOAP" name="verificaPagoRecaudoPSSOAP">
      <soap:address location="http://10.9.104.55:8003/Middleware/OperationsAndExecution/Payments/verificaPagoRecaudo"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>