<wsdl:definitions name="actualizarDatosPlantillaPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/actualizarDatosPlantillaPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/actualizarDatosPlantillaPS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/gestionesEstadoCuentaTypes">


	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/gestionesEstadoCuentaTypes" schemaLocation="../../GestionesEstadoCuenta/xsd/gestionesEstadoCuentaTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="actualizarDatosPlantilla">
		<wsdl:part element="cons:actualizarDatosPlantilla" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="actualizarDatosPlantillaResponse">
		<wsdl:part element="cons:actualizarDatosPlantillaResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="actualizarDatosPlantillaPS">
		<wsdl:operation name="actualizarDatosPlantilla" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="tns:actualizarDatosPlantilla"/>
			<wsdl:output message="tns:actualizarDatosPlantillaResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="actualizarDatosPlantillaPSSOAP" type="tns:actualizarDatosPlantillaPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="actualizarDatosPlantilla">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/actualizarDatosPlantillaPS/actualizarDatosPlantilla"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="tns:actualizarDatosPlantilla" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="tns:actualizarDatosPlantillaResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="actualizarDatosPlantillaPS">
		<wsdl:port binding="tns:actualizarDatosPlantillaPSSOAP" name="actualizarDatosPlantillaPSSOAP">
			<soap:address location="https://mwomnicanal:8004/Middleware/ReferenceData/BusinessPartner/actualizarDatosPlantilla"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>