<wsdl:definitions name="ConsultarImagenService" targetNamespace="http://ConsultaImagen.ficohsa.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ConsultaImagen.ficohsa.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
<import namespace="http://ConsultaImagen.ficohsa.com/" schemaLocation="../xsd/XMLSchema_-131460889.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="convertirImagenResponse">
    <wsdl:part element="tns:convertirImagenResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="convertirImagen">
    <wsdl:part element="tns:convertirImagen" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ConsultarImagen">
    <wsdl:operation name="convertirImagen">
      <wsdl:input message="tns:convertirImagen" name="convertirImagen">
    </wsdl:input>
      <wsdl:output message="tns:convertirImagenResponse" name="convertirImagenResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultarImagenServiceSoapBinding" type="tns:ConsultarImagen">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="convertirImagen">
      <soap:operation soapAction="urn:ConvertirImagen" style="document"/>
      <wsdl:input name="convertirImagen">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="convertirImagenResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ConsultarImagenService">
    <wsdl:port binding="tns:ConsultarImagenServiceSoapBinding" name="ConsultarImagenPort">
      <soap:address location="http://172.20.6.14:8080/ConsultaImagen/services/ConsultarImagenPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>