<wsdl:definitions name="consultaComisionesPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaComisionesPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaComisionesPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaComisionesTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaComisionesTypes" schemaLocation="../xsd/consultaComisionesTypes.xsd"/> 
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="consultaComisionesRequest">
		<wsdl:part element="cons:consultaComisiones" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaComisionesResponse">
		<wsdl:part element="cons:consultaComisionesResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="consultaComisionesPS">
		<wsdl:operation name="consultaComisiones" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaComisionesRequest"/>
			<wsdl:output message="fic:consultaComisionesResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaComisionesPSSOAP" type="fic:consultaComisionesPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaComisiones">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaComisionesPS/consultaComisiones"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaComisionesRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaComisionesResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="consultaComisionesPS">
    <wsdl:port binding="fic:consultaComisionesPSSOAP" name="consultaComisionesPSSOAP">
      <soap:address location="http://mwomnidesa:8003/Middleware/ReferenceData/CommonBusinessInformation/consultaComisiones"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>