<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaGarantiasCredito/consultaGarantiasCredito" name="consultaGarantiasCredito-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaGarantiasCredito/consultaGarantiasCredito" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaGarantiasCredito/consultaGarantiasCredito" location="consultaGarantiasCredito.wsdl"/>
  <binding name="consultaGarantiasCredito_ptt-binding" type="tns:consultaGarantiasCredito_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaGarantiasCredito">
      <soap:operation soapAction="consultaGarantiasCredito"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaGarantiasCredito-service">
    <port name="consultaGarantiasCredito-port" binding="tns:consultaGarantiasCredito_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>