<wsdl:definitions name="aplicaRetiroATMT24PS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/aplicaRetiroATMT24PS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/aplicaRetiroATMT24PS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:rcb="http://www.ficohsa.com.hn/middleware.services/aplicaRetiroATMT24Types">

    <wsdl:types>
    <xsd:schema>
        <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
    </xsd:schema>
    <xsd:schema>
        <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/aplicaRetiroATMT24Types" schemaLocation="../xsd/aplicaRetiroATMT24Types.xsd"/>
    </xsd:schema>
    </wsdl:types> 

    <wsdl:message name="aplicaRetiroATMT24">
        <wsdl:part element="rcb:aplicaRetiroATMT24" name="parameters"/>
        <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
    </wsdl:message>
    <wsdl:message name="aplicaRetiroATMT24Response">
        <wsdl:part element="rcb:aplicaRetiroATMT24Response" name="result"/>
        <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
    </wsdl:message>

    <wsdl:portType name="aplicaRetiroATMT24PS">
        <wsdl:operation name="aplicaRetiroATMT24" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="fic:aplicaRetiroATMT24"/>
            <wsdl:output message="fic:aplicaRetiroATMT24Response"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="aplicaRetiroATMT24PSSOAP" type="fic:aplicaRetiroATMT24PS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="aplicaRetiroATMT24">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/aplicaRetiroATMT24PS/aplicaRetiroATMT24"/>
            <wsdl:input>
                <soap:body use="literal" parts="parameters"/>
                <soap:header message="fic:aplicaRetiroATMT24" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="result"/>
                <soap:header message="fic:aplicaRetiroATMT24Response" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation> 
    </wsdl:binding>

    <wsdl:service name="aplicaRetiroATMT24PS">
        <wsdl:port binding="fic:aplicaRetiroATMT24PSSOAP" name="aplicaRetiroATMT24PSSOAP">
            <soap:address location="http://localhost:8003/Middleware/OperationsAndExecution/Messaging/aplicaRetiroATMT24"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>