<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication2/LineasCreditoRTN/LineasCreditoRTN_db" name="LineasCreditoRTN_db-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="LineasCreditoRTN_db.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication2/LineasCreditoRTN/LineasCreditoRTN_db"/>
    <wsdl:binding name="LineasCreditoRTN_db_ptt-binding" type="lin:LineasCreditoRTN_db_ptt" xmlns:lin="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication2/LineasCreditoRTN/LineasCreditoRTN_db">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="LineasCreditoRTN_db">
            <soap:operation soapAction="LineasCreditoRTN_db"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>