<wsdl:definitions name="sjConsultaSituacionFinancieraPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaSituacionFinancieraPS" xmlns:tns="SplitJoinTest" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/sjConsultaSituacionFinancieraPS" xmlns:envi="http://www.ficohsa.com.hn/middleware.services/sjConsultaSituacionFinanciera" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../../../Resources/esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaSituacionFinanciera" schemaLocation="../xsd/sjConsultaSituacionFinanciera.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="sjConsultaSituacionFinancieraRequest">
		<wsdl:part name="inputParameters" element="envi:sjConsultaSituacionFinanciera"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	
	<wsdl:message name="sjConsultaSituacionFinancieraResponse">
		<wsdl:part name="outputParameters" element="envi:sjConsultaSituacionFinancieraResponse"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="sjConsultaSituacionFinancieraPS">
		<wsdl:operation name="ConsultaSituacionFinanciera" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:sjConsultaSituacionFinancieraRequest"/>
			<wsdl:output message="fic:sjConsultaSituacionFinancieraResponse"/>		
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="sjConsultaSituacionFinancieraPSSOAP" type="fic:sjConsultaSituacionFinancieraPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="ConsultaSituacionFinanciera">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/sjConsultaSituacionFinancieraPS/sjConsultaSituacionFinanciera"/>
			<wsdl:input>
				<soap:body use="literal" parts="inputParameters"/>
				<soap:header message="fic:sjConsultaSituacionFinancieraRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="outputParameters"/>
				<soap:header message="fic:sjConsultaSituacionFinancieraResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="sjConsultaSituacionFinancieraPS">
		<wsdl:port name="sjConsultaSituacionFinancieraPSSOAP" binding="fic:sjConsultaSituacionFinancieraPSSOAP">
			<soap:address location="http://mwomnidesa:8003/Middleware/SJS/ConsultaSituacionFinanciera"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>