<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarCorresponsalB/consultarCorresponsalB" name="consultarCorresponsalB-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarCorresponsalB/consultarCorresponsalB" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarCorresponsalB/consultarCorresponsalB" location="consultarCorresponsalB.wsdl"/>
  <binding name="consultarCorresponsalB_ptt-binding" type="tns:consultarCorresponsalB_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultarCorresponsalB">
      <soap:operation soapAction="consultarCorresponsalB"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultarCorresponsalB-service">
    <port name="consultarCorresponsalB-port" binding="tns:consultarCorresponsalB_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>