<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksPASOAApplication/ConsultaMovimientosCuentaHoy/consultaMovimientosCuentaHoy" name="consultaMovimientosCuentaHoy-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksPASOAApplication/ConsultaMovimientosCuentaHoy/consultaMovimientosCuentaHoy" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksPASOAApplication/ConsultaMovimientosCuentaHoy/consultaMovimientosCuentaHoy" location="consultaMovimientosCuentaHoy.wsdl"/>
  <binding name="consultaMovimientosCuentaHoy_ptt-binding" type="tns:consultaMovimientosCuentaHoy_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaMovimientosCuentaHoy">
      <soap:operation soapAction="consultaMovimientosCuentaHoy"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaMovimientosCuentaHoy-service">
    <port name="consultaMovimientosCuentaHoy-port" binding="tns:consultaMovimientosCuentaHoy_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksPA"/>
    </port>
  </service>
</definitions>