<wsdl:definitions name="registroContratoACHPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/registroContratoACHPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/registroContratoACHPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tran="http://www.ficohsa.com.hn/middleware.services/registroContratoACHTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">

	<!-- Se define los namespaces de los XSD que se estaran mapeando -->			  
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/registroContratoACHTypes" schemaLocation="../xsd/registroContratoACHTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<!-- Se define los parametros de Entrada -->
	<wsdl:message name="registroContratoACHRequest">
        <wsdl:part element="tran:registroContratoACH" name="parameters"/>
        <wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
    </wsdl:message>
    
    <!-- Se define los parametros de Salida -->
    <wsdl:message name="registroContratoACHResponse">
        <wsdl:part element="tran:registroContratoACHResponse" name="result"/>
        <wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
    </wsdl:message>
	
	<!-- Establecemos los parametros con sus puertos de Entrada y Salida-->
    <wsdl:portType name="registroContratoACHPS">
        <wsdl:operation name="registroContratoACH" parameterOrder="parameters RequestHeader result ResponseHeader">
            <wsdl:input message="fic:registroContratoACHRequest"/>
            <wsdl:output message="fic:registroContratoACHResponse"/>
        </wsdl:operation>
    </wsdl:portType>
	
	<!-- Establecemos los parametros de la mensajeria SOAP de Entrada y Salida-->
    <wsdl:binding name="registroContratoACHPSSOAP" type="fic:registroContratoACHPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="registroContratoACH">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/registroContratoACHPS/registroContratoACH"/>
            <wsdl:input>
                <soap:body parts="parameters" use="literal"/>
                <soap:header message="fic:registroContratoACHRequest" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body parts="result" use="literal"/>
                <soap:header message="fic:registroContratoACHResponse" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

	<!-- Establecemos los parametros de llamado al servicio-->
    <wsdl:service name="registroContratoACHPS">
        <wsdl:port binding="fic:registroContratoACHPSSOAP" name="registroContratoACHPSSOAP">
            <soap:address location="https://10.9.104.32:8004/Middleware/OperationsAndExecution/CustomerContracts/registroContratoACH"/>
        </wsdl:port>
    </wsdl:service>
	
</wsdl:definitions>