<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="FPCWithdrawalConsultationBS" targetNamespace="http://xmlns.oracle.com/SBHN__Pension_FPCWithdrawalConsultation/SBRG_Pension_FPCWithdrawalConsultation/FPCWithdrawalConsultationBS" xmlns:tns="http://xmlns.oracle.com/SBHN__Pension_FPCWithdrawalConsultation/SBRG_Pension_FPCWithdrawalConsultation/FPCWithdrawalConsultationBS" xmlns:inp1="https://www.ficohsa.com/regional/pension" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="FPCWithdrawalConsultationBS">
        <plnk:role name="FPCWithdrawalConsultationBSProvider" portType="tns:FPCWithdrawalConsultationBS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www.ficohsa.com/regional/pension" schemaLocation="../Schemas/FPCWithdrawalConsultationTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="FPCWithdrawalConsultation_inputMessage">
        <wsdl:part name="request" element="inp1:FPCWithdrawalConsultation"/>
    </wsdl:message>
    <wsdl:message name="FPCWithdrawalConsultation_outputMessage">
        <wsdl:part name="reply" element="inp1:FPCWithdrawalConsultationResponse"/>
    </wsdl:message>
    <wsdl:portType name="FPCWithdrawalConsultationBS_ptt">
        <wsdl:operation name="FPCWithdrawalConsultation">
            <wsdl:input message="tns:FPCWithdrawalConsultation_inputMessage"/>
            <wsdl:output message="tns:FPCWithdrawalConsultation_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="FPCWithdrawalConsultationBS_ptt-binding" type="tns:FPCWithdrawalConsultationBS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="FPCWithdrawalConsultation">
            <soap:operation style="document" soapAction="http://xmlns.oracle.com/SBHN__Pension_FPCWithdrawalConsultation/SBRG_Pension_FPCWithdrawalConsultation/FPCWithdrawalConsultationBS/FPCWithdrawalConsultation"/>
            <wsdl:input>
                <soap:body use="literal" parts="request"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="reply"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../Schemas/FPCWithdrawalConsultationTypes.xsd" namespace="https://www.ficohsa.com/regional/pension" ref="SBRG_Pension_FPCWithdrawalConsultation/Schemas/FPCWithdrawalConsultationTypes"/>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/SBHN__Pension_FPCWithdrawalConsultation/SBRG_Pension_FPCWithdrawalConsultation/FPCWithdrawalConsultationBS</con:targetNamespace>
</con:wsdlEntry>