<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="FPCWithdrawalConsultation" targetNamespace="https://www.ficohsa.com/regional/pension" xmlns:tns="https://www.ficohsa.com/regional/pension" xmlns:inp1="https://www.ficohsa.com/regional/pension" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="https://www.ficohsa.com/regional/pension" schemaLocation="../Schemas/FPCWithdrawalConsultationTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="FPCWithdrawalConsultation" element="tns:FPCWithdrawalConsultation"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="FPCWithdrawalConsultationResponse" element="tns:FPCWithdrawalConsultationResponse"/>
    </wsdl:message>
    <wsdl:portType name="FPCWithdrawalConsultationPtt">
        <wsdl:operation name="FPCWithdrawalConsultation">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="FPCWithdrawalConsultationBind" type="tns:FPCWithdrawalConsultationPtt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="FPCWithdrawalConsultation">
            <soap:operation style="document" soapAction="FPCWithdrawalConsultation"/>
            <wsdl:input>
                <soap:body use="literal" namespace="https://www.ficohsa.com/regional/pension"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="https://www.ficohsa.com/regional/pension"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../Schemas/FPCWithdrawalConsultationTypes.xsd" namespace="https://www.ficohsa.com/regional/pension" ref="SBRG_Pension_FPCWithdrawalConsultation/Schemas/FPCWithdrawalConsultationTypes"/>
    </con:dependencies>
    <con:targetNamespace>https://www.ficohsa.com/regional/pension</con:targetNamespace>
</con:wsdlEntry>