<wsdl:definitions targetNamespace="http://www.ficohsa.com.hn/middleware.services/solicitudTarjetaDebitoRelieve/" name="solicitudTarjetaDebitoRelievePS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/solicitudTarjetaDebitoRelieve/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:sol="http://www.ficohsa.com.hn/middleware.services/solicitudTarjetaDebitoRelieveTypes">
  
  <wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/solicitudTarjetaDebitoRelieveTypes" schemaLocation="../xsd/solicitudTarjetaDebitoRelieveTypes.xsd"/>
		</xsd:schema>
   </wsdl:types>
   
   <wsdl:message name="solicitudTarjetaDebitoRelieveRequest">
		<wsdl:part element="sol:solicitudTarjetaDebitoRelieve" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="solicitudTarjetaDebitoRelieveResponse">
		<wsdl:part element="sol:solicitudTarjetaDebitoRelieveResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="solicitudTarjetaDebitoRelievePS">
		<wsdl:operation name="solicitudTarjetaDebitoRelieve" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:solicitudTarjetaDebitoRelieveRequest"/>
			<wsdl:output message="fic:solicitudTarjetaDebitoRelieveResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="solicitudTarjetaDebitoRelievePSSOAP" type="fic:solicitudTarjetaDebitoRelievePS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="solicitudTarjetaDebitoRelieve">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/solicitudTarjetaDebitoRelievePS/solicitudTarjetaDebitoRelieve"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:solicitudTarjetaDebitoRelieveRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:solicitudTarjetaDebitoRelieveResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
   
   <wsdl:service name="solicitudTarjetaDebitoRelievePS">
		<wsdl:port binding="fic:solicitudTarjetaDebitoRelievePSSOAP" name="solicitudTarjetaDebitoRelievePSSOAP">
	  		<soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/CustomerDeposits/solicitudTarjetaDebitoRelieve"/>
	   	</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>