<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate3/CreditCardProcessor/PaymentRecordCreditCard" name="PaymentRecordCreditCard-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="PaymentRecordCreditCard.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate3/CreditCardProcessor/PaymentRecordCreditCard"/>
    <wsdl:binding name="PaymentRecordCreditCard_ptt-binding" type="pay:PaymentRecordCreditCard_ptt" xmlns:pay="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate3/CreditCardProcessor/PaymentRecordCreditCard">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="PaymentRecordCreditCard">
            <soap:operation soapAction="PaymentRecordCreditCard"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>