<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Prueba/Despignoraciones_OPI" name="Despignoraciones_OPI-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Prueba/Despignoraciones_OPI" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Prueba/Despignoraciones_OPI" location="Despignoraciones_OPI.wsdl"/>
  <binding name="Despignoraciones_OPI_ptt-binding" type="tns:Despignoraciones_OPI_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="Despignoraciones_OPI">
      <soap:operation soapAction="Despignoraciones_OPI"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="Despignoraciones_OPI-service">
    <port name="Despignoraciones_OPI-port" binding="tns:Despignoraciones_OPI_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>