<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/PAGO_RETIRO_FPC/PAGO_RETIRO_FPC" name="PAGO_RETIRO_FPC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/PAGO_RETIRO_FPC/PAGO_RETIRO_FPC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/PAGO_RETIRO_FPC/PAGO_RETIRO_FPC" location="PAGO_RETIRO_FPC.wsdl"/>
  <binding name="PAGO_RETIRO_FPC_ptt-binding" type="tns:PAGO_RETIRO_FPC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="PAGO_RETIRO_FPC">
      <soap:operation soapAction="PAGO_RETIRO_FPC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="PAGO_RETIRO_FPC-service">
    <port name="PAGO_RETIRO_FPC-port" binding="tns:PAGO_RETIRO_FPC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionFicopen"/>
    </port>
  </service>
</definitions>