<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate2/CreditCardProcessor/GetCreditCardDetails_V2" name="GetCreditCardDetails_V2-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GetCreditCardDetails_V2.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate2/CreditCardProcessor/GetCreditCardDetails_V2"/>
    <wsdl:binding name="GetCreditCardDetails_V2_ptt-binding" type="get:GetCreditCardDetails_V2_ptt" xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate2/CreditCardProcessor/GetCreditCardDetails_V2">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="GetCreditCardDetails_V2">
            <soap:operation soapAction="GetCreditCardDetails_V2"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>