<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationTest/INTEGRACION_CONSULTA_TRX_TARJETAS/integracionConsultaTrxTarjetas" name="integracionConsultaTrxTarjetas-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationTest/INTEGRACION_CONSULTA_TRX_TARJETAS/integracionConsultaTrxTarjetas" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationTest/INTEGRACION_CONSULTA_TRX_TARJETAS/integracionConsultaTrxTarjetas" location="integracionConsultaTrxTarjetas.wsdl"/>
  <binding name="integracionConsultaTrxTarjetas_ptt-binding" type="tns:integracionConsultaTrxTarjetas_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="integracionConsultaTrxTarjetas">
      <soap:operation soapAction="integracionConsultaTrxTarjetas"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="integracionConsultaTrxTarjetas-service">
    <port name="integracionConsultaTrxTarjetas-port" binding="tns:integracionConsultaTrxTarjetas_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionCustomerCreditRisk"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="integracionConsultaTrxTarjetas.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationTest/INTEGRACION_CONSULTA_TRX_TARJETAS/integracionConsultaTrxTarjetas">
            <con:wsdl ref="Middleware/v2/BusinessServices/DWConsultaConsolidada/integracionConsultaTrxTarjetas/wsdl/integracionConsultaTrxTarjetas"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationTest/INTEGRACION_CONSULTA_TRX_TARJETAS/integracionConsultaTrxTarjetas</con:targetNamespace>
</con:wsdlEntry>