<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MigrationDynamo/PensionFunds/GetCustomerProducts_BS" name="GetCustomerProducts_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GetCustomerProducts_BS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MigrationDynamo/PensionFunds/GetCustomerProducts_BS"/>
    <wsdl:binding name="GetCustomerProducts_BS_ptt-binding" type="get:GetCustomerProducts_BS_ptt" xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/MigrationDynamo/PensionFunds/GetCustomerProducts_BS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="GetCustomerProducts_BS">
            <soap:operation soapAction="GetCustomerProducts_BS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>