<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/HN/registraTargetTipoPrestamo/registraTargetTipoPrestamo" name="registraTargetTipoPrestamo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/HN/registraTargetTipoPrestamo/registraTargetTipoPrestamo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/HN/registraTargetTipoPrestamo/registraTargetTipoPrestamo" location="registraTargetTipoPrestamo.wsdl"/>
  <binding name="registraTargetTipoPrestamo_ptt-binding" type="tns:registraTargetTipoPrestamo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registraTargetTipoPrestamo">
      <soap:operation soapAction="registraTargetTipoPrestamo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registraTargetTipoPrestamo-service">
    <port name="registraTargetTipoPrestamo-port" binding="tns:registraTargetTipoPrestamo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionDLC"/>
    </port>
  </service>
</definitions>