<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/TransformarReciboRecaudo/transformarReciboRecaudo" name="transformarReciboRecaudo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/TransformarReciboRecaudo/transformarReciboRecaudo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/TransformarReciboRecaudo/transformarReciboRecaudo" location="transformarReciboRecaudo.wsdl"/>
  <binding name="transformarReciboRecaudo_ptt-binding" type="tns:transformarReciboRecaudo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="transformarReciboRecaudo">
      <soap:operation soapAction="transformarReciboRecaudo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="transformarReciboRecaudo-service">
    <port name="transformarReciboRecaudo-port" binding="tns:transformarReciboRecaudo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>