<wsdl:definitions name="eliminarDeudoresDepRefPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/eliminarDeudoresDepRefPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/eliminarDeudoresDepRefPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/depositosReferenciadosTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/depositosReferenciadosTypes" schemaLocation="../../DepositosReferenciados/xsd/depositosReferenciadosTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="eliminarDeudoresRequest">
		<wsdl:part element="cons:eliminarDeudores" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="eliminarDeudoresResponse">
		<wsdl:part element="cons:eliminarDeudoresResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="eliminarDeudoresDepRefPS">
		<wsdl:operation name="eliminarDeudores" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:eliminarDeudoresRequest"/>
			<wsdl:output message="fic:eliminarDeudoresResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="eliminarDeudoresDepRefPSSOAP" type="fic:eliminarDeudoresDepRefPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="eliminarDeudores">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/eliminarDeudoresDepRefPS/eliminarDeudores"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:eliminarDeudoresRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:eliminarDeudoresResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="eliminarDeudoresDepRefPS">
		<wsdl:port binding="fic:eliminarDeudoresDepRefPSSOAP" name="eliminarDeudoresDepRefPSSOAP">
			<soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/BusinessPartner/eliminarDeudoresDepRef"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>