<?binding.jca creaPrestamo_db.jca?><wsdl:definitions name="creaPrestamo" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/creaPrestamo/creaPrestamo" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/creaPrestamo" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/creaPrestamo/creaPrestamo" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="creaPrestamo_plt">
        <plt:role name="creaPrestamo_role">
            <plt:portType name="tns:creaPrestamo_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/creaPrestamo" schemaLocation="../xsd/creaPrestamo_sp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="creaPrestamo_ptt">
        <wsdl:operation name="creaPrestamo">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>