<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultaReorden/consultaReorden" name="consultaReorden-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultaReorden/consultaReorden" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultaReorden/consultaReorden" location="consultaReorden.wsdl"/>
  <binding name="consultaReorden_ptt-binding" type="tns:consultaReorden_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaReorden">
      <soap:operation soapAction="consultaReorden"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaReorden-service">
    <port name="consultaReorden-port" binding="tns:consultaReorden_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionDebitCard"/>
    </port>
  </service>
</definitions>