<wsdl:definitions name="consultaCuentaRetiroEfectivoPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaCuentaRetiroEfectivoPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaCuentaRetiroEfectivoPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaCuentaRetiroEfectivoCBTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElementsCB.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaCuentaRetiroEfectivoCBTypes" schemaLocation="../xsd/consultaCuentaRetiroEfectivoCBTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaCuentaRetiroEfectivoRequest">
		<wsdl:part element="cons:consultaCuentaRetiroEfectivo" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaCuentaRetiroEfectivoResponse">
		<wsdl:part element="cons:consultaCuentaRetiroEfectivoResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaCuentaRetiroEfectivoPS">
		<wsdl:operation name="consultaCuentaRetiroEfectivo" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaCuentaRetiroEfectivoRequest"/>
			<wsdl:output message="fic:consultaCuentaRetiroEfectivoResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaCuentaRetiroEfectivoPSSOAP" type="fic:consultaCuentaRetiroEfectivoPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaCuentaRetiroEfectivo">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaCuentaRetiroEfectivoPS/consultaCuentaRetiroEfectivo"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaCuentaRetiroEfectivoRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaCuentaRetiroEfectivoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaCuentaRetiroEfectivoPS">
		<wsdl:port binding="fic:consultaCuentaRetiroEfectivoPSSOAP" name="consultaCuentaRetiroEfectivoPSSOAP">
			<soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/CustomerDeposits/consultaCuentaRetiroEfectivoCB"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>