<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/eCisRequestControl/eCisRequestControl" name="eCisRequestControl-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/eCisRequestControl/eCisRequestControl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/eCisRequestControl/eCisRequestControl" location="eCisRequestControl.wsdl"/>
  <binding name="eCisRequestControl_ptt-binding" type="tns:eCisRequestControl_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="eCisRequestControl">
      <soap:operation soapAction="eCisRequestControl"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="eCisRequestControl-service">
    <port name="eCisRequestControl-port" binding="tns:eCisRequestControl_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProcesosHN"/>
    </port>
  </service>
</definitions>