<wsdl:definitions name="generaURLPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/generaURLPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:gen="http://www.ficohsa.com.hn/middleware.services/generaURLPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/generaURLTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/generaURLTypes" schemaLocation="../xsd/generaURLTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestHeader">
        <wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
    </wsdl:message>
    <wsdl:message name="responseHeader">
        <wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
    </wsdl:message>
    <wsdl:message name="generaURL">
        <wsdl:part element="tns:generaURL" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="generaURLResponse">
        <wsdl:part element="tns:generaURLResponse" name="result"/>
    </wsdl:message>
    <wsdl:portType name="generaURLPS">
        <wsdl:operation name="generaURL" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="gen:generaURL"/>
            <wsdl:output message="gen:generaURLResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="generaURLPSSOAP" type="gen:generaURLPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="generaURL">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/generaURLPS/generaURL"/>
            <wsdl:input>
                <soap:body parts="parameters" use="literal"/>
                <soap:header message="gen:requestHeader" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body parts="result" use="literal"/>
                <soap:header message="gen:responseHeader" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="generaURLPS">
        <wsdl:port binding="gen:generaURLPSSOAP" name="generaURLPSSOAP">
            <soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Cards/actualizacionClienteTarjetaCredito"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
