<wsdl:definitions name="obtieneEstadoSistemaPS"
	targetNamespace="http://www.ficohsa.com.hn/middleware.services/obtieneEstadoSistemaPS/"
	xmlns:fic="http://www.ficohsa.com.hn/middleware.services/obtieneEstadoSistemaPS/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType"
	xmlns:gen="http://www.ficohsa.com.hn/middleware.services/digitalizacionTarjetasTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType"
				schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import
				namespace="http://www.ficohsa.com.hn/middleware.services/digitalizacionTarjetasTypes"
				schemaLocation="../../DigitalizacionTarjetas/xsd/digitalizacionTarjetasTypes.xsd" />
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="obtieneEstadoSistema">
		<wsdl:part element="gen:obtieneEstadoSistema" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader" />
	</wsdl:message>
	
	<wsdl:message name="obtieneEstadoSistemaResponse">
		<wsdl:part element="gen:obtieneEstadoSistemaResponse"
			name="result" />
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader" />
	</wsdl:message>

	<wsdl:portType name="obtieneEstadoSistemaPS">
		<wsdl:operation name="obtieneEstadoSistema"
			parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:obtieneEstadoSistema" />
			<wsdl:output message="fic:obtieneEstadoSistemaResponse" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="obtieneEstadoSistemaPSSOAP" type="fic:obtieneEstadoSistemaPS">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="obtieneEstadoSistema">
			<soap:operation
				soapAction="http://www.ficohsa.com.hn/middleware.services/obtieneEstadoSistemaPS" />
			<wsdl:input>
				<soap:body use="literal" parts="parameters" />
				<soap:header message="fic:obtieneEstadoSistema"
					part="RequestHeader" use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result" />
				<soap:header message="fic:obtieneEstadoSistemaResponse"
					part="ResponseHeader" use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="obtieneEstadoSistemaPS">
		<wsdl:port binding="fic:obtieneEstadoSistemaPSSOAP"
			name="obtieneEstadoSistemaPSSOAP">
			<soap:address
				location="http://10.9.104.55:8003/Middleware/OperationsAndExecution/Messaging/obtieneEstadoSistema" />
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>