<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SalesforceGestionesMonetarias/InterfazSFC/validaNumeroViajero" name="validaNumeroViajero-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SalesforceGestionesMonetarias/InterfazSFC/validaNumeroViajero" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SalesforceGestionesMonetarias/InterfazSFC/validaNumeroViajero" location="validaNumeroViajero.wsdl"/>
  <binding name="validaNumeroViajero_ptt-binding" type="tns:validaNumeroViajero_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="validaNumeroViajero">
      <soap:operation soapAction="validaNumeroViajero"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="validaNumeroViajero-service">
    <port name="validaNumeroViajero-port" binding="tns:validaNumeroViajero_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterfazSFC"/>
    </port>
  </service>
</definitions>