<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DepositoReferenciados/MasterDataPA/conDatoCliente" name="conDatoCliente-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DepositoReferenciados/MasterDataPA/conDatoCliente" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DepositoReferenciados/MasterDataPA/conDatoCliente" location="conDatoCliente.wsdl"/>
  <binding name="conDatoCliente_ptt-binding" type="tns:conDatoCliente_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conDatoCliente">
      <soap:operation soapAction="conDatoCliente"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conDatoCliente-service">
    <port name="conDatoCliente-port" binding="tns:conDatoCliente_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>