<wsdl:definitions name="UpdateCustomerPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/UpdateCustomerPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/UpdateCustomerPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:upd="http://www.ficohsa.com.hn/middleware.services/UpdateCustomerTypes" xmlns:aut="http://www.ficohsa.com.hn/middleware.services/autType">

<wsdl:types>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/UpdateCustomerTypes" schemaLocation="../xsd/UpdateCustomerTypes.xsd"/>
	</xsd:schema>
</wsdl:types>

<wsdl:message name="UpdateCustomerPSRequest">
	<wsdl:part name="reqHeader" element="aut:RequestHeader"/>
	<wsdl:part name="inputParameters" element="upd:UpdateCustomerRequest"/>
</wsdl:message>

<wsdl:message name="UpdateCustomerPSResponse">
	<wsdl:part name="rspHeader" element="aut:ResponseHeader"/>
	<wsdl:part name="outputResult" element="upd:UpdateCustomerResponse"/>
</wsdl:message>

<wsdl:portType name="UpdateCustomerPS">
	<wsdl:operation name="UpdateCustomer">
		<wsdl:input message="fic:UpdateCustomerPSRequest"/>		
		<wsdl:output message="fic:UpdateCustomerPSResponse"/>
	</wsdl:operation>
</wsdl:portType>

<wsdl:binding name="UpdateCustomerPSSOAP" type="fic:UpdateCustomerPS">
	<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>	
	<wsdl:operation name="UpdateCustomer">
		<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/UpdateCustomerPS/UpdateCustomer"/>
		<wsdl:input>
			<soap:header use="literal" part="reqHeader" message="fic:UpdateCustomerPSRequest"/>
			<soap:body use="literal" parts="inputParameters"/>
		</wsdl:input>				
		<wsdl:output>
			<soap:header use="literal" part="rspHeader" message="fic:UpdateCustomerPSResponse"/>
			<soap:body use="literal" parts="outputResult"/>
		</wsdl:output>
	</wsdl:operation>
</wsdl:binding>

<wsdl:service name="UpdateCustomerPS">
	<wsdl:port name="UpdateCustomerPSSOAP" binding="fic:UpdateCustomerPSSOAP">
		<soap:address location="http://10.9.104.55:8003/Middleware/SalesAndServices/CustomerManagement/UpdateCustomer"/>
	</wsdl:port>
</wsdl:service>

</wsdl:definitions>