<?binding.jca T24UpdateGRPDB_db.jca?><wsdl:definitions name="T24UpdateGRPDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/T24UpdateGRPDB/T24UpdateGRPDB/T24UpdateGRPDB" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/T24UpdateGRPDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/T24UpdateGRPDB/T24UpdateGRPDB/T24UpdateGRPDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="T24UpdateGRPDB_plt">
        <plt:role name="T24UpdateGRPDB_role">
            <plt:portType name="tns:T24UpdateGRPDB_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/T24UpdateGRPDB" schemaLocation="../xsd/T24UpdateGRPDB_sp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="T24UpdateGRPDB_ptt">
        <wsdl:operation name="T24UpdateGRPDB">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>