<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/T24UpdateGRPDB/T24UpdateGRPDB/T24UpdateGRPDB" name="T24UpdateGRPDB-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/T24UpdateGRPDB/T24UpdateGRPDB/T24UpdateGRPDB" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/T24UpdateGRPDB/T24UpdateGRPDB/T24UpdateGRPDB" location="T24UpdateGRPDB.wsdl"/>
  <binding name="T24UpdateGRPDB_ptt-binding" type="tns:T24UpdateGRPDB_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="T24UpdateGRPDB">
      <soap:operation soapAction="T24UpdateGRPDB"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="T24UpdateGRPDB-service">
    <port name="T24UpdateGRPDB-port" binding="tns:T24UpdateGRPDB_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>