<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/ConsultaCertificadoDeposito/ConsultaCertificadoDeposito" name="ConsultaCertificadoDeposito-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/ConsultaCertificadoDeposito/ConsultaCertificadoDeposito" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/ConsultaCertificadoDeposito/ConsultaCertificadoDeposito" location="ConsultaCertificadoDeposito.wsdl"/>
  <binding name="ConsultaCertificadoDeposito_ptt-binding" type="tns:ConsultaCertificadoDeposito_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ConsultaCertificadoDeposito">
      <soap:operation soapAction="ConsultaCertificadoDeposito"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ConsultaCertificadoDeposito-service">
    <port name="ConsultaCertificadoDeposito-port" binding="tns:ConsultaCertificadoDeposito_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>