<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MDA-55558/LIMITES_TRANSACCIONALES/limiteTrxRegistrar" name="limiteTrxRegistrar-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MDA-55558/LIMITES_TRANSACCIONALES/limiteTrxRegistrar" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MDA-55558/LIMITES_TRANSACCIONALES/limiteTrxRegistrar" location="limiteTrxRegistrar.wsdl"/>
  <binding name="limiteTrxRegistrar_ptt-binding" type="tns:limiteTrxRegistrar_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="limiteTrxRegistrar">
      <soap:operation soapAction="limiteTrxRegistrar"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="limiteTrxRegistrar-service">
    <port name="limiteTrxRegistrar-port" binding="tns:limiteTrxRegistrar_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>