<wsdl:definitions name="consultaImagenFirmasPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaImagenFirmasPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaImagenFirmasPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaImagenFirmasTypes">

	<wsdl:types>
    	<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaImagenFirmasTypes" schemaLocation="consultaImagenFirmasTypes.xsd"/>
		</xsd:schema>
  	</wsdl:types>
  	
  	<wsdl:message name="consultaImagenFirmasRequest">
		<wsdl:part element="cons:consultaImagenFirmas" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaImagenFirmasResponse">
		<wsdl:part element="cons:consultaImagenFirmasResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="consultaImagenFirmasPS">
		<wsdl:operation name="consultaImagenFirmas" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaImagenFirmasRequest"/>
			<wsdl:output message="fic:consultaImagenFirmasResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaImagenFirmasPSSOAP" type="fic:consultaImagenFirmasPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaImagenFirmas">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaImagenFirmasPS/consultaImagenFirmas"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaImagenFirmasRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaImagenFirmasResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="consultaImagenFirmasPS">
    	<wsdl:port binding="fic:consultaImagenFirmasPSSOAP" name="consultaImagenFirmasPSSOAP">
    	  <soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/Payments/ConsultaImagenFirmas"/>
    	</wsdl:port>
  	</wsdl:service>

</wsdl:definitions>