<?xml version="1.0" encoding="UTF-8"?>
<con:xqueryEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:xquery><![CDATA[xquery version "2004-draft";
<routing>
   <rule>
      <key>HN01</key>
      <serviceName>Middleware/v3/ProxyServices/PagoTarjetaCredito/local/PagoTarjetaCreditoHN</serviceName>
   </rule>
   <rule>
      <key>GT01</key>
      <serviceName>Middleware/v3/ProxyServices/PagoTarjetaCredito/local/PagoTarjetaCreditoGT</serviceName>
   </rule>
   <rule>
      <key>NI01</key>
      <serviceName>Middleware/v3/ProxyServices/PagoTarjetaCredito/local/PagoTarjetaCreditoNI</serviceName>
   </rule>
   <rule>
      <key>PA01</key>
      <serviceName>Middleware/v3/ProxyServices/PagoTarjetaCredito/local/PagoTarjetaCreditoPA</serviceName>
   </rule>
</routing>]]></con:xquery>
</con:xqueryEntry>