<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizaDatosGFF/MCPagoPolizaSeguro/MCPagoPolizaSeguro" name="MCPagoPolizaSeguro-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizaDatosGFF/MCPagoPolizaSeguro/MCPagoPolizaSeguro" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizaDatosGFF/MCPagoPolizaSeguro/MCPagoPolizaSeguro" location="MCPagoPolizaSeguro.wsdl"/>
  <binding name="MCPagoPolizaSeguro_ptt-binding" type="tns:MCPagoPolizaSeguro_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="MCPagoPolizaSeguro">
      <soap:operation soapAction="MCPagoPolizaSeguro"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="MCPagoPolizaSeguro-service">
    <port name="MCPagoPolizaSeguro-port" binding="tns:MCPagoPolizaSeguro_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>