<?binding.jca consultaSituacionFinanciera_db.jca?><wsdl:definitions name="consultaSituacionFinanciera" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaSituacionFinanciera/Project1/consultaSituacionFinanciera" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/consultaSituacionFinanciera" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaSituacionFinanciera/Project1/consultaSituacionFinanciera" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="consultaSituacionFinanciera_plt">
        <plt:role name="consultaSituacionFinanciera_role">
            <plt:portType name="tns:consultaSituacionFinanciera_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/consultaSituacionFinanciera" schemaLocation="../xsd/consultaSituacionFinanciera_sp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="consultaSituacionFinanciera_ptt">
        <wsdl:operation name="consultaSituacionFinanciera">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>