<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application/consultaProgramaLealtad/consultaProgramaLealtad" name="consultaProgramaLealtad-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application/consultaProgramaLealtad/consultaProgramaLealtad" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application/consultaProgramaLealtad/consultaProgramaLealtad" location="consultaProgramaLealtad.wsdl"/>
  <binding name="consultaProgramaLealtad_ptt-binding" type="tns:consultaProgramaLealtad_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaProgramaLealtad">
      <soap:operation soapAction="consultaProgramaLealtad"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaProgramaLealtad-service">
    <port name="consultaProgramaLealtad-port" binding="tns:consultaProgramaLealtad_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterfaz"/>
    </port>
  </service>
</definitions>