<wsdl:definitions 
	name="transferenciaCuentasRegionalPS" 
	targetNamespace="http://www.ficohsa.com.hn/middleware.services/transferenciaCuentasRegionalPS/"
	xmlns:fic="http://www.ficohsa.com.hn/middleware.services/transferenciaCuentasRegionalPS/" 
 	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
 	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:trans="http://www.ficohsa.com.hn/middleware.services/transferenciasType" 
 	xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" >
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/transferenciasType" schemaLocation="../../TransferenciaCuentas/xsd/transferenciaCuentasType.xsd"/>
		</xsd:schema>	
	</wsdl:types>
	
	<wsdl:message name="transferenciaCuentasRegionalRequest">
		<wsdl:part element="trans:transferenciaCuentasRequest" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="transferenciaCuentasRegionalResponse">
		<wsdl:part element="trans:transferenciaCuentasResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		<wsdl:portType name="transferenciaCuentasRegionalPS">
		<wsdl:operation name="transferenciaCuentasRegional" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:transferenciaCuentasRegionalRequest"/>
			<wsdl:output message="fic:transferenciaCuentasRegionalResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="transferenciaCuentasRegionalPSSOAP"	type="fic:transferenciaCuentasRegionalPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="transferenciaCuentasRegional">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/transferenciaCuentasPS/transferenciaCuentas"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:transferenciaCuentasRegionalRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:transferenciaCuentasRegionalResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="transferenciaCuentasRegionalPS">
		<wsdl:port binding="fic:transferenciaCuentasRegionalPSSOAP"	name="transferenciaCuentasRegionalPSSOAP">
			<soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/CustomerDeposits/TransferenciaCuentasRegional"/>
		</wsdl:port>
	</wsdl:service>
	
	
</wsdl:definitions>

