<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBGT_CARD/SBGT_Card_RollbackPurchase/DBActTicketAdapter" name="DBActTicketAdapter-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="DBActTicketAdapter.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBGT_CARD/SBGT_Card_RollbackPurchase/DBActTicketAdapter"/>
    <wsdl:binding name="DBActTicketAdapter_ptt-binding" type="dbac:DBActTicketAdapter_ptt" xmlns:dbac="http://xmlns.oracle.com/pcbpel/adapter/db/SBGT_CARD/SBGT_Card_RollbackPurchase/DBActTicketAdapter">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DBActTicketAdapter">
            <soap:operation soapAction="DBActTicketAdapter"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>