<wsdl:definitions name="RollbackPurchase" targetNamespace="https://www.ficohsa.com/guatemala/card" xmlns:tns="https://www.ficohsa.com/guatemala/card" xmlns:inp1="https://www.ficohsa.com/regional/card" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="https://www.ficohsa.com/regional/card" 
            schemaLocation="../Schemas/RollbackPurchaseTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="rollbackPurchase" element="inp1:getStatusTicket"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="rollbackPurchaseResponse" element="inp1:getStatusTicketResponse"/>
    </wsdl:message>
    <wsdl:portType name="rollbackPurchasePtt">
        <wsdl:operation name="rollbackPurchase">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="rollbackPurchaseBind" type="tns:rollbackPurchasePtt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="rollbackPurchase">
            <soap:operation style="document" soapAction="rollbackPurchase"/>
            <wsdl:input>
                <soap:body use="literal" namespace="https://www.ficohsa.com/guatemala/card"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="https://www.ficohsa.com/guatemala/card"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>