<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingGT/UpdateCustomer_BS" name="UpdateCustomer_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="UpdateCustomer_BS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingGT/UpdateCustomer_BS"/>
    <wsdl:binding name="UpdateCustomer_BS_ptt-binding" type="upd:UpdateCustomer_BS_ptt" xmlns:upd="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingGT/UpdateCustomer_BS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="UpdateCustomer_BS">
            <soap:operation soapAction="UpdateCustomer_BS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>