<WL5G3N0:definitions name="consultaHistoricoAutorizacionesPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaHistoricoAutorizacionesPS/" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://www.ficohsa.com.hn/middleware.services/consultaHistoricoAutorizacionesTypes" xmlns:WL5G3N2="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:WL5G3N3="http://www.ficohsa.com.hn/middleware.services/consultaHistoricoAutorizacionesPS/" xmlns:WL5G3N4="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:con="http://www.ficohsa.com.hn/middleware.services/consultaHistoricoAutorizacionesPS/" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaHistoricoAutorizacionesTypes" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsd/XMLSchema_-1024141718.xsd"/>
    </xsd:schema>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:con="http://www.ficohsa.com.hn/middleware.services/consultaHistoricoAutorizacionesPS/" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaHistoricoAutorizacionesTypes" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaHistoricoAutorizacionesTypes" schemaLocation="../xsd/XMLSchema_-1732058956.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="consultaHistoricoAutorizacionesRequest">
    <WL5G3N0:part element="WL5G3N1:consultaHistoricoAutorizacionesRequest" name="parameters"/>
    <WL5G3N0:part element="WL5G3N2:RequestHeader" name="RequestHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="consultaHistoricoAutorizacionesResponse">
    <WL5G3N0:part element="WL5G3N1:consultaHistoricoAutorizacionesResponse" name="result"/>
    <WL5G3N0:part element="WL5G3N2:ResponseHeader" name="ResponseHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="consultaHistoricoAutorizacionesPS">
    <WL5G3N0:operation name="consultaHistoricoAutorizaciones" parameterOrder="parameters RequestHeader ResponseHeader">
      <WL5G3N0:input message="WL5G3N3:consultaHistoricoAutorizacionesRequest"/>
      <WL5G3N0:output message="WL5G3N3:consultaHistoricoAutorizacionesResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="consultaHistoricoAutorizacionesPSSOAP" type="WL5G3N3:consultaHistoricoAutorizacionesPS">
    <WL5G3N4:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="consultaHistoricoAutorizaciones">
      <WL5G3N4:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaHistoricoAutorizacionesPS"/>
      <WL5G3N0:input>
        <WL5G3N4:header message="WL5G3N3:consultaHistoricoAutorizacionesRequest" part="RequestHeader" use="literal"/>
        <WL5G3N4:body parts="parameters" use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N4:header message="WL5G3N3:consultaHistoricoAutorizacionesResponse" part="ResponseHeader" use="literal"/>
        <WL5G3N4:body parts="result" use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="consultaHistoricoAutorizacionesPS">
    <WL5G3N0:port binding="WL5G3N3:consultaHistoricoAutorizacionesPSSOAP" name="consultaHistoricoAutorizacionesPSSOAP">
      <WL5G3N4:address location="https://172.23.13.19:8004/Middleware/OperationsAndExecution/Cards/ConsultaHistoricoAutorizaciones"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>