<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultaFICOPEN/consultaFICOPEN" name="consultaFICOPEN-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultaFICOPEN/consultaFICOPEN" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultaFICOPEN/consultaFICOPEN" location="ConsultaFICOPEN/consultaFICOPEN.wsdl"/>
  <binding name="consultaFICOPEN_ptt-binding" type="tns:consultaFICOPEN_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaFICOPEN">
      <soap:operation soapAction="consultaFICOPEN"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaFICOPEN-service">
    <port name="consultaFICOPEN-port" binding="tns:consultaFICOPEN_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionFicopen"/>
    </port>
  </service>
</definitions>