<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DepositoReferenciados/ConTransacciones/conTransaccionesHistorica" name="conTransaccionesHistorica-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DepositoReferenciados/ConTransacciones/conTransaccionesHistorica" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DepositoReferenciados/ConTransacciones/conTransaccionesHistorica" location="conTransaccionesHistoricas.wsdl"/>
  <binding name="conTransaccionesHistorica_ptt-binding" type="tns:conTransaccionesHistorica_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conTransaccionesHistorica">
      <soap:operation soapAction="conTransaccionesHistorica"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conTransaccionesHistorica-service">
    <port name="conTransaccionesHistorica-port" binding="tns:conTransaccionesHistorica_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProcesosGT"/>
    </port>
  </service>
</definitions>