<wsdl:definitions name="consultaTasaCambioPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaTasaCambioPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaTasaCambioPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaTasaCambioTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaTasaCambioTypes" schemaLocation="consultaTasaCambioTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="consultaTasaCambioRequest">
		<wsdl:part element="cons:consultaTasaCambio" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaTasaCambioResponse">
		<wsdl:part element="cons:consultaTasaCambioResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="consultaTasaCambioPS">
		<wsdl:operation name="consultaTasaCambio" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaTasaCambioRequest"/>
			<wsdl:output message="fic:consultaTasaCambioResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaTasaCambioPSSOAP" type="fic:consultaTasaCambioPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaTasaCambio">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaTasaCambioPS/consultaTasaCambio"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaTasaCambioRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaTasaCambioResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="consultaTasaCambioPS">
    <wsdl:port binding="fic:consultaTasaCambioPSSOAP" name="consultaTasaCambioPSSOAP">
      <soap:address location="http://mwomnicanal:8003/Middleware/ReferenceData/CommonBusinessInformation/ConsultaTasaCambio"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>