<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultaDataRenap/consultaDataRenap" name="consultaDataRenap-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultaDataRenap/consultaDataRenap" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultaDataRenap/consultaDataRenap" location="consultaDataRenap.wsdl"/>
  <binding name="consultaDataRenap_ptt-binding" type="tns:consultaDataRenap_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaDataRenap">
      <soap:operation soapAction="consultaDataRenap"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaDataRenap-service">
    <port name="consultaDataRenap-port" binding="tns:consultaDataRenap_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionRENAP"/>
    </port>
  </service>
</definitions>