<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/TSPBITMASIVOS/registraBitacoraTSPMasivos" name="registraBitacoraTSPMasivos-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/TSPBITMASIVOS/registraBitacoraTSPMasivos" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/TSPBITMASIVOS/registraBitacoraTSPMasivos" location="registraBitacoraTSPMasivos.wsdl"/>
  <binding name="registraBitacoraTSPMasivos_ptt-binding" type="tns:registraBitacoraTSPMasivos_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registraBitacoraTSPMasivos">
      <soap:operation soapAction="registraBitacoraTSPMasivos"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registraBitacoraTSPMasivos-service">
    <port name="registraBitacoraTSPMasivos-port" binding="tns:registraBitacoraTSPMasivos_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterfazdb"/>
    </port>
  </service>
</definitions>