<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultaReciboPrestamo/consultaReciboPrestamo" name="consultaReciboPrestamo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultaReciboPrestamo/consultaReciboPrestamo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/InterbancaSOAApplication/ConsultaReciboPrestamo/consultaReciboPrestamo" location="consultaReciboPrestamo.wsdl"/>
  <binding name="consultaReciboPrestamo_ptt-binding" type="tns:consultaReciboPrestamo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaReciboPrestamo">
      <soap:operation soapAction="consultaReciboPrestamo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaReciboPrestamo-service">
    <port name="consultaReciboPrestamo-port" binding="tns:consultaReciboPrestamo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksPA"/>
    </port>
  </service>
</definitions>