<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/PagoPrestamo/PagoPrestamo" name="PagoPrestamo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/PagoPrestamo/PagoPrestamo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/PagoPrestamo/PagoPrestamo" location="PagoPrestamo.wsdl"/>
  <binding name="PagoPrestamo_ptt-binding" type="tns:PagoPrestamo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="PagoPrestamo">
      <soap:operation soapAction="PagoPrestamo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="PagoPrestamo-service">
    <port name="PagoPrestamo-port" binding="tns:PagoPrestamo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>