<wsdl:definitions name="SrvAplCobisTarjetaDebito" targetNamespace="http://impl.service.srvaplcobistarjetadebito.ecobis.cobiscorp/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://service.srvaplcobistarjetadebito.ecobis.cobiscorp" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:S1="http://impl.service.srvaplcobistarjetadebito.ecobis.cobiscorp/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://impl.service.srvaplcobistarjetadebito.ecobis.cobiscorp/">
      <xsd:import namespace="http://service.srvaplcobistarjetadebito.ecobis.cobiscorp" schemaLocation="../xsd/services.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="MsjOpConsultaTarjetaDebitoRespuesta">
    <wsdl:part name="parameters" element="tns:opConsultaTarjetaDebitoRespuesta"/>
  </wsdl:message>
  <wsdl:message name="MsjOpConsultaTarjetaDebitoSolicitud">
    <wsdl:part name="parameters" element="tns:opConsultaTarjetaDebitoSolicitud"/>
  </wsdl:message>
  <wsdl:portType name="SrvAplCobisTarjetaDebito">
    <wsdl:operation name="OpConsultaTarjetaDebito">
      <wsdl:input message="S1:MsjOpConsultaTarjetaDebitoSolicitud"/>
      <wsdl:output message="S1:MsjOpConsultaTarjetaDebitoRespuesta"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SrvAplCobisTarjetaDebitoBindingSOAP12" type="S1:SrvAplCobisTarjetaDebito">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="OpConsultaTarjetaDebito">
      <soap12:operation/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SrvAplCobisTarjetaDebitoService">
    <wsdl:port name="SrvAplCobisTarjetaDebitoBindingSOAP12" binding="S1:SrvAplCobisTarjetaDebitoBindingSOAP12">
      <soap12:address location="http://10.235.53.145:9080/GerenciaTarjetaDebito/SrvAplCobisTarjetaDebitoService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>