<wsdl:definitions name="SrvAplCobisTransacciones" targetNamespace="http://impl.service.srvaplcobistransacciones.ecobis.cobiscorp/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://service.srvaplcobistransacciones.ecobis.cobiscorp" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:S1="http://impl.service.srvaplcobistransacciones.ecobis.cobiscorp/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://impl.service.srvaplcobistransacciones.ecobis.cobiscorp/"><xsd:import namespace="http://service.srvaplcobistransacciones.ecobis.cobiscorp" schemaLocation="../xsd/services.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:message name="MsjOpConsultarDetalleTransaccionRespuesta">
    <wsdl:part name="parameters" element="tns:opConsultarDetalleTransaccionRespuesta">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="MsjOpConsultarDetalleTransaccionSolicitud">
    <wsdl:part name="parameters" element="tns:opConsultarDetalleTransaccionSolicitud">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="SrvAplCobisTransacciones">
    <wsdl:operation name="OpConsultarDetalleTransaccion">
      <wsdl:input message="S1:MsjOpConsultarDetalleTransaccionSolicitud">
    </wsdl:input>
      <wsdl:output message="S1:MsjOpConsultarDetalleTransaccionRespuesta">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SrvAplCobisTransaccionesBindingSOAP12" type="S1:SrvAplCobisTransacciones">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="OpConsultarDetalleTransaccion">
      <soap12:operation/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SrvAplCobisTransaccionesService">
    <wsdl:port name="SrvAplCobisTransaccionesBindingSOAP12" binding="S1:SrvAplCobisTransaccionesBindingSOAP12">
      <soap12:address location="http://10.235.53.145:9080/GerenciaProductoTransacciones/SrvAplCobisTransaccionesService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>