<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaRecaudoAbanks/consultaRecaudoAbanks" name="consultaRecaudoAbanks-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaRecaudoAbanks/consultaRecaudoAbanks" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaRecaudoAbanks/consultaRecaudoAbanks" location="consultaRecaudoAbanks.wsdl"/>
  <binding name="consultaRecaudoAbanks_ptt-binding" type="tns:consultaRecaudoAbanks_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaRecaudoAbanks">
      <soap:operation soapAction="consultaRecaudoAbanks"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaRecaudoAbanks-service">
    <port name="consultaRecaudoAbanks-port" binding="tns:consultaRecaudoAbanks_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>