<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaInformacionLaboralFPC/consultaInformacionLaboralFPC" name="consultaInformacionLaboralFPC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaInformacionLaboralFPC/consultaInformacionLaboralFPC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaInformacionLaboralFPC/consultaInformacionLaboralFPC" location="consultaInformacionLaboralFPC.wsdl"/>
  <binding name="consultaInformacionLaboralFPC_ptt-binding" type="tns:consultaInformacionLaboralFPC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaInformacionLaboralFPC">
      <soap:operation soapAction="consultaInformacionLaboralFPC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaInformacionLaboralFPC-service">
    <port name="consultaInformacionLaboralFPC-port" binding="tns:consultaInformacionLaboralFPC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionFicopen"/>
    </port>
  </service>
</definitions>