<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/actualizaCredencialesSalesforce" name="actualizaCredencialesSalesforce-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/actualizaCredencialesSalesforce" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/actualizaCredencialesSalesforce" location="actualizaCredencialesSalesforce.wsdl"/>
  <binding name="actualizaCredencialesSalesforce_ptt-binding" type="tns:actualizaCredencialesSalesforce_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="actualizaCredencialesSalesforce">
      <soap:operation soapAction="actualizaCredencialesSalesforce"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="actualizaCredencialesSalesforce-service">
    <port name="actualizaCredencialesSalesforce-port" binding="tns:actualizaCredencialesSalesforce_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>