<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/aperturaDescuentoDocumento/aperturaDescuentoDocumento" name="aperturaDescuentoDocumento-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/aperturaDescuentoDocumento/aperturaDescuentoDocumento" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/aperturaDescuentoDocumento/aperturaDescuentoDocumento" location="aperturaDescuentoDocumento.wsdl"/>
  <binding name="aperturaDescuentoDocumento_ptt-binding" type="tns:aperturaDescuentoDocumento_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="aperturaDescuentoDocumento">
      <soap:operation soapAction="aperturaDescuentoDocumento"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="aperturaDescuentoDocumento-service">
    <port name="aperturaDescuentoDocumento-port" binding="tns:aperturaDescuentoDocumento_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionAbanksHN"/>
    </port>
  </service>
</definitions>