<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/consultaSituacionFinanciera" name="consultaSituacionFinanciera-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/consultaSituacionFinanciera" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/consultaSituacionFinanciera" location="consultaSituacionFinanciera.wsdl"/>
  <binding name="consultaSituacionFinanciera_ptt-binding" type="tns:consultaSituacionFinanciera_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaSituacionFinanciera">
      <soap:operation soapAction="consultaSituacionFinanciera"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaSituacionFinanciera-service">
    <port name="consultaSituacionFinanciera-port" binding="tns:consultaSituacionFinanciera_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionAdquirVasa"/>
    </port>
  </service>
</definitions>