<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application/obtenerBlazeData/obtenerBlazeData" name="obtenerBlazeData-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application/obtenerBlazeData/obtenerBlazeData" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application/obtenerBlazeData/obtenerBlazeData" location="obtenerBlazeData.wsdl"/>
  <binding name="obtenerBlazeData_ptt-binding" type="tns:obtenerBlazeData_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="obtenerBlazeData">
      <soap:operation soapAction="obtenerBlazeData"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="obtenerBlazeData-service">
    <port name="obtenerBlazeData-port" binding="tns:obtenerBlazeData_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>