<wsdl:definitions name="consultaGuiaDePagoDEIPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaGuiaDePagoDEIPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaGuiaDePagoDEIPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/tributosTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/tributosTypes" schemaLocation="../../TributosDEI/xsd/tributosTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaGuiaDePagoRequest">
		<wsdl:part element="cons:consultaGuiaDePago" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaGuiaDePagoResponse">
		<wsdl:part element="cons:consultaGuiaDePagoResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaGuiaDePagoDEIPS">
		<wsdl:operation name="consultaGuiaDePago" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaGuiaDePagoRequest"/>
			<wsdl:output message="fic:consultaGuiaDePagoResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaGuiaDePagoDEIPSSOAP" type="fic:consultaGuiaDePagoDEIPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaGuiaDePago">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaGuiaDePagoDEIPS/consultaGuiaDePago"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaGuiaDePagoRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaGuiaDePagoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaGuiaDePagoDEIPS">
		<wsdl:port binding="fic:consultaGuiaDePagoDEIPSSOAP" name="consultaGuiaDePagoDEIPSSOAP">
			<soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/BusinessPartner/consultaGuiaDePago"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>