<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/cargarArchivoLote/cargarArchivoLote" name="cargarArchivoLote-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/cargarArchivoLote/cargarArchivoLote" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/cargarArchivoLote/cargarArchivoLote" location="cargarArchivoLote.wsdl"/>
  <binding name="cargarArchivoLote_ptt-binding" type="tns:cargarArchivoLote_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="cargarArchivoLote">
      <soap:operation soapAction="cargarArchivoLote"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="cargarArchivoLote-service">
    <port name="cargarArchivoLote-port" binding="tns:cargarArchivoLote_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>