<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/actualizaRelDesembolso/actualizaRelDesembolso" name="actualizaRelDesembolso-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/actualizaRelDesembolso/actualizaRelDesembolso" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/actualizaRelDesembolso/actualizaRelDesembolso" location="actualizaRelDesembolso.wsdl"/>
  <binding name="actualizaRelDesembolso_ptt-binding" type="tns:actualizaRelDesembolso_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="actualizaRelDesembolso">
      <soap:operation soapAction="actualizaRelDesembolso"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="actualizaRelDesembolso-service">
    <port name="actualizaRelDesembolso-port" binding="tns:actualizaRelDesembolso_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterfazdb"/>
    </port>
  </service>
</definitions>