<wsdl:definitions name="sjEvaluateAbanksAccount" targetNamespace="http://xmlns.oracle.com/sjEvaluateAbanksAccount" xmlns:tns="http://xmlns.oracle.com/sjEvaluateAbanksAccount" xmlns:inp1="http://www.ficohsa.com.hn/middleware.services/sjEvaluateAbanksAccountTypes" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plnk:partnerLinkType name="sjEvaluateAbanksAccount">
    <plnk:role name="sjEvaluateAbanksAccountProvider" portType="tns:sjEvaluateAbanksAccount_ptt"/>
  </plnk:partnerLinkType>
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjEvaluateAbanksAccountTypes" schemaLocation="../../../../../MWBanking/Accounts/RequestorServices/XSD/sjEvaluateAbanksAccountTypes.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="sjEvaluateAbanksAccountRequest">
    <wsdl:part name="inputParameters" element="inp1:sjEvaluateAbanksAccountRequest"/>
  </wsdl:message>
  <wsdl:message name="sjEvaluateAbanksAccountResponse">
    <wsdl:part name="outputParameters" element="inp1:sjEvaluateAbanksAccountResponse"/>
  </wsdl:message>
  <wsdl:portType name="sjEvaluateAbanksAccount_ptt">
    <wsdl:operation name="sjEvaluateAbanksAccount">
      <wsdl:input message="tns:sjEvaluateAbanksAccountRequest"/>
      <wsdl:output message="tns:sjEvaluateAbanksAccountResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="sjEvaluateAbanksAccount_ptt-binding" type="tns:sjEvaluateAbanksAccount_ptt">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sjEvaluateAbanksAccount">
      <soap:operation style="document" soapAction="sjEvaluateAbanksAccount"/>
      <wsdl:input>
        <soap:body use="literal" namespace="http://xmlns.oracle.com/sjEvaluateAbanksAccount" parts="inputParameters"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" namespace="http://xmlns.oracle.com/sjEvaluateAbanksAccount" parts="outputParameters"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>