<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/armarMensajeChqVir/ConsultaTransSinPreQualityGT/conTransaccionesSinPreQ" name="conTransaccionesSinPreQ-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/armarMensajeChqVir/ConsultaTransSinPreQualityGT/conTransaccionesSinPreQ" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/armarMensajeChqVir/ConsultaTransSinPreQualityGT/conTransaccionesSinPreQ" location="conTransaccionesSinPreQ.wsdl"/>
  <binding name="conTransaccionesSinPreQ_ptt-binding" type="tns:conTransaccionesSinPreQ_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conTransaccionesSinPreQ">
      <soap:operation soapAction="conTransaccionesSinPreQ"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conTransaccionesSinPreQ-service">
    <port name="conTransaccionesSinPreQ-port" binding="tns:conTransaccionesSinPreQ_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetasGT"/>
    </port>
  </service>
</definitions>