<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/consultaDatoCreditScore/consultaDatoCreditScore" name="consultaDatoCreditScore-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/consultaDatoCreditScore/consultaDatoCreditScore" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/consultaDatoCreditScore/consultaDatoCreditScore" location="consultaDatoCreditScore.wsdl"/>
  <binding name="consultaDatoCreditScore_ptt-binding" type="tns:consultaDatoCreditScore_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaDatoCreditScore">
      <soap:operation soapAction="consultaDatoCreditScore"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaDatoCreditScore-service">
    <port name="consultaDatoCreditScore-port" binding="tns:consultaDatoCreditScore_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="consultaDatoCreditScore.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/consultaDatoCreditScore/consultaDatoCreditScore">
            <con:wsdl ref="Middleware/v2/BusinessServices/PWS/consultaDatoCreditScore/wsdl/consultaDatoCreditScore"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/consultaDatoCreditScore/consultaDatoCreditScore</con:targetNamespace>
</con:wsdlEntry>