<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/ConsultaPasivosCliente/consultaPasivosCliente" name="consultaPasivosCliente-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/ConsultaPasivosCliente/consultaPasivosCliente" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/ConsultaPasivosCliente/consultaPasivosCliente" location="GetCustomerLiabilities_BS.wsdl"/>
  <binding name="consultaPasivosCliente_ptt-binding" type="tns:consultaPasivosCliente_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaPasivosCliente">
      <soap:operation soapAction="consultaPasivosCliente"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaPasivosCliente-service">
    <port name="consultaPasivosCliente-port" binding="tns:consultaPasivosCliente_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksPA"/>
    </port>
  </service>
</definitions>