<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/altaContrato/altaContrato" name="altaContrato-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/altaContrato/altaContrato" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/altaContrato/altaContrato" location="altaContrato.wsdl"/>
  <binding name="altaContrato_ptt-binding" type="tns:altaContrato_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="altaContrato">
      <soap:operation soapAction="altaContrato"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="altaContrato-service">
    <port name="altaContrato-port" binding="tns:altaContrato_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWorkflow"/>
    </port>
  </service>
</definitions>