<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/TransformCollectionReceipt" name="TransformCollectionReceipt-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="TransformCollectionReceipt.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/TransformCollectionReceipt"/>
    <wsdl:binding name="TransformCollectionReceipt_ptt-binding" type="tran:TransformCollectionReceipt_ptt" xmlns:tran="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/TransformCollectionReceipt">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="TransformCollectionReceipt">
            <soap:operation soapAction="TransformCollectionReceipt"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>