<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/NonStandardAgreementOperRec" name="NonStandardAgreementOperRec-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="NonStandardAgreementOperRec.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/NonStandardAgreementOperRec"/>
    <wsdl:binding name="NonStandardAgreementOperRec_ptt-binding" type="non:NonStandardAgreementOperRec_ptt" xmlns:non="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/NonStandardAgreementOperRec">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="NonStandardAgreementOperRec">
            <soap:operation soapAction="NonStandardAgreementOperRec"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>