<WL5G3N0:definitions name="reversaEfectivoTCPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/reversaEfectivoTCPS" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://www.ficohsa.com.hn/middleware.services/reversaEfectivoTCTypes" xmlns:WL5G3N2="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:WL5G3N3="http://www.ficohsa.com.hn/middleware.services/reversaEfectivoTCPS" xmlns:WL5G3N4="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:efe="http://www.ficohsa.com.hn/middleware.services/reversaEfectivoTCTypes" xmlns:rev="http://www.ficohsa.com.hn/middleware.services/reversaEfectivoTCPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsd/XMLSchema_-542608478.xsd"/>
    </xsd:schema>
    <xsd:schema xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:efe="http://www.ficohsa.com.hn/middleware.services/reversaEfectivoTCTypes" xmlns:rev="http://www.ficohsa.com.hn/middleware.services/reversaEfectivoTCPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/reversaEfectivoTCTypes" schemaLocation="../xsd/XMLSchema_-1638440918.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="reversaEfectivoTCRequest">
    <WL5G3N0:part element="WL5G3N1:reversaEfectivoTC" name="parameters"/>
    <WL5G3N0:part element="WL5G3N2:RequestHeader" name="RequestHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="reversaEfectivoTCResponse">
    <WL5G3N0:part element="WL5G3N1:reversaEfectivoTCResponse" name="result"/>
    <WL5G3N0:part element="WL5G3N2:ResponseHeader" name="ResponseHeader"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="reversaEfectivoTCPS">
    <WL5G3N0:operation name="reversaEfectivoTC" parameterOrder="parameters RequestHeader ResponseHeader">
      <WL5G3N0:input message="WL5G3N3:reversaEfectivoTCRequest"/>
      <WL5G3N0:output message="WL5G3N3:reversaEfectivoTCResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="reversaEfectivoTCPSSOAP" type="WL5G3N3:reversaEfectivoTCPS">
    <WL5G3N4:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="reversaEfectivoTC">
      <WL5G3N4:operation soapAction="http://www.ficohsa.com.hn/middleware.services/reversaEfectivoTC/reversaEfectivoTCPS"/>
      <WL5G3N0:input>
        <WL5G3N4:header message="WL5G3N3:reversaEfectivoTCRequest" part="RequestHeader" use="literal"/>
        <WL5G3N4:body parts="parameters" use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N4:header message="WL5G3N3:reversaEfectivoTCResponse" part="ResponseHeader" use="literal"/>
        <WL5G3N4:body parts="result" use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="reversaEfectivoTCPS">
    <WL5G3N0:port binding="WL5G3N3:reversaEfectivoTCPSSOAP" name="reversaEfectivoTCPSSOAP">
      <WL5G3N4:address location="http://JUMUNOZ.CIDENET.LOCAL:7001/Middleware/OperationsAndExecution/Cards/ReversaEfectivoTC"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>