<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/registrarFacturaCobranzas/registrarFacturaCobranzas" name="registrarFacturaCobranzas-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/registrarFacturaCobranzas/registrarFacturaCobranzas" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/registrarFacturaCobranzas/registrarFacturaCobranzas" location="registrarFacturaCobranzas.wsdl"/>
  <binding name="registrarFacturaCobranzas_ptt-binding" type="tns:registrarFacturaCobranzas_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registrarFacturaCobranzas">
      <soap:operation soapAction="registrarFacturaCobranzas"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registrarFacturaCobranzas-service">
    <port name="registrarFacturaCobranzas-port" binding="tns:registrarFacturaCobranzas_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>