<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBConSaldosTCOffLine/registraMovimientosRecientesTC/registraMovimientosRecientesTC" name="registraMovimientosRecientesTC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBConSaldosTCOffLine/registraMovimientosRecientesTC/registraMovimientosRecientesTC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBConSaldosTCOffLine/registraMovimientosRecientesTC/registraMovimientosRecientesTC" location="registraMovimientosRecientesTC.wsdl"/>
  <binding name="registraMovimientosRecientesTC_ptt-binding" type="tns:registraMovimientosRecientesTC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registraMovimientosRecientesTC">
      <soap:operation soapAction="registraMovimientosRecientesTC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registraMovimientosRecientesTC-service">
    <port name="registraMovimientosRecientesTC-port" binding="tns:registraMovimientosRecientesTC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionClientdata"/>
    </port>
  </service>
</definitions>