<wsdl:definitions name="consultaListaClientePS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/reimpresionReciboPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/reimpresionReciboPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:rei="http://www.ficohsa.com.hn/middleware.services/reimpresionReciboTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/reimpresionReciboTypes" schemaLocation="../xsd/reimpresionReciboTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="reimpresionReciboRequest">
		<wsdl:part element="rei:reimpresionRecibo" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="reimpresionReciboResponse">
		<wsdl:part element="rei:reimpresionReciboResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="reimpresionReciboPS">
		<wsdl:operation name="reimpresionRecibo" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:reimpresionReciboRequest"/>
			<wsdl:output message="fic:reimpresionReciboResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="reimpresionReciboPSSOAP" type="fic:reimpresionReciboPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="reimpresionRecibo">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/reimpresionReciboPS"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:reimpresionReciboRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:reimpresionReciboResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="reimpresionReciboPS">
    <wsdl:port binding="fic:reimpresionReciboPSSOAP" name="reimpresionReciboPSSOAP">
      <soap:address location="http://10.9.104.55:8003/Middleware/OperationsAndExecution/Payments/reimpresionRecibo"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>