<wsdl:definitions name="reprocesoACHEnviadasCRPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/reprocesoACHEnviadasCR/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/reprocesoACHEnviadasCR/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:rep="http://www.ficohsa.com.hn/middleware.services/reprocesoACHEnviadasCRTypes">
				
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/reprocesoACHEnviadasCRTypes" schemaLocation="../xsd/reprocesoACHEnviadasCRTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="reprocesoACHEnviadasCRRequest">
		<wsdl:part element="rep:reprocesoACHEnviadasCR" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="reprocesoACHEnviadasCRResponse">
		<wsdl:part element="rep:reprocesoACHEnviadasCRResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="reprocesoACHEnviadasCRPS">
		<wsdl:operation name="reprocesoACHEnviadasCR" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:reprocesoACHEnviadasCRRequest"/>
			<wsdl:output message="fic:reprocesoACHEnviadasCRResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="reprocesoACHEnviadasCRPSSOAP" type="fic:reprocesoACHEnviadasCRPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="reprocesoACHEnviadasCR">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/reprocesoACHEnviadasCRPS/reprocesoACHEnviadasCR"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:reprocesoACHEnviadasCRRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:reprocesoACHEnviadasCRResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="reprocesoACHEnviadasCRPS">
	    <wsdl:port binding="fic:reprocesoACHEnviadasCRPSSOAP" name="reprocesoACHEnviadasCRPSSOAP">
	      <soap:address location="http://10.9.104.55:8003/SMiddleware/OperationsAndExecution/Payments/ReprocesoACHEnviadasCR"/>
	    </wsdl:port>
  	</wsdl:service>
	
</wsdl:definitions>