<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/EnviarCorreoLauKey/renviarCorreo" name="renviarCorreo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/EnviarCorreoLauKey/renviarCorreo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/EnviarCorreoLauKey/renviarCorreo" location="renviarCorreo.wsdl"/>
  <binding name="renviarCorreo_ptt-binding" type="tns:renviarCorreo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="renviarCorreo">
      <soap:operation soapAction="renviarCorreo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="renviarCorreo-service">
    <port name="renviarCorreo-port" binding="tns:renviarCorreo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionAppEnvioCorreo"/>
    </port>
  </service>
</definitions>