
sequenceDiagram
    autonumber
    participant Consumidor as Consumidore/Aplicación
    participant API as API Consulta Gestiones Monetarias <br> Epica 2380: ConsultaGestionesMonetarias <br> HU 7014:  POST -  /servicing/customer-case-mgmt-retrieve/v1/retrieve-transaction-status
    participant CL as Caché Local
    participant Lambda as Lambda de parámetros
    participant Lib as Librería Pipeline (ConfigMap)
    participant wrapper as Wrapper Abanks Multidestino <br> Schema: SALESFORCE <br> SP: SFC_P_CON_GESTIONES_MONETARIAS 
    participant Errors as Control de Errores <br> Librería de mapeo de errores
    
    Note over Consumidor, Errors: Flujo Multiregion (HN01 | GT01 | PA01) - Consulta Gestiones Monetarias

    Consumidor->>API: REST Request
    Note right of Consumidor: header: <br> sourceBank <br> body: <br> customerReference, <br> caseDetail

    API->>API: Validar Request
    Note over API: Valida campos obligatorios según contrato OpenAPI 

    API->>API: Validación exitosa

    alt Consulta parametros en caché local

        API->>CL: Consultar parámetros Lambda Parámetros caché local
        Note right of API: Domain: "CUSTOMER_CASE_MGMT_RETRIEVE" <br> name: "RETRIEVE_TRANSACTION_STATUS" <br> country: XRS 

        CL->>API: Obtiene parámetros Lambda Parámetros Cahé Local
        Note left of CL: Obtiene parámetros de regionalización, conexión y negocio

    else Consulta  parametros en Lambda Parámetros 

        API->>Lambda: Consultar parámetros lambda parámetros
        Note right of API: Domain: "CUSTOMER_CASE_MGMT_RETRIEVE" <br> name: "RETRIEVE_TRANSACTION_STATUS" <br> country: XRS 

        Lambda->>API: Obtiene parámetros Lambda Parámetros
        Note left of Lambda: Obtiene parámetros de regionalización, conexión y negocio

        API->>CL: Guarda parámetros lambda Parámetros en caché local
        Note right of API: value.param-name 

    end

    API->>API: Validar Servicio Regional
    Note over API: Usando parámetros de regionalización obtenidos

    API->>API: Validación Regional Exitosa
    Note over API: Servicio habilitado para HN01 | GT01 | PA01

    API->>Lib: Consulta Constantes
    
    Lib->>API: Retorna constantes necesarias
    Note left of Lib: Constantes: <br> connectionType <br> operationType  <br> catalogeName <br> procedureName <br> caller-service

    API->>API: Construye Request Wrapper Abanks Multidestino SP: SFC_P_CON_GESTIONES_MONETARIAS 
    Note over API: Mapeo: <br> connection { <br> parm = lambda.param-name <br> secm = lambda.secret-name } <br> connectionType = const.connectionType <br> operationType  = const.operationType <br> catalogueName = const.catalogeName <br> procedureName = const.procedureNameCB <br> package = const.packageCB <br> params : { <br> PV_NUMUSU = request.customerReference  <br> PV_PAIS = header.sourceBank <br> PV_DETALLE = request.caseDetail <br> }

    API->>wrapper: Consume Wrapper Abanks Multidestino SP: SFC_P_CON_GESTIONES_MONETARIAS 
    Note right of API: connection, connectionType <br> operationType, catalogueName <br> params: { <br> PV_NUMUSU, PV_PAIS, PV_DETALLE <br> }

    wrapper->>API: Response Wrapper Abanks Multidestino SP: SFC_P_CON_GESTIONES_MONETARIAS 
    Note over wrapper: Response: <br> success, data

    API->>API: Evalúa Response Wrapper Abanks Multidestino SP: SFC_P_CON_GESTIONES_MONETARIAS 

    alt If data.Pv_CodigoMensaje == `SUCCESS` 

        API->>API: Construye response API
        Note over API: Mapeo uno a uno campos del objeto Pt_Campos_Resultado <br> hacia campos response API según contrato open API

        API->>Consumidor: Response Exitoso
        Note left of API: HTTP 200: Response Body 

    else If data.Pv_CodigoMensaje != `SUCCESS` 

        API->> Errors: Mapear código de error
        Note right of API: Mapeo de errores según tabla de homologación
        
        Errors ->> API: Retorna código mapeado
        
        API->> Consumidor: Retorna error
        Note left of API: HTTP 4XX / 5XX

    end

    Note over Consumidor, Errors: Flujo Alternativo - Error
    activate API
    alt Exception occurs
        note over Errors: Error Library Handler
        activate Errors
            API->> Errors: Mapear código de error
            Errors ->> API: Retorna código mapeado
        deactivate Errors
        activate Consumidor
            API-->> Consumidor: Retorna error
        deactivate Consumidor
        Note over Consumidor,Errors: Diagrama guía de manejo de errores <br> http://bit.ly/4rpKVIU
    end
    deactivate API