<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaTransaccionLote/consultaTransaccionLote" name="consultaTransaccionLote-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaTransaccionLote/consultaTransaccionLote" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaTransaccionLote/consultaTransaccionLote" location="consultaTransaccionLote.wsdl"/>
  <binding name="consultaTransaccionLote_ptt-binding" type="tns:consultaTransaccionLote_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaTransaccionLote">
      <soap:operation soapAction="consultaTransaccionLote"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaTransaccionLote-service">
    <port name="consultaTransaccionLote-port" binding="tns:consultaTransaccionLote_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>