<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationTest/INTEGRACION_CONSULTA_TRX_PASIVOS/integracionConsultaTrxPasivos" name="integracionConsultaTrxPasivos-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationTest/INTEGRACION_CONSULTA_TRX_PASIVOS/integracionConsultaTrxPasivos" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationTest/INTEGRACION_CONSULTA_TRX_PASIVOS/integracionConsultaTrxPasivos" location="integracionConsultaTrxPasivos.wsdl"/>
  <binding name="integracionConsultaTrxPasivos_ptt-binding" type="tns:integracionConsultaTrxPasivos_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="integracionConsultaTrxPasivos">
      <soap:operation soapAction="integracionConsultaTrxPasivos"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="integracionConsultaTrxPasivos-service">
    <port name="integracionConsultaTrxPasivos-port" binding="tns:integracionConsultaTrxPasivos_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionCustomerCreditRisk"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="integracionConsultaTrxPasivos.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationTest/INTEGRACION_CONSULTA_TRX_PASIVOS/integracionConsultaTrxPasivos">
            <con:wsdl ref="Middleware/v2/BusinessServices/DWConsultaConsolidada/integracionConsultaTrxPasivos/wsdl/integracionConsultaTrxPasivos"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/ApplicationTest/INTEGRACION_CONSULTA_TRX_PASIVOS/integracionConsultaTrxPasivos</con:targetNamespace>
</con:wsdlEntry>