<wsdl:definitions name="tokenizacionProcesamientoBlazePS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/tokenizacionProcesamientoBlazePS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/tokenizacionProcesamientoBlazePS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:tpb="http://www.ficohsa.com.hn/middleware.services/tokenizacionProcesamientoBlazeTypes">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/tokenizacionProcesamientoBlazeTypes" schemaLocation="../xsd/tokenizacionProcesamientoBlazeTypes.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="tokenizacionProcesamientoBlazeRequest">
    <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
  </wsdl:message>
  <wsdl:message name="tokenizacionProcesamientoBlazeResponse">
    <wsdl:part element="tpb:tokenizacionProcesamientoBlazeResponse" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  <wsdl:portType name="tokenizacionProcesamientoBlazePS">
    <wsdl:operation name="tokenizacionProcesamientoBlaze" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="fic:tokenizacionProcesamientoBlazeRequest"/>
      <wsdl:output message="fic:tokenizacionProcesamientoBlazeResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="tokenizacionProcesamientoBlazePSSOAP" type="fic:tokenizacionProcesamientoBlazePS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="tokenizacionProcesamientoBlaze">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/tokenizacionProcesamientoBlazePS/NewOperation"/>
      <wsdl:input>
        <soap:body use="literal"/>
        <soap:header message="fic:tokenizacionProcesamientoBlazeRequest" part="RequestHeader" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header message="fic:tokenizacionProcesamientoBlazeResponse" part="ResponseHeader" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="tokenizacionProcesamientoBlazePS">
    <wsdl:port binding="fic:tokenizacionProcesamientoBlazePSSOAP" name="tokenizacionProcesamientoBlazePSSOAP">
      <soap:address location="https://vortexmw:8010/TokenizacionProcesamientoBlaze"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>