<wsdl:definitions name="consultaComisionesH2HPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaComisionesH2HPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaComisionesH2HPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaComisionesH2HTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../EsquemasGenerales/headerElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaComisionesH2HTypes" schemaLocation="../xsd/consultaComisionesH2HTypes.xsd"/> 
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="consultaComisionesH2HRequest">
		<wsdl:part element="cons:consultaComisionesH2HRequest" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaComisionesH2HResponse">
		<wsdl:part element="cons:consultaComisionesH2HResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="consultaComisionesH2HPS">
		<wsdl:operation name="consultaComisionesH2H" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaComisionesH2HRequest"/>
			<wsdl:output message="fic:consultaComisionesH2HResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaComisionesH2HPSSOAP" type="fic:consultaComisionesH2HPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaComisionesH2H">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaComisionesH2HPS/consultaComisionesH2H"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaComisionesH2HRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaComisionesH2HResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="consultaComisionesH2HPS">
    <wsdl:port binding="fic:consultaComisionesH2HPSSOAP" name="consultaComisionesH2HPSSOAP">
      <soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/CommonBusinessInformation/consultaComisionesH2H"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>