<wsdl:definitions name="consultasTipoIdentidadPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultasTipoIdentidadPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultasTipoIdentidadPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultasTipoIdentidadTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultasTipoIdentidadTypes" schemaLocation="consultasTipoIdentidadTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="consultasTipoIdentidadRequest">
		<wsdl:part element="cons:consultasTipoIdentidad" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultasTipoIdentidadResponse">
		<wsdl:part element="cons:consultasTipoIdentidadResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="consultasTipoIdentidadPS">
		<wsdl:operation name="consultasTipoIdentidad" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultasTipoIdentidadRequest"/>
			<wsdl:output message="fic:consultasTipoIdentidadResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultasTipoIdentidadPSSOAP" type="fic:consultasTipoIdentidadPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultasTipoIdentidad">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultasTipoIdentidadPS/consultasTipoIdentidad"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultasTipoIdentidadRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultasTipoIdentidadResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="consultasTipoIdentidadPS">
    <wsdl:port binding="fic:consultasTipoIdentidadPSSOAP" name="consultasTipoIdentidadPSSOAP">
      <soap:address location="http://mwinterbanca:8003/Middleware/ReferenceData/CommonBusinessInformation/ConsultaTipoIdentidad"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>