<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CreditCardProcessor/GetCatalogEquivalence" name="GetCatalogEquivalence-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GetCatalogEquivalence.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CreditCardProcessor/GetCatalogEquivalence"/>
    <wsdl:binding name="GetCatalogEquivalence_ptt-binding" type="get:GetCatalogEquivalence_ptt" xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CreditCardProcessor/GetCatalogEquivalence">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="GetCatalogEquivalence">
            <soap:operation soapAction="GetCatalogEquivalence"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>