<wsdl:definitions name="GetCatalogEquivalence" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CreditCardProcessor/GetCatalogEquivalence" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CreditCardProcessor/GetCatalogEquivalence" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/GetCatalogEquivalence" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="GetCatalogEquivalence_plt">
    <plt:role name="GetCatalogEquivalence_role">
      <plt:portType name="tns:GetCatalogEquivalence_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/GetCatalogEquivalence" schemaLocation="../../XSD/GetCatalogEquivalence/GetCatalogEquivalence_sp.xsd"/>
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="GetCatalogEquivalence_ptt">
        <wsdl:operation name="GetCatalogEquivalence">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>