dependencies {
    implementation project(':model')
    implementation project(':ports')
    implementation project(':use-case')
    implementation project(':helpers')

    implementation libs.boot.starter.webflux
    implementation libs.boot.springdoc.webflux
    implementation libs.ficohsa.router
    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor
}
