<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application/Project/MCCONSTransaccionVNT" name="MCCONSTransaccionVNT-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application/Project/MCCONSTransaccionVNT" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application/Project/MCCONSTransaccionVNT" location="MCCONSTransaccionVNT.wsdl"/>
  <binding name="MCCONSTransaccionVNT_ptt-binding" type="tns:MCCONSTransaccionVNT_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="MCCONSTransaccionVNT">
      <soap:operation soapAction="MCCONSTransaccionVNT"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="MCCONSTransaccionVNT-service">
    <port name="MCCONSTransaccionVNT-port" binding="tns:MCCONSTransaccionVNT_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>