<wsdl:definitions name="AutorizacionEfectivoPrestamosOTBPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/AutorizacionEfectivoPrestamosOTBPS/" xmlns:aep="http://www.ficohsa.com.hn/middleware.services/AutorizacionEfectivoPrestamosOTBPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:aept="http://www.ficohsa.com.hn/middleware.services/AutorizacionEfectivoPrestamosOTBTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/AutorizacionEfectivoPrestamosOTBTypes" schemaLocation="../xsd/AutorizacionEfectivoPrestamosOTBTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="AutorizacionEfectivoPrestamosOTB">
		<wsdl:part name="parameters" element="aept:AutorizacionEfectivoPrestamosOTB"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	
	<wsdl:message name="AutorizacionEfectivoPrestamosOTBResponse">
		<wsdl:part name="result" element="aept:AutorizacionEfectivoPrestamosOTBResponse"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="AutorizacionEfectivoPrestamosOTBPS">
		<wsdl:operation name="AutorizacionEfectivoPrestamosOTB" parameterOrder="parameters RequestHeader ResponseHeader">
			
			<wsdl:input message="aep:AutorizacionEfectivoPrestamosOTB"/>
			<wsdl:output message="aep:AutorizacionEfectivoPrestamosOTBResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="AutorizacionEfectivoPrestamosOTBPSSOAP" type="aep:AutorizacionEfectivoPrestamosOTBPS">
		
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		
		<wsdl:operation name="AutorizacionEfectivoPrestamosOTB">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/AutorizacionEfectivoPrestamosOTBPS/AutorizacionEfectivoPrestamosOTB"/>
			
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="aep:AutorizacionEfectivoPrestamosOTB" part="RequestHeader" use="literal"/>
			</wsdl:input>
			
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="aep:AutorizacionEfectivoPrestamosOTBResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>	 

	  <wsdl:service name="AutorizacionEfectivoPrestamosOTBPS">
	    <wsdl:port name="AutorizacionEfectivoPrestamosOTBPSSOAP" binding="aep:AutorizacionEfectivoPrestamosOTBPSSOAP">
	    	
	      <soap:address location="https://mwomnicanal:8004/Middleware/OperationsAndExecution/Cards/AutorizacionEfectivoPrestamosOTB"/>
	    </wsdl:port>
	  </wsdl:service>
</wsdl:definitions>