<wsdl:definitions targetNamespace="http://www.ficohsa.com.hn/middleware.services/programaLealtad/" name="redencionPuntosLealtadPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/programaLealtad/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:pro="http://www.ficohsa.com.hn/middleware.services/programaLealtadTypes">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/programaLealtadTypes" schemaLocation="../../ProgramaLealtad/xsd/programaLealtadTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="redencionPuntosLealtadRequest">
		<wsdl:part element="pro:redencionPuntosLealtad" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="redencionPuntosLealtadResponse">
		<wsdl:part element="pro:redencionPuntosLealtadResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="programaLealtadPS">
		<wsdl:operation name="redencionPuntosLealtad" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:redencionPuntosLealtadRequest"/>
			<wsdl:output message="fic:redencionPuntosLealtadResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="programaLealtadPSSOAP" type="fic:programaLealtadPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="redencionPuntosLealtad">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/programaLealtadPS/programaLealtad"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:redencionPuntosLealtadRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:redencionPuntosLealtadResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>	
	</wsdl:binding>

	<wsdl:service name="redencionPuntosLealtadPS">
		<wsdl:port binding="fic:programaLealtadPSSOAP" name="programaLealtadPSSOAP">
	  		<soap:address location="http://172.23.13.19:8003/Middleware/SalesAndServices/BrandManagement/RedencionPuntosLealtad"/>
	   	</wsdl:port>
	</wsdl:service>

</wsdl:definitions>