<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/listadoCiudadesAldeasFPC/listadoCiudadesAldeasFPC" name="listadoCiudadesAldeasFPC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/listadoCiudadesAldeasFPC/listadoCiudadesAldeasFPC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/listadoCiudadesAldeasFPC/listadoCiudadesAldeasFPC" location="listadoCiudadesAldeasFPC.wsdl"/>
  <binding name="listadoCiudadesAldeasFPC_ptt-binding" type="tns:listadoCiudadesAldeasFPC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="listadoCiudadesAldeasFPC">
      <soap:operation soapAction="listadoCiudadesAldeasFPC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="listadoCiudadesAldeasFPC-service">
    <port name="listadoCiudadesAldeasFPC-port" binding="tns:listadoCiudadesAldeasFPC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionFicopen"/>
    </port>
  </service>
</definitions>