<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BD+abanks+GT/soa/ConsultaRiesgoCobis" name="ConsultaRiesgoCobis-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BD+abanks+GT/soa/ConsultaRiesgoCobis" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BD+abanks+GT/soa/ConsultaRiesgoCobis" location="ConsultaRiesgoCobis.wsdl"/>
  <binding name="ConsultaRiesgoCobis_ptt-binding" type="tns:ConsultaRiesgoCobis_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ConsultaRiesgoCobis">
      <soap:operation soapAction="ConsultaRiesgoCobis"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ConsultaRiesgoCobis-service">
    <port name="ConsultaRiesgoCobis-port" binding="tns:ConsultaRiesgoCobis_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionSysbase"/>
    </port>
  </service>
</definitions>