<wsdl:definitions name="consultaDestinosPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaDestinosPS/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/consultaDestinosPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:set="http://www.ficohsa.com.hn/middleware.services/catalogosInfoClienteTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/catalogosInfoClienteTypes" schemaLocation="../../CatalogosInfoCliente/xsd/catalogosInfoClienteTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="consultaDestinos">
		<wsdl:part element="set:consultaDestinos" name="parameters"/>
		<wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaDestinosResponse">
		<wsdl:part element="set:consultaDestinosResponse" name="result"/>
		<wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="consultaDestinosPS">	
		<wsdl:operation name="consultaDestinos" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="tns:consultaDestinos"/>
			<wsdl:output message="tns:consultaDestinosResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaDestinosPSSOAP" type="tns:consultaDestinosPS">
	
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		
		<wsdl:operation name="consultaDestinos">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/catalogosInfoClientePS/catalogosInfoCliente"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="tns:consultaDestinos" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="tns:consultaDestinosResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>	
	</wsdl:binding>

	<wsdl:service name="consultaDestinosPS">
		<wsdl:port binding="tns:consultaDestinosPSSOAP" name="consultaDestinosPS">
	  		<soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/CustomerLoans/consultaDestinos"/>
	   	</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>