<xsd:schema targetNamespace="https://www.ficohsa.com/nicaragua/referenceData" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="https://www.ficohsa.com/nicaragua/referenceData" xmlns:com="https://www.ficohsa.com/regional/common/commonTypes">
  <xsd:import schemaLocation="../../SBNI_ReferenceData_Commons/Schemas/CommonTypes.xsd" namespace="https://www.ficohsa.com/regional/common/commonTypes"/>
  <xsd:element name="getCatalogsCoreBanking">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="GeneralInfo" type="com:GeneralInfoType"/>
        <xsd:element name="Channel" type="xsd:string"/>
        <xsd:element name="Operation" type="xsd:string"/>
        <xsd:element name="Condition1" type="xsd:string" minOccurs="0"/>
        <xsd:element name="Condition2" type="xsd:string" minOccurs="0"/>
        <xsd:element name="Condition3" type="xsd:string" minOccurs="0"/>
        <xsd:element name="Condition4" type="xsd:string" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="getCatalogsCoreBankingResponse">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Catalogs" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Catalog" type="xsd:string"/>
              <xsd:element name="Code" type="xsd:string"/>
              <xsd:element name="CodeIso" type="xsd:string"/>
              <xsd:element name="Description1" type="xsd:string"/>
              <xsd:element name="Description2" type="xsd:string"/>
              <xsd:element name="Status" type="xsd:string"/>
              <xsd:element name="RegisterDate" type="xsd:string"/>
              <xsd:element name="Action" type="xsd:string" minOccurs="0"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="StatusInfo" type="com:StatusInfoType"/>
        <xsd:element name="ErrorInfo" type="com:ErrorInfoType"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>