<wsdl:definitions name="TransfersRouter_PS" targetNamespace="http://xmlns.oracle.com/DynamoMigrate/MWBanking/TransfersRouter_PS" xmlns:tns="http://xmlns.oracle.com/DynamoMigrate/MWBanking/TransfersRouter_PS" xmlns:inp1="http://www.ficohsa.com.hn/middleware.services/transferTypes" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="TransfersRouter_PS">
        <plnk:role name="TransfersRouter_PSProvider" portType="tns:TransfersRouter_PS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/transferTypes" schemaLocation="../../../../../MWBanking/Transfers/RequestorServices/XSD/transferTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="transfersAccount_inputMessage">
        <wsdl:part name="request" element="inp1:transfersAccountRequest"/>
    </wsdl:message>
    <wsdl:message name="transfersAccount_outputMessage">
        <wsdl:part name="reply" element="inp1:transfersAccountResponse"/>
    </wsdl:message>
    <wsdl:portType name="TransfersRouter_PS_ptt">
        <wsdl:operation name="transfersAccount">
            <wsdl:input message="tns:transfersAccount_inputMessage"/>
            <wsdl:output message="tns:transfersAccount_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="TransfersRouter_PS_ptt-binding" type="tns:TransfersRouter_PS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="transfersAccount">
            <soap:operation soapAction="transfersAccount"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>