<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Prueba/registraParametrizacion/registraParametrizacion" name="registraParametrizacion-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Prueba/registraParametrizacion/registraParametrizacion" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Prueba/registraParametrizacion/registraParametrizacion" location="registraParametrizacion.wsdl"/>
  <binding name="registraParametrizacion_ptt-binding" type="tns:registraParametrizacion_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registraParametrizacion">
      <soap:operation soapAction="registraParametrizacion"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registraParametrizacion-service">
    <port name="registraParametrizacion-port" binding="tns:registraParametrizacion_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>