<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RecaudoNI/RecaudoNI/ConsultaRecaudoNI" name="ConsultaRecaudoNI-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/RecaudoNI/RecaudoNI/ConsultaRecaudoNI" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/RecaudoNI/RecaudoNI/ConsultaRecaudoNI" location="ConsultaConvenio.wsdl"/>
  <binding name="ConsultaRecaudoNI_ptt-binding" type="tns:ConsultaRecaudoNI_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ConsultaRecaudoNI">
      <soap:operation soapAction="ConsultaRecaudoNI"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ConsultaRecaudoNI-service">
    <port name="ConsultaRecaudoNI-port" binding="tns:ConsultaRecaudoNI_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConveniosNI"/>
    </port>
  </service>
</definitions>