<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MDA-55558/LIMITES_TRANSACCIONALES/limiteTrxConsultarRem" name="limiteTrxConsultarRem-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MDA-55558/LIMITES_TRANSACCIONALES/limiteTrxConsultarRem" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MDA-55558/LIMITES_TRANSACCIONALES/limiteTrxConsultarRem" location="limiteTrxConsultarRem.wsdl"/>
  <binding name="limiteTrxConsultarRem_ptt-binding" type="tns:limiteTrxConsultarRem_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="limiteTrxConsultarRem">
      <soap:operation soapAction="limiteTrxConsultarRem"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="limiteTrxConsultarRem-service">
    <port name="limiteTrxConsultarRem-port" binding="tns:limiteTrxConsultarRem_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>