<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnvioMensajeSMS/actualizaEstadoRemesa/actualizaEstadoRemesa" name="actualizaEstadoRemesa-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/EnvioMensajeSMS/actualizaEstadoRemesa/actualizaEstadoRemesa" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnvioMensajeSMS/actualizaEstadoRemesa/actualizaEstadoRemesa" location="actualizaEstadoRemesa.wsdl"/>
  <binding name="actualizaEstadoRemesa_ptt-binding" type="tns:actualizaEstadoRemesa_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="actualizaEstadoRemesa">
      <soap:operation soapAction="actualizaEstadoRemesa"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="actualizaEstadoRemesa-service">
    <port name="actualizaEstadoRemesa-port" binding="tns:actualizaEstadoRemesa_ptt-binding">
      <soap:address location="jca://eis/DB/FLINK_DESA75"/>
    </port>
  </service>
</definitions>