<wsdl:definitions name="altaContratoDEIPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/altaContratoPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/altaContratoPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:trb="http://www.ficohsa.com.hn/middleware.services/tributosTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>    	    
    </xsd:schema>    	
    <xsd:schema>
    	<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/tributosTypes" schemaLocation="../../TributosDEI/xsd/tributosTypes.xsd"/>
    </xsd:schema>    
  </wsdl:types>
  
  
  <wsdl:message name="altaContratoRequest">
    <wsdl:part element="trb:altaContrato" name="parameters"/>
    <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
  </wsdl:message>
  
  <wsdl:message name="altaContratoResponse">
    <wsdl:part element="trb:altaContratoResponse" name="result"/>
    <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="altaContratoPS">
    <wsdl:operation name="altaContrato" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="fic:altaContratoRequest"/>
      <wsdl:output message="fic:altaContratoResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  
  
  <wsdl:binding name="altaContratoPSSOAP" type="fic:altaContratoPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="altaContrato">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/altaContratoPS/altaContrato"/>
      <wsdl:input>
        <soap:body use="literal" parts="parameters"/>
        <soap:header use="literal" part="RequestHeader" message="fic:altaContratoRequest"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="result"/>
        <soap:header use="literal" part="ResponseHeader" message="fic:altaContratoResponse"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="altaContratoPS">
    <wsdl:port binding="fic:altaContratoPSSOAP" name="altaContratoPSSOAP">
      <soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/CommonBusinessInformation/altaContrato_v2"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>