<wsdl:definitions name="cashOpenToBuyInquiryPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/cashOpenToBuyInquiryPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cas="http://www.ficohsa.com.hn/middleware.services/cashOpenToBuyInquiryPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/cashOpenToBuyInquiryTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/cashOpenToBuyInquiryTypes" schemaLocation="../xsd/cashOpenToBuyInquiryTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestHeader">
        <wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
    </wsdl:message>
    <wsdl:message name="responseHeader">
        <wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
    </wsdl:message>
    <wsdl:message name="cashOpenToBuyInquiry">
        <wsdl:part element="tns:cashOpenToBuyInquiry" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="cashOpenToBuyInquiryResponse">
        <wsdl:part element="tns:cashOpenToBuyInquiryResponse" name="result"/>
    </wsdl:message>
    <wsdl:portType name="cashOpenToBuyInquiryPS">
        <wsdl:operation name="cashOpenToBuyInquiry" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="cas:cashOpenToBuyInquiry"/>
            <wsdl:output message="cas:cashOpenToBuyInquiryResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="cashOpenToBuyInquiryPSSOAP" type="cas:cashOpenToBuyInquiryPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="cashOpenToBuyInquiry">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/cashOpenToBuyInquiryPS/cashOpenToBuyInquiry"/>
            <wsdl:input>
                <soap:body parts="parameters" use="literal"/>
                <soap:header message="cas:requestHeader" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body parts="result" use="literal"/>
                <soap:header message="cas:responseHeader" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="cashOpenToBuyInquiryPS">
        <wsdl:port binding="cas:cashOpenToBuyInquiryPSSOAP" name="cashOpenToBuyInquiryPSSOAP">
            <soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Cards/CashOpenToBuyInquiry"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>