<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/validaAccesoH2H" name="validaAccesoH2H-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/validaAccesoH2H" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project1/validaAccesoH2H" location="validaAccesoH2H.wsdl"/>
  <binding name="validaAccesoH2H_ptt-binding" type="tns:validaAccesoH2H_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="validaAccesoH2H">
      <soap:operation soapAction="validaAccesoH2H"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="validaAccesoH2H-service">
    <port name="validaAccesoH2H-port" binding="tns:validaAccesoH2H_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterfazdb"/>
    </port>
  </service>
</definitions>