<wsdl:definitions name="enviaVerificacionOTPPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/enviaVerificacionOTPPS/" xmlns:ev="http://www.ficohsa.com.hn/middleware.services/enviaVerificacionOTPPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/digitalizacionTarjetasTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/digitalizacionTarjetasTypes" schemaLocation="../../DigitalizacionTarjetas/xsd/digitalizacionTarjetasTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="enviaVerificacionOTPRequest">
		<wsdl:part element="tns:enviaVerificacionOTP" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="enviaVerificacionOTPResponse">
		<wsdl:part element="tns:enviaVerificacionOTPResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	<wsdl:portType name="enviaVerificacionOTPPS">
		<wsdl:operation name="enviaVerificacionOTP" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="ev:enviaVerificacionOTPRequest"/>
			<wsdl:output message="ev:enviaVerificacionOTPResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="enviaVerificacionOTPPSSOAP" type="ev:enviaVerificacionOTPPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="enviaVerificacionOTP">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/enviaVerificacionOTPPS/enviaVerificacionOTP"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="ev:enviaVerificacionOTPRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="ev:enviaVerificacionOTPResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="enviaVerificacionOTPPS">
		<wsdl:port binding="ev:enviaVerificacionOTPPSSOAP" name="enviaVerificacionOTPPSSOAP">
			<soap:address location="http://172.23.13.35:8003/Middleware/OperationsAndExecution/CustomerDeposits/digitalizacionTarjetas"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>