<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaSaldoPromedioCuenta/consultaSaldoPromedioCuenta" name="consultaSaldoPromedioCuenta-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaSaldoPromedioCuenta/consultaSaldoPromedioCuenta" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultaSaldoPromedioCuenta/consultaSaldoPromedioCuenta" location="consultaSaldoPromedioCuenta.wsdl"/>
  <binding name="consultaSaldoPromedioCuenta_ptt-binding" type="tns:consultaSaldoPromedioCuenta_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaSaldoPromedioCuenta">
      <soap:operation soapAction="consultaSaldoPromedioCuenta"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaSaldoPromedioCuenta-service">
    <port name="consultaSaldoPromedioCuenta-port" binding="tns:consultaSaldoPromedioCuenta_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksPA"/>
    </port>
  </service>
</definitions>