<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DBConnections/validaLineaCredito/validaLineaCredito" name="validaLineaCredito-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DBConnections/validaLineaCredito/validaLineaCredito" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DBConnections/validaLineaCredito/validaLineaCredito" location="../wsdl/validaLineaCredito.wsdl"/>
  <binding name="validaLineaCredito_ptt-binding" type="tns:validaLineaCredito_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="validaLineaCredito">
      <soap:operation soapAction="validaLineaCredito"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="validaLineaCredito-service">
    <port name="validaLineaCredito-port" binding="tns:validaLineaCredito_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionAbanksHN"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="../wsdl/validaLineaCredito.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DBConnections/validaLineaCredito/validaLineaCredito">
            <con:wsdl ref="Middleware/v2/BusinessServices/ValidaLineaCredito/wsdl/validaLineaCredito"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/DBConnections/validaLineaCredito/validaLineaCredito</con:targetNamespace>
</con:wsdlEntry>