<wsdl:definitions name="solicitaActualizacionDatosClientePS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/solicitaActualizacionDatosClientePS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:sol="http://www.ficohsa.com.hn/middleware.services/solicitaActualizacionDatosClientePS/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/solicitaActualizacionDatosClienteTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/solicitaActualizacionDatosClienteTypes" schemaLocation="../xsd/solicitaActualizacionDatosClienteTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestHeader">
        <wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
    </wsdl:message>
    <wsdl:message name="responseHeader">
        <wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
    </wsdl:message>
    <wsdl:message name="solicitaActualizacionDatosCliente">
        <wsdl:part element="tns:solicitaActualizacionDatosCliente" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="solicitaActualizacionDatosClienteResponse">
        <wsdl:part element="tns:solicitaActualizacionDatosClienteResponse" name="result"/>
    </wsdl:message>
    <wsdl:portType name="solicitaActualizacionDatosClientePS">
        <wsdl:operation name="solicitaActualizacionDatosCliente" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="sol:solicitaActualizacionDatosCliente"/>
            <wsdl:output message="sol:solicitaActualizacionDatosClienteResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="solicitaActualizacionDatosClientePSSOAP" type="sol:solicitaActualizacionDatosClientePS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="solicitaActualizacionDatosCliente">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/solicitaActualizacionDatosClientePS/solicitaActualizacionDatosCliente"/>
            <wsdl:input>
                <soap:body parts="parameters" use="literal"/>
                <soap:header message="sol:requestHeader" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body parts="result" use="literal"/>
                <soap:header message="sol:responseHeader" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="solicitaActualizacionDatosClientePS">
        <wsdl:port binding="sol:solicitaActualizacionDatosClientePSSOAP" name="solicitaActualizacionDatosClientePSSOAP">
            <soap:address location="http://10.9.104.55:8004/Middleware/SalesAndServices/CustomerManagement/solicitaActualizacionDatosCliente"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
