<wsdl:definitions name="ConsultaDatosTarjetaDebito" targetNamespace="http://www.ficohsa.com.hn/middleware.services/ConsultaDatosTarjetaDebitoTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:FicCdtd="http://www.ficohsa.com.hn/middleware.services/ConsultaDatosTarjetaDebitoTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	TYPE DEFINITION - List of services participating in this BPEL process
	The default output of the BPEL designer uses strings as input and 
	output to the BPEL Process. But you can define or import any XML 
	Schema type and use them as part of the message types.
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.ficohsa.com.hn/middleware.services/ConsultaDatosTarjetaDebitoTypes" schemaLocation="../xsd/ConsultaDatosTarjetaDebitoTypes.xsd"/>
		</schema>
	</wsdl:types>
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	MESSAGE TYPE DEFINITION - Definition of the message types used as 
	part of the port type defintions
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<wsdl:message name="ConsultaDatosTarjetaDebitoRequestMessage">
		<wsdl:part name="payload" element="FicCdtd:consultaDatosTarjetaDebitoRequest"/>
		<wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="ConsultaDatosTarjetaDebitoResponseMessage">
		<wsdl:part name="payload" element="FicCdtd:consultaDatosTarjetaDebitoResponse"/>
		<wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
	</wsdl:message>
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	PORT TYPE DEFINITION - A port type groups a set of operations into
	a logical service unit.
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<!-- portType implemented by the SolicitaHistorialCrediticio BPEL process -->
	<wsdl:portType name="ConsultaDatosTarjetaDebito">
		<wsdl:operation name="ConsultaDatosTarjetaDebito">
			<wsdl:input message="FicCdtd:ConsultaDatosTarjetaDebitoRequestMessage"/>
			<wsdl:output message="FicCdtd:ConsultaDatosTarjetaDebitoResponseMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	PARTNER LINK TYPE DEFINITION
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
	<wsdl:binding name="ConsultaDatosTarjetaDebitoSOAP" type="FicCdtd:ConsultaDatosTarjetaDebito">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="ConsultaDatosTarjetaDebito">
			<soap:operation style="document" soapAction="http://www.ficohsa.com.hn/middleware.services/ConsultaDatosTarjetaDebitoPS/ConsultaDatosTarjetaDebito"/>
			<wsdl:input>
				<soap:body use="literal" parts="payload"/>
				<soap:header message="FicCdtd:ConsultaDatosTarjetaDebitoRequestMessage" use="literal" part="RequestHeader"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="payload"/>
				<soap:header message="FicCdtd:ConsultaDatosTarjetaDebitoResponseMessage" use="literal" part="ResponseHeader"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ConsultaDatosTarjetaDebitoPS">
		<wsdl:port name="ConsultaDatosTarjetaDebitoPSSOAP" binding="FicCdtd:ConsultaDatosTarjetaDebitoSOAP">
			<soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Cards/ConsultaDatosTarjetaDebito"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>