<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/BITACORA_TERCERO/registraBitacoraTerceroEncabezado" name="registraBitacoraTerceroEncabezado-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/BITACORA_TERCERO/registraBitacoraTerceroEncabezado" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/BITACORA_TERCERO/registraBitacoraTerceroEncabezado" location="registraBitacoraTerceroEncabezado.wsdl"/>
  <binding name="registraBitacoraTerceroEncabezado_ptt-binding" type="tns:registraBitacoraTerceroEncabezado_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registraBitacoraTerceroEncabezado">
      <soap:operation soapAction="registraBitacoraTerceroEncabezado"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registraBitacoraTerceroEncabezado-service">
    <port name="registraBitacoraTerceroEncabezado-port" binding="tns:registraBitacoraTerceroEncabezado_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>