<wsdl:definitions name="consultaInformacionLaboralPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaInformacionLaboralPS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaInformacionLaboralTypes" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaInformacionLaboralPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../xsd/HeaderElements.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaInformacionLaboralTypes" schemaLocation="../xsd/GetEmploymentInformation.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="consultaInformacionLaboralPSRequest">
    <wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
    <wsdl:part element="cons:consultaInformacionLaboralRequest" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="consultaInformacionLaboralPSResponse">
    <wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
    <wsdl:part element="cons:consultaInformacionLaboralResponse" name="result"/>
  </wsdl:message>
  <wsdl:portType name="consultaInformacionLaboralPS">
    <wsdl:operation name="consultaInformacionLaboral" parameterOrder="parameters RequestHeader ResponseHeader">
      <wsdl:input message="fic:consultaInformacionLaboralPSRequest"/>
      <wsdl:output message="fic:consultaInformacionLaboralPSResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="consultaInformacionLaboralPSSOAP" type="fic:consultaInformacionLaboralPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultaInformacionLaboral">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaInformacionLaboralPS"/>
      <wsdl:input>
        <soap:body parts="parameters" use="literal"/>
        <soap:header message="fic:consultaInformacionLaboralPSRequest" part="RequestHeader" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="result" use="literal"/>
        <soap:header message="fic:consultaInformacionLaboralPSResponse" part="ResponseHeader" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="consultaInformacionLaboralPS">
    <wsdl:port binding="fic:consultaInformacionLaboralPSSOAP" name="consultaInformacionLaboralPSSOAP">
      <soap:address location="https://dynamoosbdev:8004/regional/pension/soap/getEmploymentInformation/v11g"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>