<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/LegacyCoreBankingHN/AmortizationSchedule_BS" name="AmortizationSchedule_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="AmortizationSchedule_BS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/LegacyCoreBankingHN/AmortizationSchedule_BS"/>
    <wsdl:binding name="AmortizationSchedule_BS_ptt-binding" type="amor:AmortizationSchedule_BS_ptt" xmlns:amor="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/LegacyCoreBankingHN/AmortizationSchedule_BS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="AmortizationSchedule_BS">
            <soap:operation soapAction="AmortizationSchedule_BS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>