<wsdl:definitions name="consultaDetalleLotePS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaDetalleLotePS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaDetalleLotePS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:trans="http://www.ficohsa.com.hn/middleware.services/aperturaMasivaTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../EsquemasGenerales/headerElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/aperturaMasivaTypes" schemaLocation="../../AperturaMasiva/xsd/aperturaMasivaTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaDetalleLoteRequest">
		<wsdl:part element="trans:consultaDetalleLoteRequest" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaDetalleLoteResponse">
		<wsdl:part element="trans:consultaDetalleLoteResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="consultaDetalleLotePS">
		<wsdl:operation name="consultaDetalleLote" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaDetalleLoteRequest"/>
			<wsdl:output message="fic:consultaDetalleLoteResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaDetalleLotePSSOAP" type="fic:consultaDetalleLotePS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaDetalleLote">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaDetalleLotePS/consultaDetalleLote"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaDetalleLoteRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaDetalleLoteResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaDetalleLotePS">
		<wsdl:port binding="fic:consultaDetalleLotePSSOAP" name="consultaDetalleLotePSSOAP">
			<soap:address location="https://mwomnicanal:8004/MWHostToHost/SalesAndServices/CustomerManagement/AperturaMasiva"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>