<wsdl:definitions name="consultaOfertaCreditoConsumoPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaOfertaCreditoConsumoPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaOfertaCreditoConsumoPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/consultaOfertaCreditoConsumoTypes">
  
    <wsdl:types>
	    <xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaOfertaCreditoConsumoTypes" schemaLocation="../xsd/consultaOfertaCreditoConsumoTypes.xsd"/>
		</xsd:schema>
 	 </wsdl:types>
  	
  	 <wsdl:message name="consultaOfertaCreditoConsumoRequest">
		<wsdl:part element="tns:consultaOfertaCreditoConsumoRequest" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaOfertaCreditoConsumoResponse">
		<wsdl:part element="tns:consultaOfertaCreditoConsumoResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="consultaOfertaCreditoConsumoPS">
		<wsdl:operation name="consultaOfertaCreditoConsumo" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaOfertaCreditoConsumoRequest"/>
			<wsdl:output message="fic:consultaOfertaCreditoConsumoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaOfertaCreditoConsumoPSSOAP" type="fic:consultaOfertaCreditoConsumoPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaOfertaCreditoConsumo">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaOfertaCreditoConsumoPS/consultaOfertaCreditoConsumo"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaOfertaCreditoConsumoRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaOfertaCreditoConsumoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="consultaOfertaCreditoConsumoPS">
    <wsdl:port binding="fic:consultaOfertaCreditoConsumoPSSOAP" name="consultaOfertaCreditoConsumoPSSOAP">
      <soap:address location="http://mwomnicanal:8003/Middleware/ReferenceData/CommonBusinessInformation/consultaOfertaCreditoConsumo"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>