<wsdl:definitions 
xmlns:giu="http://www.ficohsa.com.hn/middleware.services/procesarTransaccionCorePS/" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" 
name="procesarTransaccionCorePS" 
xmlns:cet="http://www.ficohsa.com.hn/middleware.services/procesarTransaccionCoreTypes"
targetNamespace="http://www.ficohsa.com.hn/middleware.services/procesarTransaccionCorePS/">


  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
		<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/procesarTransaccionCoreTypes" schemaLocation="../xsd/procesarTransaccionCoreTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
    <wsdl:message name="procesarTransaccionCore">
		<wsdl:part element="cet:procesarTransaccionCore" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>  
	<wsdl:message name="procesarTransaccionCoreResponse">
		<wsdl:part element="cet:procesarTransaccionCoreResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
  
  <wsdl:portType name="procesarTransaccionCorePS">
		<wsdl:operation name="procesarTransaccionCore" parameterOrder="parameters RequestHeader ResponseHeader">
		    <wsdl:input message="giu:procesarTransaccionCore"/>
			<wsdl:output message="giu:procesarTransaccionCoreResponse"/>
		</wsdl:operation>
	</wsdl:portType>
  
  <wsdl:binding name="procesarTransaccionCorePSSOAP" type="giu:procesarTransaccionCorePS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="procesarTransaccionCore">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/procesarTransaccionCorePS/procesarTransaccionCore"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="giu:procesarTransaccionCore" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="giu:procesarTransaccionCoreResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="procesarTransaccionCorePS">
    <wsdl:port binding="giu:procesarTransaccionCorePSSOAP" name="procesarTransaccionCorePSSOAP">
      <soap:address location="https://172.23.13.19:8004/Middleware/OperationsAndExecution/BankingPartner/procesarTransaccionCore"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
