<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:tns="http://copa.com/osb/userprofile"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="CopaUserProfileService" targetNamespace="http://copa.com/osb/userprofile">

  <types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://copa.com/osb/userprofile"
            xmlns:tns="http://copa.com/osb/userprofile"
            elementFormDefault="qualified">
    <xsd:include schemaLocation="../xsd/copaUserProfileTypes.xsd"/>
</xsd:schema>
  </types>

  <message name="CopaUserProfileRequestMessage">
    <part name="parameters" element="tns:copaUserProfileRequest"/>
  </message>

  <message name="CopaUserProfileResponseMessage">
    <part name="parameters" element="tns:copaUserProfileResponse"/>
  </message>

  <message name="CopaUserProfileResponseHeaderMessage">
    <part name="header" element="tns:CopaResponseHeader"/>
  </message>

  <portType name="CopaUserProfilePortType">
    <operation name="copaUserProfile">
      <input message="tns:CopaUserProfileRequestMessage"/>
      <output message="tns:CopaUserProfileResponseMessage"/>
    </operation>
  </portType>

  <binding name="CopaUserProfileBinding" type="tns:CopaUserProfilePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="copaUserProfile">
      <soap:operation soapAction="urn:copaUserProfile"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:header message="tns:CopaUserProfileResponseHeaderMessage" part="header" use="literal"/>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="CopaUserProfileService">
    <port name="CopaUserProfilePort" binding="tns:CopaUserProfileBinding">
      <soap:address location="https://oic-qa.ocservices.ficohsa.com:443/ic/ws/integration/v1/flows/soap/COPAUSERPROFILE/1.0"/>
    </port>
  </service>

</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="true" schemaLocation="../xsd/copaUserProfileTypes.xsd" namespace="http://copa.com/osb/userprofile" ref="Middleware/v2/BusinessServices/ConnectMiles/xsd/copaUserProfileTypes"/>
    </con:dependencies>
    <con:targetNamespace>http://copa.com/osb/userprofile</con:targetNamespace>
</con:wsdlEntry>