<wsdl:definitions name="sjGetRemittancesResilience" targetNamespace="http://xmlns.oracle.com/DynamoMigrate/CoreBankingHN/sjGetRemittancesResilience" xmlns:tns="http://xmlns.oracle.com/DynamoMigrate/CoreBankingHN/sjGetRemittancesResilience" xmlns:inp1="T24WebServicesImpl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jdjna="http://jaxb.dev.java.net/array">
  <plnk:partnerLinkType name="sjGetRemittancesResilience">
    <plnk:role name="sjGetRemittancesResilienceProvider" portType="tns:execute_ptt"/>
  </plnk:partnerLinkType>
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="T24WebServicesImpl" schemaLocation="../../../../ProviderServices/XSD/Remittances/Remittances.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import schemaLocation="../../../../ProviderServices/XSD/Remittances/RemittancesArray.xsd" namespace="http://jaxb.dev.java.net/array"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="sjGetRemittancesResilience">
    <wsdl:part name="parameters" element="inp1:Consultaderemesa"/>
  </wsdl:message>
  <wsdl:message name="sjGetRemittancesResilienceResponse">
    <wsdl:part name="parameters" element="inp1:ConsultaderemesaResponse"/>
  </wsdl:message>
  <wsdl:portType name="sjT24WebServicesImpl">
    <wsdl:operation name="Consultaderemesa">
      <wsdl:input message="tns:sjGetRemittancesResilience"/>
      <wsdl:output message="tns:sjGetRemittancesResilienceResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="T24WebServicesImplPortBinding" type="tns:sjT24WebServicesImpl">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Consultaderemesa">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="T24WebServicesImplService">
    <wsdl:port name="T24WebServicesImplPort" binding="tns:T24WebServicesImplPortBinding">
      <soap:address location="http://10.9.104.55:7003/svcRemesas/services"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>