<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/consultaConveniosH2H" name="consultaConveniosH2H-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/consultaConveniosH2H" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project2/consultaConveniosH2H" location="consultaConveniosH2H.wsdl"/>
  <binding name="consultaConveniosH2H_ptt-binding" type="tns:consultaConveniosH2H_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaConveniosH2H">
      <soap:operation soapAction="consultaConveniosH2H"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaConveniosH2H-service">
    <port name="consultaConveniosH2H-port" binding="tns:consultaConveniosH2H_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterfazdb"/>
    </port>
  </service>
</definitions>