<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project5/ProtecionIdentidad_EnvioCorreo" name="ProtecionIdentidad_EnvioCorreo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project5/ProtecionIdentidad_EnvioCorreo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application2/Project5/ProtecionIdentidad_EnvioCorreo" location="ProtecionIdentidad_EnvioCorreo.wsdl"/>
  <binding name="ProtecionIdentidad_EnvioCorreo_ptt-binding" type="tns:ProtecionIdentidad_EnvioCorreo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ProtecionIdentidad_EnvioCorreo">
      <soap:operation soapAction="ProtecionIdentidad_EnvioCorreo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ProtecionIdentidad_EnvioCorreo-service">
    <port name="ProtecionIdentidad_EnvioCorreo-port" binding="tns:ProtecionIdentidad_EnvioCorreo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionPMFraude"/>
    </port>
  </service>
</definitions>