<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/validarInformacionPago/validarInformacionPago/validarInformacionPago" name="validarInformacionPago-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/validarInformacionPago/validarInformacionPago/validarInformacionPago" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/validarInformacionPago/validarInformacionPago/validarInformacionPago" location="validarInformacionPago.wsdl"/>
  <binding name="validarInformacionPago_ptt-binding" type="tns:validarInformacionPago_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="validarInformacionPago">
      <soap:operation soapAction="validarInformacionPago"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="validarInformacionPago-service">
    <port name="validarInformacionPago-port" binding="tns:validarInformacionPago_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConveniosPA"/>
    </port>
  </service>
</definitions>