<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBConSaldosTCOffLine/registraPuntosLealtad/registraPuntosLealtad" name="registraPuntosLealtad-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBConSaldosTCOffLine/registraPuntosLealtad/registraPuntosLealtad" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBConSaldosTCOffLine/registraPuntosLealtad/registraPuntosLealtad" location="registraPuntosLealtad.wsdl"/>
  <binding name="registraPuntosLealtad_ptt-binding" type="tns:registraPuntosLealtad_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registraPuntosLealtad">
      <soap:operation soapAction="registraPuntosLealtad"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registraPuntosLealtad-service">
    <port name="registraPuntosLealtad-port" binding="tns:registraPuntosLealtad_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionClientdata"/>
    </port>
  </service>
</definitions>