<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/RegistrarUsoServicio/registrarUsoServicio" name="registrarUsoServicio-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/RegistrarUsoServicio/registrarUsoServicio" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/RegistrarUsoServicio/registrarUsoServicio" location="registrarUsoServicio.wsdl"/>
  <binding name="registrarUsoServicio_ptt-binding" type="tns:registrarUsoServicio_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registrarUsoServicio">
      <soap:operation soapAction="registrarUsoServicio"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="registrarUsoServicio-service">
    <port name="registrarUsoServicio-port" binding="tns:registrarUsoServicio_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>