<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Strongview/Strongview/obtenerbfemBitacoraEC" name="obtenerbfemBitacoraEC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Strongview/Strongview/obtenerbfemBitacoraEC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Strongview/Strongview/obtenerbfemBitacoraEC" location="obtenerbfemBitacoraEC.wsdl"/>
  <binding name="obtenerbfemBitacoraEC_ptt-binding" type="tns:obtenerbfemBitacoraEC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="obtenerbfemBitacoraEC">
      <soap:operation soapAction="obtenerbfemBitacoraEC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="obtenerbfemBitacoraEC-service">
    <port name="obtenerbfemBitacoraEC-port" binding="tns:obtenerbfemBitacoraEC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionStrongview"/>
    </port>
  </service>
</definitions>