<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="DeviceInfo_BS" targetNamespace="http://xmlns.oracle.com/VUSecurity/Middleware/DeviceInfo_BS" xmlns:tns="http://xmlns.oracle.com/VUSecurity/Middleware/DeviceInfo_BS" xmlns:inp1="http://www.ficohsa.com.hn/middleware.services/DeviceInfoTypes" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="DeviceInfo_BS">
        <plnk:role name="DeviceInfo_BSProvider" portType="tns:DeviceInfo_BS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/DeviceInfoTypes" schemaLocation="../xsd/DeviceInfoTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="getDevices_inputMessage">
        <wsdl:part name="request" element="inp1:DeviceInfoRequestVU"/>
    </wsdl:message>
    <wsdl:message name="getDevices_outputMessage">
        <wsdl:part name="reply" element="inp1:DeviceInfoResponseVU"/>
    </wsdl:message>
    <wsdl:portType name="DeviceInfo_BS_ptt">
        <wsdl:operation name="getDevices">
            <wsdl:input message="tns:getDevices_inputMessage"/>
            <wsdl:output message="tns:getDevices_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="DeviceInfo_BS_ptt-binding" type="tns:DeviceInfo_BS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getDevices">
            <soap:operation soapAction="getDevices"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../xsd/DeviceInfoTypes.xsd" namespace="http://www.ficohsa.com.hn/middleware.services/DeviceInfoTypes" ref="Middleware/v2/Resources/DeviceInfo/xsd/DeviceInfoTypes"/>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/VUSecurity/Middleware/DeviceInfo_BS</con:targetNamespace>
</con:wsdlEntry>