<wsdl:definitions name="GetParametersRestBS" targetNamespace="http://xmlns.oracle.com/SBRG_MassivePayment/SBRG_MassivePayment_Commons/GetParametersRestBS" xmlns:tns="http://xmlns.oracle.com/SBRG_MassivePayment/SBRG_MassivePayment_Commons/GetParametersRestBS" xmlns:inp1="https://www.ficohsa.com/regional/utility/constants" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="GetParametersRestBS">
        <plnk:role name="GetParametersRestBSProvider" portType="tns:GetParametersRestBS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www.ficohsa.com/regional/utility/constants" schemaLocation="SBRG_Constants_Commons/Schemas/CustomParameter.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="GetParameters_inputMessage">
        <wsdl:part name="request" element="inp1:GetParameters"/>
    </wsdl:message>
    <wsdl:message name="GetParameters_outputMessage">
        <wsdl:part name="reply" element="inp1:GetParametersResponse"/>
    </wsdl:message>
    <wsdl:portType name="GetParametersRestBS_ptt">
        <wsdl:operation name="GetParameters">
            <wsdl:input message="tns:GetParameters_inputMessage"/>
            <wsdl:output message="tns:GetParameters_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="GetParametersRestBS_ptt-binding" type="tns:GetParametersRestBS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="GetParameters">
            <soap:operation soapAction="GetParameters"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>