<wsdl:definitions name="LoggingRegionalRestBS" targetNamespace="http://xmlns.oracle.com/SBRG_MassivePayment/SBRG_MassivePayment_Commons/LoggingRegionalRestBS" xmlns:tns="http://xmlns.oracle.com/SBRG_MassivePayment/SBRG_MassivePayment_Commons/LoggingRegionalRestBS" xmlns:inp1="https://www.ficohsa.com/regional/utility/logging" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="LoggingRegionalRestBS">
        <plnk:role name="LoggingRegionalRestBSProvider" portType="tns:LoggingRegionalRestBS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www.ficohsa.com/regional/utility/logging" schemaLocation="SBRG_Logging_Commons/Schemas/LoggingRegional.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="SaveLogInFileSystem_inputMessage">
        <wsdl:part name="request" element="inp1:LoggingInput"/>
    </wsdl:message>
    <wsdl:message name="Rest_EmptyMessage"/>
    <wsdl:portType name="LoggingRegionalRestBS_ptt">
        <wsdl:operation name="SaveLogInFileSystem">
            <wsdl:input message="tns:SaveLogInFileSystem_inputMessage"/>
            <wsdl:output message="tns:Rest_EmptyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="LoggingRegionalRestBS_ptt-binding" type="tns:LoggingRegionalRestBS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="SaveLogInFileSystem">
            <soap:operation soapAction="SaveLogInFileSystem"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>