<wsdl:definitions name="WriteToFileSystemRestBS" targetNamespace="http://xmlns.oracle.com/SBRG_MassivePayment/SBRG_MassivePayment_Commons/WriteToFileSystemRestBS" xmlns:tns="http://xmlns.oracle.com/SBRG_MassivePayment/SBRG_MassivePayment_Commons/WriteToFileSystemRestBS" xmlns:inp1="https://www.ficohsa.com/regional/utility/logging" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="WriteToFileSystemRestBS">
        <plnk:role name="WriteToFileSystemRestBSProvider" portType="tns:WriteToFileSystemRestBS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www.ficohsa.com/regional/utility/logging" schemaLocation="SBRG_Logging_Commons/Schemas/Log.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="WriteToFileSystem_inputMessage">
        <wsdl:part name="request" element="inp1:logElement"/>
    </wsdl:message>
    <wsdl:message name="Rest_EmptyMessage"/>
    <wsdl:portType name="WriteToFileSystemRestBS_ptt">
        <wsdl:operation name="WriteToFileSystem">
            <wsdl:input message="tns:WriteToFileSystem_inputMessage"/>
            <wsdl:output message="tns:Rest_EmptyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="WriteToFileSystemRestBS_ptt-binding" type="tns:WriteToFileSystemRestBS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="WriteToFileSystem">
            <soap:operation soapAction="WriteToFileSystem"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>