<wsdl:definitions name="consultaRubroPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaRubroPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaRubroPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaRubroTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaRubroTypes" schemaLocation="consultaRubroTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaRubroRequest">
		<wsdl:part element="cons:consultaRubro" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaRubroResponse">
		<wsdl:part element="cons:consultaRubroResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaRubroPS">
		<wsdl:operation name="consultaRubro" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaRubroRequest"/>
			<wsdl:output message="fic:consultaRubroResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaRubroPSSOAP" type="fic:consultaRubroPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaRubro">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaRubroPS/consultaRubro"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaRubroRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaRubroResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaRubroPS">
		<wsdl:port binding="fic:consultaRubroPSSOAP" name="consultaRubroPSSOAP">
			<soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/Payments/consultaRubro"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>