<wsdl:definitions name="consultaNroContratoDEIPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaNroContratoDEIPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaNroContratoDEIPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/tributosTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/tributosTypes" schemaLocation="../../TributosDEI/xsd/tributosTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultarNroContratoRequest">
		<wsdl:part element="cons:consultarNroContrato" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultarNroContratoResponse">
		<wsdl:part element="cons:consultarNroContratoResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultarNroContratoDEIPS">
		<wsdl:operation name="consultarNroContrato" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultarNroContratoRequest"/>
			<wsdl:output message="fic:consultarNroContratoResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultarNroContratoDEIPSSOAP" type="fic:consultarNroContratoDEIPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultarNroContrato">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultarNroContratoDEIPS/consultarNroContrato"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultarNroContratoRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultarNroContratoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultarNroContratoDEIPS">
		<wsdl:port binding="fic:consultarNroContratoDEIPSSOAP" name="consultarNroContratoDEIPSSOAP">
			<soap:address location="http://172.23.13.19:8003/Middleware/ReferenceData/BusinessPartner/consultarNroContrato"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>