<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication1/SBProject/SecActualizaSolicitudRemesa" name="SecActualizaSolicitudRemesa-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication1/SBProject/SecActualizaSolicitudRemesa" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication1/SBProject/SecActualizaSolicitudRemesa" location="SecActualizaSolicitudRemesa.wsdl"/>
  <binding name="SecActualizaSolicitudRemesa_ptt-binding" type="tns:SecActualizaSolicitudRemesa_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="SecActualizaSolicitudRemesa">
      <soap:operation soapAction="SecActualizaSolicitudRemesa"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="SecActualizaSolicitudRemesa-service">
    <port name="SecActualizaSolicitudRemesa-port" binding="tns:SecActualizaSolicitudRemesa_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>