<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ModificaMontoDebitoAFP/ModificaMontoDebitoAFP" name="ModificaMontoDebitoAFP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ModificaMontoDebitoAFP/ModificaMontoDebitoAFP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ModificaMontoDebitoAFP/ModificaMontoDebitoAFP" location="ModificaMontoDebitoAFP.wsdl"/>
  <binding name="ModificaMontoDebitoAFP_ptt-binding" type="tns:ModificaMontoDebitoAFP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ModificaMontoDebitoAFP">
      <soap:operation soapAction="ModificaMontoDebitoAFP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ModificaMontoDebitoAFP-service">
    <port name="ModificaMontoDebitoAFP-port" binding="tns:ModificaMontoDebitoAFP_ptt-binding">
      <soap:address location="jca://eis/DB/jdbc/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>