<wsdl:definitions name="consultaMaestraSaldoCuentaPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaMaestraSaldoCuentaPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaMaestraSaldoCuentaPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultasType">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultasType" schemaLocation="../Resources/consultasGeneralesCuentasTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaMaestraSaldoCuentaRequest">
		<wsdl:part element="cons:consultaMaestraSaldoCuenta" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaMaestraSaldoCuentaResponse">
		<wsdl:part element="cons:consultaMaestraSaldoCuentaResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaMaestraSaldoCuentaPS">
		<wsdl:operation name="consultaMaestraSaldoCuenta" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaMaestraSaldoCuentaRequest"/>
			<wsdl:output message="fic:consultaMaestraSaldoCuentaResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaMaestraSaldoCuentaPSSOAP" type="fic:consultaMaestraSaldoCuentaPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaMaestraSaldoCuenta">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaMaestraSaldoCuentaPS/consultaMaestraSaldoCuenta"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaMaestraSaldoCuentaRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaMaestraSaldoCuentaResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaMaestraSaldoCuentaPS">
		<wsdl:port binding="fic:consultaMaestraSaldoCuentaPSSOAP" name="consultaMaestraSaldoCuentaPSSOAP">
			<soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/CustomerDeposits/consultaMaestraSaldoCuenta"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>