<wsdl:definitions name="consultaInformacionHUELLAPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaInformacionHUELLAPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaInformacionHUELLAPS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/consultaInformacionRENAPTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaInformacionRENAPTypes" schemaLocation="../../ConsultaInformacionRENAP/xsd/consultaInformacionRENAPTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="consultaInformacionHUELLARequest">
		<wsdl:part element="tns:consultaInformacionHUELLA" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaInformacionHUELLAResponse">
		<wsdl:part element="tns:consultaInformacionHUELLAResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="consultaInformacionHUELLAPS">
		<wsdl:operation name="consultaInformacionHUELLA" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaInformacionHUELLARequest"/>
			<wsdl:output message="fic:consultaInformacionHUELLAResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="consultaInformacionHUELLAPSSOAP" type="fic:consultaInformacionHUELLAPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaInformacionHUELLA">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaInformacionHUELLAPS/consultaInformacionHUELLA"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaInformacionHUELLARequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaInformacionHUELLAResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaInformacionHUELLAPS">
		<wsdl:port binding="fic:consultaInformacionHUELLAPSSOAP" name="consultaInformacionHUELLAPSSOAP">
			<soap:address location="https://172.23.13.19:8004/Middleware/ReferenceData/BusinessPartner/ConsultaInformacionRENAP"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>