<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/desembolsaPrestamo/desembolsaPrestamo" name="desembolsaPrestamo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/desembolsaPrestamo/desembolsaPrestamo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/desembolsaPrestamo/desembolsaPrestamo" location="desembolsaPrestamo.wsdl"/>
  <binding name="desembolsaPrestamo_ptt-binding" type="tns:desembolsaPrestamo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="desembolsaPrestamo">
      <soap:operation soapAction="desembolsaPrestamo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="desembolsaPrestamo-service">
    <port name="desembolsaPrestamo-port" binding="tns:desembolsaPrestamo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>