<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ejemplo/conDatoAutorizacionesHistoricaGT/conDatoAutorizacionesHistorica" name="conDatoAutorizacionesHistorica-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Ejemplo/conDatoAutorizacionesHistoricaGT/conDatoAutorizacionesHistorica" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Ejemplo/conDatoAutorizacionesHistoricaGT/conDatoAutorizacionesHistorica" location="conDatoAutorizacionesHistorica.wsdl"/>
  <binding name="conDatoAutorizacionesHistorica_ptt-binding" type="tns:conDatoAutorizacionesHistorica_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conDatoAutorizacionesHistorica">
      <soap:operation soapAction="conDatoAutorizacionesHistorica"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conDatoAutorizacionesHistorica-service">
    <port name="conDatoAutorizacionesHistorica-port" binding="tns:conDatoAutorizacionesHistorica_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>