<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/armarPagoRecaudo/armarConsultaRecaudo/armarConsultaRecaudo" name="armarConsultaRecaudo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/armarPagoRecaudo/armarConsultaRecaudo/armarConsultaRecaudo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/armarPagoRecaudo/armarConsultaRecaudo/armarConsultaRecaudo" location="armarConsultaRecaudo.wsdl"/>
  <binding name="armarConsultaRecaudo_ptt-binding" type="tns:armarConsultaRecaudo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="armarConsultaRecaudo">
      <soap:operation soapAction="armarConsultaRecaudo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="armarConsultaRecaudo-service">
    <port name="armarConsultaRecaudo-port" binding="tns:armarConsultaRecaudo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConveniosPA"/>
    </port>
  </service>
</definitions>