<wsdl:definitions name="aplicaDebitoChequePS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/aplicaDebitoChequePS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/aplicaDebitoChequePS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/aplicaDebitoChequeTypes">
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/aplicaDebitoChequeTypes" schemaLocation="aplicaDebitoChequeTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="aplicaDebitoChequeRequest">
		<wsdl:part element="cons:aplicaDebitoCheque" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="aplicaDebitoChequeResponse">
		<wsdl:part element="cons:aplicaDebitoChequeResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="aplicaDebitoChequePS">
		<wsdl:operation name="aplicaDebitoCheque" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:aplicaDebitoChequeRequest"/>
			<wsdl:output message="fic:aplicaDebitoChequeResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="aplicaDebitoChequePSSOAP" type="fic:aplicaDebitoChequePS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="aplicaDebitoCheque">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/aplicaDebitoChequePS/aplicaDebitoCheque"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:aplicaDebitoChequeRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:aplicaDebitoChequeResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="aplicaDebitoChequePS">
		<wsdl:port binding="fic:aplicaDebitoChequePSSOAP" name="aplicaDebitoChequePSSOAP">
			<soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/Payments/AplicaDebitoCheque"/>
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>