<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SPEnvents/CustomerTSP/customerTSP" name="customerTSP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SPEnvents/CustomerTSP/customerTSP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SPEnvents/CustomerTSP/customerTSP" location="customerTSP.wsdl"/>
  <binding name="customerTSP_ptt-binding" type="tns:customerTSP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="customerTSP">
      <soap:operation soapAction="customerTSP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="customerTSP-service">
    <port name="customerTSP-port" binding="tns:customerTSP_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionEventsRepository"/>
    </port>
  </service>
</definitions>