<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareCobroTSPTransferencia/CobroTSPTransferencia/cobroTSPTransferencia" name="cobroTSPTransferencia-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareCobroTSPTransferencia/CobroTSPTransferencia/cobroTSPTransferencia" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareCobroTSPTransferencia/CobroTSPTransferencia/cobroTSPTransferencia" location="cobroTSPTransferencia.wsdl"/>
  <binding name="cobroTSPTransferencia_ptt-binding" type="tns:cobroTSPTransferencia_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="cobroTSPTransferencia">
      <soap:operation soapAction="cobroTSPTransferencia"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="cobroTSPTransferencia-service">
    <port name="cobroTSPTransferencia-port" binding="tns:cobroTSPTransferencia_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTSP"/>
    </port>
  </service>
</definitions>