<wsdl:definitions name="actualizaParametrosPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/actualizaParametrosPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/actualizaParametrosPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:trans="http://www.ficohsa.com.hn/middleware.services/aperturaMasivaTypes" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../EsquemasGenerales/headerElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/aperturaMasivaTypes" schemaLocation="../../AperturaMasiva/xsd/aperturaMasivaTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="actualizaParametrosRequest">
		<wsdl:part element="trans:actualizaParametrosRequest" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="actualizaParametrosResponse">
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="actualizaParametrosPS">
		<wsdl:operation name="actualizaParametros" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:actualizaParametrosRequest"/>
			<wsdl:output message="fic:actualizaParametrosResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="actualizaParametrosPSSOAP" type="fic:actualizaParametrosPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="actualizaParametros">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/actualizaParametrosPS/actualizaParametros"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:actualizaParametrosRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:header message="fic:actualizaParametrosResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="actualizaParametrosPS">
		<wsdl:port binding="fic:actualizaParametrosPSSOAP" name="actualizaParametrosPSSOAP">
			<soap:address location="https://mwomnicanal:8004/MWHostToHost/SalesAndServices/CustomerManagement/AperturaMasiva"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>