<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Convenios/BancaSat/PagoISV_TC_Declaraguate" name="PagoISV_TC_Declaraguate-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Convenios/BancaSat/PagoISV_TC_Declaraguate" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Convenios/BancaSat/PagoISV_TC_Declaraguate" location="PagoISV_TC_Declaraguate.wsdl"/>
  <binding name="PagoISV_TC_Declaraguate_ptt-binding" type="tns:PagoISV_TC_Declaraguate_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="PagoISV_TC_Declaraguate">
      <soap:operation soapAction="PagoISV_TC_Declaraguate"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="PagoISV_TC_Declaraguate-service">
    <port name="PagoISV_TC_Declaraguate-port" binding="tns:PagoISV_TC_Declaraguate_ptt-binding">
      <soap:address location="jca://eis/DB/TercerosGT"/>
    </port>
  </service>
</definitions>