<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="GetCustomerDetailsRestBS" targetNamespace="http://xmlns.oracle.com/SBHN_Pension/SBHN_Pension_GetCustomerDetails/GetCustomerDetailsRestBS" xmlns:tns="http://xmlns.oracle.com/SBHN_Pension/SBHN_Pension_GetCustomerDetails/GetCustomerDetailsRestBS" xmlns:inp1="https://www.ficohsa.com/honduras/pension" xmlns:inp2="https://www.ficohsa.com/honduras/pension" xmlns:inp3="https://www.ficohsa.com/honduras/pension" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="GetCustomerDetailsRestBS">
        <plnk:role name="GetCustomerDetailsRestBSProvider" portType="tns:GetCustomerDetailsRestBS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www.ficohsa.com/honduras/pension" schemaLocation="../Schemas/CustomerLocatorFavoritesTypes.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www.ficohsa.com/honduras/pension" schemaLocation="../Schemas/CustomerWorkTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="GetFavorites_inputMessage">
        <wsdl:part name="request" element="inp1:customerLocatorFavoritesRequest"/>
    </wsdl:message>
    <wsdl:message name="GetFavorites_outputMessage">
        <wsdl:part name="reply" element="inp1:customerLocatorFavoritesResponse"/>
    </wsdl:message>
    <wsdl:message name="GetWorkInformation_inputMessage">
        <wsdl:part name="request" element="inp1:customerWorkRequest"/>
    </wsdl:message>
    <wsdl:message name="GetWorkInformation_outputMessage">
        <wsdl:part name="reply" element="inp1:customerWorkResponse"/>
    </wsdl:message>
    <wsdl:portType name="GetCustomerDetailsRestBS_ptt">
        <wsdl:operation name="GetFavorites">
            <wsdl:input message="tns:GetFavorites_inputMessage"/>
            <wsdl:output message="tns:GetFavorites_outputMessage"/>
        </wsdl:operation>
        <wsdl:operation name="GetWorkInformation">
            <wsdl:input message="tns:GetWorkInformation_inputMessage"/>
            <wsdl:output message="tns:GetWorkInformation_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="GetCustomerDetailsRestBS_ptt-binding" type="tns:GetCustomerDetailsRestBS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="GetFavorites">
            <soap:operation soapAction="GetFavorites"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GetWorkInformation">
            <soap:operation soapAction="GetWorkInformation"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../Schemas/CustomerLocatorFavoritesTypes.xsd" namespace="https://www.ficohsa.com/honduras/pension" ref="SBHN_Pension_GetCustomerDetails/Schemas/CustomerLocatorFavoritesTypes"/>
        <con:schemaRef isInclude="false" schemaLocation="../Schemas/CustomerWorkTypes.xsd" namespace="https://www.ficohsa.com/honduras/pension" ref="SBHN_Pension_GetCustomerDetails/Schemas/CustomerWorkTypes"/>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/SBHN_Pension/SBHN_Pension_GetCustomerDetails/GetCustomerDetailsRestBS</con:targetNamespace>
</con:wsdlEntry>