<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaEmailPersonaFPC/consultaEmailPersonaFPC" name="consultaEmailPersonaFPC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaEmailPersonaFPC/consultaEmailPersonaFPC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/consultaEmailPersonaFPC/consultaEmailPersonaFPC" location="consultaEmailPersonaFPC.wsdl"/>
  <binding name="consultaEmailPersonaFPC_ptt-binding" type="tns:consultaEmailPersonaFPC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaEmailPersonaFPC">
      <soap:operation soapAction="consultaEmailPersonaFPC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaEmailPersonaFPC-service">
    <port name="consultaEmailPersonaFPC-port" binding="tns:consultaEmailPersonaFPC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionFicopen"/>
    </port>
  </service>
</definitions>