<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MCRegFlujoEfectivo/MCRegFlujoEfectivo" name="MCRegFlujoEfectivo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MCRegFlujoEfectivo/MCRegFlujoEfectivo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MCRegFlujoEfectivo/MCRegFlujoEfectivo" location="MCRegFlujoEfectivo.wsdl"/>
  <binding name="MCRegFlujoEfectivo_ptt-binding" type="tns:MCRegFlujoEfectivo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="MCRegFlujoEfectivo">
      <soap:operation soapAction="MCRegFlujoEfectivo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="MCRegFlujoEfectivo-service">
    <port name="MCRegFlujoEfectivo-port" binding="tns:MCRegFlujoEfectivo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>