<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/OBTENER_TIPO_REMESADORA/ObtenerTipoRemesadora" name="ObtenerTipoRemesadora-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/OBTENER_TIPO_REMESADORA/ObtenerTipoRemesadora" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TESTWS/OBTENER_TIPO_REMESADORA/ObtenerTipoRemesadora" location="ObtenerTipoRemesadora.wsdl"/>
  <binding name="ObtenerTipoRemesadora_ptt-binding" type="tns:ObtenerTipoRemesadora_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ObtenerTipoRemesadora">
      <soap:operation soapAction="ObtenerTipoRemesadora"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ObtenerTipoRemesadora-service">
    <port name="ObtenerTipoRemesadora-port" binding="tns:ObtenerTipoRemesadora_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>