<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/creaBin/creaBin/creaBin" name="creaBin-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/creaBin/creaBin/creaBin" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/creaBin/creaBin/creaBin" location="creaBin.wsdl"/>
  <binding name="creaBin_ptt-binding" type="tns:creaBin_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="creaBin">
      <soap:operation soapAction="creaBin"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="creaBin-service">
    <port name="creaBin-port" binding="tns:creaBin_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>