<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingGT/GetLoanDetailsGT_BS" name="GetLoanDetailsGT_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GetLoanDetailsGT_BS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingGT/GetLoanDetailsGT_BS"/>
    <wsdl:binding name="GetLoanDetailsGT_BS_ptt-binding" type="get:GetLoanDetailsGT_BS_ptt" xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingGT/GetLoanDetailsGT_BS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="GetLoanDetailsGT_BS">
            <soap:operation soapAction="GetLoanDetailsGT_BS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>