<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ABANKSHNMod/cambiaEstadoAccesoUsuario" name="cambiaEstadoAccesoUsuario-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ABANKSHNMod/cambiaEstadoAccesoUsuario" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ABANKSHNMod/cambiaEstadoAccesoUsuario" location="cambiaEstadoAccesoUsuario.wsdl"/>
  <binding name="cambiaEstadoAccesoUsuario_ptt-binding" type="tns:cambiaEstadoAccesoUsuario_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="cambiaEstadoAccesoUsuario">
      <soap:operation soapAction="cambiaEstadoAccesoUsuario"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="cambiaEstadoAccesoUsuario-service">
    <port name="cambiaEstadoAccesoUsuario-port" binding="tns:cambiaEstadoAccesoUsuario_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>