<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/ConsultaFechaSistema/consultaFechaSistema" name="consultaFechaSistema-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/ConsultaFechaSistema/consultaFechaSistema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/ConsultaFechaSistema/consultaFechaSistema" location="consultaFechaSistema.wsdl"/>
  <binding name="consultaFechaSistema_ptt-binding" type="tns:consultaFechaSistema_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaFechaSistema">
      <soap:operation soapAction="consultaFechaSistema"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaFechaSistema-service">
    <port name="consultaFechaSistema-port" binding="tns:consultaFechaSistema_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>