<wsdl:definitions name="sjTransferenciaInternacionalH2HPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjTransferenciaInternacionalH2HPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/sjTransferenciaInternacionalH2HPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:hcob="http://www.ficohsa.com.hn/middleware.services/sjTransfersH2HTypes">

    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjTransfersH2HTypes" schemaLocation="../xsd/sjTransferenciaInternacionalH2H.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="sjTransferenciaInternacionalH2HRequest">
        <wsdl:part element="hcob:sjTransferenciaInternacionalRequest" name="inputParameters"/>
    </wsdl:message>

    <wsdl:message name="sjTransferenciaInternacionalH2HResponse">
        <wsdl:part element="hcob:sjTransferenciaInternacionalResponse" name="outputParameters"/>
    </wsdl:message>

    <wsdl:portType name="sjTransferenciaInternacionalH2HPS">
        <wsdl:operation name="sjTransferencia" parameterOrder="inputParameters">
            <wsdl:input message="fic:sjTransferenciaInternacionalH2HRequest"/>
            <wsdl:output message="fic:sjTransferenciaInternacionalH2HResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="sjTransferenciaInternacionalH2HPSSOAP" type="fic:sjTransferenciaInternacionalH2HPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="sjTransferencia">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/sjTransferenciaInternacionalH2HPS/op"/>
            <wsdl:input>
                <soap:body use="literal" parts="inputParameters"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="outputParameters"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="sjTransferenciaInternacionalH2HPS">
        <wsdl:port binding="fic:sjTransferenciaInternacionalH2HPSSOAP" name="sjTransferenciaInternacionalH2HPSSOAP">
            <soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Payments/TransferenciaInternacionalH2H"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>