<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/validaCanjeCupon" name="validaCanjeCupon-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/validaCanjeCupon" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/validaCanjeCupon" location="validaCanjeCupon.wsdl"/>
  <binding name="validaCanjeCupon_ptt-binding" type="tns:validaCanjeCupon_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="validaCanjeCupon">
      <soap:operation soapAction="validaCanjeCupon"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="validaCanjeCupon-service">
    <port name="validaCanjeCupon-port" binding="tns:validaCanjeCupon_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionOperacionesTD"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="validaCanjeCupon.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/validaCanjeCupon">
            <con:wsdl ref="Middleware/v2/BusinessServices/OperacionesTarjetaDebito/ValidaCanjeCupon_db/wsdl/validaCanjeCupon"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/RetiroSinTD/validaCanjeCupon</con:targetNamespace>
</con:wsdlEntry>