<wsdl:definitions targetNamespace="http://www.ficohsa.com.hn/middleware.services/bulkProvisionStatusJob" name="bulkProvisionStatusJobOIC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/bulkProvisionStatusJob" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:com="http://www.ficohsa.com.hn/middleware.services/bulkProvisionStatusJobTypes">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/bulkProvisionStatusJobTypes" schemaLocation="../xsd/bulkProvisionStatusJobTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="BulkProvisionStatusJob">
		<wsdl:part element="com:BulkProvisionStatusJob" name="parameters"/>
	</wsdl:message>
	<wsdl:message name="BulkProvisionStatusJobResponse">
		<wsdl:part element="com:BulkProvisionStatusJobResponse" name="result"/>
	</wsdl:message>
	<wsdl:portType name="bulkProvisionStatusJobOIC">
		<wsdl:operation name="bulkProvisionStatusJob">
			<wsdl:input message="fic:BulkProvisionStatusJob"/>
			<wsdl:output message="fic:BulkProvisionStatusJobResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="bulkProvisionStatusJobOICSOAP" type="fic:bulkProvisionStatusJobOIC">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="bulkProvisionStatusJob">
			<soap:operation soapAction="bulkProvisionStatusJob"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="bulkProvisionStatusJobOIC">
		<wsdl:port binding="fic:bulkProvisionStatusJobOICSOAP" name="bulkProvisionStatusJobOICSOAP">
			<soap:address location="https://oicproddr-ficocloud-px.integration.ocp.oraclecloud.com/ic/ws/integration/v1/flows/soap/BULKPROVISIONSTATUSJOB/1.0/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>