<wsdl:definitions name="consultaSobregiroCuentaPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaSobregiroCuentaPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaSobregiroCuentaPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaSobregiroCuentaTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaSobregiroCuentaTypes" schemaLocation="../xsd/consultaSobregiroCuentaTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="consultaSobregiroCuentaRequest">
		<wsdl:part element="cons:consultaSobregiroCuenta" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaSobregiroCuentaResponse">
		<wsdl:part element="cons:consultaSobregiroCuentaResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="consultaSobregiroCuentaPS">
		<wsdl:operation name="consultaSobregiroCuenta" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaSobregiroCuentaRequest"/>
			<wsdl:output message="fic:consultaSobregiroCuentaResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaSobregiroCuentaPSSOAP" type="fic:consultaSobregiroCuentaPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaSobregiroCuenta">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaSobregiroCuentaPS/consultaSobregiroCuenta"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaSobregiroCuentaRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaSobregiroCuentaResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="consultaSobregiroCuentaPS">
    <wsdl:port binding="fic:consultaSobregiroCuentaPSSOAP" name="consultaSobregiroCuentaPSSOAP">
      <soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/CustomerDeposits/consultaSobregiroCuenta"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>