<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultaSeguros/consultaSeguros/consultaSeguros" name="consultaSeguros-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/consultaSeguros/consultaSeguros/consultaSeguros" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultaSeguros/consultaSeguros/consultaSeguros" location="consultaSeguros.wsdl"/>
  <binding name="consultaSeguros_ptt-binding" type="tns:consultaSeguros_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaSeguros">
      <soap:operation soapAction="consultaSeguros"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaSeguros-service">
    <port name="consultaSeguros-port" binding="tns:consultaSeguros_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionClientdata"/>
    </port>
  </service>
</definitions>