<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/EnviarCorreoLauKey/verificarEnvioCorreo" name="verificarEnvioCorreo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/EnviarCorreoLauKey/verificarEnvioCorreo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/EnviarCorreoLauKey/verificarEnvioCorreo" location="verificarEnvioCorreo.wsdl"/>
  <binding name="verificarEnvioCorreo_ptt-binding" type="tns:verificarEnvioCorreo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="verificarEnvioCorreo">
      <soap:operation soapAction="verificarEnvioCorreo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="verificarEnvioCorreo-service">
    <port name="verificarEnvioCorreo-port" binding="tns:verificarEnvioCorreo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionAppEnvioCorreo"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="verificarEnvioCorreo.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/EnviarCorreoLauKey/verificarEnvioCorreo">
            <con:wsdl ref="Middleware/v2/BusinessServices/EnvioCorreoLauKey/verificarEnvioCorreo/wsdl/verificarEnvioCorreo"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/Application1/EnviarCorreoLauKey/verificarEnvioCorreo</con:targetNamespace>
</con:wsdlEntry>