<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/consultaParametrosCBR" name="consultaParametrosCBR-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/consultaParametrosCBR" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/consultaParametrosCBR" location="consultaParametrosCBR.wsdl"/>
  <binding name="consultaParametrosCBR_ptt-binding" type="tns:consultaParametrosCBR_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaParametrosCBR">
      <soap:operation soapAction="consultaParametrosCBR"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaParametrosCBR-service">
    <port name="consultaParametrosCBR-port" binding="tns:consultaParametrosCBR_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="consultaParametrosCBR.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/consultaParametrosCBR">
            <con:wsdl ref="MWHostToHost/v1/BusinessServices/ABKHN/consultaParametrosCBR/wsdl/consultaParametrosCBR"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/Application1/Project1/consultaParametrosCBR</con:targetNamespace>
</con:wsdlEntry>