<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application3/Project3/registrarBitacoraH2H" name="registrarBitacoraH2H-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application3/Project3/registrarBitacoraH2H" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application3/Project3/registrarBitacoraH2H" location="registrarBitacoraH2H.wsdl"/>
  <binding name="registrarBitacoraH2H_ptt-binding" type="tns:registrarBitacoraH2H_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="registrarBitacoraH2H">
      <soap:operation soapAction="registrarBitacoraH2H"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="registrarBitacoraH2H-service">
    <port name="registrarBitacoraH2H-port" binding="tns:registrarBitacoraH2H_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterfazdb"/>
    </port>
  </service>
</definitions>