<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksPASOAApplication/ConsultaTasaCambio/consultaTasaCambio" name="consultaTasaCambio-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksPASOAApplication/ConsultaTasaCambio/consultaTasaCambio" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksPASOAApplication/ConsultaTasaCambio/consultaTasaCambio" location="consultaTasaCambio.wsdl"/>
  <binding name="consultaTasaCambio_ptt-binding" type="tns:consultaTasaCambio_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaTasaCambio">
      <soap:operation soapAction="consultaTasaCambio"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaTasaCambio-service">
    <port name="consultaTasaCambio-port" binding="tns:consultaTasaCambio_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksPA"/>
    </port>
  </service>
</definitions>