<wsdl:definitions name="validacionCuentaPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/validacionCuentaPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/validacionCuentaPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:trans="http://www.ficohsa.com.hn/middleware.services/validacionCuentaType" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../../../v2/Resources/esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/validacionCuentaType" schemaLocation="../xsd/validacionCuentaType.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="validacionCuenta">
		<wsdl:part element="trans:validacionCuenta" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="validacionCuentaResponse">
		<wsdl:part element="trans:validacionCuentaResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="validacionCuentaPS">
		<wsdl:operation name="validacionCuenta" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:validacionCuenta"/>
			<wsdl:output message="fic:validacionCuentaResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="validacionCuentaPSSOAP" type="fic:validacionCuentaPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="validacionCuenta">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/validacionCuentaPS/validacionCuenta"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				
				<soap:header message="fic:validacionCuenta" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:validacionCuentaResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="validacionCuentaPS">
		<wsdl:port binding="fic:validacionCuentaPSSOAP" name="validacionCuentaPSSOAP">
			<soap:address location="http://mwomnidesa:8003/Middleware/OperationsAndExecution/CalculationServices/ValidacionCuenta"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>