<wsdl:definitions name="notificaDivisasPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/notificaDivisasPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:not="http://www.ficohsa.com.hn/middleware.services/notificaDivisasPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/notificaDivisasTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/notificaDivisasTypes" schemaLocation="../xsd/notificaDivisasTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestHeader">
        <wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
    </wsdl:message>
    <wsdl:message name="responseHeader">
        <wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
    </wsdl:message>
    <wsdl:message name="notificaDivisas">
        <wsdl:part element="tns:notificaDivisas" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="notificaDivisasResponse">
        <wsdl:part element="tns:notificaDivisasResponse" name="result"/>
    </wsdl:message>
    <wsdl:portType name="notificaDivisasPS">
        <wsdl:operation name="notificaDivisas" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="not:notificaDivisas"/>
            <wsdl:output message="not:notificaDivisasResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="notificaDivisasPSSOAP" type="not:notificaDivisasPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="notificaDivisas">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/notificaDivisasPS/notificaDivisas"/>
            <wsdl:input>
                <soap:body parts="parameters" use="literal"/>
                <soap:header message="not:requestHeader" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body parts="result" use="literal"/>
                <soap:header message="not:responseHeader" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="notificaDivisasPS">
        <wsdl:port binding="not:notificaDivisasPSSOAP" name="notificaDivisasPSSOAP">
            <soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Payments/CompraVentaDivisas"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
