<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="Soap12" 
    targetNamespace="http://schemas.servicestack.net/types" 
    xmlns:svc="http://schemas.servicestack.net/types" 
    xmlns:tns="http://schemas.servicestack.net/types" 
    
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
    xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" 
    xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" 
    xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" 
    xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" 
    xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" 
    xmlns:wsa10="http://www.w3.org/2005/08/addressing" 
    xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex">

	<wsdl:types>
		<xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="anyType" nillable="true" type="xs:anyType" />
  <xs:element name="anyURI" nillable="true" type="xs:anyURI" />
  <xs:element name="base64Binary" nillable="true" type="xs:base64Binary" />
  <xs:element name="boolean" nillable="true" type="xs:boolean" />
  <xs:element name="byte" nillable="true" type="xs:byte" />
  <xs:element name="dateTime" nillable="true" type="xs:dateTime" />
  <xs:element name="decimal" nillable="true" type="xs:decimal" />
  <xs:element name="double" nillable="true" type="xs:double" />
  <xs:element name="float" nillable="true" type="xs:float" />
  <xs:element name="int" nillable="true" type="xs:int" />
  <xs:element name="long" nillable="true" type="xs:long" />
  <xs:element name="QName" nillable="true" type="xs:QName" />
  <xs:element name="short" nillable="true" type="xs:short" />
  <xs:element name="string" nillable="true" type="xs:string" />
  <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte" />
  <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt" />
  <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong" />
  <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort" />
  <xs:element name="char" nillable="true" type="tns:char" />
  <xs:simpleType name="char">
    <xs:restriction base="xs:int" />
  </xs:simpleType>
  <xs:element name="duration" nillable="true" type="tns:duration" />
  <xs:simpleType name="duration">
    <xs:restriction base="xs:duration">
      <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?" />
      <xs:minInclusive value="-P10675199DT2H48M5.4775808S" />
      <xs:maxInclusive value="P10675199DT2H48M5.4775807S" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="guid" nillable="true" type="tns:guid" />
  <xs:simpleType name="guid">
    <xs:restriction base="xs:string">
      <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}" />
    </xs:restriction>
  </xs:simpleType>
  <xs:attribute name="FactoryType" type="xs:QName" />
  <xs:attribute name="Id" type="xs:ID" />
  <xs:attribute name="Ref" type="xs:IDREF" />
</xs:schema>
<xs:schema xmlns:tns="http://schemas.servicestack.net/types" elementFormDefault="qualified" targetNamespace="http://schemas.servicestack.net/types" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
  <xs:complexType name="DatosHNPago">
    <xs:sequence>
      <xs:element minOccurs="0" name="Clave" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="DatosBanco" nillable="true" type="tns:DatosBanco" />
      <xs:element minOccurs="0" name="Fecha" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Hora" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="IDTrans" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Monto" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNPago" nillable="true" type="tns:DatosHNPago" />
  <xs:complexType name="DatosBanco">
    <xs:sequence>
      <xs:element minOccurs="0" name="Agencia" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Banco" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Sucursal" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Terminal" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Usuario" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosBanco" nillable="true" type="tns:DatosBanco" />
  <xs:complexType name="DatosHNConsulta">
    <xs:sequence>
      <xs:element minOccurs="0" name="Clave" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="DatosBanco" nillable="true" type="tns:DatosBanco" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNConsulta" nillable="true" type="tns:DatosHNConsulta" />
  <xs:complexType name="DatosHNReversion">
    <xs:sequence>
      <xs:element minOccurs="0" name="Clave" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="DatosBanco" nillable="true" type="tns:DatosBanco" />
      <xs:element minOccurs="0" name="Fecha" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Hora" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="IDTrans" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Monto" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNReversion" nillable="true" type="tns:DatosHNReversion" />
  <xs:complexType name="DatosHNValidaChecksum">
    <xs:sequence>
      <xs:element minOccurs="0" name="Banco" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="CheckSum" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Clave" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Fecha" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Monto" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNValidaChecksum" nillable="true" type="tns:DatosHNValidaChecksum" />
  <xs:complexType name="DatosHNConsultaUtimoPago">
    <xs:sequence>
      <xs:element minOccurs="0" name="Clave" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNConsultaUtimoPago" nillable="true" type="tns:DatosHNConsultaUtimoPago" />
  <xs:complexType name="DatosHNConsultaUltPagoBanco">
    <xs:sequence>
      <xs:element minOccurs="0" name="Banco" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Clave" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNConsultaUltPagoBanco" nillable="true" type="tns:DatosHNConsultaUltPagoBanco" />
  <xs:complexType name="DatosHNAnulaAutorizacion">
    <xs:sequence>
      <xs:element minOccurs="0" name="Clave" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNAnulaAutorizacion" nillable="true" type="tns:DatosHNAnulaAutorizacion" />
  <xs:complexType name="DatosHNGrabaAutorizacion">
    <xs:sequence>
      <xs:element minOccurs="0" name="Clave" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Observacion" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Razon" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Valor" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNGrabaAutorizacion" nillable="true" type="tns:DatosHNGrabaAutorizacion" />
  <xs:complexType name="DatosHNConsultaPagosPend">
    <xs:sequence>
      <xs:element minOccurs="0" name="Clave" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNConsultaPagosPend" nillable="true" type="tns:DatosHNConsultaPagosPend" />
  <xs:complexType name="DatosHNValidaPago">
    <xs:sequence>
      <xs:element minOccurs="0" name="Clave" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="DatosBanco" nillable="true" type="tns:DatosBanco" />
      <xs:element minOccurs="0" name="Fecha" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Monto" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNValidaPago" nillable="true" type="tns:DatosHNValidaPago" />
  <xs:complexType name="ConvertSessionToToken">
    <xs:sequence>
      <xs:element minOccurs="0" name="PreserveSession" type="xs:boolean" />
      <xs:element minOccurs="0" name="Meta" nillable="true" xmlns:q1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" type="q1:ArrayOfKeyValueOfstringstring" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ConvertSessionToToken" nillable="true" type="tns:ConvertSessionToToken" />
  <xs:complexType name="GetAccessToken">
    <xs:sequence>
      <xs:element minOccurs="0" name="RefreshToken" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="UseTokenCookie" nillable="true" type="xs:boolean" />
      <xs:element minOccurs="0" name="Meta" nillable="true" xmlns:q2="http://schemas.microsoft.com/2003/10/Serialization/Arrays" type="q2:ArrayOfKeyValueOfstringstring" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="GetAccessToken" nillable="true" type="tns:GetAccessToken" />
  <xs:complexType name="DatosHNPagoResponse">
    <xs:complexContent mixed="false">
      <xs:extension base="tns:DatosHNResponse">
        <xs:sequence>
          <xs:element minOccurs="0" name="Cajero" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="CheckSum" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="DatosFactura" nillable="true" type="tns:DatosHNFactura2" />
          <xs:element minOccurs="0" name="FechaTransaccion" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="IdTransaccionBanco" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="ReferenciaPago" nillable="true" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="DatosHNPagoResponse" nillable="true" type="tns:DatosHNPagoResponse" />
  <xs:complexType name="DatosHNResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="CodigoError" type="xs:int" />
      <xs:element minOccurs="0" name="Mensaje" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Resultado" type="xs:boolean" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNResponse" nillable="true" type="tns:DatosHNResponse" />
  <xs:complexType name="DatosHNFactura2">
    <xs:sequence>
      <xs:element minOccurs="0" name="CargoISV" type="xs:double" />
      <xs:element minOccurs="0" name="CiudadSucursal" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Claveprimaria" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="DescTrans" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="EntiAgencia" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Nis" type="xs:double" />
      <xs:element minOccurs="0" name="Nombre" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="SubtotalsinISV" type="xs:double" />
      <xs:element minOccurs="0" name="Totalcalculado" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNFactura2" nillable="true" type="tns:DatosHNFactura2" />
  <xs:complexType name="DatosHNConsultaResponse">
    <xs:complexContent mixed="false">
      <xs:extension base="tns:DatosHNResponse">
        <xs:sequence>
          <xs:element minOccurs="0" name="DatosFactura" nillable="true" type="tns:DatosHNFactura" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="DatosHNConsultaResponse" nillable="true" type="tns:DatosHNConsultaResponse" />
  <xs:complexType name="DatosHNFactura">
    <xs:sequence>
      <xs:element minOccurs="0" name="CargoISV" type="xs:double" />
      <xs:element minOccurs="0" name="Cargodemanda" type="xs:double" />
      <xs:element minOccurs="0" name="Cargoreactivo" type="xs:double" />
      <xs:element minOccurs="0" name="CargosPeriodo" type="xs:double" />
      <xs:element minOccurs="0" name="Cargovoltaje" type="xs:double" />
      <xs:element minOccurs="0" name="Claveprimaria" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Clavesecundaria" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Cobroalumbrado" type="xs:double" />
      <xs:element minOccurs="0" name="Cobroenergia" type="xs:double" />
      <xs:element minOccurs="0" name="Cobrointeres" type="xs:double" />
      <xs:element minOccurs="0" name="Diasfacturados" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Factorpotencia" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Fechaactual" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Fechaanterior" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Fechaemision" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Lectactual" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Lectanterior" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Numaviso" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="OtrosDebcred" type="xs:double" />
      <xs:element minOccurs="0" name="SaldoMesant" type="xs:double" />
      <xs:element minOccurs="0" name="SubtotalsinISV" type="xs:double" />
      <xs:element minOccurs="0" name="Totalcalculado" type="xs:double" />
      <xs:element minOccurs="0" name="UltMesfacturado" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Vlrrectificacion" type="xs:double" />
      <xs:element minOccurs="0" name="consumo" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="contador" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="direccion" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="lecturaAviso" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="multiplo" type="xs:double" />
      <xs:element minOccurs="0" name="nombre" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="pagos" type="xs:double" />
      <xs:element minOccurs="0" name="reactivo" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="subsidio" type="xs:double" />
      <xs:element minOccurs="0" name="tarifa" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNFactura" nillable="true" type="tns:DatosHNFactura" />
  <xs:complexType name="DatosHNReversionResponse">
    <xs:complexContent mixed="false">
      <xs:extension base="tns:DatosHNResponse">
        <xs:sequence>
          <xs:element minOccurs="0" name="RefAnulacion" nillable="true" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="DatosHNReversionResponse" nillable="true" type="tns:DatosHNReversionResponse" />
  <xs:complexType name="DatosHNValidaChecksumResponse">
    <xs:complexContent mixed="false">
      <xs:extension base="tns:DatosHNResponse">
        <xs:sequence />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="DatosHNValidaChecksumResponse" nillable="true" type="tns:DatosHNValidaChecksumResponse" />
  <xs:complexType name="DatosHNConsultaUtimoPagoResponse">
    <xs:complexContent mixed="false">
      <xs:extension base="tns:DatosHNResponse">
        <xs:sequence>
          <xs:element minOccurs="0" name="Clave" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="CodigoBanco" type="xs:double" />
          <xs:element minOccurs="0" name="CodigoSucursal" type="xs:double" />
          <xs:element minOccurs="0" name="EstadoPago" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="FechaPago" type="xs:dateTime" />
          <xs:element minOccurs="0" name="NombreBanco" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="NombreEstado" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="NombreSucursal" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="ValorImpuesto" type="xs:double" />
          <xs:element minOccurs="0" name="ValorPago" type="xs:double" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="DatosHNConsultaUtimoPagoResponse" nillable="true" type="tns:DatosHNConsultaUtimoPagoResponse" />
  <xs:complexType name="DatosHNConsultaUltPagoBancoResponse">
    <xs:complexContent mixed="false">
      <xs:extension base="tns:DatosHNResponse">
        <xs:sequence>
          <xs:element minOccurs="0" name="Clave" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="CodigoBanco" type="xs:double" />
          <xs:element minOccurs="0" name="CodigoSucursal" type="xs:double" />
          <xs:element minOccurs="0" name="FechaPago" type="xs:dateTime" />
          <xs:element minOccurs="0" name="IDBanco" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="IDPasarela" type="xs:double" />
          <xs:element minOccurs="0" name="NombreBanco" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="NombreSucursal" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="ValorImpuesto" type="xs:double" />
          <xs:element minOccurs="0" name="ValorPago" type="xs:double" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="DatosHNConsultaUltPagoBancoResponse" nillable="true" type="tns:DatosHNConsultaUltPagoBancoResponse" />
  <xs:complexType name="DatosHNAnulaAutorizacionResponse">
    <xs:complexContent mixed="false">
      <xs:extension base="tns:DatosHNResponse">
        <xs:sequence />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="DatosHNAnulaAutorizacionResponse" nillable="true" type="tns:DatosHNAnulaAutorizacionResponse" />
  <xs:complexType name="DatosHNGrabaAutorizacionResponse">
    <xs:complexContent mixed="false">
      <xs:extension base="tns:DatosHNResponse">
        <xs:sequence>
          <xs:element minOccurs="0" name="Referencia" nillable="true" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="DatosHNGrabaAutorizacionResponse" nillable="true" type="tns:DatosHNGrabaAutorizacionResponse" />
  <xs:complexType name="DatosHNConsultaPagosPendResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="ImpuestoPend" type="xs:double" />
      <xs:element minOccurs="0" name="TotalPagoPend" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="DatosHNConsultaPagosPendResponse" nillable="true" type="tns:DatosHNConsultaPagosPendResponse" />
  <xs:complexType name="DatosHNValidaPagoResponse">
    <xs:complexContent mixed="false">
      <xs:extension base="tns:DatosHNResponse">
        <xs:sequence>
          <xs:element minOccurs="0" name="CheckSum" nillable="true" type="xs:string" />
          <xs:element minOccurs="0" name="DatosFactura" nillable="true" type="tns:DatosHNFactura" />
          <xs:element minOccurs="0" name="ReferenciaPago" nillable="true" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="DatosHNValidaPagoResponse" nillable="true" type="tns:DatosHNValidaPagoResponse" />
  <xs:complexType name="GetNavItemsResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="BaseUrl" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Results" nillable="true" type="tns:ArrayOfNavItem" />
      <xs:element minOccurs="0" name="NavItemsMap" nillable="true" xmlns:q3="http://schemas.microsoft.com/2003/10/Serialization/Arrays" type="q3:ArrayOfKeyValueOfstringArrayOfNavItemEdXdwojR" />
      <xs:element minOccurs="0" name="Meta" nillable="true" xmlns:q4="http://schemas.microsoft.com/2003/10/Serialization/Arrays" type="q4:ArrayOfKeyValueOfstringstring" />
      <xs:element minOccurs="0" name="ResponseStatus" nillable="true" type="tns:ResponseStatus" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="GetNavItemsResponse" nillable="true" type="tns:GetNavItemsResponse" />
  <xs:complexType name="ArrayOfNavItem">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="NavItem" nillable="true" type="tns:NavItem" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ArrayOfNavItem" nillable="true" type="tns:ArrayOfNavItem" />
  <xs:complexType name="NavItem">
    <xs:sequence>
      <xs:element minOccurs="0" name="Children" nillable="true" type="tns:ArrayOfNavItem" />
      <xs:element minOccurs="0" name="ClassName" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Exact" nillable="true" type="xs:boolean" />
      <xs:element minOccurs="0" name="Hide" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Href" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="IconClass" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Id" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Label" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Meta" nillable="true" xmlns:q5="http://schemas.microsoft.com/2003/10/Serialization/Arrays" type="q5:ArrayOfKeyValueOfstringstring" />
      <xs:element minOccurs="0" name="Show" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="NavItem" nillable="true" type="tns:NavItem" />
  <xs:complexType name="ResponseStatus">
    <xs:sequence>
      <xs:element minOccurs="0" name="ErrorCode" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Message" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="StackTrace" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Errors" nillable="true" type="tns:ArrayOfResponseError" />
      <xs:element minOccurs="0" name="Meta" nillable="true" xmlns:q6="http://schemas.microsoft.com/2003/10/Serialization/Arrays" type="q6:ArrayOfKeyValueOfstringstring" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ResponseStatus" nillable="true" type="tns:ResponseStatus" />
  <xs:complexType name="ArrayOfResponseError">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="ResponseError" nillable="true" type="tns:ResponseError" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ArrayOfResponseError" nillable="true" type="tns:ArrayOfResponseError" />
  <xs:complexType name="ResponseError">
    <xs:sequence>
      <xs:element minOccurs="0" name="ErrorCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <DefaultValue EmitDefaultValue="false" xmlns="http://schemas.microsoft.com/2003/10/Serialization/" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="FieldName" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <DefaultValue EmitDefaultValue="false" xmlns="http://schemas.microsoft.com/2003/10/Serialization/" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Message" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo>
            <DefaultValue EmitDefaultValue="false" xmlns="http://schemas.microsoft.com/2003/10/Serialization/" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Meta" nillable="true" xmlns:q7="http://schemas.microsoft.com/2003/10/Serialization/Arrays" type="q7:ArrayOfKeyValueOfstringstring">
        <xs:annotation>
          <xs:appinfo>
            <DefaultValue EmitDefaultValue="false" xmlns="http://schemas.microsoft.com/2003/10/Serialization/" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ResponseError" nillable="true" type="tns:ResponseError" />
  <xs:complexType name="ConvertSessionToTokenResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="Meta" nillable="true" xmlns:q8="http://schemas.microsoft.com/2003/10/Serialization/Arrays" type="q8:ArrayOfKeyValueOfstringstring" />
      <xs:element minOccurs="0" name="AccessToken" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="RefreshToken" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="ResponseStatus" nillable="true" type="tns:ResponseStatus" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ConvertSessionToTokenResponse" nillable="true" type="tns:ConvertSessionToTokenResponse" />
  <xs:complexType name="GetAccessTokenResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="AccessToken" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="Meta" nillable="true" xmlns:q9="http://schemas.microsoft.com/2003/10/Serialization/Arrays" type="q9:ArrayOfKeyValueOfstringstring" />
      <xs:element minOccurs="0" name="ResponseStatus" nillable="true" type="tns:ResponseStatus" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="GetAccessTokenResponse" nillable="true" type="tns:GetAccessTokenResponse" />
</xs:schema>
<xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import namespace="http://schemas.servicestack.net/types" />
  <xs:complexType name="ArrayOfKeyValueOfstringstring">
    <xs:annotation>
      <xs:appinfo>
        <IsDictionary xmlns="http://schemas.microsoft.com/2003/10/Serialization/">true</IsDictionary>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="KeyValueOfstringstring">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Key" nillable="true" type="xs:string" />
            <xs:element name="Value" nillable="true" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ArrayOfKeyValueOfstringstring" nillable="true" type="tns:ArrayOfKeyValueOfstringstring" />
  <xs:complexType name="ArrayOfKeyValueOfstringArrayOfNavItemEdXdwojR">
    <xs:annotation>
      <xs:appinfo>
        <IsDictionary xmlns="http://schemas.microsoft.com/2003/10/Serialization/">true</IsDictionary>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="KeyValueOfstringArrayOfNavItemEdXdwojR">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Key" nillable="true" type="xs:string" />
            <xs:element name="Value" nillable="true" xmlns:q1="http://schemas.servicestack.net/types" type="q1:ArrayOfNavItem" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ArrayOfKeyValueOfstringArrayOfNavItemEdXdwojR" nillable="true" type="tns:ArrayOfKeyValueOfstringArrayOfNavItemEdXdwojR" />
</xs:schema>
	</wsdl:types>
    <wsdl:message name="DatosHNPagoIn">
        <wsdl:part name="par" element="tns:DatosHNPago" />
    </wsdl:message>
    <wsdl:message name="DatosHNPagoOut">
        <wsdl:part name="par" element="tns:DatosHNPagoResponse" />
    </wsdl:message><wsdl:message name="DatosHNConsultaIn">
        <wsdl:part name="par" element="tns:DatosHNConsulta" />
    </wsdl:message>
    <wsdl:message name="DatosHNConsultaOut">
        <wsdl:part name="par" element="tns:DatosHNConsultaResponse" />
    </wsdl:message><wsdl:message name="DatosHNReversionIn">
        <wsdl:part name="par" element="tns:DatosHNReversion" />
    </wsdl:message>
    <wsdl:message name="DatosHNReversionOut">
        <wsdl:part name="par" element="tns:DatosHNReversionResponse" />
    </wsdl:message><wsdl:message name="DatosHNValidaChecksumIn">
        <wsdl:part name="par" element="tns:DatosHNValidaChecksum" />
    </wsdl:message>
    <wsdl:message name="DatosHNValidaChecksumOut">
        <wsdl:part name="par" element="tns:DatosHNValidaChecksumResponse" />
    </wsdl:message><wsdl:message name="DatosHNConsultaUtimoPagoIn">
        <wsdl:part name="par" element="tns:DatosHNConsultaUtimoPago" />
    </wsdl:message>
    <wsdl:message name="DatosHNConsultaUtimoPagoOut">
        <wsdl:part name="par" element="tns:DatosHNConsultaUtimoPagoResponse" />
    </wsdl:message><wsdl:message name="DatosHNConsultaUltPagoBancoIn">
        <wsdl:part name="par" element="tns:DatosHNConsultaUltPagoBanco" />
    </wsdl:message>
    <wsdl:message name="DatosHNConsultaUltPagoBancoOut">
        <wsdl:part name="par" element="tns:DatosHNConsultaUltPagoBancoResponse" />
    </wsdl:message><wsdl:message name="DatosHNAnulaAutorizacionIn">
        <wsdl:part name="par" element="tns:DatosHNAnulaAutorizacion" />
    </wsdl:message>
    <wsdl:message name="DatosHNAnulaAutorizacionOut">
        <wsdl:part name="par" element="tns:DatosHNAnulaAutorizacionResponse" />
    </wsdl:message><wsdl:message name="DatosHNGrabaAutorizacionIn">
        <wsdl:part name="par" element="tns:DatosHNGrabaAutorizacion" />
    </wsdl:message>
    <wsdl:message name="DatosHNGrabaAutorizacionOut">
        <wsdl:part name="par" element="tns:DatosHNGrabaAutorizacionResponse" />
    </wsdl:message><wsdl:message name="DatosHNConsultaPagosPendIn">
        <wsdl:part name="par" element="tns:DatosHNConsultaPagosPend" />
    </wsdl:message>
    <wsdl:message name="DatosHNConsultaPagosPendOut">
        <wsdl:part name="par" element="tns:DatosHNConsultaPagosPendResponse" />
    </wsdl:message><wsdl:message name="DatosHNValidaPagoIn">
        <wsdl:part name="par" element="tns:DatosHNValidaPago" />
    </wsdl:message>
    <wsdl:message name="DatosHNValidaPagoOut">
        <wsdl:part name="par" element="tns:DatosHNValidaPagoResponse" />
    </wsdl:message><wsdl:message name="ConvertSessionToTokenIn">
        <wsdl:part name="par" element="tns:ConvertSessionToToken" />
    </wsdl:message>
    <wsdl:message name="ConvertSessionToTokenOut">
        <wsdl:part name="par" element="tns:ConvertSessionToTokenResponse" />
    </wsdl:message><wsdl:message name="GetAccessTokenIn">
        <wsdl:part name="par" element="tns:GetAccessToken" />
    </wsdl:message>
    <wsdl:message name="GetAccessTokenOut">
        <wsdl:part name="par" element="tns:GetAccessTokenResponse" />
    </wsdl:message>

	

	<wsdl:portType name="ISyncReply"><wsdl:operation name="DatosHNPago">
        <wsdl:input message="svc:DatosHNPagoIn" />
        <wsdl:output message="svc:DatosHNPagoOut" />
    </wsdl:operation><wsdl:operation name="DatosHNConsulta">
        <wsdl:input message="svc:DatosHNConsultaIn" />
        <wsdl:output message="svc:DatosHNConsultaOut" />
    </wsdl:operation><wsdl:operation name="DatosHNReversion">
        <wsdl:input message="svc:DatosHNReversionIn" />
        <wsdl:output message="svc:DatosHNReversionOut" />
    </wsdl:operation><wsdl:operation name="DatosHNValidaChecksum">
        <wsdl:input message="svc:DatosHNValidaChecksumIn" />
        <wsdl:output message="svc:DatosHNValidaChecksumOut" />
    </wsdl:operation><wsdl:operation name="DatosHNConsultaUtimoPago">
        <wsdl:input message="svc:DatosHNConsultaUtimoPagoIn" />
        <wsdl:output message="svc:DatosHNConsultaUtimoPagoOut" />
    </wsdl:operation><wsdl:operation name="DatosHNConsultaUltPagoBanco">
        <wsdl:input message="svc:DatosHNConsultaUltPagoBancoIn" />
        <wsdl:output message="svc:DatosHNConsultaUltPagoBancoOut" />
    </wsdl:operation><wsdl:operation name="DatosHNAnulaAutorizacion">
        <wsdl:input message="svc:DatosHNAnulaAutorizacionIn" />
        <wsdl:output message="svc:DatosHNAnulaAutorizacionOut" />
    </wsdl:operation><wsdl:operation name="DatosHNGrabaAutorizacion">
        <wsdl:input message="svc:DatosHNGrabaAutorizacionIn" />
        <wsdl:output message="svc:DatosHNGrabaAutorizacionOut" />
    </wsdl:operation><wsdl:operation name="DatosHNConsultaPagosPend">
        <wsdl:input message="svc:DatosHNConsultaPagosPendIn" />
        <wsdl:output message="svc:DatosHNConsultaPagosPendOut" />
    </wsdl:operation><wsdl:operation name="DatosHNValidaPago">
        <wsdl:input message="svc:DatosHNValidaPagoIn" />
        <wsdl:output message="svc:DatosHNValidaPagoOut" />
    </wsdl:operation><wsdl:operation name="ConvertSessionToToken">
        <wsdl:input message="svc:ConvertSessionToTokenIn" />
        <wsdl:output message="svc:ConvertSessionToTokenOut" />
    </wsdl:operation><wsdl:operation name="GetAccessToken">
        <wsdl:input message="svc:GetAccessTokenIn" />
        <wsdl:output message="svc:GetAccessTokenOut" />
    </wsdl:operation></wsdl:portType>

	

	<wsdl:binding name="WSHttpBinding_ISyncReply" type="svc:ISyncReply">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="DatosHNPago">
      <soap12:operation soapAction="http://schemas.servicestack.net/types/DatosHNPago" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation><wsdl:operation name="DatosHNConsulta">
      <soap12:operation soapAction="http://schemas.servicestack.net/types/DatosHNConsulta" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation><wsdl:operation name="DatosHNReversion">
      <soap12:operation soapAction="http://schemas.servicestack.net/types/DatosHNReversion" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation><wsdl:operation name="DatosHNValidaChecksum">
      <soap12:operation soapAction="http://schemas.servicestack.net/types/DatosHNValidaChecksum" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation><wsdl:operation name="DatosHNConsultaUtimoPago">
      <soap12:operation soapAction="http://schemas.servicestack.net/types/DatosHNConsultaUtimoPago" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation><wsdl:operation name="DatosHNConsultaUltPagoBanco">
      <soap12:operation soapAction="http://schemas.servicestack.net/types/DatosHNConsultaUltPagoBanco" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation><wsdl:operation name="DatosHNAnulaAutorizacion">
      <soap12:operation soapAction="http://schemas.servicestack.net/types/DatosHNAnulaAutorizacion" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation><wsdl:operation name="DatosHNGrabaAutorizacion">
      <soap12:operation soapAction="http://schemas.servicestack.net/types/DatosHNGrabaAutorizacion" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation><wsdl:operation name="DatosHNConsultaPagosPend">
      <soap12:operation soapAction="http://schemas.servicestack.net/types/DatosHNConsultaPagosPend" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation><wsdl:operation name="DatosHNValidaPago">
      <soap12:operation soapAction="http://schemas.servicestack.net/types/DatosHNValidaPago" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation><wsdl:operation name="ConvertSessionToToken">
      <soap12:operation soapAction="http://schemas.servicestack.net/types/ConvertSessionToToken" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation><wsdl:operation name="GetAccessToken">
      <soap12:operation soapAction="http://schemas.servicestack.net/types/GetAccessToken" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    </wsdl:binding>
        
	

	<wsdl:service name="SyncReply">
        <wsdl:port name="WSHttpBinding_ISyncReply" binding="svc:WSHttpBinding_ISyncReply">
            <soap12:address location="https://pruebas.recaudoenee.com:4999/soap12" />
        </wsdl:port>
    </wsdl:service>

	
	
</wsdl:definitions>