<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/conDatosTarjetaCliente/conDatosTarjetaCliente" name="conDatosTarjetaCliente-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/conDatosTarjetaCliente/conDatosTarjetaCliente" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/conDatosTarjetaCliente/conDatosTarjetaCliente" location="conDatosTarjetaCliente.wsdl"/>
  <binding name="conDatosTarjetaCliente_ptt-binding" type="tns:conDatosTarjetaCliente_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conDatosTarjetaCliente">
      <soap:operation soapAction="conDatosTarjetaCliente"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conDatosTarjetaCliente-service">
    <port name="conDatosTarjetaCliente-port" binding="tns:conDatosTarjetaCliente_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="conDatosTarjetaCliente.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/conDatosTarjetaCliente/conDatosTarjetaCliente">
            <con:wsdl ref="Middleware/v2/BusinessServices/MasterDataGT/conDatosTarjetaCliente/wsdl/conDatosTarjetaCliente"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/conDatosTarjetaCliente/conDatosTarjetaCliente</con:targetNamespace>
</con:wsdlEntry>