<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AppMiddleware/consultaLotes/consultaLotes" name="consultaLotes-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AppMiddleware/consultaLotes/consultaLotes" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AppMiddleware/consultaLotes/consultaLotes" location="consultaLotes.wsdl"/>
  <binding name="consultaLotes_ptt-binding" type="tns:consultaLotes_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaLotes">
      <soap:operation soapAction="consultaLotes"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaLotes-service">
    <port name="consultaLotes-port" binding="tns:consultaLotes_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionDebitCard"/>
    </port>
  </service>
</definitions>