<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBconDatoEstado/conDatoEstado/conDatoEstado" name="conDatoEstado-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBconDatoEstado/conDatoEstado/conDatoEstado" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBconDatoEstado/conDatoEstado/conDatoEstado" location="conDatoEstado.wsdl"/>
  <binding name="conDatoEstado_ptt-binding" type="tns:conDatoEstado_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conDatoEstado">
      <soap:operation soapAction="conDatoEstado"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conDatoEstado-service">
    <port name="conDatoEstado-port" binding="tns:conDatoEstado_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>