<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/conTransaccionesActuales_v2/conTransaccionesActuales_v2" name="conTransaccionesActuales_v2-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/conTransaccionesActuales_v2/conTransaccionesActuales_v2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionTarjetasGT/conTransaccionesActuales_v2/conTransaccionesActuales_v2" location="conTransaccionesActuales_v2.wsdl"/>
  <binding name="conTransaccionesActuales_v2_ptt-binding" type="tns:conTransaccionesActuales_v2_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conTransaccionesActuales_v2">
      <soap:operation soapAction="conTransaccionesActuales_v2"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conTransaccionesActuales_v2-service">
    <port name="conTransaccionesActuales_v2-port" binding="tns:conTransaccionesActuales_v2_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProcesosGT"/>
    </port>
  </service>
</definitions>