<xsd:schema targetNamespace="https://www.ficohsa.com/regional/referencedata" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="https://www.ficohsa.com/regional/referencedata" xmlns:ctp="https://www.ficohsa.com/regional/common/commonTypes" xmlns:rd="https://www.ficohsa.com/regional/common/referenceDataCommonType">
  <xsd:import schemaLocation="CommonTypes.xsd" namespace="https://www.ficohsa.com/regional/common/commonTypes"/>
  <xsd:import schemaLocation="ReferenceDataCommonTypes.xsd" id="ReferenceDataCommonTypes" namespace="https://www.ficohsa.com/regional/common/referenceDataCommonType"/>
  <xsd:element name="getBankAgencies">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="GeneralInfo" type="ctp:GeneralInfoType" minOccurs="1"/>
        <xsd:element name="BranchCode" type="xsd:string" minOccurs="0"/>
        <xsd:element name="BranchType" type="xsd:string" minOccurs="0"/>
        <xsd:element name="GeographicZone" type="xsd:string" minOccurs="0"/>
        <xsd:element name="ServiceCode" type="xsd:string" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="getBankAgenciesResponse">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="StatusInfo" type="ctp:StatusInfoType" minOccurs="1"/>
        <xsd:element name="ErrorInfo" type="ctp:ErrorInfoType" minOccurs="0"/>
        <xsd:element name="AgenciesDetails" type="rd:AgenciesDetailsType" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  
  
  
   
  <!--Entrega 5-->
  
  <xsd:element name="getSystemDate">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="GeneralInfo" type="ctp:GeneralInfoType"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="getSystemDateResponse">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="StatusInfo" type="ctp:StatusInfoType" minOccurs="1"/>
        <xsd:element name="ErrorInfo" type="ctp:ErrorInfoType" minOccurs="0"/>
        <xsd:element name="WorkingDate" type="xsd:date" minOccurs="1"/>
        <xsd:element name="JulianDate" type="xsd:string" minOccurs="1"/>
        <xsd:element name="NextWorkingDate" type="xsd:date" minOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
   <!-- Definición del elemento getAccountOfficers -->
  <xsd:element name="getAccountOfficers">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="GeneralInfo" type="ctp:GeneralInfoType"/>
        <xsd:element name="OfficerCode" type="xsd:string" minOccurs="0"/>
        <xsd:element name="BranchCode" type="xsd:string" minOccurs="0"/>
        <xsd:element name="Application" type="xsd:string" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  
  <!-- Definición del elemento getAccountOfficersResponse -->
  <xsd:element name="getAccountOfficersResponse">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="StatusInfo" type="ctp:StatusInfoType" minOccurs="1"/>
        <xsd:element name="ErrorInfo" type="ctp:ErrorInfoType" minOccurs="0"/>
        <xsd:element name="BussinessOfficers" type="rd:BussinessOfficerType"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <!--Entrega 6-->
  
  <xsd:element name="getInternationalBank">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="GeneralInfo" type="ctp:GeneralInfoType"/>
        <xsd:element name="BankCodeType" type="ctp:string1" minOccurs="1"/>
        <xsd:element name="BankCode" type="xsd:string" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="getInternationalBankResponse">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="StatusInfo" type="ctp:StatusInfoType" minOccurs="1"/>
        <xsd:element name="ErrorInfo" type="ctp:ErrorInfoType" minOccurs="0"/>
        <xsd:element name="BankCode" type="xsd:string" minOccurs="1"/>
        <xsd:element name="BankCodeType" type="xsd:string" minOccurs="1"/>
        <xsd:element name="BankName" type="xsd:string" minOccurs="1"/>
        <xsd:element name="CountryCode" type="xsd:string" minOccurs="1"/>
        <xsd:element name="CountryName" type="xsd:string" minOccurs="1"/>
        <xsd:element name="Office" type="xsd:string" minOccurs="1"/>
        <xsd:element name="State" type="xsd:string" minOccurs="1"/>
        <xsd:element name="City" type="xsd:string" minOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  
  
  
  <!-- Entrega 7 -->
 <xsd:element name="getHolidaysNonWorkingDays">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="GeneralInfo" type="ctp:GeneralInfoType"/>
        <xsd:element name="Year" type="xsd:integer" minOccurs="0"/>
        <xsd:element name="Month" type="xsd:string" minOccurs="0"/>
        <xsd:element name="Day" type="xsd:string" minOccurs="0"/>
        <xsd:element name="Module" type="xsd:string" minOccurs="0"/>
        <xsd:element name="Status" type="xsd:string" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="getHolidaysNonWorkingDaysResponse">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="StatusInfo" type="ctp:StatusInfoType" minOccurs="1"/>
        <xsd:element name="ErrorInfo" type="ctp:ErrorInfoType" minOccurs="0"/>
        <xsd:element name="NonWorkingDays" type="rd:NonWorkingDays" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  
  
</xsd:schema>