<wsdl:definitions name="sjConsultaSituacionFinancieraNIInternoPS" 
				  targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaSituacionFinancieraNIInternoPS" 
				  xmlns:tns="SplitJoinTest" 
				  xmlns:fic="http://www.ficohsa.com.hn/middleware.services/sjConsultaSituacionFinancieraNIInternoPS" 
				  xmlns:envi="http://www.ficohsa.com.hn/middleware.services/sjConsultaSituacionFinancieraInterno" 
				  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
				  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
				  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
				  xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../../../Resources/esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaSituacionFinancieraInterno" schemaLocation="../../../../Resources/ConsultaSituacionFinanciera/xsd/sjConsultaSituacionFinancieraInterno.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="sjConsultaSituacionFinancieraNIInternoRequest">
		<wsdl:part name="inputParameters" element="envi:sjConsultaSituacionFinancieraInterno"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	
	<wsdl:message name="sjConsultaSituacionFinancieraNIInternoResponse">
		<wsdl:part name="outputParameters" element="envi:sjConsultaSituacionFinancieraInternoResponse"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="sjConsultaSituacionFinancieraNIInternoPS">
		<wsdl:operation name="ConsultaSituacionFinancieraNIInterno" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:sjConsultaSituacionFinancieraNIInternoRequest"/>
			<wsdl:output message="fic:sjConsultaSituacionFinancieraNIInternoResponse"/>		
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="sjConsultaSituacionFinancieraNIInternoPSSOAP" type="fic:sjConsultaSituacionFinancieraNIInternoPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="ConsultaSituacionFinancieraNIInterno">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/sjConsultaSituacionFinancieraNIInternoPS/sjConsultaSituacionFinancieraNIInterno"/>
			<wsdl:input>
				<soap:body use="literal" parts="inputParameters"/>
				<soap:header message="fic:sjConsultaSituacionFinancieraNIInternoRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="outputParameters"/>
				<soap:header message="fic:sjConsultaSituacionFinancieraNIInternoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="sjConsultaSituacionFinancieraNIInternoPS">
		<wsdl:port name="sjConsultaSituacionFinancieraNIInternoPSSOAP" binding="fic:sjConsultaSituacionFinancieraNIInternoPSSOAP">
			<soap:address location="http://mwomnidesa:8003/Middleware/SJS/ConsultaSituacionFinanciera"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>