<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Card/SBHN_Card_GetHistoricalCreditCardStatement/DBConTransaccioneshistoricasBS" name="DBConTransaccioneshistoricasBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="DBConTransaccioneshistoricasBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Card/SBHN_Card_GetHistoricalCreditCardStatement/DBConTransaccioneshistoricasBS"/>
    <wsdl:binding name="DBConTransaccioneshistoricasBS_ptt-binding" type="dbc:DBConTransaccioneshistoricasBS_ptt" xmlns:dbc="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Card/SBHN_Card_GetHistoricalCreditCardStatement/DBConTransaccioneshistoricasBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DBConTransaccioneshistoricasBS">
            <soap:operation soapAction="DBConTransaccioneshistoricasBS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>