<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Card/SBHN_Card_GetHistoricalCreditCardStatement/DBConnectionProcesosHNBS" name="DBConnectionProcesosHNBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="DBConnectionProcesosHNBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Card/SBHN_Card_GetHistoricalCreditCardStatement/DBConnectionProcesosHNBS"/>
    <wsdl:binding name="DBConnectionProcesosHNBS_ptt-binding" type="dbc:DBConnectionProcesosHNBS_ptt" xmlns:dbc="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Card/SBHN_Card_GetHistoricalCreditCardStatement/DBConnectionProcesosHNBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="DBConnectionProcesosHNBS">
            <soap:operation soapAction="DBConnectionProcesosHNBS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>