<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultaCargaArchivoDAT/consultaCargaArchivoDAT" name="consultaCargaArchivoDAT-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultaCargaArchivoDAT/consultaCargaArchivoDAT" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/consultaCargaArchivoDAT/consultaCargaArchivoDAT" location="consultaCargaArchivoDAT.wsdl"/>
  <binding name="consultaCargaArchivoDAT_ptt-binding" type="tns:consultaCargaArchivoDAT_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaCargaArchivoDAT">
      <soap:operation soapAction="consultaCargaArchivoDAT"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaCargaArchivoDAT-service">
    <port name="consultaCargaArchivoDAT-port" binding="tns:consultaCargaArchivoDAT_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWorkflow"/>
    </port>
  </service>
</definitions>