<wsdl:definitions name="cargaProveedoresPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/cargaProveedoresPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/cargaProveedoresPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:pag="http://www.ficohsa.com.hn/middleware.services/pagosMasivosTypes">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/pagosMasivosTypes" schemaLocation="../../PagosMasivos/xsd/pagosMasivosTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="cargarProveedoresRequest">
		<wsdl:part element="pag:cargarProveedores" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="cargarProveedoresResponse">
		<wsdl:part element="pag:cargarProveedoresResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="cargaProveedoresPS">
		<wsdl:operation name="cargarProveedores" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:cargarProveedoresRequest"/>
			<wsdl:output message="fic:cargarProveedoresResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="cargaProveedoresPSSOAP" type="fic:cargaProveedoresPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="cargarProveedores">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/cargaProveedoresPS/cargarProveedores"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:cargarProveedoresRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:cargarProveedoresResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="cargaProveedoresPS">
		<wsdl:port binding="fic:cargaProveedoresPSSOAP" name="cargaProveedoresPSSOAP">
			<soap:address location="http://mwomnicanal:8003/Middleware/ReferenceData/BusinessPartner/cargarProveedores"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>