<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplePay/ApplePay/pushProvisioningNotification" name="pushProvisioningNotification-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ApplePay/ApplePay/pushProvisioningNotification" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ApplePay/ApplePay/pushProvisioningNotification" location="pushProvisioningNotification.wsdl"/>
  <binding name="pushProvisioningNotification_ptt-binding" type="tns:pushProvisioningNotification_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="pushProvisioningNotification">
      <soap:operation soapAction="pushProvisioningNotification"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="pushProvisioningNotification-service">
    <port name="pushProvisioningNotification-port" binding="tns:pushProvisioningNotification_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionDigitalizacionTarjetas"/>
    </port>
  </service>
</definitions>