openapi: 3.0.3
info:
  title: Reward Points Account Admin
  description: API que permite Permite la eliminación de tasas de cambio de puntos configuradas previamente en los diferentes países.
  version: 1.0.0
  contact:
    name: FICOHSA API Team
    email: api-support@ficohsa.com
servers:
  - url: https://{environment}.labs.integration.ficohsa.com
    description: "Non-production environments"
    variables:
      environment:
        default: "dev"
        enum: ["dev", "stg", "uat"]
    x-mtls-required: true
  - url: https://live.integration.ficohsa.com
    description: "Production"
    x-mtls-required: true

tags:
  - name: Card Points
    description: Endpoints related to calculate credit Points

paths:
  /crss-prdct-ops/reward-points-accnt-admin/v1/{reference}/delete:
    post:
      tags: ["Reward Points Account"]
      summary: Permite la eliminación de tasas de cambio de puntos configuradas previamente en los diferentes países.
      description: Implementar el servicio de eliminar factor de canje para gestión de puntos de tarjetas.
      parameters:
        - name: Authorization
          in: header
          required: true
          description: "Token de autenticación en formato Bearer <token> (normalmente JWT u otro mecanismo OAuth2)"
          schema:
            type: string
        - name: Correlation-Id
          in: header
          required: false
          description: "Identificador único de la transacción para trazabilidad extremo a extremo. Se propaga en toda la cadena de llamadas (Debe ser el mismo en la respuesta). Formato UUID.Este campo puede ir vacío, y en este caso, desde la API se debe generar para tener trazabilidad interna del flujo de la API a nivel de petición y respuesta"
          schema:
            type: string
            format: uuid
        - name: Source-Bank
          in: header
          required: true
          description: "Código del banco origen de la petición. Podría validarse contra el token para evitar suplantaciones. Ejemplo: HN01, GT01"
          schema:
            type: string
        - name: Destination-Bank
          in: header
          required: false
          description: "Código del banco destino de la operación. Ejemplo: HN01, GT01"
          schema:
            type: string
        - name: Application-Id
          in: header
          required: true
          description: "Identificador de la Aplicación que consume la API. Podría derivarse del token."
          schema:
            type: string
        - name: Application-User
          in: header
          required: false
          description: "Usuario de la aplicación consumidora que está ejecutando el servicio"
          schema:
            type: string
        - name: Caller-Service
          in: header
          required: false
          description: "En caso de APIs de experiencia o composición se usaría, para identificar la API que compone a las APIs de Producto"
          schema:
            type: string
        - name: Channel
          in: header
          required: false
          description: "Canal de interacción de la petición. Ejemplo: web, mobile, partner, atm, branch, ivr, etc."
          schema:
            type: string
        - name: Transaction-Date
          in: header
          required: false
          description: "Fecha de la transacción. Formato DateTime. YYYY-MM-DDTHH:MI:SS."
          schema:
            type: string
        - name: Accept-Language
          in: header
          required: false
          description: "Idioma preferido para mensajes y errores, usando código ISO 639-1 (es para español, en para inglés)"
          schema:
            type: string
        - name: reference
          in: path
          required: true
          description: Identificador de la promoción a eliminar
          schema:
            type: string
            minLength: 1
      
      responses:
        "200":
          description: "No content returned"
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    $ref: '#/components/schemas/meta'
                  data:
                    type: object  
                  
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          $ref: "#/components/responses/Conflict"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
        "423":
          $ref: "#/components/responses/Locked"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
        "502":
          $ref: "#/components/responses/BadGateway"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
        "504":
          $ref: "#/components/responses/GatewayTimeout"        

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.ficohsa.com/oauth2/token
          scopes:
            api.read: "Read access to product APIs"
  schemas:                                                    
    meta:
      type: object
      properties:
        bian:
          type: object
          properties:
            businessArea:
              type: string
              example: "OperationsAndExecution"
            businessDomain:
              type: string
              example: "OperationalServices"
            serviceDomain:
              type: string
              example: "IssuedDeviceAdministration"
    Error:
      type: object
      properties:
        type:
          type: string
          description: URL del tipo de error (RFC 7807)
          example: "https://live.integration.ficohsa.com/errors/bad-request"
        title:
          type: string
          description: Título corto del error HTTP
        status:
          type: integer
          description: Código HTTP del error
        detail:
          type: string
          description: Detalle del error en HTTP
        instance:
          type: string
          description: Ruta donde ocurrió el error
        correlationId:
          type: string
          description: Correlation ID para trazabilidad
        timestamp:
          type: string
          format: date-time
          description: Fecha del error

  responses:
    BadRequest:
      description: Los parámetros o formato son inválidos
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            badRequest:
              value:
                type: "https://live.integration.ficohsa.com/errors/bad-request"
                title: "Bad Request"
                status: 400
                detail: "Los parámetros o formato son inválidos"
                instance: "/operational-services/issued-dev-admin-debit-card-retrieves/v1"
                correlationId: "4f7b-abc123"
                timestamp: "2025-08-14T20:15:00Z"

    Unauthorized:
      description: Cliente no autenticado o credenciales inválidas
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            unauthorized:
              value:
                type: "https://live.integration.ficohsa.com/errors/unauthorized"
                title: "Unauthorized"
                status: 401
                detail: "Cliente no autenticado o credenciales inválidas"
                instance: "/operational-services/issued-dev-admin-debit-card-retrieves/v1"
                correlationId: "4f7b-abc123"
                timestamp: "2025-08-14T20:15:00Z"

    Forbidden:
      description: Cliente autenticado pero sin permisos
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            forbidden:
              value:
                type: "https://live.integration.ficohsa.com/errors/forbidden"
                title: "Forbidden"
                status: 403
                detail: "Cliente autenticado pero sin permisos"
                instance: "/operational-services/issued-dev-admin-debit-card-retrieves/v1"
                correlationId: "4f7b-abc123"
                timestamp: "2025-08-14T20:15:00Z"

    NotFound:
      description: Recurso solicitado no existe
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            notFound:
              value:
                type: "https://live.integration.ficohsa.com/errors/not-found"
                title: "Not Found"
                status: 404
                detail: "Recurso solicitado no existe"
                instance: "/operational-services/issued-dev-admin-debit-card-retrieves/v1"
                correlationId: "4f7b-abc123"
                timestamp: "2025-08-14T20:15:00Z"

    Conflict:
      description: Conflicto de estado 
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            conflict:
              value:
                type: "https://live.integration.ficohsa.com/errors/conflict"
                title: "Conflict"
                status: 409
                detail: "Conflicto de estado "
                instance: "/operational-services/issued-dev-admin-debit-card-retrieves/v1"
                correlationId: "4f7b-abc123"
                timestamp: "2025-08-14T20:15:00Z"

    UnprocessableEntity:
      description: Datos válidos en formato pero con errores de negocio
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            UnprocessableEntity:
              value:
                type: "https://live.integration.ficohsa.com/errors/unprocessable-entity"
                title: "Unprocessable Entity"
                status: 422
                detail: "Datos válidos en formato pero con errores de negocio"
                instance: "/operational-services/issued-dev-admin-debit-card-retrieves/v1"
                correlationId: "4f7b-abc123"
                timestamp: "2025-08-14T20:15:00Z"
            

    Locked:
      description: El recurso está temporalmente bloqueado
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            Locked:
              value:
                type: "https://live.integration.ficohsa.com/errors/locked"
                title: "Locked"
                status: 423
                detail: "El recurso está temporalmente bloqueado"
                instance: "/operational-services/issued-dev-admin-debit-card-retrieves/v1"
                correlationId: "4f7b-abc123"
                timestamp: "2025-08-14T20:15:00Z"

    TooManyRequests:
      description: Cliente excedió límite de peticiones
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            TooManyRequests:
              value:
                type: "https://live.integration.ficohsa.com/errors/too-many-requests"
                title: "Too Many Requests"
                status: 429
                detail: "Cliente excedió límite de peticiones"
                instance: "/operational-services/issued-dev-admin-debit-card-retrieves/v1"
                correlationId: "4f7b-abc123"
                timestamp: "2025-08-14T20:15:00Z"

    InternalServerError:
      description: Error inesperado en el servicio
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            InternalServerError:
                value:
                  type: "https://live.integration.ficohsa.com/errors/internal-server-error"
                  title: "Internal Server Error"
                  status: 500
                  detail: "Error inesperado en el servicio"
                  instance: "/operational-services/issued-dev-admin-debit-card-retrieves/v1"
                  correlationId: "4f7b-abc123"
                  timestamp: "2025-08-14T20:15:00Z"

    BadGateway:
      description: Falla de un servicio intermedio/gateway
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            BadGateway:
                value:
                  type: "https://live.integration.ficohsa.com/errors/bad-gateway"
                  title: "Bad Gateway"
                  status: 502
                  detail: "Falla de un servicio intermedio/gateway"
                  instance: "/operational-services/issued-dev-admin-debit-card-retrieves/v1"
                  correlationId: "4f7b-abc123"
                  timestamp: "2025-08-14T20:15:00Z"

    ServiceUnavailable:
      description: Servicio temporalmente no disponible
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            ServiceUnavailable:
                value:
                  type: "https://live.integration.ficohsa.com/errors/service-unavailable"
                  title: "Service Unavailable"
                  status: 503
                  detail: "Servicio temporalmente no disponible"
                  instance: "/operational-services/issued-dev-admin-debit-card-retrieves/v1"
                  correlationId: "4f7b-abc123"
                  timestamp: "2025-08-14T20:15:00Z"

    GatewayTimeout:
      description: Tiempo de espera excedido en servicio dependiente
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples:
            GatewayTimeout:
                value:
                  type: "https://live.integration.ficohsa.com/errors/gateway-timeout"
                  title: "Gateway Timeout"
                  status: 504
                  detail: "Tiempo de espera excedido en servicio dependiente"
                  instance: "/operational-services/issued-dev-admin-debit-card-retrieves/v1"
                  correlationId: "4f7b-abc123"
                  timestamp: "2025-08-14T20:15:00Z"

