<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultaFondosPensionesClienteFPC/consultaConsolidadRiesgoCliente/consultaConsolidadRiesgoCliente" name="consultaConsolidadRiesgoCliente-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/consultaFondosPensionesClienteFPC/consultaConsolidadRiesgoCliente/consultaConsolidadRiesgoCliente" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultaFondosPensionesClienteFPC/consultaConsolidadRiesgoCliente/consultaConsolidadRiesgoCliente" location="consultaConsolidadaRiesgoCliente.wsdl"/>
  <binding name="consultaConsolidadRiesgoCliente_ptt-binding" type="tns:consultaConsolidadRiesgoCliente_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaConsolidadRiesgoCliente">
      <soap:operation soapAction="consultaConsolidadRiesgoCliente"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaConsolidadRiesgoCliente-service">
    <port name="consultaConsolidadRiesgoCliente-port" binding="tns:consultaConsolidadRiesgoCliente_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionCustomerCreditRisk"/>
    </port>
  </service>
</definitions>