<wsdl:definitions name="consultaTiposPrestamosPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaTiposPrestamosPS/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/consultaTiposPrestamosPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:set="http://www.ficohsa.com.hn/middleware.services/catalogosInfoPrestamoTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/catalogosInfoPrestamoTypes" schemaLocation="../../CatalogosInfoPrestamo/xsd/catalogosInfoPrestamoTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="consultaTiposPrestamos">
		<wsdl:part element="set:consultaTiposPrestamos" name="parameters"/>
		<wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaTiposPrestamosResponse">
		<wsdl:part element="set:consultaTiposPrestamosResponse" name="result"/>
		<wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="consultaTiposPrestamosPS">	
		<wsdl:operation name="consultaTiposPrestamos" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="tns:consultaTiposPrestamos"/>
			<wsdl:output message="tns:consultaTiposPrestamosResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaTiposPrestamosPSSOAP" type="tns:consultaTiposPrestamosPS">
	
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		
		<wsdl:operation name="consultaTiposPrestamos">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/catalogosInfoPrestamoPS/catalogosInfoPrestamo"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="tns:consultaTiposPrestamos" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="tns:consultaTiposPrestamosResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>	
	</wsdl:binding>

	<wsdl:service name="consultaTiposPrestamosPS">
		<wsdl:port binding="tns:consultaTiposPrestamosPSSOAP" name="consultaTiposPrestamosPS">
	  		<soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/CustomerLoans/consultaTiposPrestamos"/>
	   	</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>