<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/modificaReorden/modificaReorden" name="modificaReorden-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/modificaReorden/modificaReorden" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/modificaReorden/modificaReorden" location="modificaReorden.wsdl"/>
  <binding name="modificaReorden_ptt-binding" type="tns:modificaReorden_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="modificaReorden">
      <soap:operation soapAction="modificaReorden"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="modificaReorden-service">
    <port name="modificaReorden-port" binding="tns:modificaReorden_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionDebitCard"/>
    </port>
  </service>
</definitions>