<wsdl:definitions name="colocacionExtraATMPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/colocacionExtraATMPS" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/colocacionExtraATMPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/colocacionExtraATMTypes">
  
  <wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/colocacionExtraATMTypes" schemaLocation="../xsd/colocacionExtraATMTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
  
  <wsdl:message name="colocacionExtraATMPSRequest">
  	<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
    <wsdl:part element="tns:colocacionExtraATMRequest" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="colocacionExtraATMPSResponse">
  	<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
    <wsdl:part element="tns:colocacionExtraATMResponse" name="result"/>
  </wsdl:message>
  
  
  <wsdl:portType name="colocacionExtraATMPS">
    <wsdl:operation name="colocacionExtraATM">
      <wsdl:input message="fic:colocacionExtraATMPSRequest"/>
      <wsdl:output message="fic:colocacionExtraATMPSResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="colocacionExtraATMPSSOAP" type="fic:colocacionExtraATMPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="colocacionExtraATM">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/colocacionExtraATMPS"/>
      <wsdl:input>
        <soap:header message="fic:colocacionExtraATMPSRequest" part="RequestHeader" use="literal"/>
        <soap:body use="literal" parts="parameters"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="fic:colocacionExtraATMPSResponse" part="ResponseHeader" use="literal"/>
        <soap:body use="literal" parts="result"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="colocacionExtraATMPS">
    <wsdl:port binding="fic:colocacionExtraATMPSSOAP" name="colocacionExtraATMPSSOAP">
      <soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Messaging/ColocacionExtraATM"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>