<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionWorkflow/consultaTiposImpuestos/consultaTiposImpuestos" name="consultaTiposImpuestos-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionWorkflow/consultaTiposImpuestos/consultaTiposImpuestos" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConnectionWorkflow/consultaTiposImpuestos/consultaTiposImpuestos" location="consultaTiposImpuestos.wsdl"/>
  <binding name="consultaTiposImpuestos_ptt-binding" type="tns:consultaTiposImpuestos_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaTiposImpuestos">
      <soap:operation soapAction="consultaTiposImpuestos"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaTiposImpuestos-service">
    <port name="consultaTiposImpuestos-port" binding="tns:consultaTiposImpuestos_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWorkflow"/>
    </port>
  </service>
</definitions>