<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOAApplication/Project3/chequeTotal" name="chequeTotal-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAApplication/Project3/chequeTotal" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOAApplication/Project3/chequeTotal" location="chequeTotal.wsdl"/>
  <binding name="chequeTotal_ptt-binding" type="tns:chequeTotal_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="chequeTotal">
      <soap:operation soapAction="chequeTotal"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="chequeTotal-service">
    <port name="chequeTotal-port" binding="tns:chequeTotal_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>