<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AfiliacionCAP/afiliacionCAP/afiliacionCAP" name="afiliacionCAP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AfiliacionCAP/afiliacionCAP/afiliacionCAP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AfiliacionCAP/afiliacionCAP/afiliacionCAP" location="afiliacionCAP.wsdl"/>
  <binding name="afiliacionCAP_ptt-binding" type="tns:afiliacionCAP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="afiliacionCAP">
      <soap:operation soapAction="afiliacionCAP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="afiliacionCAP-service">
    <port name="afiliacionCAP-port" binding="tns:afiliacionCAP_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionAhorroProgramado"/>
    </port>
  </service>
</definitions>