<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingGT/AssignDebitCardGT_BS" name="AssignDebitCardGT_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="AssignDebitCardGT_BS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingGT/AssignDebitCardGT_BS"/>
    <wsdl:binding name="AssignDebitCardGT_BS_ptt-binding" type="ass:AssignDebitCardGT_BS_ptt" xmlns:ass="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingGT/AssignDebitCardGT_BS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="AssignDebitCardGT_BS">
            <soap:operation soapAction="AssignDebitCardGT_BS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>