<wsdl:definitions name="SrvAplCobisTicket" targetNamespace="http://impl.service.srvaplcobisticket.ecobis.cobiscorp/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://service.srvaplcobisticket.ecobis.cobiscorp" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:S1="http://impl.service.srvaplcobisticket.ecobis.cobiscorp/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://impl.service.srvaplcobisticket.ecobis.cobiscorp/">
      <xsd:import namespace="http://service.srvaplcobisticket.ecobis.cobiscorp" schemaLocation="../xsd/services.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="MsjOpConsultaTicketSolicitud">
    <wsdl:part name="parameters" element="tns:opConsultaTicketSolicitud"/>
  </wsdl:message>
  <wsdl:message name="MsjOpConsultaTicketRespuesta">
    <wsdl:part name="parameters" element="tns:opConsultaTicketRespuesta"/>
  </wsdl:message>
  <wsdl:portType name="SrvAplCobisTicket">
    <wsdl:operation name="OpConsultaTicket">
      <wsdl:input message="S1:MsjOpConsultaTicketSolicitud"/>
      <wsdl:output message="S1:MsjOpConsultaTicketRespuesta"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SrvAplCobisTicketBindingSOAP12" type="S1:SrvAplCobisTicket">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="OpConsultaTicket">
      <soap12:operation/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SrvAplCobisTicketService">
    <wsdl:port name="SrvAplCobisTicketBindingSOAP12" binding="S1:SrvAplCobisTicketBindingSOAP12">
      <soap12:address location="http://10.235.53.149:9080/GerenciaProductoTicket/SrvAplCobisTicketService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>