<wsdl:definitions name="consultaDetallePDPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaDetallePDPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaDetallePDPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaDetallePDTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaDetallePDTypes" schemaLocation="consultaDetallePDTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="consultaDetallePDRequest">
		<wsdl:part element="cons:consultaDetallePD" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaDetallePDResponse">
		<wsdl:part element="cons:consultaDetallePDResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="consultaDetallePDPS">
		<wsdl:operation name="consultaDetallePD" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaDetallePDRequest"/>
			<wsdl:output message="fic:consultaDetallePDResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaDetallePDPSSOAP" type="fic:consultaDetallePDPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaDetallePD">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaDetallePDPS/consultaDetallePD"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaDetallePDRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaDetallePDResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="consultaDetallePDPS">
    <wsdl:port binding="fic:consultaDetallePDPSSOAP" name="consultaDetallePDPSSOAP">
      <soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/CustomerDeposits/consultaDetallePD"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>