<wsdl:definitions name="consultaBancosLocalesPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaBancosLocalesPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaBancosLocalesPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaBancosLocalesTypes">

	<wsdl:types>
    	<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaBancosLocalesTypes" schemaLocation="consultaBancosLocalesTypes.xsd"/>
		</xsd:schema>
 	</wsdl:types>

	<wsdl:message name="consultaBancosLocalesRequest">
		<wsdl:part element="cons:consultaBancosLocales" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaBancosLocalesResponse">
		<wsdl:part element="cons:consultaBancosLocalesResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="consultaBancosLocalesPS">
		<wsdl:operation name="consultaBancosLocales" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaBancosLocalesRequest"/>
			<wsdl:output message="fic:consultaBancosLocalesResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaBancosLocalesPSSOAP" type="fic:consultaBancosLocalesPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaBancosLocales">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaBancosLocales/consultaBancosLocales"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaBancosLocalesRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaBancosLocalesResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="consultaBancosLocalesPS">
	   <wsdl:port binding="fic:consultaBancosLocalesPSSOAP" name="consultaBancosLocalesPSSOAP">
	     <soap:address location="http://mwinterbanca:8003/Middleware/ReferenceData/CommonBusinessInformation/ConsultaBancosLocales"/>
	   </wsdl:port>
	</wsdl:service>

</wsdl:definitions>