<wsdl:definitions name="GetAccountMappingT24Citi" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/GetAccountMappingT24Citi" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/GetAccountMappingT24Citi" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/GetAccountMappingT24Citi" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="GetAccountMappingT24Citi_plt">
    <plt:role name="GetAccountMappingT24Citi_role">
      <plt:portType name="tns:GetAccountMappingT24Citi_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/GetAccountMappingT24Citi" schemaLocation="../../XSD/GetAccountMappingT24Citi/GetAccountMappingT24Citi_sp.xsd"/>
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="GetAccountMappingT24Citi_ptt">
        <wsdl:operation name="GetAccountMappingT24Citi">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>