<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ModificaCuentaAFP/ModificaCuentaAFP" name="ModificaCuentaAFP-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ModificaCuentaAFP/ModificaCuentaAFP" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ModificaCuentaAFP/ModificaCuentaAFP" location="../wsdl/ModificaCuentaAFP.wsdl"/>
  <binding name="ModificaCuentaAFP_ptt-binding" type="tns:ModificaCuentaAFP_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ModificaCuentaAFP">
      <soap:operation soapAction="ModificaCuentaAFP"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ModificaCuentaAFP-service">
    <port name="ModificaCuentaAFP-port" binding="tns:ModificaCuentaAFP_ptt-binding">
      <soap:address location="jca://eis/DB/jdbc/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="../wsdl/ModificaCuentaAFP.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ModificaCuentaAFP/ModificaCuentaAFP">
            <con:wsdl ref="Middleware/v2/BusinessServices/ABKHN/FondoPensiones/ModificaCuentaAFP/wsdl/ModificaCuentaAFP"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/OSB/ModificaCuentaAFP/ModificaCuentaAFP</con:targetNamespace>
</con:wsdlEntry>