<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/pagoFicoRemesas/pagoFicoRemesas/pagoFicoRemesas" name="pagoFicoRemesas-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/pagoFicoRemesas/pagoFicoRemesas/pagoFicoRemesas" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/pagoFicoRemesas/pagoFicoRemesas/pagoFicoRemesas" location="pagoFicoRemesas.wsdl"/>
  <binding name="pagoFicoRemesas_ptt-binding" type="tns:pagoFicoRemesas_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="pagoFicoRemesas">
      <soap:operation soapAction="pagoFicoRemesas"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="pagoFicoRemesas-service">
    <port name="pagoFicoRemesas-port" binding="tns:pagoFicoRemesas_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>