<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/OSB/validaListaNegraDelitos" name="validaListaNegraDelitos-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/OSB/validaListaNegraDelitos" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Middleware/OSB/validaListaNegraDelitos" location="validaListaNegraDelitos.wsdl"/>
  <binding name="validaListaNegraDelitos_ptt-binding" type="tns:validaListaNegraDelitos_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="validaListaNegraDelitos">
      <soap:operation soapAction="validaListaNegraDelitos"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="validaListaNegraDelitos-service">
    <port name="validaListaNegraDelitos-port" binding="tns:validaListaNegraDelitos_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionPrecredit"/>
    </port>
  </service>
</definitions>