<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/PaymentCollectionAbanks" name="PaymentCollectionAbanks-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="PaymentCollectionAbanks.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/PaymentCollectionAbanks"/>
    <wsdl:binding name="PaymentCollectionAbanks_ptt-binding" type="pay:PaymentCollectionAbanks_ptt" xmlns:pay="http://xmlns.oracle.com/pcbpel/adapter/db/DynamoMigrate/CoreBankingHN/PaymentCollectionAbanks">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="PaymentCollectionAbanks">
            <soap:operation soapAction="PaymentCollectionAbanks"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>