<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBConSaldosTCOffLine/consultaPuntosLealtad/consultaPuntosLealtad" name="consultaPuntosLealtad-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBConSaldosTCOffLine/consultaPuntosLealtad/consultaPuntosLealtad" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBConSaldosTCOffLine/consultaPuntosLealtad/consultaPuntosLealtad" location="consultaPuntosLealtad.wsdl"/>
  <binding name="consultaPuntosLealtad_ptt-binding" type="tns:consultaPuntosLealtad_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaPuntosLealtad">
      <soap:operation soapAction="consultaPuntosLealtad"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaPuntosLealtad-service">
    <port name="consultaPuntosLealtad-port" binding="tns:consultaPuntosLealtad_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionClientdata"/>
    </port>
  </service>
</definitions>