<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksPASOAApplication/TransferenciaInternacional/transferenciaInternacional" name="transferenciaInternacional-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksPASOAApplication/TransferenciaInternacional/transferenciaInternacional" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksPASOAApplication/TransferenciaInternacional/transferenciaInternacional" location="transferenciaInternacional.wsdl"/>
  <binding name="transferenciaInternacional_ptt-binding" type="tns:transferenciaInternacional_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="transferenciaInternacional">
      <soap:operation soapAction="transferenciaInternacional"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="transferenciaInternacional-service">
    <port name="transferenciaInternacional-port" binding="tns:transferenciaInternacional_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionAbanksPA"/>
    </port>
  </service>
</definitions>