<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="GetCustomerDetails11gPS"
     targetNamespace="http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetCustomerDetails/GetCustomerDetails11gPS"
     xmlns:tns="http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetCustomerDetails/GetCustomerDetails11gPS"
     xmlns:inp1="https://www.ficohsa.com/regional/pension"
     xmlns:inp2="http://www.ficohsa.com.hn/middleware.services/autType"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="https://www.ficohsa.com/regional/pension" schemaLocation="../Schemas/GetCustomerDetailsTypes.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../SBRG_Pension_Commons/Schemas/HeaderElements.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="getCustomerDetails11gPS" element="inp1:getCustomerDetails"/>
        <wsdl:part name="requestHeader" element="inp2:RequestHeader"/>
    </wsdl:message>
	<wsdl:message name="replyMessage">
       <wsdl:part name="getCustomerDetailsResponse" element="inp1:getCustomerDetailsResponse"/>
    </wsdl:message>
    <wsdl:portType name="getCustomerDetails11gPSPtt">
        <wsdl:operation name="getCustomerDetails11gPS">
            <wsdl:input message="tns:requestMessage"/>
			<wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="getCustomerDetails11gPSBind" type="tns:getCustomerDetails11gPSPtt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getCustomerDetails11gPS">
            <soap:operation style="document" soapAction="getCustomerDetails11gPS"/>
            <wsdl:input>
                <soap:body use="literal" namespace="https://www.ficohsa.com/regional/pension"
                     parts="getCustomerDetails11gPS"/>
                <soap:header message="tns:requestMessage" part="requestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
              <soap:body use="literal" parts="getCustomerDetailsResponse" namespace="https://www.ficohsa.com/regional/pension"/>
            </wsdl:output>			
        </wsdl:operation>
    </wsdl:binding>
	  <wsdl:service name="getCustomerDetailsPS">
    <wsdl:port binding="tns:getCustomerDetails11gPSBind" name="getCustomerDetails11gPSBind">
      <soap:address location="https://dynamoosbdev:8004/regional/pension/soap/getCustomerDetails/v11g"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../Schemas/GetCustomerDetailsTypes.xsd" namespace="https://www.ficohsa.com/regional/pension" ref="SBRG_Pension_GetCustomerDetails/Schemas/GetCustomerDetailsTypes"/>
        <con:schemaRef isInclude="false" schemaLocation="../../SBRG_Pension_Commons/Schemas/HeaderElements.xsd" namespace="http://www.ficohsa.com.hn/middleware.services/autType" ref="SBRG_Pension_Commons/Schemas/HeaderElements"/>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/SBRG_Pension/SBRG_Pension_GetCustomerDetails/GetCustomerDetails11gPS</con:targetNamespace>
</con:wsdlEntry>