<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/UpdateAccount" name="UpdateAccount_db" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="UpdateAccount.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/UpdateAccount"/>
  <wsdl:binding name="UpdateAccount_ptt-binding" type="con:UpdateAccount_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/sp/UpdateAccount">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="UpdateAccount">
      <soap:operation soapAction="ConnectionAbanksGT"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>