<wsdl:definitions name="reversionDataCapturePS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/reversionDataCapturePS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/reversionDataCapturePS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/reversionDataCaptureTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/reversionDataCaptureTypes" schemaLocation="reversionDataCaptureTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="reversionDataCaptureRequest">
		<wsdl:part element="cons:reversionDataCapture" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="reversionDataCaptureResponse">
		<wsdl:part element="cons:reversionDataCaptureResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="reversionDataCapturePS">
		<wsdl:operation name="reversionDataCapture" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:reversionDataCaptureRequest"/>
			<wsdl:output message="fic:reversionDataCaptureResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="reversionDataCapturePSSOAP" type="fic:reversionDataCapturePS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="reversionDataCapture">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/reversionDataCapturePS/reversionDataCapture"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:reversionDataCaptureRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:reversionDataCaptureResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="reversionDataCapturePS">
    <wsdl:port binding="fic:reversionDataCapturePSSOAP" name="reversionDataCapturePSSOAP">
      <soap:address location="http://mwinterbanca:8003/Middleware/OperationsAndExecution/CustomerDeposits/ReversionDataCapture"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>