<wsdl:definitions name="creaClienteTarjetaCreditoPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/creaClienteTarjetaCreditoPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cre="http://www.ficohsa.com.hn/middleware.services/creaClienteTarjetaCreditoPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/creaClienteTarjetaCreditoTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/creaClienteTarjetaCreditoTypes" schemaLocation="../xsd/creaClienteTarjetaCreditoTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestHeader">
        <wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
    </wsdl:message>
    <wsdl:message name="responseHeader">
        <wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
    </wsdl:message>
    <wsdl:message name="creaClienteTarjetaCredito">
        <wsdl:part element="tns:creaClienteTarjetaCredito" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="creaClienteTarjetaCreditoResponse">
        <wsdl:part element="tns:creaClienteTarjetaCreditoResponse" name="result"/>	</wsdl:message>
    <wsdl:portType name="creaClienteTarjetaCreditoPS">
        <wsdl:operation name="creaClienteTarjetaCredito" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="cre:creaClienteTarjetaCredito"/>
            <wsdl:output message="cre:creaClienteTarjetaCreditoResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="creaClienteTarjetaCreditoPSSOAP" type="cre:creaClienteTarjetaCreditoPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="creaClienteTarjetaCredito">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/creaClienteTarjetaCreditoPS/creaClienteTarjetaCredito"/>
            <wsdl:input>
                <soap:body parts="parameters" use="literal"/>
                <soap:header message="cre:requestHeader" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body parts="result" use="literal"/>
                <soap:header message="cre:responseHeader" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="creaClienteTarjetaCreditoPS">
        <wsdl:port binding="cre:creaClienteTarjetaCreditoPSSOAP" name="creaClienteTarjetaCreditoPSSOAP">
            <soap:address location="https://172.23.13.19:8004/Middleware/OperationsAndExecution/Cards/CreaClienteTarjetaCredito"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>