<routing>
   <rule>
      <key>HN01</key>
      <serviceName>Middleware/v3/ProxyServices/PagoTarjetaCredito/local/PagoTarjetaCreditoHN</serviceName>
   </rule>
   <rule>
      <key>GT01</key>
      <serviceName>Middleware/v3/ProxyServices/PagoTarjetaCredito/local/PagoTarjetaCreditoGT</serviceName>
   </rule>
   <rule>
      <key>NI01</key>
      <serviceName>Middleware/v3/ProxyServices/PagoTarjetaCredito/local/PagoTarjetaCreditoNI</serviceName>
   </rule>
   <rule>
      <key>PA01</key>
      <serviceName>Middleware/v3/ProxyServices/PagoTarjetaCredito/local/PagoTarjetaCreditoPA</serviceName>
   </rule>
</routing>