<wsdl:definitions name="ampliacionLimiteClienteVentaPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/ampliacionLimiteClienteVentaPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:con="http://www.ficohsa.com.hn/middleware.services/ampliacionLimiteClienteVentaPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/ampliacionLimiteClienteVentaTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/ampliacionLimiteClienteVentaTypes" schemaLocation="../xsd/ampliacionLimiteClienteVentaTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestHeader">
        <wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
    </wsdl:message>
    <wsdl:message name="responseHeader">
        <wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
    </wsdl:message>
    <wsdl:message name="ampliacionLimiteClienteVenta">
        <wsdl:part element="tns:ampliacionLimiteClienteVenta" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="ampliacionLimiteClienteVentaResponse">
        <wsdl:part element="tns:ampliacionLimiteClienteVentaResponse" name="result"/>
    </wsdl:message>
    <wsdl:portType name="ampliacionLimiteClienteVentaPS">
        <wsdl:operation name="ampliacionLimiteClienteVenta" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="con:ampliacionLimiteClienteVenta"/>
            <wsdl:output message="con:ampliacionLimiteClienteVentaResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ampliacionLimiteClienteVentaPSSOAP" type="con:ampliacionLimiteClienteVentaPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ampliacionLimiteClienteVenta">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/ampliacionLimiteClienteVentaPS/ampliacionLimiteClienteVenta"/>
            <wsdl:input>
                <soap:body parts="parameters" use="literal"/>
                <soap:header message="con:requestHeader" part="RequestHeader" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body parts="result" use="literal"/>
                <soap:header message="con:responseHeader" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ampliacionLimiteClienteVentaPS">
        <wsdl:port binding="con:ampliacionLimiteClienteVentaPSSOAP" name="ampliacionLimiteClienteVentaPSSOAP">
            <soap:address location="https://mwomnicanal:8004/Middleware/OperationsAndExecution/ConsumerService/ampliacionLimiteClienteVenta"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>