<?binding.jca consultaAccesoUsuario_db.jca?><wsdl:definitions name="consultaAccesoUsuario" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ABANKSHN+NEW/consultaAccesoUsuario" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ABANKSHN+NEW/consultaAccesoUsuario" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/PROXYABANKSHN/OSB_K_GIA_USUARIOS_HN/OSB_P_VALIDA_USUARIO_HN/">
    <plt:partnerLinkType name="consultaAccesoUsuario_plt">
        <plt:role name="consultaAccesoUsuario_role">
            <plt:portType name="tns:consultaAccesoUsuario_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/PROXYABANKSHN/OSB_K_GIA_USUARIOS_HN/OSB_P_VALIDA_USUARIO_HN/" schemaLocation="../xsd/consultaAccesoUsuario_sp.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="consultaAccesoUsuario_ptt">
        <wsdl:operation name="consultaAccesoUsuario">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>