<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PagoTarjetaCredito/Project1/PagoTarjetaCredito" name="PagoTarjetaCredito-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PagoTarjetaCredito/Project1/PagoTarjetaCredito" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/PagoTarjetaCredito/Project1/PagoTarjetaCredito" location="PagoTarjetaCredito.wsdl"/>
  <binding name="PagoTarjetaCredito_ptt-binding" type="tns:PagoTarjetaCredito_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="PagoTarjetaCredito">
      <soap:operation soapAction="PagoTarjetaCredito"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="PagoTarjetaCredito-service">
    <port name="PagoTarjetaCredito-port" binding="tns:PagoTarjetaCredito_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>