<wsdl:definitions name="registraLoteExternoPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/registraLoteExternoPS/" xmlns:op="http://www.ficohsa.com.hn/middleware.services/registraLoteExternoPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/registraLoteExternoTypes">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/registraLoteExternoTypes" schemaLocation="../xsd/registraLoteExternoTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="registraLoteExternoRequest">
		<wsdl:part element="tns:registraLoteExterno" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="registraLoteExternoResponse">
		<wsdl:part element="tns:registraLoteExternoResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>

	<wsdl:portType name="registraLoteExternoPS">
		<wsdl:operation name="registraLoteExterno" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="op:registraLoteExternoRequest"/>
			<wsdl:output message="op:registraLoteExternoResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="registraLoteExternoPSSOAP" type="op:registraLoteExternoPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="registraLoteExterno">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/registraLoteExternoPS/registraLoteExterno"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="op:registraLoteExternoRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="op:registraLoteExternoResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="registraLoteExternoPS">
		<wsdl:port binding="op:registraLoteExternoPSSOAP" name="registraLoteExternoPSSOAP">
			<soap:address location="https://10.242.104.250:8004/Middleware/OperationsAndExecution/Payments/registraLoteExterno/"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>