<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultaDestinos/consultaDestinos/consultaDestinos" name="consultaDestinos-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/consultaDestinos/consultaDestinos/consultaDestinos" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/consultaDestinos/consultaDestinos/consultaDestinos" location="consultaDestinos.wsdl"/>
  <binding name="consultaDestinos_ptt-binding" type="tns:consultaDestinos_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaDestinos">
      <soap:operation soapAction="consultaDestinos"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaDestinos-service">
    <port name="consultaDestinos-port" binding="tns:consultaDestinos_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>