<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOAApplication/ProcesadorTarjetasPA/conInfoClienteTE" name="conInfoClienteTE-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAApplication/ProcesadorTarjetasPA/conInfoClienteTE" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOAApplication/ProcesadorTarjetasPA/conInfoClienteTE" location="conInfoClienteTE.wsdl"/>
  <binding name="conInfoClienteTE_ptt-binding" type="tns:conInfoClienteTE_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conInfoClienteTE">
      <soap:operation soapAction="conInfoClienteTE"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conInfoClienteTE-service">
    <port name="conInfoClienteTE-port" binding="tns:conInfoClienteTE_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetas"/>
    </port>
  </service>
</definitions>