<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/AfiliarDeudoresDepRef/ingresarDeudoresDepRef" name="ingresarDeudoresDepRef-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/AfiliarDeudoresDepRef/ingresarDeudoresDepRef" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/AfiliarDeudoresDepRef/ingresarDeudoresDepRef" location="ingresarDeudoresDepRef.wsdl"/>
  <binding name="ingresarDeudoresDepRef_ptt-binding" type="tns:ingresarDeudoresDepRef_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ingresarDeudoresDepRef">
      <soap:operation soapAction="ingresarDeudoresDepRef"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ingresarDeudoresDepRef-service">
    <port name="ingresarDeudoresDepRef-port" binding="tns:ingresarDeudoresDepRef_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="ingresarDeudoresDepRef.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/AfiliarDeudoresDepRef/ingresarDeudoresDepRef">
            <con:wsdl ref="Middleware/v2/BusinessServices/ABK/ingresarDeudoresDepRef/wsdl/ingresarDeudoresDepRef"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/Application1/AfiliarDeudoresDepRef/ingresarDeudoresDepRef</con:targetNamespace>
</con:wsdlEntry>