<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Servicios/svnACHProgramadas/svnACHProgramadas" name="svnACHProgramadas-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Servicios/svnACHProgramadas/svnACHProgramadas" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Servicios/svnACHProgramadas/svnACHProgramadas" location="svnACHProgramadas.wsdl"/>
  <binding name="svnACHProgramadas_ptt-binding" type="tns:svnACHProgramadas_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="svnACHProgramadas">
      <soap:operation soapAction="svnACHProgramadas"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="svnACHProgramadas-service">
    <port name="svnACHProgramadas-port" binding="tns:svnACHProgramadas_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterfazdb"/>
    </port>
  </service>
</definitions>