<wsdl:definitions name="envioMensajeUnicoRGPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/envioMensajeUnicoRGPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/envioMensajeUnicoRGPS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cet="http://www.ficohsa.com.hn/middleware.services/envioCorreoElectronicoTypes">
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/envioCorreoElectronicoTypes" schemaLocation="../../EnvioCorreoElectronico/xsd/envioCorreoElectronicoTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="envioMensajeUnicoRGRequest">
		<wsdl:part element="cet:envioMensajeUnico" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="envioMensajeUnicoRGResponse">
		<wsdl:part element="cet:envioMensajeUnicoResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="envioMensajeUnicoRGPS">
		<wsdl:operation name="envioMensajeUnicoRG">
			<wsdl:input message="fic:envioMensajeUnicoRGRequest"/>
			<wsdl:output message="fic:envioMensajeUnicoRGResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="envioMensajeUnicoRGPSSOAP" type="fic:envioMensajeUnicoRGPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="envioMensajeUnicoRG">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/envioMensajeUnicoRGPS/envioMensajeUnicoRG"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:envioMensajeUnicoRGRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:envioMensajeUnicoRGResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="envioMensajeUnicoRGPS">
		<wsdl:port binding="fic:envioMensajeUnicoRGPSSOAP" name="envioMensajeUnicoRGPSSOAP">
			<soap:address location="https://mwomnicanal:8004/Middleware/OperationsAndExecution/Messaging/EnvioCorreoElectronico"/>
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>