<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/safewatchRegistraBitacora/safewatchRegistraBitacora" name="safewatchRegistraBitacora-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/safewatchRegistraBitacora/safewatchRegistraBitacora" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/safewatchRegistraBitacora/safewatchRegistraBitacora" location="../wsdl/safewatchRegistraBitacora.wsdl"/>
  <binding name="safewatchRegistraBitacora_ptt-binding" type="tns:safewatchRegistraBitacora_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="safewatchRegistraBitacora">
      <soap:operation soapAction="safewatchRegistraBitacora"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="safewatchRegistraBitacora-service">
    <port name="safewatchRegistraBitacora-port" binding="tns:safewatchRegistraBitacora_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionMiddleware"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="../wsdl/safewatchRegistraBitacora.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/safewatchRegistraBitacora/safewatchRegistraBitacora">
            <con:wsdl ref="Middleware/v2/BusinessServices/SafewatchRegistraBitacora/wsdl/safewatchRegistraBitacora"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseAdapters/safewatchRegistraBitacora/safewatchRegistraBitacora</con:targetNamespace>
</con:wsdlEntry>