<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Card/SBHN_Card_GetCreditCardTransactions/registraMovimientosRecientesTC" name="registraMovimientosRecientesTC-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="registraMovimientosRecientesTC.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Card/SBHN_Card_GetCreditCardTransactions/registraMovimientosRecientesTC"/>
    <wsdl:binding name="registraMovimientosRecientesTC_ptt-binding" type="reg:registraMovimientosRecientesTC_ptt" xmlns:reg="http://xmlns.oracle.com/pcbpel/adapter/db/SBHN_Card/SBHN_Card_GetCreditCardTransactions/registraMovimientosRecientesTC">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="registraMovimientosRecientesTC">
            <soap:operation soapAction="registraMovimientosRecientesTC"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>