<wsdl:definitions name="ConsumerServiceRouter_PS" targetNamespace="http://xmlns.oracle.com/ConsumerServiceRouter_PS" xmlns:tns="http://xmlns.oracle.com/ConsumerServiceRouter_PS" xmlns:inp1="http://www.ficohsa.com.hn/getExchangeRateTypes" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <plnk:partnerLinkType name="ConsumerServiceRouter_PS">
        <plnk:role name="ConsumerServiceRouter_PSProvider" portType="tns:ConsumerServiceRouter_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.ficohsa.com.hn/getExchangeRateTypes" schemaLocation="../XSD/getExchangeRateTypes.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="getExchangeRate_inputMessage">
        <wsdl:part name="request" element="inp1:getExchangeRateRequest"/>
    </wsdl:message>
    <wsdl:message name="getExchangeRate_outputMessage">
        <wsdl:part name="response" element="inp1:getExchangeRateResponse"/>
    </wsdl:message>
    <wsdl:portType name="ConsumerServiceRouter_ptt">
        <wsdl:operation name="getExchangeRate">
            <wsdl:input message="tns:getExchangeRate_inputMessage"/>
            <wsdl:output message="tns:getExchangeRate_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ConsumerServiceRouter_ptt-binding" type="tns:ConsumerServiceRouter_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getExchangeRate">
            <soap:operation soapAction="getExchangeRate"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>