<wsdl:definitions name="cargaArchivoFacturasPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/cargaArchivoFacturasPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/cargaArchivoFacturasPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:pag="http://www.ficohsa.com.hn/middleware.services/cobranzasElectronicasTypes">

  <wsdl:types>
    <xsd:schema>
        <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
    </xsd:schema>
    <xsd:schema>
        <xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/cobranzasElectronicasTypes" schemaLocation="../../CobranzasElectronicas/xsd/cobranzasElectronicasTypes.xsd"/>
    </xsd:schema>
    </wsdl:types> 

    <wsdl:message name="cargaArchivoFacturasRequest">
        <wsdl:part element="pag:cargaArchivoFacturas" name="parameters"/>
        <wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
    </wsdl:message>
    <wsdl:message name="cargaArchivoFacturasResponse">
        <wsdl:part element="pag:cargaArchivoFacturasResponse" name="result"/>
        <wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
    </wsdl:message>

    <wsdl:portType name="cargaArchivoFacturasPS">
        <wsdl:operation name="cargaArchivoFacturas" parameterOrder="parameters RequestHeader ResponseHeader">
            <wsdl:input message="fic:cargaArchivoFacturasRequest"/>
            <wsdl:output message="fic:cargaArchivoFacturasResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="cargaArchivoFacturasPSSOAP" type="fic:cargaArchivoFacturasPS">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="cargaArchivoFacturas">
            <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/cargaArchivoFacturasPS/cargaArchivoFacturas"/>
            <wsdl:input>
                <soap:body use="literal" parts="parameters"/> 
                <soap:header message="fic:cargaArchivoFacturasRequest" part="RequestHeader" use="literal"/>
                
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="result"/>
                <soap:header message="fic:cargaArchivoFacturasResponse" part="ResponseHeader" use="literal"/>
            </wsdl:output>
        </wsdl:operation> 
    </wsdl:binding>

    <wsdl:service name="cargaArchivoFacturasPS">
        <wsdl:port binding="fic:cargaArchivoFacturasPSSOAP" name="cargaArchivoFacturasPSSOAP">
            <soap:address location="http://mwomnidesa:8003/Middleware/OperationsAndExecution/Cards/cargaArchivoFacturas"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>