<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/actualizaDireccionPersonaFPC/actualizaDireccionPersonaFPC" name="actualizaDireccionPersonaFPC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/actualizaDireccionPersonaFPC/actualizaDireccionPersonaFPC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AFPSOAApplication/actualizaDireccionPersonaFPC/actualizaDireccionPersonaFPC" location="actualizaDireccionPersonaFPC.wsdl"/>
  <binding name="actualizaDireccionPersonaFPC_ptt-binding" type="tns:actualizaDireccionPersonaFPC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="actualizaDireccionPersonaFPC">
      <soap:operation soapAction="actualizaDireccionPersonaFPC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="actualizaDireccionPersonaFPC-service">
    <port name="actualizaDireccionPersonaFPC-port" binding="tns:actualizaDireccionPersonaFPC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionFicopen"/>
    </port>
  </service>
</definitions>