<wsdl:definitions name="gestionTCAumentoReduccionLCPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/gestionTCAumentoReduccionLCPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:con="http://www.ficohsa.com.hn/middleware.services/gestionTCAumentoReduccionLCPS/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/gestionTCAumentoReduccionLCTypes">
 
 	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
    	</xsd:schema>
	    <xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/gestionTCAumentoReduccionLCTypes" schemaLocation="../xsd/gestionTCAumentoReduccionLCTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="gestionTCAumentoReduccionLC">
		<wsdl:part element="cons:gestionTCAumentoReduccionLC" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
 	<wsdl:message name="gestionTCAumentoReduccionLCResponse">
		<wsdl:part element="cons:gestionTCAumentoReduccionLCResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
	
	<wsdl:portType name="gestionTCAumentoReduccionLCPS">
		<wsdl:operation name="gestionTCAumentoReduccionLC" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="con:gestionTCAumentoReduccionLC"/>
			<wsdl:output message="con:gestionTCAumentoReduccionLCResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="gestionTCAumentoReduccionLCPSSOAP" type="con:gestionTCAumentoReduccionLCPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="gestionTCAumentoReduccionLC">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/gestionTCAumentoReduccionLCPS"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="con:gestionTCAumentoReduccionLC" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="con:gestionTCAumentoReduccionLCResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="gestionTCAumentoReduccionLCPS">
		<wsdl:port binding="con:gestionTCAumentoReduccionLCPSSOAP" name="gestionTCAumentoReduccionLCPSSOAP">
			<soap:address location="https://mwomnicanal:8004/Middleware/OperationsAndExecution/Cards/GestionTCAumentoReduccionLC"/>
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>