<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/ConsultaListaCuentas/consultaListaCuentas" name="consultaListaCuentas-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/ConsultaListaCuentas/consultaListaCuentas" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AbanksGTSOAApplication/ConsultaListaCuentas/consultaListaCuentas" location="consultaListaCuentas.wsdl"/>
  <binding name="consultaListaCuentas_ptt-binding" type="tns:consultaListaCuentas_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaListaCuentas">
      <soap:operation soapAction="consultaListaCuentas"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaListaCuentas-service">
    <port name="consultaListaCuentas-port" binding="tns:consultaListaCuentas_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksGT"/>
    </port>
  </service>
</definitions>