<wsdl:definitions name="sjConsultaMultiplesProductosPA" targetNamespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaMultiplesProductosPA" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/sjConsultaMultiplesProductosPA">
  <wsdl:types>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/sjConsultaMultiplesProductosPA" schemaLocation="../xsd/sjConsultaMultipleProductosPA.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="sjConsultaMultipleProductosPARequest">
    <wsdl:part element="tns:sjConsultaMultiplesProductosPA" name="inputParameters"/>
  </wsdl:message>
  <wsdl:message name="sjConsultaMultipleProductosPAResponse">
    <wsdl:part element="tns:sjConsultaMultiplesProductosPAResponse" name="outputParameters"/>
  </wsdl:message>
  
  <wsdl:portType name="sjConsultaMultiplesProductosPA">
    <wsdl:operation name="consultaProductos">
      <wsdl:input message="tns:sjConsultaMultipleProductosPARequest"/>
      <wsdl:output message="tns:sjConsultaMultipleProductosPAResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="sjConsultaMultiplesProductosPASOAP" type="tns:sjConsultaMultiplesProductosPA">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultaProductos">
      <wsdl:input>
        <soap:body parts="inputParameters" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="outputParameters" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="sjConsultaMultiplesProductosPA">
    <wsdl:port binding="tns:sjConsultaMultiplesProductosPASOAP" name="sjConsultaMultiplesProductosPASOAP">
      <soap:address location="http://172.23.13.19:8003/Middleware/SJS/consultaProductos"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>