<wsdl:definitions name="consultaOrigenFondosPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaOrigenFondosPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaOrigenFondosPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaOrigenFondosTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaOrigenFondosTypes" schemaLocation="consultaOrigenFondosTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="consultaOrigenFondosRequest">
		<wsdl:part element="cons:consultaOrigenFondos" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaOrigenFondosResponse">
		<wsdl:part element="cons:consultaOrigenFondosResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="consultaOrigenFondosPS">
		<wsdl:operation name="consultaOrigenFondos" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaOrigenFondosRequest"/>
			<wsdl:output message="fic:consultaOrigenFondosResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaOrigenFondosPSSOAP" type="fic:consultaOrigenFondosPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaOrigenFondos">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaOrigenFondosPS/consultaOrigenFondos"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaOrigenFondosRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaOrigenFondosResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="consultaOrigenFondosPS">
    <wsdl:port binding="fic:consultaOrigenFondosPSSOAP" name="consultaOrigenFondosPSSOAP">
      <soap:address location="http://mwinterbanca:8003/Middleware/ReferenceData/CommonBusinessInformation/ConsultaOrigenFondos"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>