<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application/Middleware/integracionConsultaPasivos" name="integracionConsultaPasivos-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application/Middleware/integracionConsultaPasivos" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application/Middleware/integracionConsultaPasivos" location="integracionConsultaPasivos.wsdl"/>
  <binding name="integracionConsultaPasivos_ptt-binding" type="tns:integracionConsultaPasivos_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="integracionConsultaPasivos">
      <soap:operation soapAction="integracionConsultaPasivos"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="integracionConsultaPasivos-service">
    <port name="integracionConsultaPasivos-port" binding="tns:integracionConsultaPasivos_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionCustomerCreditRisk"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="integracionConsultaPasivos.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application/Middleware/integracionConsultaPasivos">
            <con:wsdl ref="Middleware/v2/BusinessServices/DataWarehouse/integracionConsultaPasivos/wsdl/integracionConsultaPasivos"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/Application/Middleware/integracionConsultaPasivos</con:targetNamespace>
</con:wsdlEntry>