<wsdl:definitions name="modificaFechaAporteFondoPensionesPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/modificaFechaAporteFondoPensionesPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/modificaFechaAporteFondoPensionesPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/modificaFechaAporteFondoPensionesTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/modificaFechaAporteFondoPensionesTypes" schemaLocation="../xsd/modificaFechaAporteFondoPensionesTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="modificaFechaAporteFondoPensionesRequest">
		<wsdl:part element="cons:modificaFechaAporteFondoPensionesRequest" name="parameters"/>
		<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="modificaFechaAporteFondoPensionesResponse">
		<wsdl:part element="cons:modificaFechaAporteFondoPensionesResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="modificaFechaAporteFondoPensionesPS">
		<wsdl:operation name="modificaFechaAporteFondoPensiones" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="fic:modificaFechaAporteFondoPensionesRequest"/>
			<wsdl:output message="fic:modificaFechaAporteFondoPensionesResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="modificaFechaAporteFondoPensionesPSSOAP" type="fic:modificaFechaAporteFondoPensionesPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="modificaFechaAporteFondoPensiones">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/modificaFechaAporteFondoPensionesPS/modificaFechaAporteFondoPensiones"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:modificaFechaAporteFondoPensionesRequest" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:modificaFechaAporteFondoPensionesResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="modificaFechaAporteFondoPensionesPS">
    <wsdl:port binding="fic:modificaFechaAporteFondoPensionesPSSOAP" name="modificaFechaAporteFondoPensionesPSSOAP">
      <soap:address location="http://mwomnicanal:8003/Middleware/ReferenceData/BusinessPartner/modificaFechaAporteFondoPensiones"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>