<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/ConsultaEstadoTransaccionPrestamo/ConsultaEstadoTransaccionPrestamo" name="ConsultaEstadoTransaccionPrestamo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/ConsultaEstadoTransaccionPrestamo/ConsultaEstadoTransaccionPrestamo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/ConsultaEstadoTransaccionPrestamo/ConsultaEstadoTransaccionPrestamo" location="ConsultaEstadoTransaccionPrestamo.wsdl"/>
  <binding name="ConsultaEstadoTransaccionPrestamo_ptt-binding" type="tns:ConsultaEstadoTransaccionPrestamo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ConsultaEstadoTransaccionPrestamo">
      <soap:operation soapAction="ConsultaEstadoTransaccionPrestamo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ConsultaEstadoTransaccionPrestamo-service">
    <port name="ConsultaEstadoTransaccionPrestamo-port" binding="tns:ConsultaEstadoTransaccionPrestamo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionProxyAbanksHN"/>
    </port>
  </service>
</definitions>