<wsdl:definitions name="consultaExtraATMPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaExtraATMPS" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaExtraATMPS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/consultaExtraATMTypes">
	
  <wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaExtraATMTypes" schemaLocation="../xsd/consultaExtraATMTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
  
  <wsdl:message name="consultaExtraATMPSRequest">
  	<wsdl:part name="RequestHeader" element="auth:RequestHeader"/>
    <wsdl:part element="tns:consultaExtraATMRequest" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="consultaExtraATMPSResponse">
  	<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
    <wsdl:part element="tns:consultaExtraATMResponse" name="result"/>
  </wsdl:message>
  
  <wsdl:portType name="consultaExtraATMPS">
    <wsdl:operation name="consultaExtraATM">
      <wsdl:input message="fic:consultaExtraATMPSRequest"/>
      <wsdl:output message="fic:consultaExtraATMPSResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  
  <wsdl:binding name="consultaExtraATMPSSOAP" type="fic:consultaExtraATMPS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultaExtraATM">
      <soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaExtraATM"/>
      <wsdl:input>
        <soap:header message="fic:consultaExtraATMPSRequest" part="RequestHeader" use="literal"/>
        <soap:body use="literal" parts="parameters"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="fic:consultaExtraATMPSResponse" part="ResponseHeader" use="literal"/>
        <soap:body use="literal" parts="result"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="consultaExtraATMPS">
    <wsdl:port binding="fic:consultaExtraATMPSSOAP" name="consultaExtraATMPSSOAP">
      <soap:address location="http://172.23.13.19:8003/Middleware/OperationsAndExecution/Messaging/ConsultaExtraATM"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>