<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/conDatoTarjetaGT/consultaListaOFAC/consultaListaOFAC" name="consultaListaOFAC-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/conDatoTarjetaGT/consultaListaOFAC/consultaListaOFAC" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/conDatoTarjetaGT/consultaListaOFAC/consultaListaOFAC" location="consultaListaOFAC.wsdl"/>
  <binding name="consultaListaOFAC_ptt-binding" type="tns:consultaListaOFAC_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultaListaOFAC">
      <soap:operation soapAction="consultaListaOFAC"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultaListaOFAC-service">
    <port name="consultaListaOFAC-port" binding="tns:consultaListaOFAC_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionWebServices"/>
    </port>
  </service>
</definitions>