<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BIZ11g/ConsultaListasClienteNI/ConsultaListasClienteNI" name="ConsultaListasClienteNI-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BIZ11g/ConsultaListasClienteNI/ConsultaListasClienteNI" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BIZ11g/ConsultaListasClienteNI/ConsultaListasClienteNI" location="../wsdl/ConsultaListasClienteNI.wsdl"/>
  <binding name="ConsultaListasClienteNI_ptt-binding" type="tns:ConsultaListasClienteNI_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="ConsultaListasClienteNI">
      <soap:operation soapAction="ConsultaListasClienteNI"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ConsultaListasClienteNI-service">
    <port name="ConsultaListasClienteNI-port" binding="tns:ConsultaListasClienteNI_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionCustomerRiskNI"/>
    </port>
  </service>
</definitions>]]></con:wsdl>
    <con:dependencies>
        <con:import location="../wsdl/ConsultaListasClienteNI.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BIZ11g/ConsultaListasClienteNI/ConsultaListasClienteNI">
            <con:wsdl ref="Middleware/v2/BusinessServices/DataWarehouse/ConsultaListasCliente/wsdl/ConsultaListasClienteNI"/>
        </con:import>
    </con:dependencies>
    <con:targetNamespace>http://xmlns.oracle.com/pcbpel/adapter/db/BIZ11g/ConsultaListasClienteNI/ConsultaListasClienteNI</con:targetNamespace>
</con:wsdlEntry>