<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_ADAPTER/RegistroBitacoraPagoSeguro/RegistroBitacoraPagoSeguro" name="RegistroBitacoraPagoSeguro-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DB_ADAPTER/RegistroBitacoraPagoSeguro/RegistroBitacoraPagoSeguro" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_ADAPTER/RegistroBitacoraPagoSeguro/RegistroBitacoraPagoSeguro" location="RegistroBitacoraPagoSeguro.wsdl"/>
  <binding name="RegistroBitacoraPagoSeguro_ptt-binding" type="tns:RegistroBitacoraPagoSeguro_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="RegistroBitacoraPagoSeguro">
      <soap:operation soapAction="RegistroBitacoraPagoSeguro"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="RegistroBitacoraPagoSeguro-service">
    <port name="RegistroBitacoraPagoSeguro-port" binding="tns:RegistroBitacoraPagoSeguro_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionConvenios"/>
    </port>
  </service>
</definitions>