<wsdl:definitions name="cambiaEstadoAccesoUsuarioPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/cambiaEstadoAccesoUsuarioPS/" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cam="http://www.ficohsa.com.hn/middleware.services/cambiaEstadoAccesoUsuarioPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.ficohsa.com.hn/middleware.services/gestionAccesosUsuariosTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/gestionAccesosUsuariosTypes" schemaLocation="../../GestionAccesosUsuarios/xsd/gestionAccesosUsuariosTypes.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="requestHeader">
		<wsdl:part element="auth:RequestHeader" name="RequestHeader"/>
	</wsdl:message>
	<wsdl:message name="responseHeader">
		<wsdl:part element="auth:ResponseHeader" name="ResponseHeader"/>
	</wsdl:message>
	<wsdl:message name="cambiaEstadoAccesoUsuario">
		<wsdl:part element="tns:cambiaEstadoAccesoUsuario" name="parameters"/>
	</wsdl:message>
	<wsdl:message name="cambiaEstadoAccesoUsuarioResponse">
		<wsdl:part element="tns:cambiaEstadoAccesoUsuarioResponse" name="result"/>
	</wsdl:message>
	<wsdl:portType name="cambiaEstadoAccesoUsuarioPS">
		<wsdl:operation name="cambiaEstadoAccesoUsuario" parameterOrder="parameters RequestHeader ResponseHeader">
			<wsdl:input message="cam:cambiaEstadoAccesoUsuario"/>
			<wsdl:output message="cam:cambiaEstadoAccesoUsuarioResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="cambiaEstadoAccesoUsuarioPSSOAP" type="cam:cambiaEstadoAccesoUsuarioPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="cambiaEstadoAccesoUsuario">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/cambiaEstadoAccesoUsuarioPS/cambiaEstadoAccesoUsuario"/>
			<wsdl:input>
				<soap:body parts="parameters" use="literal"/>
				<soap:header message="cam:requestHeader" part="RequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="result" use="literal"/>
				<soap:header message="cam:responseHeader" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="cambiaEstadoAccesoUsuarioPS">
		<wsdl:port binding="cam:cambiaEstadoAccesoUsuarioPSSOAP" name="cambiaEstadoAccesoUsuarioPSSOAP">
			<soap:address location="https://172.23.13.19:7010/Middleware/OperationsAndExecution/Users/GestionAccesosUsuarios?wsdl"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>