<definitions
	targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/inbound/T24IFAdapters/T24CustomerPMSV/T24CustomerPMSV"
	name="T24CustomerPMSV-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/inbound/T24IFAdapters/T24CustomerPMSV/T24CustomerPMSV"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	<import
		namespace="http://xmlns.oracle.com/pcbpel/adapter/inbound/T24IFAdapters/T24CustomerPMSV/T24CustomerPMSV"
		location="T24CustomerPMSV.wsdl" />
	<binding name="EventPoll_ptt-binding" type="tns:EventPoll_ptt">
		<soap:binding style="document"
			transport="http://www.bea.com/wli/sb/transports/jca" />
		<operation name="EventPoll">
			<soap:operation soapAction="EventPoll" />
			<input>
				<soap:body use="literal" />
			</input>
		</operation>
	</binding>
	<service name="T24CustomerPMSV-service">
		<port name="T24CustomerPMSV-port" binding="tns:EventPoll_ptt-binding">
			<soap:address location="jca://eis/T24Adapter" />
		</port>
	</service>
</definitions>