<wsdl:definitions name="consultaPaisesPS" targetNamespace="http://www.ficohsa.com.hn/middleware.services/consultaPaisesPS/" xmlns:fic="http://www.ficohsa.com.hn/middleware.services/consultaPaisesPS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:auth="http://www.ficohsa.com.hn/middleware.services/autType" xmlns:cons="http://www.ficohsa.com.hn/middleware.services/consultaPaisesTypes">

  <wsdl:types>
    <xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/autType" schemaLocation="../../esquemas_generales/HeaderElements.xsd"/>
	</xsd:schema>
	<xsd:schema>
		<xsd:import namespace="http://www.ficohsa.com.hn/middleware.services/consultaPaisesTypes" schemaLocation="consultaPaisesTypes.xsd"/>
	</xsd:schema>
  </wsdl:types>
  
  	<wsdl:message name="consultaPaisesRequest">
		<wsdl:part element="cons:consultaPaises" name="parameters"/>
		<wsdl:part name="AutenticacionRequestHeader" element="auth:AutenticacionRequestHeader"/>
	</wsdl:message>
	<wsdl:message name="consultaPaisesResponse">
		<wsdl:part element="cons:consultaPaisesResponse" name="result"/>
		<wsdl:part name="ResponseHeader" element="auth:ResponseHeader"/>
	</wsdl:message>
		
	<wsdl:portType name="consultaPaisesPS">
		<wsdl:operation name="consultaPaises" parameterOrder="parameters AutenticacionRequestHeader ResponseHeader">
			<wsdl:input message="fic:consultaPaisesRequest"/>
			<wsdl:output message="fic:consultaPaisesResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="consultaPaisesPSSOAP" type="fic:consultaPaisesPS">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="consultaPaises">
			<soap:operation soapAction="http://www.ficohsa.com.hn/middleware.services/consultaPaisesPS/consultaPaises"/>
			<wsdl:input>
				<soap:body use="literal" parts="parameters"/>
				<soap:header message="fic:consultaPaisesRequest" part="AutenticacionRequestHeader" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="result"/>
				<soap:header message="fic:consultaPaisesResponse" part="ResponseHeader" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
  
  <wsdl:service name="consultaPaisesPS">
    <wsdl:port binding="fic:consultaPaisesPSSOAP" name="consultaPaisesPSSOAP">
      <soap:address location="http://mwinterbanca:8003/Middleware/ReferenceData/CommonBusinessInformation/ConsultaPaises"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>