<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MD/conReversarPagoTCRG" name="conReversarPagoTCRG-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MD/conReversarPagoTCRG" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/MD/conReversarPagoTCRG" location="conReversarPagoTCRG.wsdl"/>
  <binding name="conReversarPagoTCRG_ptt-binding" type="tns:conReversarPagoTCRG_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="conReversarPagoTCRG">
      <soap:operation soapAction="conReversarPagoTCRG"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="conReversarPagoTCRG-service">
    <port name="conReversarPagoTCRG-port" binding="tns:conReversarPagoTCRG_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionTarjetasHN"/>
    </port>
  </service>
</definitions>