<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarReciboPagoPtmo/consultarReciboPagoPtmo" name="consultarReciboPagoPtmo-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarReciboPagoPtmo/consultarReciboPagoPtmo" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/MiddlewareSOAApplication/ConsultarReciboPagoPtmo/consultarReciboPagoPtmo" location="consultarReciboPagoPtmo.wsdl"/>
  <binding name="consultarReciboPagoPtmo_ptt-binding" type="tns:consultarReciboPagoPtmo_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="consultarReciboPagoPtmo">
      <soap:operation soapAction="consultarReciboPagoPtmo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="consultarReciboPagoPtmo-service">
    <port name="consultarReciboPagoPtmo-port" binding="tns:consultarReciboPagoPtmo_ptt-binding">
      <soap:address location="jca://eis/DB/ConnectionInterbanca"/>
    </port>
  </service>
</definitions>